Add: Electrostaff - weapon for real NT shitcure
ss220club/Paradise-SS220 pull request #1011
Opened 2024-02-11 14:44 UTC by TheFckReal

## Баунти от OverBlues

## Что этот PR делает
 Добавляет новый предмет - электропосох. Электропосох - это двуручное электрическое оружие, работающee, как улучшенный станбатон (по характеристикам), но только в двух руках, и не имеющий внешнего разьема для подзарядки (то есть нужно выкручивать батарею и заряжать ее отдельно).
 Добавлен выбор скинов для этого предмета (отличаются свечением: оранжевый (по умолчанию), синий, красный и фиолетовый цвета). 
 Не может быть во включенном состоянии не в руках.
### Характеристики: 
 **По сравнению со станбатоном**: На 5 секунд увеличены стандартные эффекты, на 20 увеличен стаминадемейдж (итого 80), увеличен хиткост на 1000 (итого 2000).
 Имеет 10 брут урона, 5 урона ожогами (во включенном состоянии).

### Остальные изменения:
 Добавлен "Electrostaff parts kits" для крафта электропосоха. Делается на протолате при уровне исследований ("combat" = 7, "magnets" = 5, "powerstorage" = 5). 
 
 Добавлен крафт в Weapons электропосоха с названием "Electrostaff". Крафтится из 2 станбатонов (или станпродов для кустарных ребятишек), high-capacity cell, 5 проводов и при наличии инструментов: отвертки и кусачек.
 
 Добавлен электропосох в ящик Блющилда, добавлена отвертка (как великая щедрость НТ).

## Почему это хорошо для игры
Потому что новые предметы - это круто. А еще это одобренное баунти. Вопросы?

## Изображения изменений
![visual_staff](https://github.com/ss220club/Paradise-SS220/assets/102225891/40c37e1b-48ce-4671-84da-eb2fff3c6d01)

## Тестирование
На локалке с товарищем. Тестили эффекты, крафты на протолате китов, сам крафт, удары и +- думали о балансе.

## Changelog

:cl:
add: Электропосох для Блющилда, а также в протолат оружейные части для крафта.
/:cl:

2024-02-12 06:47 UTC, PhantornRU requested changes
Нужно доделывать.

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/closets.dm
> +	new /obj/item/screwdriver(src)
Зачем дублируешь и перезаписываешь? Делай модульно. 
```suggestion
/obj/structure/closet/secure_closet/blueshield/populate_contents()
	. = ..()
	new /obj/item/melee/electrostaff/loaded(src)
	new /obj/item/screwdriver(src)
```

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +		cell = new(src)
Тоже не дучше. Но зачем ты батарейке присваиваешь Null, если она изначально null и является?
```suggestion
	cell = unlink ? null : new(src)
```

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +				icon_state = "[base_icon][current_skin]1"
1?

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	user.visible_message("<span class='suicide'>[user] is putting the live [name] in [user.p_their()] mouth! It looks like [user.p_theyre()] trying to commit suicide.</span>")
Русский, Английский...

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	return cell
Собсно. А нахуя отдельный прок?
```suggestion
/obj/item/melee/electrostaff/get_cell()
	return cell
```

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +		update_icon()
2 апдейта? Are you sure about this?
```suggestion
		update_icon()
	if(cell.charge < (hitcost)) // If after the deduction the baton doesn't have enough charge for a stun hit it turns off.
		turned_on = FALSE
		update_icon()
```

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	user.put_in_hands(cell)
почему не get_cell, если ты прок тот родил?
```suggestion
	user.put_in_hands(cell)
```

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	if(issilicon(M)) // Can't stunbaton borgs and AIs
я правильно понимаю что весь этот кусок ты скопипастил, вместо того чтобы посох наследовать от станбатона? Нахузачем?

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	desc = "Лучше, чем 2 станбатона по отдельности."
Лучше добавить каламбура
```suggestion
	desc = "Оперативный ответ."
```

2024-02-12 06:47 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +				/obj/item/stock_parts/cell/high = 1,
Всё-таки не слаймобатарея? Батарейки будут меняться тратя заряд?
```suggestion
				/obj/item/stock_parts/cell/high = 1,
```

2024-02-12 11:23 UTC, TheFckReal commented on modular_ss220/objects/code/closets.dm
> +	new /obj/item/screwdriver(src)
Модульно сделаю, не проблема

А разве то, что ты реализовал вызовет не родительский метод (то есть метод у secure_closets), а потом добавит 2 предмета? Я ж не расширяю, а не переопределяю метод.

2024-02-12 11:24 UTC, TheFckReal commented on modular_ss220/objects/code/electrostaff.dm
> +				icon_state = "[base_icon][current_skin]1"
Да, просто затычка. Про по аналогии с оффов, где вторые режимы тупо 1 становились. На уровне fireaxe1. Смысла переделывать вижу мало (придется менять имя каждого скина). Но тут уж как скажете

2024-02-12 11:25 UTC, TheFckReal commented on modular_ss220/objects/code/electrostaff.dm
> +	user.visible_message("<span class='suicide'>[user] is putting the live [name] in [user.p_their()] mouth! It looks like [user.p_theyre()] trying to commit suicide.</span>")
Не особо дошло, как это перевести, если честно. Реально думал, но не придумал. Только если совсем переписывать на что-то свое.

2024-02-12 11:28 UTC, TheFckReal commented on modular_ss220/objects/code/electrostaff.dm
> +	return cell
Украл со станбатона. Но, как видишь, это не я создаю новый прок, а определяю старый. Предполагаю, что он для чего-то и нужен, во внешних методах (насколько я помню, он нужен для recharger как минимум). Думаешь убрать?

2024-02-12 11:31 UTC, TheFckReal commented on modular_ss220/objects/code/electrostaff.dm
> +	if(issilicon(M)) // Can't stunbaton borgs and AIs
Ответ достаточно прост - станбатон (и его наследники) захардкожены в recharger, а именно то, что они могут заряжаться в нем. Согласно баунту, этого делать нельзя. Никак иначе, кроме копипаста (и я не просто копипастил код, я копипастил основные методы, а потом приходилось их переделывать), здесь ничего было сделать нельзя. Увы

2024-02-12 11:32 UTC, TheFckReal commented on modular_ss220/objects/code/electrostaff.dm
> +	user.put_in_hands(cell)
Если бы он не был родительским, я бы его не определял. А так вызов метода - это всегда нагрузка бОльшая, чем сразу к переменной обращаться. Если надо, могу переделать.

2024-02-12 11:33 UTC, TheFckReal commented on modular_ss220/objects/code/electrostaff.dm
> +				/obj/item/stock_parts/cell/high = 1,
Не очень понял о чем ты, если честно

2024-02-12 11:43 UTC, TheFckReal commented on modular_ss220/objects/code/electrostaff.dm
> +		update_icon()
Да, потому что иначе будет хуже. Обновление происходит в двух случаях:
Батарейка rigged ИЛИ заряд ниже нужного.

Если мы хотим учесть обе ситуации и сократить количество вызовов прока, то должны вынести его в конец (дабы учесть оба случая). Тогда мы получаем, что у нас будет обновляться палка КАЖДЫЙ вызов, потому что в большинстве случаев оба условия не будут выполняться и прок будет проходить без вызова обновления. В общем дааааа :Clueless:

2024-02-14 02:12 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	return ..()
```suggestion
	. = ..()
```

2024-02-14 02:13 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	..()
```suggestion
	. = ..()
```

2024-02-14 15:32 UTC, PhantornRU requested changes

2024-02-14 15:32 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	attack_verb = list("attacked", "beaten")
Можно сразу на русском, всё ж модульная разработка.

2024-02-14 15:32 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	hitcost = 1600 // 6 hits to 0 power
Многовато. Прям черезчур. Это с обычной батарейкой? Слаймовую прикручивать пробовал, или нельзя? Если нельзя, то плохо. Должен быть вариант с автозарядом, как у энергомеча.

2024-02-14 15:32 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +				icon_state = "[base_icon][current_skin]1"
Всеравно лучше переименуй, аля "on/active"

2024-02-14 15:32 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +		. += "<span class='notice'>Alt-click to change light.</span>"
Лучше перевести.

2024-02-14 15:32 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	add_fingerprint(user)
Перевод.

2024-02-14 15:32 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	add_fingerprint(user)
Произошел дубляж однотипного кода. Объедини с proc/wielded и туда проверки вынеси.

2024-02-15 00:54 UTC, PhantornRU commented on modular_ss220/objects/code/electrostaff.dm
> +	. -= "<span class='notice'>This item can be recharged in a recharger. Using a screwdriver on this item will allow you to access its power cell, which can be replaced.</span>"
Перевод

2024-02-15 00:55 UTC, PhantornRU approved these changes
А так в принципе нормально

2024-02-15 11:50 UTC, AyIong commented on modular_ss220/balance/code/species/machine.dm
> +		to_chat(user, "<span class='notice'>[G] не имеет внешних разьемов для подзарядки.</span>")
```suggestion
		to_chat(user, span_notice("[G] не имеет внешних разьемов для подзарядки."))
```
И спаны замени на макросы

2024-02-15 14:23 UTC, merged