Перевод типов раунда
ss220club/Paradise-SS220 pull request #1031
Opened 2024-02-19 17:34 UTC by VERG-SS220

## Что этот PR делает
Переводит

## Почему это хорошо для игры
Перевод

## Изображения изменений

## Тестирование
Не требуется

## Changelog

:cl:
fix: Пофикшена очепятка в подсказке
add: Переведена часть финального экрана
/:cl:

2024-02-19 17:36 UTC, AyIong approved these changes
Вроде норм

2024-02-20 10:31 UTC, dj-34 requested changes

2024-02-20 10:31 UTC, dj-34 commented on code/controllers/subsystem/SSticker.dm
> +	to_chat(world, "<span class='boldannounceooc'>Перезапуск мира через [delay/10] [delay > 10 ? "секунд" : "секунду"]. [reason]</span>")
```suggestion
	to_chat(world, "<span class='boldannounceooc'>Перезапуск через [delay/10] [delay > 10 ? "секунд" : "секунду"]. [reason]</span>")
```

2024-02-20 10:31 UTC, dj-34 commented on code/controllers/subsystem/SSticker.dm
> +				end_of_round_info += "<b>[robo.name] (Игрок: [robo_ckey]) Не смог выжить без ИИ-мастера. Законы киборга:</b>"
```suggestion
				end_of_round_info += "<b>[robo.name] (Игрок: [robo_ckey]) не смог выжить без ИИ-мастера. Законы киборга:</b>"
```

2024-02-26 16:45 UTC, closed without merging