[FEAT] Plov
ss220club/Paradise-SS220 pull request #1085
Opened 2024-03-11 16:15 UTC by Chorden523

## Что этот PR делает
Краткое описание:
Добавляет плов и его готовку через печку.

Детальное описание:
Добавляет плов, который содержит в себе 5 юнитов нутриментов, 3 юнита плантматтера, 1 юнит чёрного перца и 1 юнит витаминов. Создаётся при помощи печки. Рецепт: 2 куска мяса, 2 миски варёного риса, 1 морковка, 1 ветка ягод (идут в качестве изюма) и 1 юнита чёрного перца

## Почему это хорошо для игры
Больше еды не повредит, разнообразие для кухни.

## Изображения изменений
![output-onlinepngtools](https://github.com/ss220club/Paradise-SS220/assets/130075022/e2075faf-c45d-4a8c-99be-4fc0798c3352)

## Тестирование
Запустил локалку - поел плов, собрал все ингредиенты вместе, засунул в печь и получил плов 

## Changelog

:cl:
add: Добавлен плов. Можно приготовить с помощью печки.
/:cl:

2024-03-11 16:38 UTC, MrRomainzZ approved these changes
Моим первым ревью будет ревью на плов. Не вижу проблем. Добавляем

2024-03-11 16:47 UTC, dj-34 commented
Почему то у меня есть стойкое ощущение, будто плов уже есть в игре...

2024-03-11 16:48 UTC, MrRomainzZ commented
> Почему то у меня есть стойкое ощущение, будто плов уже есть в игре...

![изображение](https://github.com/ss220club/Paradise-SS220/assets/47046463/3f4359ae-943b-4771-a60e-d31240c892de)

2024-03-11 16:50 UTC, dj-34 commented
> > Почему то у меня есть стойкое ощущение, будто плов уже есть в игре...
> 
> ![изображение](https://private-user-images.githubusercontent.com/47046463/311789924-3f4359ae-943b-4771-a60e-d31240c892de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxNzYwMDAsIm5iZiI6MTcxMDE3NTcwMCwicGF0aCI6Ii80NzA0NjQ2My8zMTE3ODk5MjQtM2Y0MzU5YWUtOTQzYi00NzcxLWE2MGUtZDMxMjQwYzg5MmRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzExVDE2NDgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1MTI2OWViMDkzZWI5N2VhZGFiMmY0OGM1NmQ0ODc3MDk4MTkwMjU4YWYxOTFhYWQ0NjFhNWFjODAyMDAwODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mtdaa_KvXB_14vWO8aNL_nH3VSsJC8KV07lwfHueZXQ)

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/93669acb-3df8-47d3-aa54-e61bd8c1146d)

2024-03-11 16:53 UTC, dj-34 requested changes

2024-03-11 16:53 UTC, dj-34 commented on modular_ss220/food/code/food/food.dm
> +	desc = "Плов по тому самому рецепту с Земли, так ещё и с изюмом! Объеденье."
```suggestion
	desc = "Плов по тому самому рецепту с Земли, так ещё и с изюмом! Объедение."
```

2024-03-11 16:53 UTC, dj-34 commented on modular_ss220/food/code/food/food.dm
> +	bitesize = 1
1 укус, серьезно?
```suggestion
```

2024-03-11 16:53 UTC, dj-34 commented on modular_ss220/food/code/food/food.dm
> +	antable = FALSE
Зачем?
```suggestion
```

2024-03-11 16:57 UTC, dj-34 commented
Думаю еще в trash можно оставлять plate

2024-03-11 16:58 UTC, MrRomainzZ commented
Ошибся, получается... Ну, первое ревью можно и простить 
![1100008967767334912](https://github.com/ss220club/Paradise-SS220/assets/47046463/24cafff1-11b2-4563-9201-2b3c9888d2a1)

2024-03-11 17:02 UTC, Chorden523 commented on modular_ss220/food/code/food/food.dm
> +	bitesize = 1
Пока я тестил, если ставишь 5 укусов то по итогу весь плов за два укуса сжирается

2024-03-11 17:17 UTC, dj-34 requested changes

2024-03-11 17:17 UTC, dj-34 commented on modular_ss220/food/code/food/food.dm
> +	filling_color = "#B15124"
```suggestion
	icon_state = "plov"
	trash = /obj/item/trash/plate
	filling_color = "#B15124"
```

2024-03-11 17:32 UTC, dj-34 approved these changes

2024-03-12 09:43 UTC, merged

2024-03-12 09:43 UTC, PhantornRU approved these changes