[FEAT] tg beakers
ss220club/Paradise-SS220 pull request #1099
Opened 2024-03-14 14:43 UTC by Chorden523

## Что этот PR делает
Краткое описание:
Добавляет в игру x-large и metamaterial мензурки.

Детальное описание:
Добавляет в игру две новые мензурки. А именно x-large и metamaterial, вместимостью они 150 и 180 соответственно, создаются при помощи при помощи протолата. Для их печати нужно прокачать технологии хотя бы на базовый уровень исследований.

## Почему это хорошо для игры
Большее разнообразие мензурок для химиков меда и РнД.

## Изображения изменений
![output-onlinepngtools (3)](https://github.com/ss220club/Paradise-SS220/assets/130075022/cd34c7dc-4c2c-4183-a84a-8a4978853993)
![output-onlinepngtools (2)](https://github.com/ss220club/Paradise-SS220/assets/130075022/aa54533f-8401-4184-86da-f1db3756418b)

## Тестирование
Запустил локалку - оверлеи обновляются, крышки бикеров работают, реакции происходят, гранатки бахают.

## Changelog

:cl:
add: Добавлены две новые мензурки, вместимостью в 150 и 180 юнитов, можно распечатать в протолате.
/:cl:

2024-03-14 15:04 UTC, AyIong commented on modular_ss220/objects/code/beakers.dm
> +	container_type = OPENCONTAINER
Или просто добавить дополнительное при ините через += или |= 
Сам не в курсе как лучше

2024-03-14 20:24 UTC, dj-34 requested changes
Какой-то бесполезный предмет, почему нельзя просто дождаться появление Блюспейс бикера?

2024-03-14 20:24 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +	name = "Metamaterial beaker"
```suggestion
	name = "Metamaterial Beaker"
```

2024-03-14 20:24 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +	name = "X-large beaker"
```suggestion
	name = "X-large Beaker"
```

2024-03-14 20:24 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +	amount_per_transfer_from_this = 10
Уже указано в родителе
```suggestion
```

2024-03-14 20:24 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +	amount_per_transfer_from_this = 10
```suggestion
```

2024-03-14 20:24 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +	container_type = OPENCONTAINER
Уже обозначено в родителе
```suggestion
```

2024-03-14 20:24 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +	container_type = OPENCONTAINER
```suggestion
```

2024-03-14 20:24 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +/datum/design/beaker_white
Где desc у дизайнов? Что у одного что у второго.

2024-03-15 08:17 UTC, dj-34 requested changes

2024-03-15 08:17 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +	desc = "Мензурка с нанесением покрытия из укреплённого стекла и пластика"
1. Я заебался ебать за отсутствия точек в desc
2. Придерживаемся описания остальных дизайнов мензурок
```suggestion
	desc = "Мензурка с нанесением покрытия из укреплённого стекла и пластика. Вмещает до 150 юнитов."
```

2024-03-15 08:17 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +	desc = "Мензурка с нанесением покрытия из золота"
```suggestion
	desc = "Мензурка с нанесением покрытия из золота. Вмещает до 180 юнитов."
```

2024-03-15 08:17 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +
Зачем это нужно, если наш родитель beaker и так обновляет оверлеи на on_reagent_change?
```suggestion
```

2024-03-15 08:17 UTC, dj-34 commented on modular_ss220/objects/code/beakers.dm
> +		. += "assembly"
Мне не нравится что здесь полностью дублируется код родителя beaker и просто заменяется оверлей filling на internal_reagents. Получается я так понимаю что у нас создается 2 оверлея, 1 от родителя, второй твой. Не круто.

2024-03-16 03:17 UTC, Chorden523 commented on modular_ss220/objects/code/beakers.dm
> +		. += "assembly"
> Мне не нравится что здесь полностью дублируется код родителя beaker и просто впихивается оверлей internal_reagents поверх оверлея filling. Получается я так понимаю что у нас создается 2 оверлея, 1 от родителя, второй твой. Не круто.

Добавлено в основной файл теперь и берёт все оверлеи со спрайтами оттуда

2024-03-16 03:21 UTC, Furrior commented
Не смейте не модульно .дмм и .дми трогать. Ебнетесь же конфликты с ними разбирать, учитывая, что они иногда конфликтуют вообще без каких либо изменений.

2024-03-16 03:30 UTC, dj-34 commented
> Не смейте не модульно .дмм и .дми трогать. Ебнетесь же конфликты с ними разбирать, учитывая, что они иногда конфликтуют вообще без каких либо изменений.

Хуя, я даже и не обратил внимание что там немодульно иконки закинуты 💀

2024-03-16 03:31 UTC, dj-34 commented
А, он последним коммитом закинул, фух, тогда не проморгал

2024-03-28 00:17 UTC, closed without merging