Awaymission: spacebattle port (remap by ItsMeJabba)
ss220club/Paradise-SS220 pull request #1123
Opened 2024-03-22 14:31 UTC by konushi

## Что этот PR делает

Порт замечательного ремапнутого гейта с эксов. Ничего не вырезано, мелкие перестройки и замены. Правильный перевод.
В целом, все особенности и изменения тута: https://github.com/ss220-space/Paradise/pull/2200

## Почему это хорошо для игры

Больше красивых гейтов - больше красивых гейтов.

## Изображения изменений

![StrongDMM-2024-03-22 17 27 54](https://github.com/ss220club/Paradise-SS220/assets/139562134/0a21ff6b-fd80-4b31-896b-67f6f06dcf6f)

## Тестирование

Локалка, ворк.

## Changelog

:cl:
add: Перенесен гейт spacebattle. Ничего не вырезано (впрочем, ничего и не добавлено).

/:cl:

2024-03-22 14:36 UTC, dj-34 reviewed
ЧЗХ, почему у тебя в areas/gateway.dm и areas/spacebattle.dm зоны повторяются?

2024-03-22 14:38 UTC, dj-34 reviewed
Насрано
modular_ss220/maps220/icons/custom-synthetic.dmi

2024-03-22 14:38 UTC, dj-34 commented
Карту позже посмотрю

2024-03-23 15:49 UTC, dj-34 requested changes
По карте в целом вроде все ок, стенки же нельзя разобрать?

2024-03-23 15:49 UTC, dj-34 commented on modular_ss220/maps220/code/mobs.dm
> +	var/SynRange //Лут с дальников
Переведи везде в camelcase
```suggestion
	// Обычный лут, дропается со всех
	var/synmobdrop
	// Выпадение бладрига
	var/synspace
	// Лут с милишников
	var/synmelee
	// Лут с дальников
	var/synrange
```

2024-03-23 15:49 UTC, dj-34 commented on modular_ss220/maps220/code/papers.dm
> +/obj/item/paper/spacebattle/voxcap1 // Экипаж говнит вокса-офицера
Все коменты закинь наверх
```suggestion
// Экипаж говнит вокса-офицера
/obj/item/paper/spacebattle/voxcap1
```

2024-03-23 15:49 UTC, dj-34 commented on modular_ss220/maps220/code/mobs.dm
> +/obj/effect/landmark/awaymissions/spacebattle/mob_spawn/melee
У нас landmark'и не в отдельном файле случаем?

2024-03-23 15:49 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	icon_override = 'modular_ss220/clothing/icons/mob/helmet.dmi'
Сомнительно...

2024-03-24 13:58 UTC, konushi commented on modular_ss220/maps220/code/mobs.dm
> +	var/SynRange //Лут с дальников
не, стенки неразрушаемые

2024-03-24 14:10 UTC, konushi commented on modular_ss220/clothing/code/suits.dm
> +	icon_override = 'modular_ss220/clothing/icons/mob/helmet.dmi'
Этот кораблик, по лору гейта - из прошлого. Думаю не будет плохой идеей оставить такой старый хардсьютик, тем более в билде он есть, не было только спрайтика.

2024-03-24 14:11 UTC, konushi commented on modular_ss220/maps220/code/mobs.dm
> +/obj/effect/landmark/awaymissions/spacebattle/mob_spawn/melee
Вообще, это вроде как лучше в спавнеры перенести, но прошлый одобрили так шо оставил в мобах.

2024-03-25 17:35 UTC, Legendaxe requested changes

2024-03-25 17:35 UTC, Legendaxe commented on modular_ss220/clothing/code/suits.dm
> +	.=..()
```suggestion
	. = ..()
```

2024-03-25 17:55 UTC, dj-34 approved these changes
По карте вроде ок

2024-03-25 20:29 UTC, Legendaxe approved these changes

2024-03-25 20:29 UTC, merged