[FEAT] Towels
ss220club/Paradise-SS220 pull request #1126
Opened 2024-03-23 04:44 UTC by Chorden523

## Что этот PR делает
Добавляет в игру полотенца и их разноцветные вариации. Они представляют из себя костюмы без датчиков, что можно надеть на себя. Выглядят как неплохой дрип для бани или сауны. Раскиданы по всем отделам и главам.

## Почему это хорошо для игры
РП в душе? Такое нам надо. Также можно будет их сделать как дрип для сауны или бани.

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/130075022/96c4f920-0dfc-4b49-90cd-32200a57345a)
![image](https://github.com/ss220club/Paradise-SS220/assets/130075022/d01e7fbc-afd2-4f93-9917-46691fe4c7de)

## Тестирование
Запустил локалочку. Работает всё отлично, иконка отрисовывается, на куклах отрисовывается, красится хорошо.

## Changelog

:cl:
add: Добавлены полотенца. Их можно найти в душевой дорм, в каждом из отделов и у глав.
/:cl:

2024-03-23 14:07 UTC, PhantornRU approved these changes
Добавь еще скриншоты в тестирование как они выглядят и расположены на карте

2024-03-23 15:33 UTC, dj-34 requested changes
Полотенца в отделах выглядят... странно...

2024-03-23 15:33 UTC, dj-34 commented on modular_ss220/clothing/code/hats.dm
> +		"Vulpkanin" 		= 	'modular_ss220/clothing/icons/mob/hats.dmi',
Что за пробелы? Убери их

2024-03-23 15:33 UTC, dj-34 commented on modular_ss220/clothing/code/under.dm
> +//Маленькое полотенце
```suggestion
// Маленькое полотенце
```

2024-03-23 15:34 UTC, dj-34 requested changes

2024-03-23 15:34 UTC, dj-34 commented on modular_ss220/clothing/_clothing.dm
> +		new /datum/stack_recipe("полотенце", /obj/item/clothing/under/towel_long, 4, time = 1 SECONDS,)
Лишний?
```suggestion
		new /datum/stack_recipe("полотенце", /obj/item/clothing/under/towel_long, 4, time = 1 SECONDS)
```

2024-03-23 18:25 UTC, dj-34 requested changes
Лишние изменения
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/7e9321ca-c3cc-4de2-b236-6fa4bbd0f2fb)
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/c019f3d8-8e0e-465b-8396-1ed9576465d2)

2024-03-29 20:08 UTC, AyIong reviewed
На мету забыл полотешки вкинуть

2024-03-29 20:11 UTC, AyIong commented on modular_ss220/clothing/code/under.dm
> +
```suggestion
```

2024-03-29 20:11 UTC, AyIong commented on modular_ss220/clothing/code/under.dm
> +
```suggestion
```

2024-03-29 20:11 UTC, AyIong commented on modular_ss220/clothing/code/under.dm
> +
```suggestion
```

2024-03-29 20:11 UTC, AyIong commented on modular_ss220/clothing/code/under.dm
> +
```suggestion
```

2024-03-30 09:11 UTC, AyIong approved these changes
Найс ворк май фриенд

2024-03-30 16:30 UTC, dj-34 approved these changes

2024-03-30 22:06 UTC, merged