Перевод ментор и админ тикетов
ss220club/Paradise-SS220 pull request #1156
Opened 2024-04-03 14:22 UTC by AyIong

## Что этот PR делает
Перевод админ и ментор тикетов, так как туда добавили автоответчики

## Почему это хорошо для игры
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/7fd6c0bd-f6eb-4f47-b7f9-208aa9f56a47)

## Тестирование
Постепенно

## Changelog

:cl:
spellcheck: Перевод ментор и админ тикетов, а так же их автоответчиков.
/:cl:

2024-04-03 16:29 UTC, AyIong commented on code/controllers/subsystem/tickets/tickets.dm
> +		response_phrases["Exploit Report"] = "To report an exploit, please go to our <a href='[GLOB.configuration.url.exploit_url]'>Exploit Report page</a>. Then 'Start New Topic'. Then fill out the topic
Увы, хотя мы узнаём про эксплоит только после того как все его начинают использовать, так как никто не говорит :clueless:

2024-04-03 16:32 UTC, AyIong commented
Ревью от граммар полис прошло

2024-04-06 11:07 UTC, Furrior requested changes

2024-04-06 11:07 UTC, Furrior commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +		"Эксперементируй!" = "Эксперементируй! Большая часть удовольствия от этой игры, состоит в том, чтобы пробовать различные штуки и бороться с последствиями, если что-то пошло не так.",
```suggestion
		"Эксперементируй!" = "Эксперементируй! Большая часть удовольствия от этой игры, состоит в том, чтобы пробовать различные вещи и бороться с последствиями, если что-то пошло не так.",
```

2024-04-06 11:07 UTC, Furrior commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +	response_phrases = list("Известный баг" = "К сожалению, это известный баг. К счастью, он скоро будет пофикшен.",
```suggestion
	response_phrases = list("Известный баг" = "К сожалению, это известный баг. Надеемся, он скоро будет исправлен.",
```

2024-04-06 11:07 UTC, Furrior commented on code/controllers/subsystem/tickets/mentor_tickets.dm
> +		response_phrases["Новый баг"] = "Звучит как баг! Чтобы сообщить о нём, пожалуйста, перейдите на наш <a href='[GLOB.configuration.url.github_url]'>GitHub</a>. После чего перейдите в 'Issues', нажмит
```suggestion
		response_phrases["Новый баг"] = "Звучит как баг! Чтобы сообщить о нём, пожалуйста, перейдите на наш <a href='[GLOB.configuration.url.github_url]'>GitHub</a>. После чего перейдите в 'Issues', нажмите 'New Issue' и заполните форму. Если в репорте будет информация с текущего раунда, отправьте ее только после его окончания. В качестве альтернативы вы можете написать в канал 'ss13-трекер' нашего дискорд сервера, однако репорты с GitHub обрабатываются быстрее!"
```

2024-04-06 11:07 UTC, Furrior commented on code/controllers/subsystem/tickets/tickets.dm
> +		response_phrases["Appeal on the Forums"] = "Appealing a ban must occur on the forums. Privately messaging, or adminhelping about your ban will not resolve it. To appeal your ban, please head to <a
Речь может быть еще о джобке, но согласен, что не нужно нам

2024-04-06 11:07 UTC, Furrior commented on code/controllers/subsystem/tickets/tickets.dm
> +		response_phrases["Новый баг"] = "Звучит как баг! Чтобы сообщить о нём, пожалуйста, перейдите на наш <a href='[GLOB.configuration.url.github_url]'>GitHub</a>. После чего перейдите в 'Issues', нажмит
Оффы насрали копипастой?

2024-04-06 11:10 UTC, AyIong commented on code/controllers/subsystem/tickets/tickets.dm
> +		response_phrases["Новый баг"] = "Звучит как баг! Чтобы сообщить о нём, пожалуйста, перейдите на наш <a href='[GLOB.configuration.url.github_url]'>GitHub</a>. После чего перейдите в 'Issues', нажмит
Да

2024-04-06 11:12 UTC, Furrior approved these changes

2024-04-06 11:12 UTC, merged