Brainrot filter
ss220club/Paradise-SS220 pull request #1225
Opened 2024-05-13 13:22 UTC by Gaxeer

## Что этот PR делает

Добавляем речи игроков, дабы отлавливать брейнрот и другие запретные слова

## Почему это хорошо для игры

Меньше нарушения атмосферы, меньше банов за слово на букву П

## Тестирование

Всё работает. Ez

## Changelog

:cl:
add: Добавляем фильтр речи игроков (1984)
/:cl:

2024-05-13 13:31 UTC, larentoun requested changes

2024-05-13 13:31 UTC, larentoun commented on config/example/config.toml
> +# override_map = "/datum/map/test_tiny"
```suggestion
#override_map = "/datum/map/test_tiny"
```

2024-05-13 13:31 UTC, larentoun commented on modular_ss220/speech_filter/_speech_filter.dm
> +/datum/modpack/discord_link
```suggestion
/datum/modpack/speech_filter
```

2024-05-13 13:31 UTC, larentoun commented on modular_ss220/speech_filter/code/speech_filter.dm
> +	if(!isliving(target))
```suggestion
	if(!ismob(target))
```
И обсервы, и ливинги могут получать? Элемент даешь выше мобам

2024-05-13 13:45 UTC, dj-34 commented on config/example/config.toml
> +speech_filter_bypass = []
Возможно стоит добавить проверку по рангу

2024-05-13 13:49 UTC, Gaxeer commented on config/example/config.toml
> +speech_filter_bypass = []
Может быть

2024-05-13 13:50 UTC, larentoun approved these changes

2024-05-15 12:55 UTC, Legendaxe commented on modular_ss220/speech_filter/code/speech_filter.dm
> +	message = rustutils_regex_replace(message, brainrot_regex, "i", "")
```suggestion
	message = rustutils_regex_replace(message, brainrot_regex, "i", "цветочек")
```

2024-07-09 07:46 UTC, dj-34 requested changes

2024-09-01 08:32 UTC, dj-34 commented
Мне кажется можно было бы уже замержить, это будет вечный ТМ

2024-09-01 14:02 UTC, merged