Звёздные войны 13
ss220club/Paradise-SS220 pull request #1227
Opened 2024-05-14 00:11 UTC by Fullonibus

## What Does This PR Do
Добавлено несколько именных световых мечей.

- Новые иконки мечей
- Новые анимации для мечей
- Новые звуки включения/выключения и ударов
- Система зачарований с уже готовым зачарованием "рывок"

## Why It's Good For The Game
Приказ генерала Гавса

## Images of changes

![image](https://github.com/ParadiseSS13/Paradise/assets/38350888/9c6f69cc-9839-446d-afee-8a8546eec7f5)

## Testing

It just works.

## Changelog
:cl:
add: На Прайм приехала уникальная партия мечей
/:cl:

2024-05-14 00:14 UTC, Furrior reviewed
Описания в говне, непонятно, почему только на прайм, если щитспавн

2024-05-14 08:28 UTC, larentoun requested changes
Логи ты можешь смотреть в дебаггере, убери их.

Совмести логику обоих компонентов в один - не нужно их так плодить, особенно компонент в компоненте.

2024-05-14 08:28 UTC, larentoun commented on modular_ss220/objects/code/components.dm
> +/datum/component/condition_locked_pickup/Initialize(required_role, ckey_whitelist)
Зачем компонент на создание компонентов? Пусть именно этот компонент и делает все функции

2024-05-14 08:28 UTC, larentoun commented on modular_ss220/objects/code/components.dm
> +	log_debug("Попытка поднять легендарный меч")
SIGNAL_HANDLER

2024-05-14 08:28 UTC, larentoun commented on modular_ss220/objects/code/components.dm
> +	if(FALSE in SEND_SIGNAL(src, COMSIG_IS_CONDITION_PASSED, user))
Сигналы так не работают. Они используют сдвиги (1 << 0).
Будет что-то около
```
if(SEND_SIGNAL(src, COMSIG_IS_CONDITION_PASSED, user) & COMPONENT_CONDITION_PASSED
```
Где COMPONENT_CONDITION_PASSED является `1 << 0`

2024-05-14 08:28 UTC, larentoun commented on modular_ss220/objects/code/components.dm
> +		user.unEquip(src, 24, silent = FALSE)
Что за 24?

2024-05-14 08:28 UTC, larentoun commented on modular_ss220/objects/code/components.dm
> +			H.apply_damage(rand(12, 24), BRUTE, pick(BODY_ZONE_L_ARM, BODY_ZONE_R_ARM))
Урон лучше в переменные компонента запихать

2024-05-14 08:28 UTC, larentoun commented on modular_ss220/objects/code/components.dm
> +/datum/component/ckey_condition/Initialize(list/_ckeys = list())
если бы в аргументе был бы (list/ckeys), то можно было бы для переменной компонента ckeys дать значение с помощью конкретного обращения к компонентой переменной
```
src.ckeys = ckeys
```
Просто на будущее

2024-05-14 08:29 UTC, larentoun commented on modular_ss220/objects/code/components.dm
> +	if(FALSE in SEND_SIGNAL(src, COMSIG_IS_CONDITION_PASSED, user))
Ну и собственно если сигнал ретурнит COMPONENT_CONDITION_PASSED

2024-05-15 20:54 UTC, larentoun commented on modular_ss220/objects/code/components.dm
> +		user.unEquip(src, pickup_damage, silent = FALSE)
Ты уверен, что это отвечает именно за урон, а не за то, что нужно игнорировать NODROP трейты? Clueless

2024-05-16 10:34 UTC, larentoun commented
Перевел в драфт. Как будет готово к ревью, убирай с драфта

2024-06-07 00:30 UTC, closed without merging