Обширное обновление дормоториев и небольшой части техов рядом.
ss220club/Paradise-SS220 pull request #1243
Opened 2024-05-22 09:08 UTC by YheWendigo

## Что этот PR делает
Перестройка дормоториев и добавление в них: фуд-корт Чанга, уменьшенное крио, театр и комнаты клоуна с мимом рядом, добавлены (наконец) комнаты для непродолжительного сна(те самые дормы для ЕРП), небольшая зелёная зона, обширные туалеты, укороченный игровой зал, чуть увеличенная качалка, перенесённый голодек, комната для покера.

## Почему это хорошо для игры
Больше возможностей к РП отыгрышу и чуть поменьбше возможностей к РП-деятельности антагов.

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/162602777/1bd8e382-1654-4c35-be86-4f8b51bc0b06)

## Тестирование

## Changelog

:cl:
add: Были добавлены новые дормы и перестроены технические тоннели рядом с ними.
del: Были удалены старые дормы и почти все намёки на них, умеренно задеты технические тоннели рядом с дормами
/:cl:

2024-05-22 14:01 UTC, Kar4es commented
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/a4f8f613-8a43-43d6-8e37-d0991f48447d)
накакал мусором

2024-05-22 14:05 UTC, dj-34 commented
Не мержить до ревью и сбора фидбека в #инфо-по-картам

2024-05-23 12:35 UTC, PhantornRU submitted a review, later dismissed
Буду ждать фидбека и правок после ТМа.
Мои косяки в принципе исправлены и мы эти Дормитории всё-таки смогли родить каким-то чудом.

2024-05-23 12:38 UTC, PhantornRU commented
Превью карты замени.

2024-05-23 13:09 UTC, Kar4es commented
1. В техах отсутствует плитка ВООБЩЕ. Немного нужно их приукрасить - голые техи такое себе.
2. Дохуя барьеров для прохода в техах. Уменьшай до одного либо убирай вообще.
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/486185ed-aa11-422a-9e8b-4cf4ff935b6a)

3. Тоже самое.
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/72327ba3-fbf8-4735-b298-9de4ba1742d8)

4. Трубы под трибуной - неудобство для инженеров. Лучше всего прокинуть по другому, дабы можно было без альтклика менять и т.д.
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/c589b35b-8f16-426f-acd6-71db4ae25556)

5. Позор этот убрать или переместить. Неоднократно говорили.
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/a0159b44-077b-4ad8-ba8a-e1e9de0ec365)

6. Нет света в крио.
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/878e68d3-13db-43b5-ba61-8b9571c505c3)

7. Крайне странное место для кнопки затемнения. 
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/5ed7bbc6-18d7-454b-be15-af386d459d01)

8. 3 одинаковых шлюза с одинаковыми тегами без возможности их болтировать. Сделай кнопки и добавь уникальные id.
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/c0972754-f3d3-4512-9356-5773eee738c4)

9. Лампочку стоит перенести, будут по ней мисскликать. 
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/688d5383-c289-42d7-bf32-b0c18c81c821)

10. Изначально открытый шкаф непонятно зачем. Стоит закрыть.
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/bdf809f3-8811-4ebf-8c0e-e31222ee6242)

11. Где симметрия.
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/e2a6ae62-3d0a-425a-9009-0ef3311aca33)

12. Проход в техи без плитки нужно, ибо у мима без плитки.
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/6bb8472f-c541-409e-880e-9dc00d6915f6)

13. Разная плитка в туалете, сделай все одним цветом. 
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/93c4a2a5-93dd-4156-b75f-2c6c7bb25bfc)

14. Мисклик плиткой? 
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/5d7c345a-bf63-4563-9255-dd977679ef91)

В целом все что заметил написал. Неплохое начало

2024-05-23 17:20 UTC, dj-34 requested changes
## 1. Общее. 
- Вот эта часть с полами (раскраска) и диванами выглядит откровенно всрато и не красиво.
Тебе следует как минимум симметрично, а возможно и пропорционально сцене расположить диваны, а также раскраску пола (включая стеклянный).

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/c2786ea8-a267-4973-a751-b124a0d1e330)

- Чтобы поправить симметрию, тебе следует подвинуть вот эту стену влево

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/d55dbaa5-b487-4bee-866a-33612d3d6584)

 и отсимметричить раскраску пола пропорционально правой части

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/971af7ff-2bfe-4667-80f2-8a5c6ffa160f)

- Center, а не Centre, ты же не француз...

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/22e31b43-934b-4753-a112-71a52de6659c)

- У тебя на toilet2 (а скорее всего и еще на что-то) приходится 4 двери. Ни в коем случаи не называй так, потому что СКОРЕЕ ВСЕГО, это уже кто-то использовал до тебя. Обязательно перепроверяй.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/48376f9f-085b-42cc-993c-ac131e8edd92)

- Я об это говорил раньше, скажу и сейчас. Писсуары, выходящие прямо напротив дверей в туалеты, это ПОЛНЫЙ ПИЗДЕЦ, анало-говнет которому нет в жизни! Срочно убрать. 
Ну и не понятно че там делает рыба. Ну засунь ты её в душевую, ради бога, если она тебе нужна.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/95da57fa-3579-4ec9-8ff8-9f8513be9e05)

- Никаких проводов под машинерией - ебля для инженера.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/50d04271-8750-485f-a285-0726b0283d97)

- Очень скучное наполнение, буквально копипаста. Две зиппо на квадратный метр, жирно как-то.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b5929603-4ed4-440c-b79b-6b6c77f0ca7c)

- У шторок выбери инстанс с anchored 1 (к сожалению, по умолчанию оно 0 и всем похуй).

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/33af1914-19f8-452a-9e9c-b878c816f6c7)

- Newscaster в стене.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/1c739275-38e7-484b-9144-fcc335ca814c)

- Лампочки на голове. Сделай их лучше слева.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/a2e65fdb-f653-40ba-98dc-57404be96d64)

- Огромное кол-во dust и dirt. Это конечно все хорошо, но оно достаточно неплохо нагружает.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/4c4e0cc7-145b-4bfd-a3b8-5125960d1c83)

- Кнопку tint control'я на стену.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/4cf215a8-584f-4b8e-959d-1445170cb1fd)

- Двойная стена. ХАРАМ.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/6bbf459f-616b-4c5e-ae3a-6eaaed3fbf35)

- Ловушку Джокира убрать следует. Это нот фанни IMO.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b0624c5c-95a6-43d8-a48c-b899d05be0d6)

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/6f16026d-8771-4a3a-8ffd-84ff764670b7)

- Честно говоря мешанина какая-то, расставь тренажерки как-то более приземленно. Можешь глянуть как выглядят реальные тренажерные залы, если не видел в жизни.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/934d2d33-f2b4-47e8-b9e5-55507f3c365a)

- Миссклик?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/47e4e7f8-72c1-4099-927e-a83e5059be81)

- АААА ПИЗДЕЦ НАСРАНО!!! Если тебе нужно с кастомным пиксель-шифтом, то используй подтип custom, и там пиксель-шифть как хочешь. Если подтипа custom нет, то у тебя есть право поплакать об этом и использовать что дают, либо попробовать использовать базовый объект, и надеяться что линтер не будет ругаться.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/4325e1c6-ff16-4b2c-8845-9ee58f01ef97)

- Ни одной камеры в туалетах? Спорно.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/5aaa1040-3d67-4462-95e9-53e4b12270a0)

- Ни одной камеры в комнатах? Это для ЕРП?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/4c255cc7-d398-4a18-a52c-717cc5f8342a) 

## 2. Чанг.

- Оно полностью повторяет кухню по машинерии (в итоге приводя кухню в не такое уж и важное место).
- Страшно покрашенная машинерия (Пупс в глаза ебется, увы).
- Пропали статуи.
- Пропало самое важное, что делало Чанга особенным, ЕГО АВТОМАТ С ЕДОЙ...
- Пропала стена(?)-табличка.

Вместо кухни, стоило бы сделать небольшую зону персонала разделенную плоскими окнами, и сидячие места (да, 1-2 столика, но хотя бы так).

- Вот эта часть выглядит очень спорно с визуальной точки зрения.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b41f0c8b-ab91-4de8-9bc1-be400f69dedc)

- Прошлая версия с двойными аирлоками выглядела лучше...но... ладно, наверное...

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/f9a03ae7-cb07-4744-81f6-821bc03c2795)

В любом случаи, поменяй скраббер с вентом местами, ибо слева у тебя УЖЕ стоит скраббер

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/c48194ab-77cc-4ef8-ba1d-512d06ec7baf)

А также сдвинь его левее, для симметрии

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/2aa414de-a4c7-4e1e-9a98-e74034d7b671)

- Tint Control вне комнаты (хочешь чтоб посетители жмакали?). А еще нет створок.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/4bc910a8-47c8-4010-a1a4-9d2498ab4a06)

- Нет никакой нужды так разворачивать noticeboard. Разверни горизонтально.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/e39d913a-773e-4506-869d-f4220dfd53c2)

## 3. Теха ботаники.

- Опять же возвращаемся к наполнению - в техах нам предоставляют абсолютно всё, чтобы ботаника стала не такой уж и нужной.
- Повернутые NPC. Харам. Это не имеет никакого смысла и плодит лишние инстансы.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/9fd77b02-bf05-4b49-98b2-2bd0b641a0bf)

- Эта кринжа все еще выглядит неуместно.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/c23e63e4-f7d2-4bd4-8123-6fd583f760a7)

Я понимаю её значение, но по крайней мере она не должна находиться здесь. Если уж так хочется, перенеси её сюда. Я думаю это будет ВПОЛНЕ приемлемый компромисс. Просто поменяй наполнение местами.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/2eb1764a-8568-4e9f-b2ba-ab955482235e)

## 4. Сцена.

- Я так понимаю ты не сверялся с оригиналом, и подзабыл, что у клоуна и мима были уникальные вещи, которые, как можно предположить, отсутствуют у тебя.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/5c789ec8-b29e-4393-84d3-450f268e92f9)

- Возможно здесь не были бы лишним тройку деревянных стульчиков, для какой-нибудь условной сценки

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/ba007354-7020-4987-a1b6-24a7e9249168)

- Для этого у нас есть отдельный тип пола "stairs"

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/f53af493-c346-4fe2-9209-b5d0d06a736d)

2024-06-03 17:03 UTC, AyIong approved these changes
Вроде всё ок, пару раз прошёлся, под стенами посмотрел, но зона огромная, 100% проебал что-то

2024-06-07 19:06 UTC, dj-34 approved these changes
Все равно буду просматривать потом и дополнять. Тесты показали что всё (вроде) окей.

2024-06-07 20:12 UTC, merged