Add: Explorer штуки
ss220club/Paradise-SS220 pull request #1257
Opened 2024-05-28 19:25 UTC by Kar4es

## Что этот PR делает
Добавил на карты новое снаряжение исследователей.

## Почему это хорошо для игры
Хз, гейты все еще есть

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/af0e8c12-4583-4f9a-9a0b-1e42953f566e)
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/e0ce5409-069a-48d4-900f-8b03d8d67c86)
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/9bde28e6-3add-40c7-887e-ca8d683aaf03)

## Тестирование
Нет

## Changelog

:cl:
add: Добавлено недостающее снаряжение исследователей. Теперь у них отдельные комнаты, помимо гейта (только на коробке).
/:cl:

2024-05-28 19:29 UTC, dj-34 requested changes

2024-05-28 19:29 UTC, dj-34 commented on modular_ss220/maps220/code/Station/station_areas.dm
> +	name ="Гейт"
```suggestion
	name = "Гейт"
```

2024-05-28 19:49 UTC, dj-34 approved these changes

2024-05-29 00:39 UTC, AyIong requested changes
На дельте это лишнее, вообще диффбот дельты не чистый 
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/3786d366-49dd-4dcc-b4d6-01a06d3f309a)

А не чистый скорее всего потому что кто-то накакал
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/012412c9-8948-4f97-adaa-49f4457ae9ae)

На мете я бы поменял местами принтер и флаг
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/8cecefa9-3ee5-49fb-9f19-50ca85640727)

Остальное завтра чекну, поздно уже

2024-05-29 12:41 UTC, AyIong approved these changes
Не вижу файралярмы
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/a3ecde55-f12a-41e5-9198-5861f45ce4b0)

А так всё ок

2024-05-29 13:26 UTC, merged