Add: ss220 spaceruin loot
ss220club/Paradise-SS220 pull request #1258
Opened 2024-05-29 14:36 UTC by konushi

## Что этот PR делает

Накидал немного нового для исследователей на наши руины.

## Почему это хорошо для игры

Есть смысл заглядывать на них ради специализированного лута.

## Изображения изменений

## Тестирование

Локалка

## Changelog

:cl:
add: На наши космо руины добавлен новый лут для исследователей.
/:cl:

2024-05-29 15:05 UTC, dj-34 commented
А для гейта?

2024-05-29 15:48 UTC, konushi commented
> А для гейта?

Адельна, но могу и в этом

2024-05-29 16:19 UTC, dj-34 requested changes
Жду изменений на Мете и в гейтах, и хотелось бы чтобы ты ручной телепортер на Дельте переместил куда-то сюда, а не в комнату тех. обслуживания.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/94aedf8c-5526-461b-b4ae-9422130acc20)

2024-06-02 03:59 UTC, dj-34 approved these changes

2024-06-02 13:15 UTC, AyIong approved these changes

2024-06-02 13:16 UTC, merged