Изменение ABOTCH research space station.
ss220club/Paradise-SS220 pull request #1278
Opened 2024-06-02 09:54 UTC by tsoivecen199015

## Что этот PR делает

Меняет старый АБОТЧ на новый, добавляя предметы и локации.

Мостик, бриг и ботаника были вынесены за пределы основного отдела.
Мостик:
На столе енфорсер, с парой магазинов на боевых патронах, и одним на резиновых.
Бумага и ручки разных цветов, флаги НТ. Бесплатные сигареты в углу, стационарный ГПС, лом и золотая монета, так же две криокапсулы и чёрные ящики с отчётами. Так же добавлен принтер и шредер. Единственный интерком.
Дорматории:
Сверху кровати, уборная, там же компьютер общего пользования, и прочие предметы.
Вместо гидропоники расположены криокапсулы, чуть ниже кухня, в которой добавлено много техники, а ещё ниже столовая.
Слева техническая комната со СМЭСами и генераторами, справа комната переработки мусора, в которую врезались хайвботы.
Гидропоника:
Слева снизу от основной части станции, есть две коровы, два вендомата, и куча разных семян, основными из которых будут амброзия, и светошляпник.
Бриг:
Снизу от всей станции, добавлен карцер, гардероб СБ с дубинками и куртками, солнцезащитными очками и флешерами. Справа камеры, снизу оружейная и комната вардена. В оружейную добавлен дробовик, патроны к нему, скафандр, и прочее снаряжение СБ.
РНД:
Справа от основной станции, вокруг хранилища расположено оборудование, а посередине само хранилище, в которое добавлено ядро мехов, документы, чертежи.
В самой правой части плавильная печь, сверху солнечные панели.
Медицинский отдел, и атмос:
Слева от основной станции, разрушено хайвботами, остатки снаряжение инженерии снизу, сверху остатки медицинского отдела.
Окружение:
Пещеры с карпами. в которых лежит труп шахтёра с его картой.

## Почему это хорошо для игры

Это хорошо потому что новая карта, выглядит лучше, чем прошлая, детали добавляют погружения, а вроде обыденные интеркомы, и ГПСы, на мостике добавляют ему хоть какую-то функциональность, больше простора для РП.

## Изображения изменений

![StrongDMM-2024-06-02 12 03 11](https://github.com/ss220club/Paradise-SS220/assets/167395684/6e943dd3-bba4-4ba9-b493-8734aedbfda0)

## Тестирование

Я тестировал карту запуская её на локальном сервере. Нашёл некоторые ошибки и исправил их.

## Changelog

:cl:
add: Новые локации, предметы, механизмы.
tweak: Поменял карту.
/:cl:

2024-06-02 11:25 UTC, dj-34 commented
ёбаться всраться, ты реально через dreammaker маппил?

2024-06-02 11:28 UTC, dj-34 commented
> Да нет вроде, как это у меня так получается то а? Я через СтронгДММ делал...

в префах так стоит?
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/402c6225-c45a-492c-a158-cabd03cae432)

2024-06-02 11:29 UTC, tsoivecen199015 commented
Нет, ДММ

2024-06-02 11:59 UTC, tsoivecen199015 commented
> > Да нет вроде, как это у меня так получается то а? Я через СтронгДММ делал...
> 
> в префах так стоит? ![image](https://private-user-images.githubusercontent.com/20109643/335861309-402c6225-c45a-492c-a158-cabd03cae432.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMjk4NDAsIm5iZiI6MTcxNzMyOTU0MCwicGF0aCI6Ii8yMDEwOTY0My8zMzU4NjEzMDktNDAyYzYyMjUtYzQ1YS00OTJjLWExNTgtY2FiZDAzY2FlNDMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDExNTkwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlZGE0NjNjN2IxYjM2NWMzZjBmZDFjNjY5OThmYzVkMzFkYjNjYzExZjliZTk2ZGVjOWI2ZTBlM2E0MTJlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.39icA3HmC5JqSwsDajS-yC-d43BfE4_APXUiHoo2ve4)

Готово, заменено

2024-06-02 13:18 UTC, AyIong commented
Фикси это
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/da987789-c538-4432-8171-35a45ecd5b4b)

И это 
https://github.com/ss220club/Paradise-SS220/actions/runs/9338034182/job/25700677736?pr=1278#step:8:205

2024-06-02 13:19 UTC, AyIong commented
И ещё, назови карту нормально, без вот этого NEW

2024-06-02 13:39 UTC, tsoivecen199015 commented
> Фикси это ![image](https://private-user-images.githubusercontent.com/69762909/335868230-da987789-c538-4432-8171-35a45ecd5b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzU0MjksIm5iZiI6MTcxNzMzNTEyOSwicGF0aCI6Ii82OTc2MjkwOS8zMzU4NjgyMzAtZGE5ODc3ODktYzUzOC00NDMyLTgxNzEtMzVhNDVlY2Q1YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEzMzIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODViYTAwZTE2Yjk0ZDVlODk3ODdhMTQwOTMzNGRhMzljZDMwMDg0NzNiZmU3NjVmZmVjNWVjZWMwNDgyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wzl46u3F7rWkr_ImLAhBBIfoxy0RoEscGZw72k4rK4)
> 
> И это https://github.com/ss220club/Paradise-SS220/actions/runs/9338034182/job/25700677736?pr=1278#step:8:205

И как это блять фиксить ААААААААААААААААА
Попытаюсь

2024-06-02 13:48 UTC, tsoivecen199015 commented
А блять, дубликаты, я думал что то серьёзнее.

2024-06-02 13:50 UTC, dj-34 commented
> > Фикси это ![image](https://private-user-images.githubusercontent.com/69762909/335868230-da987789-c538-4432-8171-35a45ecd5b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzU0MjksIm5iZiI6MTcxNzMzNTEyOSwicGF0aCI6Ii82OTc2MjkwOS8zMzU4NjgyMzAtZGE5ODc3ODktYzUzOC00NDMyLTgxNzEtMzVhNDVlY2Q1YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEzMzIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODViYTAwZTE2Yjk0ZDVlODk3ODdhMTQwOTMzNGRhMzljZDMwMDg0NzNiZmU3NjVmZmVjNWVjZWMwNDgyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wzl46u3F7rWkr_ImLAhBBIfoxy0RoEscGZw72k4rK4)
> > И это https://github.com/ss220club/Paradise-SS220/actions/runs/9338034182/job/25700677736?pr=1278#step:8:205
> 
> И как это блять фиксить ААААААААААААААААА Попытаюсь

литерали просто путь сменить до tower/long и tower/short

2024-06-02 13:59 UTC, tsoivecen199015 commented
> > > Фикси это ![image](https://private-user-images.githubusercontent.com/69762909/335868230-da987789-c538-4432-8171-35a45ecd5b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzU0MjksIm5iZiI6MTcxNzMzNTEyOSwicGF0aCI6Ii82OTc2MjkwOS8zMzU4NjgyMzAtZGE5ODc3ODktYzUzOC00NDMyLTgxNzEtMzVhNDVlY2Q1YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEzMzIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODViYTAwZTE2Yjk0ZDVlODk3ODdhMTQwOTMzNGRhMzljZDMwMDg0NzNiZmU3NjVmZmVjNWVjZWMwNDgyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wzl46u3F7rWkr_ImLAhBBIfoxy0RoEscGZw72k4rK4)
> > > И это https://github.com/ss220club/Paradise-SS220/actions/runs/9338034182/job/25700677736?pr=1278#step:8:205
> > 
> > 
> > И как это блять фиксить ААААААААААААААААА Попытаюсь
> 
> литерали просто путь сменить до tower/long и tower/short

Где и как

2024-06-02 14:10 UTC, dj-34 commented
> > > > Фикси это ![image](https://private-user-images.githubusercontent.com/69762909/335868230-da987789-c538-4432-8171-35a45ecd5b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzU0MjksIm5iZiI6MTcxNzMzNTEyOSwicGF0aCI6Ii82OTc2MjkwOS8zMzU4NjgyMzAtZGE5ODc3ODktYzUzOC00NDMyLTgxNzEtMzVhNDVlY2Q1YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEzMzIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODViYTAwZTE2Yjk0ZDVlODk3ODdhMTQwOTMzNGRhMzljZDMwMDg0NzNiZmU3NjVmZmVjNWVjZWMwNDgyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wzl46u3F7rWkr_ImLAhBBIfoxy0RoEscGZw72k4rK4)
> > > > И это https://github.com/ss220club/Paradise-SS220/actions/runs/9338034182/job/25700677736?pr=1278#step:8:205
> > > 
> > > 
> > > И как это блять фиксить ААААААААААААААААА Попытаюсь
> > 
> > 
> > литерали просто путь сменить до tower/long и tower/short
> 
> Где и как

Через VScode, открыв DMM там

2024-06-02 14:23 UTC, tsoivecen199015 commented
> > > > > Фикси это ![image](https://private-user-images.githubusercontent.com/69762909/335868230-da987789-c538-4432-8171-35a45ecd5b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzU0MjksIm5iZiI6MTcxNzMzNTEyOSwicGF0aCI6Ii82OTc2MjkwOS8zMzU4NjgyMzAtZGE5ODc3ODktYzUzOC00NDMyLTgxNzEtMzVhNDVlY2Q1YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEzMzIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODViYTAwZTE2Yjk0ZDVlODk3ODdhMTQwOTMzNGRhMzljZDMwMDg0NzNiZmU3NjVmZmVjNWVjZWMwNDgyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wzl46u3F7rWkr_ImLAhBBIfoxy0RoEscGZw72k4rK4)
> > > > > И это https://github.com/ss220club/Paradise-SS220/actions/runs/9338034182/job/25700677736?pr=1278#step:8:205
> > > > 
> > > > 
> > > > И как это блять фиксить ААААААААААААААААА Попытаюсь
> > > 
> > > 
> > > литерали просто путь сменить до tower/long и tower/short
> > 
> > 
> > Где и как
> 
> Через VScode, открыв DMM там

А где из 24 тысяч строчек находится это? Или я не там смотрю? Новичёк просто. Объясни пожалуйста.

2024-06-02 19:48 UTC, tsoivecen199015 commented
> > > > > Фикси это ![image](https://private-user-images.githubusercontent.com/69762909/335868230-da987789-c538-4432-8171-35a45ecd5b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTczMzU0MjksIm5iZiI6MTcxNzMzNTEyOSwicGF0aCI6Ii82OTc2MjkwOS8zMzU4NjgyMzAtZGE5ODc3ODktYzUzOC00NDMyLTgxNzEtMzVhNDVlY2Q1YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAyVDEzMzIwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhODViYTAwZTE2Yjk0ZDVlODk3ODdhMTQwOTMzNGRhMzljZDMwMDg0NzNiZmU3NjVmZmVjNWVjZWMwNDgyZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8wzl46u3F7rWkr_ImLAhBBIfoxy0RoEscGZw72k4rK4)
> > > > > И это https://github.com/ss220club/Paradise-SS220/actions/runs/9338034182/job/25700677736?pr=1278#step:8:205
> > > > 
> > > > 
> > > > И как это блять фиксить ААААААААААААААААА Попытаюсь
> > > 
> > > 
> > > литерали просто путь сменить до tower/long и tower/short
> > 
> > 
> > Где и как
> 
> Через VScode, открыв DMM там

Звучит просто, но на деле, где это? Тут 24 тысячи строчки.

2024-06-02 20:04 UTC, tsoivecen199015 commented
Боже мой, ссаные тряпки
Ошибка из за тряпок... мда.

2024-06-02 20:46 UTC, tsoivecen199015 commented
Ура
Ошибок нету, наконец-то.

2024-06-03 01:22 UTC, AyIong commented
Боже... что ты делал?

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/6d9a1b49-1da4-416c-8489-9562904ace51)

2024-06-03 05:41 UTC, dj-34 requested changes
Саму карту посмотрю позже

2024-06-03 05:41 UTC, dj-34 commented on modular_ss220/maps220/code/RandomRuins/space/space_ruins.dm
> +	allow_duplicates = FALSE
Она у тебя никогда не будет спавниться без always_place
```suggestion
	allow_duplicates = FALSE
	always_place = TRUE
```

2024-06-03 05:41 UTC, dj-34 commented on modular_ss220/maps220/code/RandomRuins/space/space_ruins.dm
> +	suffix = "ABOTCH_RSN.dmm"
Всё в snake case, и description, конечно, оставляет желать лучшего
```suggestion
/datum/map_template/ruin/space/abotch_rsn
	name = "Nanotrasen ABOTCH Research Station"
	id = "abotch_rsn.dmm"
	description = "ABOTCH_THETA_CHARLIE"
	prefix = "_maps/map_files220/RandomRuins/SpaceRuins/"
	suffix = "abotch_rsn.dmm"
```

2024-06-03 05:41 UTC, dj-34 commented on config/example/config.toml
> + 	"_maps/map_files220/RandomRuins/SpaceRuins/ABOTCH_RSN.dmm",
Название карты в snake case. Файл тоже переименовать
```suggestion
 	"_maps/map_files220/RandomRuins/SpaceRuins/abotch_rsn.dmm",
```

2024-06-03 05:42 UTC, dj-34 commented
Чейнджлог внятно напиши

2024-06-03 05:43 UTC, dj-34 commented
Приложи в изображениях версию До, поэтому что по факту изменилось нам не увидеть, мапдифф естесна тут не поможет

2024-06-03 12:22 UTC, dj-34 commented
> > Приложи в изображениях версию До, потому что по факту изменения нам не увидеть, мапдифф естесна тут не поможет
> 
> Их и не увидеть, это было исправление дубликатов объектов в одном тайле.

я говорю про общие изменения, чтобы я видел версию до и после

2024-06-03 12:26 UTC, tsoivecen199015 commented
> > > Приложи в изображениях версию До, потому что по факту изменения нам не увидеть, мапдифф естесна тут не поможет
> > 
> > 
> > Их и не увидеть, это было исправление дубликатов объектов в одном тайле.
> 
> я говорю про общие изменения, чтобы я видел версию до и после

Понятно.

2024-06-04 09:18 UTC, dj-34 commented
Я всё еще жду скриншоты карты до изменений в "Изображения изменений"

2024-06-04 11:35 UTC, tsoivecen199015 commented
> Я всё еще жду скриншоты карты до изменений в "Изображения изменений"

Как я тебе их скину если я уже изменения сохранил... или ты про старый Аботч?

2024-06-05 06:09 UTC, tsoivecen199015 commented
Changes requested
1 review requesting changes by reviewers with write access. 
Чё это, и как убрать, это мешает мерджу?

2024-06-05 16:21 UTC, AyIong commented
> Changes requested 1 review requesting changes by reviewers with write access. Чё это, и как убрать, это мешает мерджу?

нет

2024-06-06 18:00 UTC, tsoivecen199015 commented
> Хотелось бы видеть хоть один фонарик и мультитул. (Те что на скринах - щитспавн)
> 
> Застрял в двух невидимых стенах. ![Застрял](https://private-user-images.githubusercontent.com/87367109/337322660-82bffeef-35e2-4148-ba77-2a34d2d4e1c0.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTY5MDAsIm5iZiI6MTcxNzY5NjYwMCwicGF0aCI6Ii84NzM2NzEwOS8zMzczMjI2NjAtODJiZmZlZWYtMzVlMi00MTQ4LWJhNzctMmEzNGQyZDRlMWMwLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE3NTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIyZmM5MTZkMTJjYjQ3OGY4NTllNmFlN2E0OWRkZGZjZjk5YjE3MjA2MTJjNGZkZTNmZTdhZWY2Yjc3MGUzNDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gVxYYOrSk8axHA1hvf7uSA5EUUnWbhKuepy0b0ff3Nk) ![невидимая стена](https://private-user-images.githubusercontent.com/87367109/337322664-9b67952d-732d-447d-9758-0ddbe53cf707.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTY5MDAsIm5iZiI6MTcxNzY5NjYwMCwicGF0aCI6Ii84NzM2NzEwOS8zMzczMjI2NjQtOWI2Nzk1MmQtNzMyZC00NDdkLTk3NTgtMGRkYmU1M2NmNzA3LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE3NTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc4YjQzYmVkZjcyZjg0M2ZmODUyNTA1NjQ0MjNhMWFiZTA5NmNjMTU1OWI4Y2Q2ZmVjMTFlN2NlN2Y0ZThkMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XfbWclUrZ-4JL4mNe8F7kq-vxL0v4K7HWyol0xoVoOQ)
> 
> В инженерку имхо стоит добавить хотя бы одну лампочку, ![темнота](https://private-user-images.githubusercontent.com/87367109/337326412-45b0f230-8ccd-4b1d-a742-1b7aea06ff4a.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTY5MDAsIm5iZiI6MTcxNzY5NjYwMCwicGF0aCI6Ii84NzM2NzEwOS8zMzczMjY0MTItNDViMGYyMzAtOGNjZC00YjFkLWE3NDItMWI3YWVhMDZmZjRhLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE3NTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxZGRmMGU3ZGZhMTUwYzI4NDRjMmQ2ZjQzOTM3MmFlYjg3MjY1MTYxNmUyYzc3N2VlZWZlMTI3NmNhMjU0OTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CO3Dcg23f4uzfowV7PK0E2baH9aHbw5Xnb5U14ILouQ)
> 
> Веселые ребята приехали в гости ДО снятия локдауна (у них есть доступ открывать как минимум синие двери самостоятельно). Какой смысл в локдауне, если можно буквально всю территорию станции посетить ДО его снятия? ![пришел сам по себе](https://private-user-images.githubusercontent.com/87367109/337326997-4256af2c-e14c-4b83-bedc-85455d05fbea.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTY5MDAsIm5iZiI6MTcxNzY5NjYwMCwicGF0aCI6Ii84NzM2NzEwOS8zMzczMjY5OTctNDI1NmFmMmMtZTE0Yy00YjgzLWJlZGMtODU0NTVkMDVmYmVhLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE3NTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZTkwOWQ0MDM0ZmFmZDMxZWU1M2JlOWRlMjQ2ZGE0MTZjNmQwNjIxOTgwZmNlZDhkNGI1M2ZiZGE0NGZmNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ESlyKtjZjSJw2x1i19shMazzEndExr5on0_yEI_an74) ![приехали](https://private-user-images.githubusercontent.com/87367109/337327010-77017276-194d-4055-b0be-86ce10d6147c.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTY5MDAsIm5iZiI6MTcxNzY5NjYwMCwicGF0aCI6Ii84NzM2NzEwOS8zMzczMjcwMTAtNzcwMTcyNzYtMTk0ZC00MDU1LWIwYmUtODZjZTEwZDYxNDdjLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE3NTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyOWVjYjBiMThkMzQ3MDFhZDRmOTU0MDg1NjI4NDU3NDM0NTM1YzM3MjQ4Mzk1MTI5MmFkZGM3MDQxMDc3YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3Lw9m0YoClybq4_Q3gVvTtBYif325cMYjauiFrlHEGs)
> 
> Под окном нет провода - невозможно запитать апц в командном отсеке и снять локдаун после того, как апц разрядился. ![Под окном нет провода](https://private-user-images.githubusercontent.com/87367109/337329626-d70f7a95-d58d-4bfa-8371-c59515247578.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTY5MDAsIm5iZiI6MTcxNzY5NjYwMCwicGF0aCI6Ii84NzM2NzEwOS8zMzczMjk2MjYtZDcwZjdhOTUtZDU4ZC00YmZhLTgzNzEtYzU5NTE1MjQ3NTc4LkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE3NTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQyNDdiMTQzODAxMDljMGUwNjc0MTYwYTg2ZjY3MTIxNzU4YzQ0NDdiOWJmNDUzMGFjMjhjNDQ1NGY2ZWZhNTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.F_PdcTW1UJMRcynyNSeqYgJiHOGhzzDp5rTOjN1Zys8)
> 
> Правая деливери труба командного отсека выплевывает тебя наружу с обеих сторон не позволяя ей воспользоваться. Предметы просто пожирает, не выплевывая их с какой либо из сторон. ![Правая деливери труба](https://private-user-images.githubusercontent.com/87367109/337331325-0745dfb5-12f1-4346-a372-6e3a03c0295a.JPG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2OTY5MDAsIm5iZiI6MTcxNzY5NjYwMCwicGF0aCI6Ii84NzM2NzEwOS8zMzczMzEzMjUtMDc0NWRmYjUtMTJmMS00MzQ2LWEzNzItNmUzYTAzYzAyOTVhLkpQRz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA2VDE3NTY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU5ZGEzODQ0NDUxNWVkNjJiZGIyMzg1NDM1NDY4ODhhM2E0M2UwYjEwMTU5NjVmNDkxNzE5YjNlMjNiMWFlYjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.EUSiVPQozMWspf7_Q_nEq9urBYu9t9b9J3AS8S9E4XA)

Исправлено

2024-06-07 03:12 UTC, AyIong requested changes
36 карпов, не дохуя ли? Уменьши до 20 хотя бы
<details>

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/619351f5-4aa1-42a1-b858-99abfc82db0f)

</details>

Замени пол на безвоздушный там где не должно быть воздуха, иначе игра будет выкачивать воздух сама, из-за чего будут лаги несколько минут у всех.
/turf/simulated/floor/plating -> /turf/simulated/floor/plating/airless
<details>

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/17c68023-3485-44ea-a526-8a7c819f3cbc)

</details>

Странное решение с этим дымком, канистры с воздухом к слову не пустые
<details>

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/8cbdd7d3-dc42-4315-8715-66f93c0baa7d)

</details>

Я конечно ничего не имею против грязи и пыли, но это пиздец, СЛИШКОМ ДОХУЯ
Урезай, и делай красиво, а не просто засирай каждый тайл грязью, плюс удали дубликаты грязи (несколько декалей грязи на одном тайле), даже под окнами, ты с ума сошёл?
<details>

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/2cc55ac2-a61c-43fd-acdd-e077887d9565)
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/3903d12c-22a1-4f2e-88ed-a1e8f2c482f2)

</details>

65 хайвботов, я очень сильно бомбил на то, что на оффовском аботче их 85, а тут мало того что карпы так ещё и хайвботы которые сука грузят сервер.
Кхм, ладно, оставь штук 15-20, и не в одном месте, не надо фанатизма

<details>

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/8775b4ce-b6ba-4adf-a50a-e9cfbf31bc9d)

</details>

И вот эту хуйню убери полностью
<details>

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/7aa87320-bb94-4042-988e-befd2f10be10)

</details>

Не стоит использовать эти файрлоки
<details>

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/37797fad-c260-4131-bac9-897c1f160ba2)

</details>

Это убрать
<details>

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/155e9a21-87be-46fd-94c6-cfe4be4ea647)

</details>

Во первых, повешай GPS на стену. 
Во вторых, убери двойные окна
В третьих, убери провода/трубы проходящие через стены под стенами, это кринге и нарушение стандартов

<details>

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/0b9fcc18-383a-4ea9-8cb4-eed7dea8fc35)

</details>


ООО БЛЯ, а мы и не думали! Теслу в мусор, это вообще пиздец, документы НТ тоже, хайриск, ну и лапу по центру повешай нормально

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/60ccd44f-4c28-44c4-a7ad-d4adab163b18)

2024-06-07 07:54 UTC, tsoivecen199015 commented
> 36 карпов, не дохуя ли? Уменьши до 20 хотя бы
> 
> Замени пол на безвоздушный там где не должно быть воздуха, иначе игра будет выкачивать воздух сама, из-за чего будут лаги несколько минут у всех. /turf/simulated/floor/plating -> /turf/simulated/floor/plating/airless
> 
> Странное решение с этим дымком, канистры с воздухом к слову не пустые
> 
> Я конечно ничего не имею против грязи и пыли, но это пиздец, СЛИШКОМ ДОХУЯ Урезай, и делай красиво, а не просто засирай каждый тайл грязью, плюс удали дубликаты грязи (несколько декалей грязи на одном тайле), даже под окнами, ты с ума сошёл?
> 
> 65 хайвботов, я очень сильно бомбил на то, что на оффовском аботче их 85, а тут мало того что карпы так ещё и хайвботы которые сука грузят сервер. Кхм, ладно, оставь штук 15-20, и не в одном месте, не надо фанатизма
> 
> И вот эту хуйню убери полностью
> 
> Не стоит использовать эти файрлоки
> 
> Это убрать
> 
> Во первых, повешай GPS на стену. Во вторых, убери двойные окна В третьих, убери провода/трубы проходящие через стены под стенами, это кринге и нарушение стандартов
> 
> ООО БЛЯ, а мы и не думали! Теслу в мусор, это вообще пиздец, документы НТ тоже, хайриск, ну и лампу по центру - повешай нормально а двери обесточить
> 
> ![image](https://private-user-images.githubusercontent.com/69762909/337507767-60ccd44f-4c28-44c4-a7ad-d4adab163b18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3NDcwMTQsIm5iZiI6MTcxNzc0NjcxNCwicGF0aCI6Ii82OTc2MjkwOS8zMzc1MDc3NjctNjBjY2Q0NGYtNGMyOC00NGM0LWE3YWQtZDRhZGFiMTYzYjE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA3VDA3NTE1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YjE5MzkxMWFjMjRlMGY5MTU0Nzk2NjdjOTYyODVhNjdmZmRmNjIxODEyYWEyMzRlNTM5NzhlYWE3OWQ4YTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4k8ENqMupDP3nUW078kKndGE720k8Czrb72-aQXiEAU)

Теслу в мусор? В оригинале она была, её запускали.

2024-06-07 09:44 UTC, tsoivecen199015 commented
Готово.

2024-06-07 09:48 UTC, tsoivecen199015 commented on modular_ss220/maps220/code/RandomRuins/space/space_ruins.dm
> +	description = "ABOTCH_THETA_CHARLIE"
**Нет** :)

2024-06-07 16:00 UTC, tsoivecen199015 commented
На шо он ругается, так...

2024-06-07 18:07 UTC, tsoivecen199015 commented
Где ошибка... не могу понять

2024-06-07 18:33 UTC, tsoivecen199015 commented
Я даже не удалил половины карты, а ошибку решил, хы.

2024-06-07 19:10 UTC, dj-34 commented on modular_ss220/maps220/code/RandomRuins/space/space_ruins.dm
> +	description = "ABOTCH_THETA_CHARLIE"
дескрипшен въебаный, это факт

2024-06-09 09:41 UTC, PhantornRU approved these changes

2024-06-09 12:00 UTC, closed without merging