Обновление камеры хранения ИИ.
ss220club/Paradise-SS220 pull request #1280
Opened 2024-06-02 13:43 UTC by YheWendigo

## Что этот PR делает
Фиксит уязвимость ИИ перед противниками которые заберутся прямо к ИИ в коридорчик 1x3.

## Почему это хорошо для игры
ИИ может спать спокойно во время культа.

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/162602777/d9a4e0f8-1697-478b-b481-87372c92d12d)

## Тестирование
Всё работает исправно.

## Changelog

:cl:
add: Укрепление камеры хранения ИИ
add: Добавлена возможность закрыть новоприобретённые окна в камере ИИ
/:cl:

2024-06-02 15:51 UTC, dj-34 requested changes
У меня ща голова лопнет от расположения кнопки сверху, сделай вот так:
Убери pixel_x у интеркома и кнопки и подними интерком до 34 пикселей

И приподними флешку справа на 1 пиксель, чтобы было pixel_y 24

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/1ae6ac3e-af9b-4354-819b-61606fd9175a)

2024-06-02 19:54 UTC, AyIong requested changes
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/5890081b-7f84-4320-8898-855b734eafe3)

Куда аир алярму подвинул?

2024-06-03 14:43 UTC, dj-34 requested changes

2024-06-03 14:43 UTC, dj-34 commented on _maps/map_files220/stations/boxstation.dmm
> +	},
НИКОГДА так не делай
```suggestion
/obj/item/radio/intercom/custom{
	pixel_y = 34
	},
```

2024-06-04 09:17 UTC, dj-34 approved these changes

2024-06-04 09:17 UTC, dj-34 commented
Резолви, когда считаешь что исправил

2024-06-08 20:48 UTC, AyIong approved these changes

2024-06-08 20:48 UTC, merged