Внедрение новых инструментов
ss220club/Paradise-SS220 pull request #1282
Opened 2024-06-02 18:30 UTC by msw7007

## Что этот PR делает

Меняет добавленный ранее музыкальный автомат в виде барабанных установок на новый (концертная колонка), позволяет этой колонке посылать сигналы на другие бутафорские колонки для их синхронизации.
Добавляет новые инструменты (спрайты, звуки, механика), добавляет возможность брать их в лодауте, в автомате мерча НТ, заказывать в карго.

## Почему это хорошо для игры

Добавит станции новое звучание, разнообразит геймплей с точки зрения музыкального взаимодействия
Позволит провести ивент-концерт

## Изображения изменений

https://youtu.be/XGJU8BY15fY

## Тестирование

Проверял на локальном сервере

## Changelog

:cl:
add: Новые инструменты (барабаны, бас-гитара, рок-гитара)
add: Концертная установка как новый музыкальный автомат
add: Концертная колонка - дополнительный предмет, который проигрывает анимацию при запуске/остановки музыки на концертной установке
add: Новые позиции в автомате мерча НТ (бас-гитара, рок-гитара, барабаны)
add: Новые позиции в лодауте (бас-гитара, рок-гитара в инструментах, гитара Арии в доноры, куртка Арии в доноры)
add: Новый груз в карго (Концертный реквизит Саундхенд)
del: Барабаны из набора карго "Big Band Instruments"
del: Барабаны как музыкальный автомат
/:cl:

2024-06-03 06:04 UTC, dj-34 requested changes
В конце всех desc проставить точки, в name убрать заглавные буквы (если это не имя собственное), все перевести в snake_case, добавить недостающие desc, убрать накаканое, поправить и изменить пути, отработать по ревью.

2024-06-03 06:04 UTC, dj-34 commented on modular_ss220/instruments/obj/structures/drums.dm
> +	var/stat = 0
Закомментировать что оно делает по примеру
```DM
/// This is your description
var/stat = 0
```

2024-06-03 06:04 UTC, dj-34 commented on modular_ss220/jukebox/_jukebox.dme
> +// BEGIN_INCLUDE
Насрано, смотреть моё ревью выше

2024-06-03 06:04 UTC, dj-34 commented on modular_ss220/jukebox/code/jukebox_subtypes.dm
> +	name = "\improper концертная установка"
```suggestion
	name = "\proper концертная установка"
```

2024-06-03 06:04 UTC, dj-34 commented on modular_ss220/jukebox/code/jukebox_subtypes.dm
> +	desc = "Концертная колонка, которая используется для воспроизведения концертной записи"
```suggestion
	desc = "Концертная колонка, которая используется для воспроизведения концертной записи."
```

2024-06-03 06:26 UTC, msw7007 commented on modular_ss220/clothing/code/suits.dm
> +
Отработано, сразу хочу уточнить, в фрагменте:
/datum/supply_packs/misc/soundhand
	name = "Soundhand Fan Crate"
	contains = list(/obj/item/clothing/suit/storage/soundhand_black_jacket,
					/obj/item/clothing/suit/storage/soundhand_olive_jacket,
					/obj/item/clothing/suit/storage/soundhand_brown_jacket)
	cost = 600
	containername = "soundhand fan crate"
	
Имя (Name) тоже тогда желательно с маленькой буквы?

2024-06-04 08:13 UTC, dj-34 requested changes
Поправь названия gitara -> guitar
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/2e9bc1a8-d737-4ccf-bd00-b8ea7e8d6d2c)

2024-06-04 08:13 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	desc = "Фанатская коричневая куртка группы Саундхэнд"
Перепроверь везде маленькую букву
```suggestion
	desc = "фанатская коричневая куртка группы Саундхэнд"
```

2024-06-04 08:13 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	desc = "Редкая серебристая куртка Саундхенд. Ограниченная серия."
Ну ты либо напиши везде Саундхенд, либо везде Саундхэнд
```suggestion
	name = "серебристая куртка группы Саундхэнд"
	desc = "Редкая серебристая куртка Саундхэнд. Ограниченная серия."
```

2024-06-04 08:13 UTC, dj-34 commented on modular_ss220/clothing/_clothing.dme
> +// BEGIN_INCLUDE
Так и не убрал накаканое

2024-06-04 08:13 UTC, dj-34 commented on modular_ss220/instruments/_instruments.dme
> +#include "obj\structures\drums.dm"
Так и не исправил пути

2024-06-04 08:13 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	name = "soundhand fan crate"
У саплаев каждое слово с заглавной буквы, смотрим на оригиналы
```suggestion
	name = "Soundhand Fan Crate"
```

2024-06-04 08:13 UTC, dj-34 commented on modular_ss220/clothing/_clothing.dme
> +#include "code\under.dm"
\ так и не вернул в /

2024-06-04 08:15 UTC, dj-34 requested changes

2024-06-04 08:15 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	desc = "Фанатская черная куртка группы Саундхэнд"
Desc повторяет name, я даже перепутал при ревью. Поменяй, или дополни. Про точки в конце desc'а не забывай

2024-06-04 08:15 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	desc = "Фанатская оливковая куртка группы Саундхэнд"
Здесь также desc повторяет name

2024-06-08 20:47 UTC, AyIong reviewed
Начнём с того, что жукбокс накидывает кучу лагов
Продолжим тем, что он хуёво работает в движении
На этом и закончим, я против
Плюс музыку надо в конфиг добавить хэдэдэ, и сжать нормально

2024-06-15 19:30 UTC, Gaxeer commented on modular_ss220/jukebox/code/jukebox_datum.dm
> +	for(var/datum/track/new_track as anything in subtypesof(/datum/track/soundhand/))
```suggestion
	for(var/datum/track/new_track as anything in subtypesof(/datum/track/soundhand))
```

2024-06-15 19:31 UTC, Gaxeer commented on modular_ss220/jukebox/_jukebox.dme
> +// BEGIN_INCLUDE
```suggestion
```

2024-06-15 19:31 UTC, Gaxeer commented on modular_ss220/jukebox/_jukebox.dme
> +// END_INCLUDE
```suggestion
```

2024-06-17 07:14 UTC, merged