Centcom Update: Drop Pods
ss220club/Paradise-SS220 pull request #1286
Opened 2024-06-04 09:48 UTC by dj-34

## Что этот PR делает
- Исправляет ошибки прошлых изменений
- Добавляет дроп под (вообще, задумывается что для дедсквада)
- Добавляет доступ ОСО на телепортерную и дроп под
- Добавляет ставни на шаттл ЕРТ, это было сделано после того как я увидел как зомби чуть не прилетели на ЦК, благо админ их всех повзрывал. Ставни помогут избежать таких недоразумений и точно (не точно) обезопасить ЦК при ивентах

## Почему это хорошо для игры
Больше опций, больше безопасности, меньше ошибок

## Изображения изменений
MapDiff

## Тестирование
Смотрел в игре

## Changelog

:cl:
experiment: Центком: добавлен собственный дроп под (подразумевается для Дедсквада (не надо на нём слать ОБР (А ТО ПРИДЕТСЯ ВЫРЕЗАТЬ...)))
tweak: Центком: На Телепортерную и Дроп Под добавлены доступы ОСО
fix: Исправлены некоторые визуальные ошибки прошлых изменений 
/:cl:

2024-06-04 09:48 UTC, dj-34 commented
Мнение по дроп поду нужно

2024-06-07 02:37 UTC, AyIong requested changes
Во первых, тут нет семи тайлов от дна карты, что плохо потому что ниже тупо чёрные квадраты
Во вторых Выглядит как отросток, имхо, не очень, плюс огромный пустой коридор и телепортерная, попробуй как-то ужать и сделать расширение вправо а не вниз
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/061d6c68-63f8-4799-a00f-7618814cdbac)

2024-06-07 12:47 UTC, dj-34 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/9b056fad-a572-479e-aeec-b4a1afaf1c3a)

2024-06-07 18:59 UTC, AyIong approved these changes

2024-06-07 19:00 UTC, merged