feat: add SSLR as roundstart magazine bazed rifle
ss220club/Paradise-SS220 pull request #1293
Opened 2024-06-06 14:37 UTC by Gaxeer

## Что этот PR делает

По просьбе Wycc добавляем щиткурам лазерную винтовку с магазинными заряжанием.
Магазин на 8 патронов, прожетайл такой же как и у других лазерок. Магазины можно печатать в РнД сразу же, так же можно заказать коробку с 4 патронами за 150 кредитов в карго.

Спрайты от EllGood

## Почему это хорошо для игры

Разнообразние

## Изображения изменений

В игре увидите

## Тестирование

Всё потестировал

## Changelog

:cl:
add: добавлена лазерная винтовка с магазинным заряжанием раундстартом у СБ.
/:cl:

2024-06-06 14:42 UTC, larentoun approved these changes
А почему нельзя печатать пустые магазины в РНД?

2024-06-06 15:02 UTC, dj-34 reviewed
Стоило бы вынести lasgun.dm из папки lasgun, и засунуть просто в папку code, по примеру с beretta.
А еще лучше создать папку weapons, закинуть туда беретту и все остальное из weapons.dm и рассортировать.................

2024-06-06 15:05 UTC, dj-34 requested changes

2024-06-06 15:05 UTC, dj-34 commented on modular_ss220/objects/code/lasgun/lasgun.dm
> +	name = "магазин для SSLR"
name в инглиш?

2024-06-06 15:05 UTC, dj-34 commented on modular_ss220/objects/code/lasgun/lasgun.dm
> +
```suggestion

```

2024-06-06 15:05 UTC, dj-34 commented on modular_ss220/objects/code/lasgun/lasgun.dm
> +	name = "Ящик с патронами для SSLR"
?
```suggestion
	name = "SSLR Ammo Crate"
```

2024-06-06 15:05 UTC, dj-34 commented on modular_ss220/objects/code/lasgun/lasgun.dm
> +	desc = "Стандартная лазерная винтовка производства Warp-Tac Industries, использующая лазерные картриджы, вместо аккумулятора - младший брат винтовки IK-M1. Одно из самых популярных решений для служб
```suggestion
	desc = "Стандартная лазерная винтовка производства Warp-Tac Industries, использующая лазерные картриджи, вместо аккумулятора - младший брат винтовки IK-M1. Одно из самых популярных решений для службы безопасности Nanotrasen."
```

2024-06-07 02:43 UTC, AyIong commented
Прайм онли?

2024-06-07 18:47 UTC, dj-34 approved these changes
вроде нормик

2024-06-07 20:46 UTC, AyIong approved these changes

2024-06-07 21:55 UTC, merged