Add: Sakura tree
ss220club/Paradise-SS220 pull request #1294
Opened 2024-06-06 15:30 UTC by dj-34

## Что этот PR делает
 - Добавляет Сакуру

## Почему это хорошо для игры
Баунти

## Изображения изменений
https://cdn.discordapp.com/attachments/1198154076739862588/1248276075088187423/Desktop_2024.06.06_-_19.00.30.01.mp4?ex=66631330&is=6661c1b0&hm=c1f0cb46da971ef3f9a49c2d034c3e3863e8ff6d61fb1136cbed2af3b5a16bb6&

## Тестирование
Проверял в игре

## Changelog

:cl:
add: Добавлена Сакура, она умеет цвести, и у неё есть собственные тайлы земли
/:cl:

2024-06-07 02:15 UTC, AyIong commented
Само дерево конечно выглядит так себе

2024-06-08 18:54 UTC, AyIong requested changes

2024-06-08 18:54 UTC, AyIong commented on modular_ss220/objects/code/flora/sakura.dm
> +	if(parent_tree == null)
```suggestion
	if(isnull(parent_tree))
```

2024-06-08 18:54 UTC, AyIong commented on modular_ss220/objects/code/flora/sakura.dm
> +			addtimer(CALLBACK(src, PROC_REF(transform_turf)), TRANSFORM_TURF_TIME, TIMER_UNIQUE | TIMER_OVERRIDE | TIMER_STOPPABLE)
```suggestion
	if(istype(T, /turf/simulated/floor/grass/sakura))
		return
	if(!parent_tree)
		return
	new /obj/effect/decal/sakura_leaves(T, src)
	// Start the timer to replace grass tile with sakura's one after 10 minutes
	addtimer(CALLBACK(src, PROC_REF(transform_turf)), TRANSFORM_TURF_TIME, TIMER_UNIQUE | TIMER_OVERRIDE | TIMER_STOPPABLE)
```

2024-06-08 18:54 UTC, AyIong commented on modular_ss220/objects/code/flora/sakura.dm
> +			qdel(D)
```suggestion
	if(!istype(T, /turf/simulated/floor/grass))
		return
	T.ChangeTurf(/turf/simulated/floor/grass/sakura)
	// Deletes pile of Sakura leaves
	for(var/obj/effect/decal/sakura_leaves/D in T)
		qdel(D)
```

2024-06-08 18:54 UTC, AyIong commented on modular_ss220/objects/code/flora/sakura.dm
> +		return ..()
```suggestion
```
Это лишнее насколько я знаю

2024-06-08 18:54 UTC, AyIong commented on modular_ss220/objects/code/flora/sakura.dm
> +	icon_state = "damaged"
```suggestion
/turf/simulated/floor/grass/sakura/break_tile()
	. = ..()
	icon_state = "damaged"

/turf/simulated/floor/grass/sakura/burn_tile()
	. = ..()
	icon_state = "damaged"
```

Почему не используешь update_icon_state()?

2024-06-08 18:55 UTC, AyIong commented on modular_ss220/objects/code/flora/sakura.dm
> +			addtimer(CALLBACK(src, PROC_REF(transform_turf)), TRANSFORM_TURF_TIME, TIMER_UNIQUE | TIMER_OVERRIDE | TIMER_STOPPABLE)
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/7aa5b492-1a66-497a-b85d-81d0f96fbfda)
Тут кстати можно под один if воткнуть всё

2024-06-08 19:55 UTC, dj-34 commented on modular_ss220/objects/code/flora/sakura.dm
> +	icon_state = "damaged"
Зачем мне вызывать прок в проке чтобы поменять 1 состояние иконки?

2024-06-08 19:58 UTC, dj-34 commented on modular_ss220/objects/code/flora/sakura.dm
> +		return ..()
Я просто скопировал как делают в большинстве случаев. Мне кажется так безопаснее, не?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/f5077a07-9f3f-41b5-ab6f-236cab8bf75a)

2024-06-08 20:36 UTC, AyIong commented on modular_ss220/objects/code/flora/sakura.dm
> +		return ..()
Пон

2024-06-08 20:45 UTC, AyIong approved these changes

2024-06-11 14:52 UTC, AyIong approved these changes

2024-06-11 14:52 UTC, merged