Звёздные войны 13
ss220club/Paradise-SS220 pull request #1300
Opened 2024-06-08 10:28 UTC by Fullonibus

## Что этот PR делает
Добавлено несколько именных световых мечей.

- Новые иконки мечей
- Новые анимации для мечей
- Новые звуки включения/выключения и ударов
- Система зачарований с уже готовым зачарованием "рывок"

## Почему это хорошо для игры
Приказ генерала Гавса

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/38350888/96b927e0-7db1-481f-9238-78348bb70272)

## Тестирование
It just works.

## Changelog

:cl:
add: На Прайм приехала уникальная партия мечей
/:cl:

2024-06-21 03:27 UTC, PhantornRU commented
Мерж конфликт нужно убрать

2024-07-01 19:25 UTC, Gaxeer commented on modular_ss220/prime_only/code/objects.dm
> +	if(world.time < cooldown)
обратись к файлу `tg_cooldowns.dm` и сделай кулдаун как надо, поищи по примерам

2024-07-04 20:06 UTC, Gaxeer requested changes

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/objects/code/components.dm
> +	return COMPONENT_CONDITION_FAILED
```suggestion
/datum/component/ckey_and_role_locked_pickup/proc/check_role_and_ckey(mob/user)
	if(user.client.ckey in ckeys)
		return TRUE

	if(required_role in user?.mind.vars)
		if(usr.mind.vars[required_role])
			return TRUE
			
	return FALSE
```

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/objects/code/components.dm
> +
```suggestion
```

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/objects/code/components.dm
> +	var/required_role
```suggestion
	var/pickup_damage
	var/force = 20
	var/required_role
	var/list/ckeys = list()
```

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/objects/code/components.dm
> +
```suggestion
/datum/component/ckey_and_role_locked_pickup/RegisterWithParent()
	RegisterSignal(parent, COMSIG_ITEM_PICKUP, PROC_REF(try_pick_up))

/datum/component/ckey_and_role_locked_pickup/UnregisterFromParent()
	UnregisterSignal(parent, COMSIG_ITEM_PICKUP)
```

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/prime_only/code/objects.dm
> +	if(!T)
```suggestion
	var/turf/destination_turf = get_turf(chargeat)
	if(!destination_turf)
```

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/prime_only/code/objects.dm
> +	for(var/atom/target in T.contents)
```suggestion
	for(var/atom/target in destination_turf.contents)
```

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/prime_only/code/objects.dm
> +
```suggestion
```

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/prime_only/code/objects.dm
> +
```suggestion
```

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/prime_only/code/objects.dm
> +
```suggestion
```

2024-07-04 20:06 UTC, Gaxeer commented on modular_ss220/prime_only/code/objects.dm
> +
```suggestion
```

2024-07-09 11:53 UTC, Gaxeer approved these changes

2024-07-09 11:53 UTC, merged