Fix neon shoes overlay
ss220club/Paradise-SS220 pull request #1317
Opened 2024-06-11 01:58 UTC by dj-34

## Что этот PR делает
 - Исправляет работу оверлея неоновых ботинок
 - Код отсортирован

## Почему это хорошо для игры
Оверлей будет отображаться корректно

## Изображения изменений
Позже

## Тестирование
Проверял в игре

## Changelog

:cl:
fix: Неоновые ботинки теперь корректно накладывают оверлей (да-да, оно было сломано).
/:cl:

2024-06-13 03:08 UTC, dj-34 commented
ревью my shit pls)

2024-06-20 12:29 UTC, Gaxeer requested changes

2024-06-20 12:29 UTC, Gaxeer commented on modular_ss220/clothing/code/shoes.dm
> +		toggle_glow(user)
```suggestion
	switch(actiontype)
		if(/datum/action/item_action/change_color)
			change_color(user)
		if(/datum/action/item_action/toggle_light)
			toggle_glow(user)
```

2024-06-20 12:29 UTC, Gaxeer commented on modular_ss220/clothing/code/shoes.dm
> +	var/mutable_appearance/neon_overlay
перенеси эту переменную в самый низ, ниже примитивных.

2024-07-01 19:47 UTC, Gaxeer commented on modular_ss220/clothing/code/shoes.dm
> +		return
сначала проверяй на то, есть ли юзер, а потом уже переменную создавай

2024-07-04 20:11 UTC, Gaxeer requested changes

2024-07-04 20:11 UTC, Gaxeer commented on modular_ss220/clothing/code/shoes.dm
> +	var/mob/living/carbon/human/H = user
```suggestion
```

2024-07-04 20:11 UTC, Gaxeer commented on modular_ss220/clothing/code/shoes.dm
> +	if(!glow_active && H.get_item_by_slot(SLOT_HUD_SHOES))
```suggestion
	if(!glow_active && user.get_item_by_slot(SLOT_HUD_SHOES))
```

2024-07-04 20:11 UTC, Gaxeer commented on modular_ss220/clothing/code/shoes.dm
> +	var/mob/living/carbon/human/H = user
```suggestion
```

2024-07-04 20:11 UTC, Gaxeer commented on modular_ss220/clothing/code/shoes.dm
> +			apply_neon_overlay(user)
```suggestion
	if(!neon_overlay)
		return
		
	remove_neon_overlay(user)
	if(user.get_item_by_slot(SLOT_HUD_SHOES))
		apply_neon_overlay(user)
```

2024-07-04 20:11 UTC, Gaxeer commented on modular_ss220/clothing/code/shoes.dm
> +	neon_overlay = mutable_appearance('modular_ss220/clothing/icons/mob/shoes.dmi', "neon_overlay", EMISSIVE_PLANE)
```suggestion
	neon_overlay = emissive_appearance('modular_ss220/clothing/icons/mob/shoes.dmi', "neon_overlay")
```

2024-07-04 20:11 UTC, Gaxeer commented on modular_ss220/clothing/code/shoes.dm
> +	var/mob/living/user
```suggestion
```

2024-07-09 02:16 UTC, dj-34 commented on modular_ss220/clothing/code/shoes.dm
> +	neon_overlay = mutable_appearance('modular_ss220/clothing/icons/mob/shoes.dmi', "neon_overlay", EMISSIVE_PLANE)
Не получится в общем с эмиссив апирансом, из-за того что оверлей накладывается на перса, у которого эмиссив блокер.
Будет без него в общем, разница нулевая.

2024-07-11 12:52 UTC, Gaxeer approved these changes

2024-07-11 12:52 UTC, merged