[Add] QuadrupleSec
ss220club/Paradise-SS220 pull request #1327
Opened 2024-06-17 20:22 UTC by HardexZ

## Что этот PR делает

Новый напиток в баре. Порт с тг. 
## Почему это хорошо для игры

Порты с тг это база. Квадриплсек круче пива.
## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/33863785/26c53863-8ba8-4a68-bff8-d2bbb99bbec2)

## Тестирование
Локалка

## Changelog

:cl:
add: Quadruple Sec в теперь в баре. Рецепт Бахама Мама = 5, Тройной цитрус = 5, Виноградный сок = 5
/:cl:

2024-06-18 08:37 UTC, dj-34 requested changes

2024-06-18 08:37 UTC, dj-34 commented on modular_ss220/food/_food.dme
> +// END_INCLUDE
насрано

2024-06-18 08:37 UTC, dj-34 commented on modular_ss220/food/code/drinks.dm
> +
```suggestion

```

2024-06-18 08:37 UTC, dj-34 commented on paradise.dme
> -// SS220 ADDITION END
НАСРАНО

2024-06-18 17:12 UTC, HardexZ commented on paradise.dme
> -// SS220 ADDITION END
оно поэтому и в драфте >:(

2024-07-06 01:26 UTC, dj-34 commented
@HardexZ че там, долго раздупляться будешь?

2024-07-14 11:11 UTC, dj-34 commented
Переоткроешь когда захочешь возродить. Уже писал тебе - ты сказал доделаешь, 3 дня прошло, так и не увидел действий с твоей стороны.

2024-07-14 11:11 UTC, closed without merging