Фикс помойки
ss220club/Paradise-SS220 pull request #1332
Opened 2024-06-19 10:44 UTC by VERG-SS220

## Что этот PR делает
Чинит робофабрику

## Почему это хорошо для игры
Чинит робофабрику

## Изображения изменений

## Тестирование
Локалка, всё прошло спокойно

## Changelog

:cl:
add: Что-то добавил
del: Что-то удалил
tweak: Поменял что-то по мелочи
fix: Что-то починил
wip: Какие-либо наработки в процессе
soundadd: Добавил новый звук
sounddel: Удалил старый звук
imageadd: Добавил новую картинку
imagedel: Удалил старую картинку
spellcheck: Исправил опечатку
experiment: Добавил экспериментальную функцию
/:cl:

2024-06-19 12:25 UTC, dj-34 requested changes

2024-06-19 12:25 UTC, dj-34 commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +		to_chat(src, "<span class='warning'>Недостаточно места! Убедитесь, что вы ставите турель на чистом полу.</span>")
```suggestion
		to_chat(src, "<span class='warning'>Недостаточно места! Убедитесь, что вы ставите турель на свободном тайле пола.</span>")
```

2024-06-19 12:25 UTC, dj-34 commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +	description = "Скачивает ПО, активирующее встроенное боевое оборудование киборгов. Киборги, построенные после покупки улучшения, будут автоматом идти с боевыми улучшениями."
```suggestion
	description = "Скачивает ПО, активирующее встроенное боевое оборудование киборгов. Киборги, построенные после покупки улучшения, будут автоматически идти с боевыми улучшениями."
```

2024-06-19 12:25 UTC, dj-34 commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +		to_chat(R, "<span class='notice'>Новое ПО загружено. Боевые улучшения включены.</span>")
```suggestion
		to_chat(R, "<span class='notice'>Новое ПО загружено. Активированы боевые улучшения.</span>")
```

2024-06-19 12:25 UTC, dj-34 commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +	unlock_text = "<span class='notice'>Вы готовите к установке энерго-турель.</span>"
```suggestion
	unlock_text = "<span class='notice'>Вы готовите энергетическую турель к развертыванию.</span>"
```

2024-06-19 12:25 UTC, dj-34 commented on code/game/gamemodes/malfunction/Malf_Modules.dm
> +	description = "Поставит где угодно турель, которая во всех органиков будет стрелять лазером."
```suggestion
	description = "Развертывает турель в любом месте, которая летально нейтрализует органиков."
```

2024-06-19 23:22 UTC, VERG-SS220 commented
Последний морж - просто синхранул ветку, чтоб не ебаться с ней потом ещё 3 часа

2024-06-21 00:15 UTC, VERG-SS220 commented
Ждем мерж

2024-06-21 15:36 UTC, dj-34 approved these changes

2024-06-21 15:36 UTC, merged