Translate: Antagonists Objectives
ss220club/Paradise-SS220 pull request #1363
Opened 2024-07-07 21:38 UTC by VERG-SS220

## Что этот PR делает
Перевод целек для антагов

## Почему это хорошо для игры
 Приятно, когда всё на рашен лангуаге.

## Изображения изменений
diff

## Тестирование
По тестам на локалке всё прошло гладко, есть некоторые неточности в духе падежов и мелькающий the. В дальнейшем, наверное, порешается?

## Changelog

:cl:
<b> Он нам и нахуй не нужон ваш CL </b>
/:cl:

2024-07-07 21:42 UTC, VERG-SS220 commented
Не трогал только цельки всяких трудеров и зондбе

2024-07-08 07:22 UTC, dj-34 requested changes

2024-07-09 14:53 UTC, VERG-SS220 commented on code/game/gamemodes/objective.dm
> +	Агенты Синдиката, другие враги корпорации, киборги, питомцы, а также закованные в наручники/болу заложники могут быть допущены на шаттл живыми. \
Так там же еще условием является то, что люди в заваренных шкафах и долах всё равно считаются на выполнение цели как заложники

2024-07-09 14:53 UTC, VERG-SS220 commented on code/game/gamemodes/objective.dm
> +	Агенты Синдиката, другие враги корпорации, киборги, питомцы, а также закованные в наручники/болу заложники могут быть допущены на шаттл живыми. \
Приеду домой - предложу текст более удобоваримый, сейчас с телефона делаю все xdd

2024-07-12 20:23 UTC, AyIong commented on code/game/gamemodes/objective.dm
> +		explanation_text = "Преподайте [target.current.real_name], the [target.assigned_role] урок, который они никогда не забудут. Жертва должна умереть лишь единожды для выполнения цели."
> Думал о выпиле этого (и других) the из текста, но у нас пока профессии не переведены, поэтому думал, что оставлю так.

Нам в принципе `the` не надо, даже с частичным переводом

2024-07-14 17:38 UTC, dj-34 commented
Там ПР залит с перевод хелперами, доделай ПР с реквестами

2024-07-18 21:32 UTC, dj-34 requested changes

2024-07-18 21:32 UTC, dj-34 commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Сбегите со станции на шаттле или эвакуационном поде."
```suggestion
	explanation_text = "Сбегите живым со станции на шаттле или эвакуационном поде."
```

2024-07-18 21:32 UTC, dj-34 commented on code/game/gamemodes/objective.dm
> +	explanation_text = "Сбегите на шаттле или эвакуационном поде под личностью [target_real_name], [target.assigned_role], нося [target.ru_p_them()] ID-карту."
```suggestion
	explanation_text = "Сбегите живым со станции на шаттле, или эвакуационном поде под личностью [target_real_name], [target.assigned_role], нося [target.ru_p_them()] ID-карту."
```

2024-07-19 02:50 UTC, dj-34 approved these changes

2024-07-20 14:29 UTC, merged