VIP получает возможность говорить на всех языках
ss220club/Paradise-SS220 pull request #1370
Opened 2024-07-10 04:36 UTC by msw7007

## Что этот PR делает

Позволяет VIP-у (5-ый тир донатная джобка) понимать и говорить на всех доступных библиотекарю языках

## Почему это хорошо для игры

Позволит учавствовать в больших РП-ситуациях

## Тестирование

Не тестировал

## Changelog

:cl:
add: VIP стал мульти-язычен
/:cl:

2024-07-10 04:42 UTC, PhantornRU requested changes

2024-07-10 04:42 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +/datum/outfit/job/donor/vip_guest(mob/living/carbon/human/H, visualsOnly = FALSE)
post_equip то ебани...

2024-07-10 04:42 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +		if(new_language.flags & (HIVEMIND|NOLIBRARIAN))
и даже на языке кидан и других рас будет говорить? нихуево.

2024-07-10 04:48 UTC, msw7007 commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +		if(new_language.flags & (HIVEMIND|NOLIBRARIAN))
Кроме киданов какие по хорошему еще стоит вырезать?

2024-07-10 05:11 UTC, msw7007 commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +/datum/outfit/job/donor/vip_guest(mob/living/carbon/human/H, visualsOnly = FALSE)
исправлено, спасибо за указание

2024-07-10 05:15 UTC, dj-34 commented
Все языки даже расовые - жирно как по мне. Да и зачем они ему, он же не дипломат какой-нибудь...

2024-07-10 05:27 UTC, msw7007 commented
> Все языки даже расовые - жирно как по мне. Да и зачем они ему, он же не дипломат какой-нибудь...

Ну, чтобы общаться даже с другими расами или как минимум, понимать их.

2024-07-11 04:58 UTC, PhantornRU approved these changes

2024-07-11 04:58 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +	..()
```suggestion
	. = ..()
```

2024-07-12 20:18 UTC, AyIong commented
Я лично тоже против, это фишка библиотекаря, и давать её донат рольке, так ещё и не дипломату какому-то, а просто VIP-Ассистуха

2024-07-14 09:34 UTC, merged

2024-07-14 10:00 UTC, dj-34 commented
вкусно 4 дизлайка мержим

2024-07-14 10:00 UTC, dj-34 commented
прям как на оффах тг