[PRIME ONLY] Exlorer Uniform Update
ss220club/Paradise-SS220 pull request #1387
Opened 2024-07-15 23:55 UTC by AloeNeverDie

## Что этот PR делает
Это порт униформы экспедиционного корпуса с Сьерры на парадиз.
Добавлены 4 новые формы для исследователей, а также заменена старая форма раундстарт на новую.

Новая форма также приехала в вендоматы для исследователей. Старая форма также осталась в вендомате.

## Почему это хорошо для игры

Запрос стримера на прайм.

## Изображения изменений

## Тестирование

Провел все тесты на локалке, все работает.

## Changelog

:cl:
add: Добавлена новая униформа для исследователей в вендомат
tweak: Поменял раундстарт униформу у исследователей
/:cl:

2024-07-16 00:12 UTC, PhantornRU commented
Только униформа или снаряжение также планируется?

2024-07-16 00:23 UTC, dj-34 requested changes
1. Скинь скриншот полного аутфита как оно все выглядит при спавне.
2. Поменяй пути

2024-07-16 00:23 UTC, dj-34 commented on modular_ss220/prime_only/_prime.dme
> +#include "code/outifits.dm"
```suggestion
#include "code/outfits.dm"
```

2024-07-16 00:23 UTC, dj-34 commented on modular_ss220/prime_only/_prime.dme
> +#include "code/under.dm"
```suggestion
#include "code/clothing/under.dm"
```

2024-07-16 00:23 UTC, dj-34 commented on modular_ss220/prime_only/_prime.dme
> +#include "code/wardrobe_vendors.dm"
```suggestion
#include "code/vending.dm"
```

2024-07-16 00:23 UTC, dj-34 commented on modular_ss220/prime_only/code/outifits.dm
> +/datum/outfit/job/explorer
Комменты на английском
```suggestion
// Explorer's outfits
/datum/outfit/job/explorer
```

2024-07-16 00:23 UTC, dj-34 commented on modular_ss220/prime_only/code/under.dm
> +/obj/item/clothing/under/rank/cargo/expedition_prime
Оно и так понятно что для прайма
```suggestion
// Explorer's outfits
/obj/item/clothing/under/rank/cargo/expedition_prime
```

2024-07-16 00:23 UTC, dj-34 commented on modular_ss220/prime_only/code/under.dm
> +	armor = list(MELEE = 5, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, RAD = 0, FIRE = 20, ACID = 20)
У одежды экспедиторов есть броня?

2024-07-16 00:23 UTC, dj-34 commented on modular_ss220/prime_only/code/under.dm
> +	item_color = "expedition_prime_grey"
Не надо в описании писать цвет, который ты и так видишь, который еще и указан в названии. +лишние строки кода
```suggestion
/obj/item/clothing/under/rank/cargo/expedition_prime/green
	name = "green expedition uniform"
	icon_state = "expedition_prime_green"
	item_state = "expedition_prime_green"
	item_color = "expedition_prime_green"

/obj/item/clothing/under/rank/cargo/expedition_prime/tan
	name = "tan expedition uniform"
	icon_state = "expedition_prime_tan"
	item_state = "expedition_prime_tan"
	item_color = "expedition_prime_tan"

/obj/item/clothing/under/rank/cargo/expedition_prime/grey
	name = "grey expedition uniform"
	icon_state = "expedition_prime_grey"
	item_state = "expedition_prime_grey"
	item_color = "expedition_prime_grey"
```

2024-07-16 00:23 UTC, dj-34 commented on modular_ss220/prime_only/code/under.dm
> +		)
Разве у Сьерры нет расовых спрайтов?

2024-07-16 00:23 UTC, dj-34 commented on modular_ss220/prime_only/code/wardrobe_vendors.dm
> +	prices = new_prices
это пиздец какой то

2024-07-16 00:23 UTC, AloeNeverDie commented
Пока не знаю буду ли менять спрайт мода или каких-либо других вещей у гейтеров, если будет желание и запрос в ближайшее время - сделаю в этом ПРе, но пока что не планирую.

2024-07-16 00:23 UTC, AloeNeverDie commented on modular_ss220/prime_only/code/under.dm
> +		)
Волновали только люди, только для них делал

2024-07-16 00:25 UTC, dj-34 commented
да какой мод, тут сначала бы в целом с аутфитом разобраться. Там и рюкзак и кепка и че-то еще просто в цвета карго.

2024-07-16 00:25 UTC, dj-34 commented
Еще и расовых спрайтов нет

2024-07-16 00:25 UTC, AloeNeverDie commented on modular_ss220/prime_only/code/wardrobe_vendors.dm
> +	prices = new_prices
Сказано было такой вариант делать, чтобы добавить новые шмотки сверху.

2024-07-16 00:27 UTC, dj-34 commented on modular_ss220/prime_only/code/under.dm
> +		)
> Волновали только люди, только для них делал

А другим расам как играть с такой униформой? Понятно что волнуют только люди, но у нас раундстарт с этим игроки появляются.

2024-07-16 00:29 UTC, AloeNeverDie commented on modular_ss220/prime_only/code/under.dm
> +	armor = list(MELEE = 5, BULLET = 0, LASER = 0, ENERGY = 0, BOMB = 0, RAD = 0, FIRE = 20, ACID = 20)
Дефолт одежда исследователей, копировал её статы

2024-07-16 00:30 UTC, dj-34 commented on modular_ss220/prime_only/code/wardrobe_vendors.dm
> +	prices = new_prices
> Сказано было такой вариант делать, чтобы добавить новые шмотки сверху.

Так у нас есть нормальный рабчоий вариант
![image](https://github.com/user-attachments/assets/1b861ae5-2a8f-41b8-b5d1-e29f57d369cc)

2024-07-16 00:34 UTC, AloeNeverDie commented on modular_ss220/prime_only/code/under.dm
> +		)
Могу скинуть как она сидит на других ксеносах, если не устроит буду думать как сделать проверку на human не human

2024-07-16 00:35 UTC, AloeNeverDie commented on modular_ss220/prime_only/code/wardrobe_vendors.dm
> +	prices = new_prices
Потому что если добавлять так, то новые шмотки будут снизу в вендомате

2024-07-16 00:41 UTC, dj-34 commented on modular_ss220/prime_only/code/under.dm
> +		)
> Могу скинуть как она сидит на других ксеносах, если не устроит буду думать как сделать проверку на human не human

Она не может сидеть нормально. Проверку на не human делать не нужно, для этого есть spritesheet - нужны только расовые спрайты (а точнее дорисовать несколько пикселей для воксов и киданов вроде (если никого не упустил)).

2024-07-16 00:47 UTC, AloeNeverDie commented
> 1. Скинь скриншот полного аутфита как оно все выглядит при спавне.
> 2. Поменяй пути
> 3. Не забывай указать в чейнджлоге что это Прайм обновы

1. 
![image](https://github.com/user-attachments/assets/e80fc656-f313-420c-b7e1-652e630ea754)
2. Готово
3. Готово

2024-07-16 00:55 UTC, dj-34 commented
> > 1. Скинь скриншот полного аутфита как оно все выглядит при спавне.
> > 2. Поменяй пути
> > 3. Не забывай указать в чейнджлоге что это Прайм обновы
> 
> 
> ![image](https://private-user-images.githubusercontent.com/93468231/348897676-e80fc656-f313-420c-b7e1-652e630ea754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTE1MzksIm5iZiI6MTcyMTA5MTIzOSwicGF0aCI6Ii85MzQ2ODIzMS8zNDg4OTc2NzYtZTgwZmM2NTYtZjMxMy00MjBjLWI3ZTEtNjUyZTYzMGVhNzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDAwNTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MzRlOTExZWQ5NWFlZTMyMzQzZTg2MGNkM2E5YzI5M2IwMDkwM2ExODFhMzZmYjY4YmUxN2Q0MDQ1MDUxMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eqUYXx_XxtigUdJ5ESR5oqBfLggXCl4AllYcbKjFVLI) 2. Готово 3. Готово

Ну да, тут тотальный аутфит ишью. Нужно либо перерисовывать кепку и рюкзак, либо выдавать условно black cap и стандартную сумку.

2024-07-16 01:10 UTC, AloeNeverDie commented
> > > 1. Скинь скриншот полного аутфита как оно все выглядит при спавне.
> > > 2. Поменяй пути
> > > 3. Не забывай указать в чейнджлоге что это Прайм обновы
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/93468231/348897676-e80fc656-f313-420c-b7e1-652e630ea754.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwOTE1MzksIm5iZiI6MTcyMTA5MTIzOSwicGF0aCI6Ii85MzQ2ODIzMS8zNDg4OTc2NzYtZTgwZmM2NTYtZjMxMy00MjBjLWI3ZTEtNjUyZTYzMGVhNzU0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE2VDAwNTM1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MzRlOTExZWQ5NWFlZTMyMzQzZTg2MGNkM2E5YzI5M2IwMDkwM2ExODFhMzZmYjY4YmUxN2Q0MDQ1MDUxMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eqUYXx_XxtigUdJ5ESR5oqBfLggXCl4AllYcbKjFVLI) 2. Готово 3. Готово
> 
> Ну да, тут тотальный аутфит ишью. Нужно либо перерисовывать кепку и рюкзак, либо выдавать условно black cap и стандартную сумку.

С кепкой все просто, могу заменить на black cap, рюкзак - это просто рюкзак отдела, у исследователей такой, я не спрайтер, рисовать не буду и не умею, увы. 
Вот как выглядит с дефолт серым рюкзаком и кепкой:
![image](https://github.com/user-attachments/assets/2adaab49-5004-4552-96ca-ac576b233dcf)

2024-07-16 01:27 UTC, AloeNeverDie commented on modular_ss220/prime_only/code/under.dm
> +		)
Вот как выглядят воксы и киданы. Слева оффы, справа новый спрайт
![image](https://github.com/user-attachments/assets/f2611384-9d66-48b9-a078-c07d3b5db6ff)

2024-07-16 01:33 UTC, AloeNeverDie commented on modular_ss220/prime_only/code/under.dm
> +		)
Я честно не вижу, чтобы это плохо сидело как-то.

2024-07-16 01:40 UTC, dj-34 commented on modular_ss220/prime_only/code/under.dm
> +		)
Плохо

2024-07-16 20:21 UTC, AloeNeverDie commented on modular_ss220/prime_only/code/under.dm
> +		)
Новые расовые спрайты:
![image](https://github.com/user-attachments/assets/bb4982b0-db56-48c4-a1ff-d478664d62c0)
![image](https://github.com/user-attachments/assets/02d9c34f-f02e-4ec0-9c8a-2c85dc6d15ee)
![image](https://github.com/user-attachments/assets/5e2b78bb-d7a2-4232-9c80-68e8d91fa555)

2024-07-18 21:14 UTC, dj-34 commented
Сначала поправь то что я указал

2024-07-20 14:23 UTC, dj-34 approved these changes
Проверил на локалочке, посмотрел код - вопросов нет.

2024-07-20 14:24 UTC, dj-34 commented
@AloeNeverDie ток вот #include "code/clothing/under.dm" закинь в самый вверх списка

2024-07-20 14:26 UTC, dj-34 commented
И еще просьба в .dmi файле киданов поменять grey и green местами, для consistency с остальными файлами
![image](https://github.com/user-attachments/assets/0e75588b-4932-4d62-b2b7-814730ce0448)

2024-07-20 14:26 UTC, AloeNeverDie commented
> @AloeNeverDie ток вот #include "code/clothing/under.dm" закинь в самый вверх списка

![image](https://github.com/user-attachments/assets/58335146-0ace-4554-82da-d3e40589b10d)
 Так?

2024-07-20 14:28 UTC, dj-34 commented
> > @AloeNeverDie ток вот #include "code/clothing/under.dm" закинь в самый вверх списка
> 
> ![image](https://private-user-images.githubusercontent.com/93468231/350700245-58335146-0ace-4554-82da-d3e40589b10d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0ODU5MTgsIm5iZiI6MTcyMTQ4NTYxOCwicGF0aCI6Ii85MzQ2ODIzMS8zNTA3MDAyNDUtNTgzMzUxNDYtMGFjZS00NTU0LTgyZGEtZDNlNDA1ODliMTBkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIwVDE0MjY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMWM5YzY3ZWQzNmZmYzM3NzU4YTllNTM0ZTVjMjVhZDcyNmFkMTIzNmFkNTBiYjA2NzhmMDQ2MWQ0M2U5NzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Tr0yoPsquysDjqIpNYnFXsOPglSpZOigyfXt2R_wxxc) Так?

да

2024-07-21 09:17 UTC, merged