New Robolimbs
ss220club/Paradise-SS220 pull request #1395
Opened 2024-07-25 13:03 UTC by Sirstaniya

## Что этот PR делает
Добавляет новые протезы для органиков и КПБ. Корпус, три вида голов, руки и ноги.

## Почему это хорошо для игры

Это разнообразит выбор конечностей для представителей КПБ, а так же увеличит ряд возможного выбора частей для подбора своего стиля.

## Изображения изменений

![321321](https://github.com/user-attachments/assets/e9638a22-2b0f-42c3-9298-b3b2b2229efc)
![213213](https://github.com/user-attachments/assets/406ea40a-1dd5-41e1-9355-cf27cbb97f68)
![123123](https://github.com/user-attachments/assets/3223d145-6c36-4cb9-be8d-fc0d3e98222f)

## Тестирование

Билд был скомпилирован и запушен, протезы так же спокойно выставляются в меню настроек и заменяются при операции с КПБ. 

## Changelog

:cl:
add: Новые протезы для КПБ и органиков.

2024-07-25 15:01 UTC, AyIong commented
Чейнджлог поправь

2024-07-25 15:03 UTC, AyIong requested changes
Чёт в ПРе написано про корпус, три вида голов, руки и ноги
Но тут только головы
Переведи в Draft если не готово

2024-07-25 15:03 UTC, AyIong commented on modular_ss220/robolimbs/_robolimbs.dm
> +	author = "sirstaniya"
```suggestion
	author = "sirstaniya"

```

2024-07-25 15:03 UTC, AyIong commented on modular_ss220/robolimbs/code/robolimbs.dm
> +	has_subtypes = null
```suggestion
	has_subtypes = null

```

2024-07-25 20:18 UTC, AyIong approved these changes
Ну допустим

2024-07-30 14:14 UTC, dj-34 commented
!merge_upstream

2024-07-30 15:46 UTC, Gaxeer approved these changes

2024-07-30 15:46 UTC, merged