Add new rack & gun rack parts fix
ss220club/Paradise-SS220 pull request #1400
Opened 2024-07-30 07:30 UTC by skifsky

## Что этот PR делает

Добавляет вертикальный стеллаж и детали для него
Добавляет иконку деталям оружейной стойки и возможность ее строительства

## Почему это хорошо для игры

На стеллаж можно произвольно раскладывать вещи, и он не выглядит как стойка для холодного оружия
Оружейная стойка больше не оставляет после себя невидимые детали

## Изображения изменений

![image](https://github.com/user-attachments/assets/9b0b4f88-5646-416d-bd4d-a79559eff5d4)

## Тестирование

Погонял на локалке. Всё гуд

## Changelog

:cl:
add: Добавлен вертикальный стеллаж
fix: Оружейную стойку теперь возможно построить
imageadd: Добавлена иконка деталей для оружейной стойки
/:cl:

2024-07-30 07:41 UTC, AyIong requested changes
Переведи всякие уведомления в спанах,
Можешь ещё описания перевести

2024-07-30 07:41 UTC, AyIong commented
`imageadd: Добавлена иконка деталей для оружейной стойки` это не обязательно

2024-07-30 07:50 UTC, AyIong requested changes
Однобуквенники надо бы поменять, плюс у тебя прок дублируется, попробуй загнать оружейную стойку как подтип, или все стойки как подтип обычной, дабы сделать один attack_self

2024-07-30 07:50 UTC, AyIong commented on modular_ss220/aesthetics/racks/code/racks.dm
> +	building = FALSE
```suggestion
	if(do_after(user, 50, target = user, progress=TRUE) || !user.drop_item(src))
		building = FALSE
		return
	var/obj/structure/rack/gunrack/R = new /obj/structure/rack/gunrack(user.loc)
	user.visible_message("<span class='notice'>[user] assembles \a [R].\
		</span>", "<span class='notice'>You assemble \a [R].</span>")
	R.add_fingerprint(user)
	building = FALSE
	qdel(src)
```
 Ступенек лучше избегать
 
Буквы на переменных можешь не экономить

Вместо `<span class...` используй макросы `span_notice("Текст")` например, все макросы можешь глянуть в модуле, но у них интуитивно понятные названия, так что можно по интуиции набрать

2024-07-30 07:50 UTC, AyIong commented on modular_ss220/aesthetics/racks/code/racks.dm
> +	building = FALSE
```suggestion
/obj/item/rack_parts/shelving_parts/attack_self(mob/user)
	if(building)
		return
	building = TRUE
	to_chat(user, "<span class='notice'>You start constructing a shelving...</span>")
	if(do_after(user, 50, target = user, progress=TRUE))
		if(!user.drop_item(src))
			return
		var/obj/structure/rack/shelving/R = new /obj/structure/rack/shelving(user.loc)
		user.visible_message("<span class='notice'>[user] assembles \a [R].\
			</span>", "<span class='notice'>You assemble \a [R].</span>")
		R.add_fingerprint(user)
		qdel(src)
	building = FALSE
```

Не обязательно дублировать прок, можешь сделать оружейный подтипом этого, дабы они использовали один прок

2024-07-30 12:20 UTC, skifsky commented on modular_ss220/aesthetics/racks/code/racks.dm
> +	building = FALSE
Поправил

2024-07-30 12:21 UTC, skifsky commented on modular_ss220/aesthetics/racks/code/racks.dm
> +	building = FALSE
Чет не особо выходит запилить это через один прок, особенно с локализацией и склонениями...

2024-07-30 12:46 UTC, AyIong requested changes

2024-07-30 12:46 UTC, AyIong commented on modular_ss220/aesthetics/racks/code/racks.dm
> +		building = FALSE
```suggestion
	to_chat(user, span_notice("Вы начинаете собирать стеллаж..."))
	if(do_after(user, 50, target = user, progress=TRUE) && user.drop_item(src))
		var/obj/structure/rack/shelving/shelf = new /obj/structure/rack/shelving(user.loc)
		user.visible_message(span_notice("[user] собирает стеллаж."), span_notice("Вы закончили собирать стеллаж."))
		shelf.add_fingerprint(user)
		building = FALSE
```

Ты про однобуквенники забыл, не надо экономить символы на переменных, это сложно читать

2024-07-30 12:47 UTC, AyIong commented on modular_ss220/aesthetics/racks/code/racks.dm
> +	building = FALSE
> Чет не особо выходит запилить это через один прок, особенно с локализацией и склонениями...

Хмм, ладно

2024-07-30 20:50 UTC, dj-34 commented on modular_ss220/aesthetics/racks/code/racks.dm
> +	name = "оружейная стойка"
Не надо переводить name

2024-07-30 20:50 UTC, dj-34 commented on modular_ss220/aesthetics/racks/code/racks.dm
> +/obj/item/rack_parts/gunrack_parts
И так понятно
```suggestion
/obj/item/rack_parts/gunrack
```

2024-07-30 20:50 UTC, dj-34 commented on modular_ss220/aesthetics/racks/code/racks.dm
> +/obj/item/rack_parts/shelving_parts
Мб лучше переименовать в shelf?
```suggestion
/obj/item/rack_parts/shelf
```

2024-07-30 20:52 UTC, dj-34 commented
Еще мне не нравится несоответствие в спрайте. Не хватает "отсвечивания" и внутренняя часть стеллажа окрашена в иной цвет.

И ножки... какие то жирные, для сборного стеллажа... Будто бы можно на 1 пиксель ужать.

![image](https://github.com/user-attachments/assets/6cbed4bc-7f44-48fa-886c-09aaf60f3feb)

2024-07-31 20:55 UTC, dj-34 commented
Спрайт то может и лучше стал, но цветовая палитра все еще не та. Подгони "белесый" цвет к синюшнему с оригинала - в первой итерации примерно то что нужно было.
![image](https://github.com/user-attachments/assets/c145866a-a85e-480a-a4d2-9726f617813f)

2024-08-01 10:59 UTC, skifsky commented
Оставлю только фикс деталей оружейной стойки, потому что там чет пиздец рантаймы идут. Может быть потом отдельным пиаром уже сделаю...

2024-08-01 18:25 UTC, dj-34 approved these changes

2024-08-01 19:52 UTC, Gaxeer approved these changes

2024-08-01 19:55 UTC, AyIong approved these changes

2024-08-01 19:55 UTC, merged