HTML Lobby Screen
ss220club/Paradise-SS220 pull request #1424
Opened 2024-08-08 15:35 UTC by AyIong

## Что этот PR делает
Апгрейд лобби, теперь на нём не только пикча в лобби.
Окошко "New Player" перекочевало прямо на лобби скрин, в новой, красивой шкурке.
Так же добавлена функция переключения между серверами, само собой, сервера вынесены в конфиг, ещё одна причина ебать ХЭДЭДЭ
В придачу ещё обновлена дефолта тайт пикча на арт годовщины от оффов.

Возможно в будущем перетащу на оффы, хоть и можно оставить модульно.

## Почему это хорошо для игры
Избавление от окошка где обычно прожимают реди, и стараются скрыть как можно дальше, на немного более приятное меню, с ЛОГОТИПОМ!

## Изображения изменений
| До начала раунда | После начала раунда | С админ нотисом |
| - | - | - |
| ![image](https://github.com/user-attachments/assets/8d6cae73-1cd8-4738-b33f-07aadb97a3e8) | ![image](https://github.com/user-attachments/assets/bc3348b6-3d73-490a-8aed-58ef0ffa9707) | ![image](https://github.com/user-attachments/assets/6bad9493-f449-48b2-aee7-c1e11eef679d) /

<details>
<summary>Видосик</summary>
Лагает из-за IE, я так думаю.
Скорее всего анимации перестанут лагать с приходом Byond 516

https://github.com/user-attachments/assets/b0b19883-f12d-4862-be8a-c0d04ad311ae

</details>

## Тестирование
Ну типа, ТМ всё равно нужен

## Changelog

:cl:
add: Лобби получило крупное обновление! Новый дизайн, новый стандартный арт и возможность сменить сервер не открывая хаб!
/:cl:

2024-08-08 17:33 UTC, AyIong commented
> старый лобби арт мне нравился больше 🥺

Твоё время прошло, старик

2024-08-10 13:32 UTC, Gaxeer requested changes

2024-08-10 13:32 UTC, Gaxeer commented on code/controllers/subsystem/SSticker.dm
> +			/* N.new_player_panel_proc() */ SStitle.show_title_screen_to(N.client) // SS220 REPLACEMENT - TITLE SCREEN
всё закомменти

2024-08-10 13:32 UTC, Gaxeer commented on modular_ss220/credits/_credits.dme
> +// END_INCLUDE
мусор

2024-08-10 13:32 UTC, Gaxeer commented on modular_ss220/title_screen/code/new_player.dm
> +		SSchangelog.OpenChangelog(client)
```suggestion
	if(href_list["ready"])
		client << output(ready, "title_browser:ready")

	if else(href_list["skip_antag"])
		client << output(client.skip_antag, "title_browser:skip_antag")

	if else(href_list["game_preferences"])
		client.setup_character()

	if else(href_list["swap_server"])
		swap_server()

	if else(href_list["wiki"])
		if(tgui_alert(usr, "Хотите открыть нашу вики?", "Вики", list("Да", "Нет")) != "Да")
			return
		client << link("https://wiki.ss220.club")

	if else(href_list["discord"])
		if(tgui_alert(usr, "Хотите перейти в наш дискорд сервер?", "Дискорд", list("Да", "Нет")) != "Да")
			return
		client << link("https://discord.gg/ss220")

	if else(href_list["changelog"])
		SSchangelog.OpenChangelog(client)
```

2024-08-10 13:32 UTC, Gaxeer commented on modular_ss220/title_screen/code/new_player.dm
> +		return
```suggestion
	if(length(servers) == 0)
		return
```

2024-08-10 13:32 UTC, Gaxeer commented on modular_ss220/title_screen/code/new_player.dm
> +	src.client << link(server_ip)
```suggestion
	client << link(server_ip)
```

2024-08-10 13:32 UTC, Gaxeer commented on modular_ss220/title_screen/code/new_player.dm
> +		server_ip = servers[server_name]
```suggestion
	var/server_name
	var/server_ip
	if(length(servers) > 1)
		server_name = tgui_input_list(src, "Пожалуйста, выберите сервер куда собираетесь отправиться...", "Смена сервера!", servers)
		if(!server_name)
			return
		server_ip = servers[server_name]

	else
		server_name = servers[1]
		server_ip = servers[server_name]
```

2024-08-10 13:32 UTC, Gaxeer commented on modular_ss220/title_screen/code/title_screen_configuration.dm
> +		for(var/list/server in data["cross_server_list"])
```suggestion
		for(var/list/server as anything in data["cross_server_list"])
```

2024-08-10 13:32 UTC, Gaxeer commented on modular_ss220/title_screen/code/new_player.dm
> +		return TRUE
```suggestion
	. = ..()
	var/task = href_list["task"]
	var/preference = href_list["preference"]
	
	if(preference == "changeslot" || (preference == "name" && (task == "random" || task == "input"))
		user.client << output(active_character.real_name, "title_browser:update_current_character")
		return TRUE
```

2024-08-10 13:32 UTC, Gaxeer commented on modular_ss220/title_screen/code/new_player.dm
> +/mob/new_player/Topic(href, href_list[])
```suggestion
/mob/new_player/Topic(href, href_list)
```

2024-08-10 15:52 UTC, Gaxeer approved these changes

2024-08-10 17:56 UTC, Legendaxe approved these changes

2024-08-10 19:36 UTC, merged