RnD remap | Deltastation
ss220club/Paradise-SS220 pull request #1442
Opened 2024-08-23 12:57 UTC by Hearstrings

## Что этот PR делает
**Ремап РнД и юго-западных техов**
_Изменения в рамках отдела РнД и переработка рабочих мест._

## Почему это хорошо для игры
РнД получает более удобные рабочие места, более защищенное хранилище, более обширные и опасные теха.

## Изображения изменений

https://cdn.discordapp.com/attachments/1097543419586428989/1261581357935624252/StrongDMM-2024-07-13_10.06.18.png?ex=66c98832&is=66c836b2&hm=7b595dcf8e5ebf39ea44d2f002332d10f78d3feebb0e0bd0af070a84c67ba66f&

## Тестирование
Локальный сервер

## Changelog

:cl:
add: Расширена ксенобиология РнД. Добавленая новая заброшенная зона в Юго-Западных техах
tweak: Изменения в рамках отдела РнД и Юго-Западных техах
/:cl:

2024-08-23 14:59 UTC, dj-34 requested changes
1. Может изменить раскраску пола? Хотелось бы корректнее выделить вентиляцию, скрабберы и голопад (не очень нравится что квадратная вентиляция расположена на полуквадратной раскраске).
Вот так например:

![image](https://github.com/user-attachments/assets/ee27fc0e-b12a-4e60-ad84-59dfbf47050f)

![image](https://github.com/user-attachments/assets/22f4ad4f-be19-4419-87c4-f46d5be3c70c)

2. Эта зона выглядит немного недоделанной, не хватает какой-то "магии". Все-таки это РнД, может быть здесь стоило бы разместить немного биолюминисцентных цветков, покрыть пол полностью сакурой, добавить каких-нибудь партиклов, например /obj/effect/firefly/green (может быть? а может и не надо). А также стоит поменять icon_state для фонтана на "fountain_g_work", мы же возможно хотим чтобы он работал?

![image](https://github.com/user-attachments/assets/5f6445d0-09f6-43ba-8f85-c7e2e0ac5d19)

3. В стекле скудновато растительности.

![image](https://github.com/user-attachments/assets/afb021a1-6a59-4800-8287-dd26d35ce837)

4. Я так понимаю ты ctrl+c ctrl+v своих старых изменений на новую карту, поэтому здесь нужно вернуть как было (досочки слева были neutral, стали просто wood).

![image](https://github.com/user-attachments/assets/59e454eb-9114-40ee-845a-f587b783c8ed)

5. Замени вар-эдитный пол в серверной на /turf/simulated/floor/bluegrid/telecomms/server и желательно голубой.

![image](https://github.com/user-attachments/assets/ff10282a-d913-4a8b-9df4-81d79cef31fb)

6. Как-то здесь кнопки некрасиво-криво расположены.

![image](https://github.com/user-attachments/assets/451e3d8d-677e-418c-8ab5-34708a386428)

Может быть как-нибудь так?
И еще сделай стандартизацию у кнопок по req_one_access_txt. А то у тебя в одной req_access_txt в остальных req_one_access_txt.

![image](https://github.com/user-attachments/assets/a5b04190-268a-4f7b-8366-68ae731d309a)

7. Конус? Окей...? Ну поправь desc хотя-бы, а то у тебя то после точки нет пробела, то ".!"

![image](https://github.com/user-attachments/assets/890ed630-39f2-4ed4-a538-08b69f8165d0)

8. В Токсинах пропал disaster counter.

![image](https://github.com/user-attachments/assets/6bb326ae-35e7-465d-b85e-fe854f6ba365)

9. Как-то много заграждений в техах, зачем?

![image](https://github.com/user-attachments/assets/47ba36c4-d621-4383-ab60-9940129f8feb)

Как ходить? Как бежать?

![image](https://github.com/user-attachments/assets/53a89073-ad02-4c1f-96f9-816002d6363a)

10. Смешная операционная. Висят шторки, зато со всех сторон прозрачные окна xdd.
Ты уж либо сделай все окна затемненные, либо сделай windoor вместо штор.

![image](https://github.com/user-attachments/assets/6ff9e1c6-ceb5-4236-adf0-b9054b803b4a)

11. У вас реквест консоль повернута неправильно.

![image](https://github.com/user-attachments/assets/03167ec9-e7f8-4b6c-a4a0-3535cdec00a7)

12. Не очень нравится как сделана эта комната

![image](https://github.com/user-attachments/assets/fcae1af4-2aac-4cc2-ad63-aa1b5e5d65cb)

Возможно лучше будет так:

![image](https://github.com/user-attachments/assets/a16b861a-67b7-4138-a9f7-e7e5e7028f99)

13. Опять вар-эдитный пол. И еще поменяй пол вокруг grid'ов на reinforced/xenobio и еще не хватает какой-то безопасности (посмотри как сделано на коробке).

![image](https://github.com/user-attachments/assets/5e05c917-e352-4ba9-b835-c141646c6f2a)

Здесь лучше поменять с green grid на blue grid. Да и во всех камерах он бы лучше смотрелся, имхо.

![image](https://github.com/user-attachments/assets/5b5294cd-31b6-4879-ab4b-93c45dc9c951)

14. Замуровано, кто будет пользоваться? Может дать пару стенок обычных + спавнер секретной/баррикады/стены?

![image](https://github.com/user-attachments/assets/113a0cfc-7ae9-4bb4-82fe-5df1e0c5a5d6)

Здесь такая же ситуация, можно было бы добавить спавнер.

![image](https://github.com/user-attachments/assets/c1639029-e0a0-4d4f-811a-0db51d8dc8c0)

15. Настоящая руна? Слишком жестко как по мне.

![image](https://github.com/user-attachments/assets/caacc08f-42f5-44bc-83d4-8075999c3885)

16. Поменяй siding на подтип wood/oak, либо вообще neutral (это Эйлонговская тема - siding будет брать цвет пола и хуе-мое).

![image](https://github.com/user-attachments/assets/8273bfd3-1b23-41f4-b488-448f679df455)

17. Поменяй дверь у РД с подтипа glass на обычную. Оно не может быть одновременно затемняться и болтироваться по кнопке.

![image](https://github.com/user-attachments/assets/034dd5c8-6b87-4c91-b12d-e023e99e3341)

И почему здесь у стекла не проведена проводка?

![image](https://github.com/user-attachments/assets/88f02107-2593-4235-8278-5cfc77c6ab89)

18. Очень слабый визуал.

![image](https://github.com/user-attachments/assets/922915a1-5b03-4d51-a627-a21430d904d5)

Может как-нибудь вот так?

![image](https://github.com/user-attachments/assets/078f4198-aec3-44f8-9686-1f430401e31d)

19. Вот этот уголок немного выглядит некрасиво.

![image](https://github.com/user-attachments/assets/f7b795c9-4e2d-46ea-b067-25d9b1eb0fa9)

Может как-нибудь вот так?

![image](https://github.com/user-attachments/assets/eb0d4d95-710a-49c0-adec-97acac88e25b)

20. Вот эти фаерлоки расположенные на стекле выглядит странно, следовало бы переместить к стенам.

![image](https://github.com/user-attachments/assets/78f4a2f4-4665-4a78-9fb9-b635016a3fac)

![image](https://github.com/user-attachments/assets/ba9e72cf-3810-40bd-ae88-1de4451b6e77)

21. Здесь под фаерлоками не хватает декалей как у остальных.

![image](https://github.com/user-attachments/assets/e8bc323f-7379-434b-8967-a6577e73f1b3)

2024-08-27 04:49 UTC, dj-34 commented
Надеюсь финальное ревью, проверь чтобы на карте все было ок, не выдавало рантаймы и был ренж у камер, интеркомов.

1. Здесь не требуется плазмастекло, а также укрепленный пол стоило бы заменить на
/turf/simulated/floor/plasteel/dark/telecomms
Для этого помещения требуется выделенная зона
/area/station/science/server/coldroom
и собственная серверная аир алярма
/obj/machinery/alarm/server/directional/west
и все остальное что требуется для новых зон: фаер алярма, апц.
и дверь в подтип glass засунь.

![image](https://github.com/user-attachments/assets/a8bcbb70-8f31-49b2-bb4f-3d036659a4cf)

И все двери поменяй к серверной на command раскраску

![image](https://github.com/user-attachments/assets/0b023a73-2c60-4a30-aa56-957a31e7398b)

2. Почему решил не притрагиваться к этой зоне? Она выглядит сыровато для РнД.

![image](https://github.com/user-attachments/assets/510ede39-23b4-436d-80fb-3e11308a5464)

3. Как-то идеально чисто для зоны обслуживания, может быть выбрать потрёпанный спрайт этой же плитки "floorgrime"?

![image](https://github.com/user-attachments/assets/6fd0274a-4124-4be0-9f38-b5ec61c2fc62)

4. Так и не поменял вар-эдитный пол. Внимательнее.

![image](https://github.com/user-attachments/assets/e6c72e71-4524-4a1c-a9fc-4a78e4fb31e9)

5. Мусоропровод обрывается.

![image](https://github.com/user-attachments/assets/68c0e54e-5c42-497c-9089-f20a6f8c7156)

6. Для идентичности сделай чтобы все переходы между комнатами были либо белой плиткой, либо розовой везде.

![image](https://github.com/user-attachments/assets/051df983-079f-4950-848f-da7f10890d04)

![image](https://github.com/user-attachments/assets/e39bd361-b141-47eb-936d-f61098621eed)

7. Мне не очень нравится что один тип (спрайта) кнопок находится на разной высоте.
Keycard Auth стоило бы поменять местами с кнопкой Biohazard Shutter Control

![image](https://github.com/user-attachments/assets/958001ae-f3ad-4a19-a21b-a2896a78a9d2)

8. В верхней комнате нет камер.

![image](https://github.com/user-attachments/assets/f092e70d-adbe-434b-924a-7768fa9ab87d)

9. У РД ни одной камеры.

![image](https://github.com/user-attachments/assets/f22781de-c226-4f59-985c-dc84471576cd)

10. Здесь снаружи тоже нет камеры.

![image](https://github.com/user-attachments/assets/b387c470-5177-486e-8e1a-7a2b2a3eb45d)

11. В этом участке коридора нет ни одной фаералярмы.

![image](https://github.com/user-attachments/assets/0a1a0e0d-eb32-4485-b8a3-eff4230bfc2e)

12. Фаералярма внутри экспериментора? Не лучшая идея.

![image](https://github.com/user-attachments/assets/db9777c9-1bb8-4117-83de-128b0431e5ed)

13. Лишний провод.

![image](https://github.com/user-attachments/assets/a9ec7423-344d-482b-9bbb-3153e98365b4)

14. Еще обрыв провода.

![image](https://github.com/user-attachments/assets/63397d25-0242-4405-a69e-624f90fe96aa)

15. Обрыв труб.

![image](https://github.com/user-attachments/assets/14a44460-e870-4395-bea2-e36c324489ea)

16. Обрыв мусоропровода.

![image](https://github.com/user-attachments/assets/3a672141-73a2-4333-a9d5-5a1af6e65696)

17. Не вижу РДшной зажигалки и офисной игрушки. Да и шредера бы не помешало.

![image](https://github.com/user-attachments/assets/c64b151a-ff70-443b-9c33-10b31073f4d7)

18. Дверь вар-эдитная.

![image](https://github.com/user-attachments/assets/41f552db-5df1-4c83-a530-7ebd38493662)

19. Двери в ксенобиологию следовало бы сделать шлюзовой, по примеру как сделано на Парадайзе - одна открывается, другая закрывается.

![image](https://github.com/user-attachments/assets/f1ac59a1-a5df-49c0-ad67-c904156bbc15)

И поделить вот эту небольшую зону на еще одну комнату

![image](https://github.com/user-attachments/assets/dadcab6a-0781-4caf-b33d-7aa6356b7327)

Вот так +-, чтобы просто показать что это (по крайней мере однажды) была защищенная зона, и немного отделить лут.

![image](https://github.com/user-attachments/assets/2453ea80-1539-4515-a25d-5fb69217ffa5)

20. Поглоти двери техов зоной техов.

![image](https://github.com/user-attachments/assets/5472cf1a-36ee-475d-8328-5d7cac1b7a12)

![image](https://github.com/user-attachments/assets/82098d3a-dd07-4390-af8f-9fb43f185933)

![image](https://github.com/user-attachments/assets/abf3f1c6-ba9a-4fad-a36c-8e760663b201)

![image](https://github.com/user-attachments/assets/2f079989-bc3b-4447-b088-d2cdb2991940)

Вот так:

![image](https://github.com/user-attachments/assets/85149975-aa1e-4d96-8bb0-58c66eb28a86)

21. РД в своей спальне не хватает отдельных затемняющихся окон с отдельной кнопкой.

![image](https://github.com/user-attachments/assets/19bc09ca-fafd-46ec-8fb1-707a0609fc4f)

22. На полигоне камера не защищена от взрыва, а также нет маячка. И не хватает предупреждающих наружных знаков.
Также по пути к полигону следовало бы разместить маячки /obj/structure/marker_beacon/dock_marker/collision по примеру с Метой.

![image](https://github.com/user-attachments/assets/cdbfe155-0d56-422a-8203-fcefb46693ea)

2024-08-27 04:59 UTC, dj-34 commented
В чейнджлоге не забывай указывать какая карта.

![image](https://github.com/user-attachments/assets/64325e27-d2bf-44b5-9888-03200c88e4a8)

2024-08-27 09:59 UTC, Hearstrings commented on _maps/map_files220/stations/deltastation.dmm
> +/obj/structure/fans/tiny,
блять... Нет конечно

2024-08-27 10:00 UTC, Hearstrings commented on _maps/map_files220/stations/deltastation.dmm
> +/obj/structure/fans/tiny,
:D

2024-08-28 01:35 UTC, dj-34 approved these changes

2024-08-28 01:36 UTC, dj-34 commented
Ну вроде самые явные ишуе поглядел, единственное что не сверял - наполнение, поэтому может что-то не хватать, или что-то быть в избытке.

2024-08-28 09:20 UTC, Hearstrings commented
Проверены кнопки, полигон, консоли. Вроде все норм

2024-08-28 10:54 UTC, AyIong requested changes
Ну типа, после диджея я бы удивился если бы нашёл много xdd

<details>
<summary> Много букав и пикч </summary>

Мне лично не нравится как трубы тут сделаны.
И ты lightsout хелпер чёт в коридор выкинул, поставь его на голопад
Плюс, слишком много ламп, тут можно смело убрать 2
| Сейчас | Предложение |
| - | - |
| ![image](https://github.com/user-attachments/assets/bbc5fee8-193d-45b5-96ba-f95d24a59004) | ![image](https://github.com/user-attachments/assets/1c35bdc7-1679-41a5-8658-59b28b6f6175) | 

Я осуждаю такое разделение помещений, особенно дважды...
Сделай как человек :xylipizdish:

| 1 | 2 |
| - | - |
| ![image](https://github.com/user-attachments/assets/489c6d5b-d8cf-4118-a491-a14d8ef1bb81) | ![image](https://github.com/user-attachments/assets/77868020-191b-46ae-8187-617f243759a0) |

Вот тут можно вытащить стеклянную дверь из под этой хуйни, так как её хуй взломаешь

![image](https://github.com/user-attachments/assets/6be4ec7e-9c06-465a-8221-49034f255c13)

Такое я тоже осуждаю.
Лучше сделай уникальный ящик, спрайт можешь попросить у рисоваров
Заодно и баллон с маской туда воткнёшь
![image](https://github.com/user-attachments/assets/959b2469-b50b-42bc-b11b-402b0332db3f)

Старайся не ставить эти ебущие провода там где их нельзя обойти
![image](https://github.com/user-attachments/assets/b139b790-edcc-4711-b9bd-0f4440b5da72)

Мне кажется тут лучше поставить перилла вместо фуллтайл стекла
![image](https://github.com/user-attachments/assets/fa481d44-726c-465a-9d91-d723f8959153)

Как-то.... скучно?
Коридоры техов в целом какие-то скучненькие, а их много
![image](https://github.com/user-attachments/assets/451eab6a-161e-4d94-b340-a827d8fef8c5)

</details>

2024-08-30 09:31 UTC, AyIong approved these changes
Вроде всё ок

2024-08-30 09:31 UTC, merged