Organ Freezer
ss220club/Paradise-SS220 pull request #1446
Opened 2024-08-26 09:09 UTC by Hearstrings

## Что этот PR делает
Добавлен холодильник для органов расширенного объема (в 2 раза)

## Почему это хорошо для игры
Удобство в хирургии

## Изображения изменений
![image](https://github.com/user-attachments/assets/56f0a280-d279-4044-a2ca-5e0453d881ee)

## Тестирование
Локальный сервер

## Changelog

:cl:
add: Добавлен холодильник для органов в хирургию на Коробку, Дельту, Мету 
del: Удалены ящики с кровью из хирургии
/:cl:

2024-08-26 09:52 UTC, AyIong requested changes

2024-08-26 09:52 UTC, AyIong commented on modular_ss220/objects/code/closets.dm
Вместо копипастинга, сделай его подтипом уже существующего ящика, и измени спрайт название, описание да количество слотов

2024-08-26 10:03 UTC, AyIong approved these changes
Можешь ещё перевести описание
А так ок

2024-08-26 19:21 UTC, dj-34 reviewed
Палитру бы сменить на цвета пожарного шкафчика, уж очень десатурированный спрайт.

2024-08-26 19:23 UTC, dj-34 commented
И ещё не понятно куда девается крышка при открытом состоянии

2024-08-28 13:58 UTC, Hearstrings commented
![image](https://github.com/user-attachments/assets/5d867f13-1f5f-43c1-8bf1-cc2b785eec16)

2024-08-28 14:00 UTC, dj-34 requested changes

2024-08-28 14:00 UTC, dj-34 commented on modular_ss220/objects/code/closets.dm
> +	name = "Organ freezer"
```suggestion
	name = "organ freezer"
```

2024-08-28 14:02 UTC, dj-34 approved these changes

2024-08-28 14:14 UTC, merged