Fix failing nanomap action
ss220club/Paradise-SS220 pull request #1469
Opened 2024-09-04 02:16 UTC by m-dzianishchyts

## Что этот PR делает
Чинит [action](https://github.com/ss220club/Paradise-SS220/actions/runs/10693387425/job/29643447872). Несуществующий файл больше не переименовывается, там уже подходящее имя.

2024-09-04 12:49 UTC, dj-34 requested changes
Какой-то не фикс.
Просто переименуй
mv "Lavaland_z1.png" "Lavaland_nanomap_z1.png"
в
mv "Lavaland_nanomap_z1.png" "Lavaland_nanomap_z1.png"

2024-09-04 18:53 UTC, AyIong commented
> Какой-то не фикс. Просто переименуй mv "Lavaland_z1.png" "Lavaland_nanomap_z1.png" в mv "Lavaland_nanomap_z1.png" "Lavaland_nanomap_z1.png"

Эта хуйня если шо переименовывает файл
Оно не может найти то что надо переименовать, а если переименовывать не надо то нахуя оно?

2024-09-04 18:53 UTC, AyIong approved these changes

2024-09-06 15:26 UTC, AyIong approved these changes

2024-09-07 00:37 UTC, dj-34 approved these changes

2024-09-07 00:37 UTC, merged