[Prime Only] add event outfits
ss220club/Paradise-SS220 pull request #1531
Opened 2024-09-19 16:36 UTC by Fullonibus

## Что этот PR делает

Добавляет аутфиты для ивентовых персонажей прайма (прайм онли)

## Почему это хорошо для игры

Легче настраивать ивентовых персонажей для раунда.

## Изображения изменений

## Тестирование

In my mind

## Changelog

:cl:
add: Добавлены аутфиты для ивентовых персонажей прайма
/:cl:

2024-09-19 16:43 UTC, PhantornRU commented
Линтер падает. Тестируй то что добавил сам.
Error OD0404 at modular_ss220/prime_only/code/outfit.dm:23:12: Type /obj/item/card/id/centcom/tanya does not exist

2024-09-19 16:43 UTC, PhantornRU requested changes
Исправь карты

2024-09-20 11:37 UTC, PhantornRU approved these changes

2024-09-20 19:17 UTC, Fullonibus commented on _maps/map_files220/RandomRuins/SpaceRuins/ussp_base.dmm
Вообще в ротацию не планировалась. Изначально помещалась чтобы прогнать её по линтеру. В целом, может пригодится админам для ивентов с СССП базой (нам в том числе)

2024-10-25 00:37 UTC, closed without merging