Add: Nanotrasen Food vendor
ss220club/Paradise-SS220 pull request #1539
Opened 2024-09-22 07:28 UTC by dj-34

## Что этот PR делает
- Добавляет новый вендор "Nanotrasen Food" - специализированный автомат поставляемый самой Нанотрейзен для своих самых дорогих сотрудников. Преимущественно нужно для Центкома (поскольку овербаффнутая еда), но можно добавлять и в какие-нибудь руинки.
- Добавлена возможность распаковки еды на Z, поскольку все обертки снимаются на эту кнопку и кликать Альтом интуитивно становится непонятно.
- На Центкоме [починил свет на мостике](https://github.com/user-attachments/assets/9d448461-3989-468a-8bb1-3afe513e004b) (ну это так, бонусом).

## Почему это хорошо для игры
Хоть что-то новое для Центкомовцев, вместо молока вульп.

## Изображения изменений

(заскринил не в лучший момент, там анимация с логотипом и бургерами)
![image](https://github.com/user-attachments/assets/10131583-2d6f-489f-8ff1-2bf4c0a1d050)

## Тестирование
Проверял в игре.

## Changelog

:cl:
add: Добавлен новый автомат "Nanotrasen Food" - специализированный автомат поставляемый самой Нанотрейзен для своих самых дорогих сотрудников. На данный момент установлены на Центкоме, но в будущем могут появиться где-то ещё.
/:cl:

2024-09-22 08:16 UTC, kyunkyunkyun commented
добавьте вульпиксы на цк вместо чанга

2024-09-22 08:21 UTC, AyIong requested changes

2024-09-22 08:21 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +	return
Теперь это нельзя кушать :c

2024-09-22 08:21 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +	AltClick(user)
Я против быстрого открытия на Z, идея была в том что-бы чел кликал на еду для открытия, а не просто лишний раз нажимал кнопку на похуй

2024-09-22 08:21 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> -	return ..()
Я это сделал не просто так, специально для еды которую надо ещё и достать, по идее это можно перенести в переменную, например `need_takeout` и уже выше в attack()
`if(opened && need_takeout) return FALSE`

2024-09-22 11:57 UTC, dj-34 commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +	AltClick(user)
Пицца открывается на Z, письма распаковываются на Z, банки откупориваются на Z.
Наличие такой идеи это конец, да еще и неудобный.

2024-09-22 15:38 UTC, AyIong requested changes

2024-09-22 15:38 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> + * MARK: | Fancy Food
```suggestion
 * MARK: Fancy Food
```
Вообще, это не обязательно так как и так понятно что вначале логика

2024-09-22 15:38 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +		return
```suggestion
		return FALSE
```
Нет смысла удалять FALSE

2024-09-22 15:38 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +		return
```suggestion
		return FALSE
```

2024-09-22 15:38 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +	AltClick(user)
> Пицца открывается на Z, письма распаковываются на Z, банки откупориваются на Z. Наличие такой идеи это конец, да еще и неудобный, непоследовательный.

Я не говорил что мне нравится то что так сейчас, с банками ещё ладно, их и в жизни в слепую открыть можно, коробку из под пиццы думаю тоже справиться можно вслепую открыть.
Но я хз как тот же условный дошик ты откроешь вслепую, банально не сразу найдёшь где бипка за которую тянуть нужно

2024-09-22 15:38 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> + * MARK: | Packed Fancy Food
```suggestion
 * MARK: Packed Fancy Food
```

2024-09-22 15:38 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +/obj/item/food/fancy/packed/LateInitialize()
```suggestion
/obj/item/food/fancy/packed/LateInitialize()
```
Я насколько помню, в гайдлайнах написано избегать использования LateInitialize

2024-09-22 15:38 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +	possible_food = list(/obj/item/food/burger/macvulp)
Думаю было бы удобнее прямо в объекте писать возможную еду, а не добавлять её в ините, и логичнее, так как практически везде так

2024-09-22 22:29 UTC, dj-34 commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +	var/list/possible_food
Ну, как в столовках. Бери что дают, не хочешь - готовь сам, или ешь в другом месте.
Что касается рас, то по задумке, эта еда чистейшая бутафория, похожая на привычную еду.

2024-09-22 22:29 UTC, dj-34 commented on modular_ss220/vending/code/vending_food.dm
> +		"Быстрая готовка, а точнее её отсутствие — Рай для корпората.",
у нас везде длинное тире юзается

2024-09-22 22:31 UTC, dj-34 commented on modular_ss220/food_and_drinks/code/drinks.dm
ЭРПе. У нас почти вся еда стоит на 3 реагентах, поэтому это не так важно брать во внимание.

2024-09-22 22:36 UTC, dj-34 commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> + * MARK: | Packed Fancy Food
я специально ебанул разделитель для категории, чтобы ее четче было видно

2024-09-22 22:37 UTC, dj-34 commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +/obj/item/food/fancy/packed/LateInitialize()
не вижу проблем, да и по другому я не вижу реализации

2024-09-23 03:10 UTC, dj-34 commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> + * MARK: | Fancy Food
Шоб красиво было, разделитель специально чтобы было видно что начинается логика, а под ней сама еда.

2024-09-23 03:37 UTC, dj-34 commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> + * MARK: | Packed Fancy Food
![image](https://github.com/user-attachments/assets/4e3950e3-5bfd-42b1-a0d1-d05d7af242ea)

2024-09-23 04:18 UTC, AyIong approved these changes

2024-09-23 04:18 UTC, AyIong commented on modular_ss220/food_and_drinks/code/food/fancy_food.dm
> +	AltClick(user)
> Солидарен с сидоджи

Я ваши рты ебал, хейтеры иммерсивности

2024-09-23 07:34 UTC, merged