Race jobs restrictions
ss220club/Paradise-SS220 pull request #1559
Opened 2024-09-27 21:13 UTC by Surikat2k

## Что этот PR делает
Добавляет возможность отключать профессии расам

## Почему это хорошо для игры
Позволит в дальнейшем вводить ограничения для использования расами профессий

## Изображения изменений
![image](https://github.com/user-attachments/assets/c5b3bdc0-b705-4c3d-bcd8-5c97c5720223)

## Тестирование
Тестировал на локалке

## Changelog

:cl:
add: Возможность возможность отключать профессии расам
/:cl:

2024-09-28 11:17 UTC, AyIong commented on modular_ss220/jobs/code/jobs_character.dm
> +#define MAX_PLAYER_AVALIABLE_DISABILITES 0xFFF // Max available bit mask for disablities
Я всё ещё не понял что это за число

2024-09-29 08:17 UTC, dj-34 reviewed
Возможно стоит ввести уточнение, ибо будут вопросы

2024-09-29 08:17 UTC, dj-34 commented on code/modules/client/preference/character.dm
> +				html += "<del class='dark'>[rank]</del></td><td class='bad'><b> \[RESTRICTION\]</b></td></tr>"
```suggestion
				html += "<del class='dark'>[rank]</del></td><td class='bad'><b> \[SPECIES RESTRICTION\]</b></td></tr>"
```

2024-09-29 08:28 UTC, dj-34 commented on code/modules/client/preference/character.dm
> +				html += "<del class='dark'>[rank]</del></td><td class='bad'><b> \[RESTRICTION\]</b></td></tr>"
А ты проверял?

2024-09-29 08:43 UTC, dj-34 commented on code/modules/client/preference/character.dm
> +				html += "<del class='dark'>[rank]</del></td><td class='bad'><b> \[RESTRICTION\]</b></td></tr>"
Ладно, выглядит не очень

2024-10-14 15:27 UTC, PhantornRU requested changes

2024-10-14 15:27 UTC, PhantornRU commented on code/modules/client/preference/character.dm
> +				continue
добавить приписку по границам
// SS220 ADD - Start
// SS220 ADD - END

2024-11-23 00:38 UTC, closed without merging