Space Ruin - Transit Bar
ss220club/Paradise-SS220 pull request #156
Opened 2023-09-05 21:25 UTC by konushi

## Что этот PR делает
Добавление маленькой косморуины - мини паб в космосе (port/remap transit_booth from Skyrat)
Лут: бухломат, раздатчики, приятная атмосфера

## Почему это хорошо для игры
Больше косморуин - больше косморуин

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/139562134/e16a25a0-ae35-402e-ade1-a7a695b29457)

## Тестирование
В этот раз ТОЧНО без косяков

## Changelog

:cl:
add: новая карта - transit_bar
/:cl:

2023-09-06 23:16 UTC, Furrior commented
Криво вмержен апстрим, потеряна одна строка в paradise.dme, что выдает ошибку в тестах
(Вот эта)
![изображение](https://github.com/ss220club/Paradise-SS220/assets/68264134/12a0ecdc-6f76-48ac-883d-f426607af32e)

2023-09-07 06:17 UTC, Aylong220 commented
Боже, что с коммитами? Чё так много... 
Ты либо как-то не так ребейзишь, либо создаёшь ветки на основе веток прошлых руин

2023-09-07 06:21 UTC, Aylong220 requested changes
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/921b4fcc-43ab-439b-bee3-dbe328b9b696)
Вентиляторы под шлюзы засунь.
А так красиво, если не смотреть в коммиты...

2023-09-07 06:37 UTC, Furrior commented
Планировка стойки, конечно, странная с таким расположением диспенсеров...

2023-09-07 06:55 UTC, konushi commented
> Планировка стойки, конечно, странная с таким расположением диспенсеров...

Могу его развернуть, это не критично. Просто подумал, что будет прикольно смотреться по типу пивной колонны

2023-09-07 06:56 UTC, konushi commented
> Боже, что с коммитами? Чё так много...
> Ты либо как-то не так ребейзишь, либо создаёшь ветки на основе веток прошлых руин

Я еще разок порядок действий своих пересмотрю…

2023-09-07 16:44 UTC, Aylong220 approved these changes
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/b76d35a0-641e-429d-9a33-7dc8a91675a5)

2023-09-08 04:00 UTC, Furrior approved these changes

2023-09-08 04:00 UTC, merged