Tweaking explorers and shaft miners rooms, adding personal closets for them
ss220club/Paradise-SS220 pull request #1579
Opened 2024-10-05 04:04 UTC by kyunkyunkyun

## Что этот PR делает

Добавляет на все карты личные шкафы для шахтёров и гейтеров. Ранее они были лишь на Дельте у шахтёров.
Расширяет комнату шахтёров на Мете.
Удаляет 2 аптечки шахтёров и 2 аптечки гейтеров на Дельте. У гейтеров есть аптечки в шкафах, а у шахтёров на всех картах по одной.
Добавляет 1 аптечку и коробку донков шахтёрам на Мете. Добавляет коробку донков шахтёрам на Коробке.
Добавляет шкаф с чипами изгнания на Дельту и Мету
Добавляет зарядник для киборгов в гейтрум на Мете.
Удаляет хранилища модов и южный шлюз в гейтруме на Мете. (МАЛО МЕСТА!).

## Почему это хорошо для игры

Даёт возможность исполнять своё СРП шахтёрам и не выносить артефакты за пределы отдела. А у гейтеров вообще СРП нет. 
Снизит процент гейтеров с контрабандой/шахтёров с артефактами, гуляющих по станции.
Игроки любит присваивать чужое. Личный шкафчик заставит их потрудиться чуть больше, чем обычно. 
Чипы изгнания должны быть на всех картах, т.к. у нас есть гейт.

## Изображения изменений

<details>
<summary>Коробка</summary>
<h1>Гейт</h1>

![image](https://github.com/user-attachments/assets/07582790-91e1-4a7c-8132-247e7a3f2850)
<h1>Шахтёрский док</h1>

![image](https://github.com/user-attachments/assets/d7d754f2-1953-4f03-ac2d-53dbe7854a4b)
</details>
<details>
<summary>Дельта</summary>
<h1>Гейт</h1>

![image](https://github.com/user-attachments/assets/64e4ff02-a58e-4cd5-8796-a2f6487fc1b6)
<h1>Ева</h1>

![image](https://github.com/user-attachments/assets/56bd75b4-0122-43b0-86cf-9c120e7fdc24)
</details>
<details>
<summary>Мета</summary>
<h1>Гейт</h1>

![image](https://github.com/user-attachments/assets/5d5d1f2d-ed02-4e32-a3c6-56021b8f563a)
<h1>Шахтёрский док</h1>

![image](https://github.com/user-attachments/assets/995740f0-0be3-4799-b25e-1b199d2beadc)
</details>

## Тестирование

Побегал на локалке, вроде файн

## Changelog

:cl:
add: У гейтеров и шахтёров на всех картах появились личные шкафы для складирования снаряжения и артефактов.
del: На Дельте отдел карго лишился четырёх аптечек чтобы покрыть расходы на новые личные шкафы для гейтеров.
tweak: Слегка изменены комнаты гейтеров, шахтёров и гейтрум на всех картах.
fix: Шкаф с чипами изгнания (exile) теперь есть в ЕВА хранилище на каждой карте.
/:cl:

2024-10-05 04:14 UTC, ErdGinalD commented
Добавь лучше шахте хилки в каждый ящик, чтобы равноценно было. Да и конкуренция за мегафауну выше будет, а не только у того кто аптечку спиздил.

2024-10-05 11:37 UTC, kyunkyunkyun commented
> Добавь лучше шахте хилки в каждый ящик, чтобы равноценно было. 

я на Мете еле шкафы впихнул путём расширения комнаты.. а ты хочешь, чтобы я ещё 3 шкафа добавил туда. Ну если дэвы скажут, то добавлю аптечки шахтёрам в раундстарт шкаф

2024-10-05 17:26 UTC, dj-34 requested changes
1. Я не вижу смысла в приват шкафах на станции, учитывая что согласно СРП, шахтёры не имеют право вывозить артефакты с Лаваленда.
Хорошей реализацией, вместо плодения сущностей на станциях, расширить комнаты на Лаваленде и добавить персональные шкафы там.

2. Не нравится реализация шкафов у экспедиторов. В целом, не вижу потребности для их персональных шкафов, учитывая что все что они вывозят оттуда - вывозится в шкафах, в основном в составе команды. Также у них нет потребности в приватных шкафах, ибо всё что они вывозят, в идеале, должно уходить в счёт станции, а не использоваться как у шахтёров - для ебки шахты.
К тому же у нас есть космо-экспедиторы. Нахождение приват шкафов в гейтерской выглядит странно и нелогично. А еще мне не нравится что шкафы экспедиторов буквально вырезались с Кибериады.

Итого: Идея неплохая, реализация подкачала.
Майнерам шкафы на Лаваленд. Экспедиторы - не нуждаются. Exile импланты на все карты - хорошо, недочёт, если где-то забыли.

2024-10-05 18:04 UTC, kyunkyunkyun commented
>  шахтёры не имеют право вывозить артефакты с Лаваленда.

Имеют право на артефакты на Лаваленде и в пределах карго. В условном режиме культа, защищать отдел (который даёт тебе снабжение оружием экипажа) артефактами будет удобнее, если артефакты будут непосредственно на станции, а не на другом Z уровне, где зачастую и сидят антаги. Мне хочется сделать шкафы на станции, ибо это банально приятнее по геймплею, когда тебе не нужно лететь в другой сектор за какой-то безделушкой. Но я могу перенести для экономии места в шахтёрском доке на станциях.

> Не нравится реализация шкафов у экспедиторов. В целом, не вижу потребности для их персональных шкафов.

Некоторые руины ты не зачистишь без дополнительного оружия или снаряжения. Сдавать контрабанду СБ = хоронить её до конца раунда, ведь СБ ей пользоваться не может и она пролежит в уликах два часа без применения. Сдавать учёным - ты сдашь 1-2 предмета, доведя нелегал до 5 уровня и всё. Я, например, не хочу на гейтере ходить с бладмодом на спине по станции. В космосе он даёт хорошую защиту, на станции он мне не нужен. 

> шкафы экспедиторов буквально вырезались с Кибериады

В них был гейтган и аптечка. Гейтган перенёс в обычный шкаф, аптечка даётся и так. Да и они со всех карт уже вырезаны, кроме Кибериады, и заменены на шкафы оффов

> Нахождение приват шкафов в гейтерской выглядит странно и нелогично

Вышел с гейта, сложил всё в шкаф и пошёл на станцию как ни в чём не бывало, не боясь, что тебя остановит СБ за красный поясок с инструментами, который у нас является контрабандой. Гейт самое укреплённое место у гейтеров, их обычная комната на Кибериаде без укреп стен, так что контрабанду оттуда достать обычным игрокам будет посложнее обычного.

2024-10-06 23:05 UTC, AyIong requested changes
Ух блять... ну ты даёшь, не надо жертвовать кучей всего ради шкафчиков которыми почти не пользуются...

<details><summary> Кибериада </summary>
Во первых, на полки ставь только не габаритные предметы, провода, тулбоксы и подобное, а на стол уже кирки и прочее здоровое
Во вторых, шкафчики снизу расположены очень странно, сделай их 5 в линию внизу и убери странный спавнер шахтёра, компы слева наверх можно
В третьих, слишком много шкафов, ими не то что-бы часто пользуются насколько я знаю, но допустим? 
В общем чекай пикчу, надеюсь поймёшь

По поводу эксплореров, верни им паутину, там и так грязно, и паутина выглядит аутентично. Гейт ганы нужно засунуть кодом в их ящик дабы не срать кодом, рации можешь так же всунуть, либо на полку вместо стола, тулбокс с проводом туда же, это если решишь полки использовать.

![image](https://github.com/user-attachments/assets/976390da-8885-4c8a-b549-4a50377c5d06)

</details>

<details><summary> Дельта </summary>
Во первых, так же проблема с полками и большими предметами, думаю лучше передвинуть полки вниз слева, и закинуть туда только тулбоксы. Карку и лопату же на раки там где сейчас полки.

![image](https://github.com/user-attachments/assets/1b9d6ded-55b8-4fe1-9d07-1b65dc096b0b)

Во вторых, в еве личный шкафчик лишний как мне кажется, лучше воткнуть аптечки которые ты спиздил у кексплореров в отделе, и цветами можно было пожертвовать придумав что-то более оптимальное.
Вообще, странное перемешивание предметов лишь бы перемешать

И это... ты куда ящик заныкал? xdd
![image](https://github.com/user-attachments/assets/9f7c6bf5-57f6-47a2-8a35-1330e0816d7a)

</details>

<details><summary> Мета </summary>
Во первых, ну ты чего? Куда нычку вырезал?
![image](https://github.com/user-attachments/assets/1dddcc91-3d3e-48d6-b1fa-440238511302)

Во вторых... ну это пиздец, мета - компактная карта, а ты личных шкафчиков напхал больше чем основных, ещё и неприлично здоровая комната... Можно ведь было просто столы почистить выкинув всё с них на полку/раки, ну и пару тайлов добавить для 3-х персональных шкафчиков.
Компы правда неплохо засунул, но ты забрал топливо, что им пить?

В третьих, ты спиздил у кексплореров их мод сторейджи ради личных шкафчиков? Харам.

В четвёртых, как я уже написал выше, личный шкафчик в еве - лишний, лучше накинуть ещё одну еву сторыгу.
</details>

2024-10-10 08:22 UTC, dj-34 commented
@kyunkyunkyun
Увы, но я это не буду рассматривать если чтобы закинуть шкафчики которыми как сказал Эйлонг, пользуются, ну дай бог, 1-2 человека за раунд - нужно жертвовать чем-то, тем более значительно, то это сразу отмена. Лаву меняешь и всё, если хочешь шкафчики. Лава это исключительный отдел шахтёров и КМа, вот пожалуйста пускай и защищают свой отдел - аванпост.
По поводу экспедиторов - не согласен ни в одном пункте. Ты априори не можешь носить и хранить контрабанду, наличие шкафчиков абсурдно, тем более в гейте (если ты исследователь космоса).
Шкафы экспедиторов не вырезались, это наша разработка, они были только на Кибериаде, потому что места на других карт под них нет.

2024-10-24 11:48 UTC, kyunkyunkyun commented
я бы вас обозвал.. но меня забанят.
а ещё я думал, что личные шкафы прикреплены к полу и их таскать нельзя, так что irrelevant

2024-10-24 11:48 UTC, closed without merging