New security helmet and coat
ss220club/Paradise-SS220 pull request #1586
Opened 2024-10-10 00:01 UTC by Glamyrio

## Что этот PR делает

ПР добавляет набор из трёх предметов которые можно примерить на вашей кукле.

## Почему это хорошо для игры

~~Моя звай Гламур! Я люблю делай косплеи! Нраица! Эта моя государства Нанотразен. Он середина между СССП, ТСФ и ещё чиндикат. Здесь моя город Кибериада. Это Вульпикс, ерпшер местный. Нехороший! А вот здесь наш бриг. А здесь живёт СЕ с Поли, местный механько и см-о-дестабилизаторомахер. Это моя хата. Заходи, пожалуйста! Он моя сосед. Ассистос Серый. Боль в моя дырка задница. Я делай всё из стекла, он тоже делай всё из стекла. Я делай баню, он тоже делай баню. Я закупай косплей. Он не накопил. Радостно! (что только не придумаешь в 3 часа ночи)~~
это крутой костюм. Все.

## Изображения изменений

![screen1](https://github.com/user-attachments/assets/efe271df-fcd4-483b-ba14-906b11b307da)
![screen2](https://github.com/user-attachments/assets/43a0e094-bec7-4029-93d5-829f29bedebe)
![screen3](https://github.com/user-attachments/assets/518b9185-e144-4445-99ad-e2547422b2ef)
Возможно в процессе придётся изменить спрайты

## Тестирование

протестировано на локалке, все работает

## Changelog

:cl: glamyr
add: Добавлен набор метрокопа во взломанный SecDrobe.
tweak: Одежда младшего персонала теперь доступна в вендорах отделов.
/:cl:

2024-10-10 00:12 UTC, AyIong commented
Ты же говорил что это не на наш билд
Спрайт маски к слову, всё ещё лоу-контраст оверколоред шляпа, ещё и огромная
Ты бы со спрайтерами посоветовался

2024-10-10 04:11 UTC, PhantornRU requested changes
Задумка нравится, но да, нужно поправить сами спрайты.
Я б без шуток, но вообще сделал бы таких юнитов "РХБЗ-ЕРТ". Если хочется зайти дальше, то можешь буквально сделать аутфит РХБЗ-ЕРТ. Ну так, просто если захочешь :)
Глазницы - точно нужно переспрайтить ИЛИ снизить прозрачность. Зайди в спрайтерскую и там это обсуди лучше, поможем.
![image](https://github.com/user-attachments/assets/5e7993dc-5e9b-4bf8-80d6-9f415908a3fd)
![image](https://github.com/user-attachments/assets/298a938d-4567-4616-82cf-729d53010ede)

2024-10-10 05:44 UTC, dj-34 reviewed
спрайт не очень, и куртка какая-то обрывистая больно

2024-10-11 09:19 UTC, dj-34 commented
> ![screenы](https://private-user-images.githubusercontent.com/174347315/375513564-3938fbc7-1a53-4d65-9b5e-3906d25bed5f.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2Mzg1NTEsIm5iZiI6MTcyODYzODI1MSwicGF0aCI6Ii8xNzQzNDczMTUvMzc1NTEzNTY0LTM5MzhmYmM3LTFhNTMtNGQ2NS05YjVlLTM5MDZkMjViZWQ1Zi5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxMVQwOTE3MzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNTkzOWJiZDgxNmI5NzNkZDQ1Y2EzZjE4ZjI0NDE4Njc4N2NlZDkyNmZhNDM4MzYzODI2MDEyNGY0Y2RmYzhlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.6E--iLcQ7ALVgf2WZLgSXtadU22_Cp25_z2Yv8V9xNo) теперь линзы шлема прозрачны, а сам шлем смахивает на клуелес. Да да, те пиксели на линзах это глаза. Так же насчёт куртки, у меня нет понятия что не так с ней, для меня она выглядит впорядке

Не сказать что что-то поменялось. Все еще нет контрастного аутлайна, очень плоский подбор цветов у линз. Расовые спрайты.

2024-10-14 01:05 UTC, dj-34 requested changes
+ Хочу упомянуть, что ты решил избавиться от спрайта обжекта заменив его просто на мелкий. Это не лучшее решение, если ты хочешь так, то советую увеличить сам спрайт и дорисовать детали. Не сложно.

2024-10-14 01:05 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	heat_protection = UPPER_TORSO|LOWER_TORSO|ARMS
```suggestion
	body_parts_covered = UPPER_TORSO | LOWER_TORSO | ARMS
	cold_protection = UPPER_TORSO | LOWER_TORSO | ARMS
	heat_protection = UPPER_TORSO | LOWER_TORSO | ARMS
```

2024-10-14 01:05 UTC, dj-34 commented on modular_ss220/clothing/code/helmet.dm
> +	armor = list(MELEE = 35, BULLET = 20, LASER = 10, ENERGY = 15, BOMB = 1, RAD = 0, FIRE = 50, ACID = 50)
Хитрый жук, везде по-маленьку подкрутил и ничего не сказал. 35 мили (+10) это по мне так дохуя.

2024-10-14 17:11 UTC, dj-34 commented on modular_ss220/clothing/code/helmet.dm
> +	item_state = "cop1"
> Я хотел, но так и не разобрался как это сделать

Посмотри как сделан фонарик

2024-10-14 17:12 UTC, dj-34 commented on modular_ss220/clothing/code/helmet.dm
> +	species_restricted = list("Human", "Skrell", "Slime People", "Skeleton", "Shadow", "Nucleation")
Стоит сделать расовые спрайты, через тулзу Пупса прокинь файлы, думаю займет не много, если разобраться

2024-10-14 17:27 UTC, dj-34 commented on modular_ss220/clothing/code/helmet.dm
> +	species_restricted = list("Human", "Skrell", "Slime People", "Skeleton", "Shadow", "Nucleation")
> попробовал, ничего не понял и делаю в асепрайт

@PhantornRU ебало?

2024-10-16 16:59 UTC, dj-34 commented
Не забывай что еще есть вульпы/таяры, драски и киданы

2024-10-17 00:39 UTC, dj-34 commented
Это конечно замечательно, но в этих 3x3 пикселя ничего не понятно, лучше приложи скрины из игры.
Еще не забудь про сам suit.

2024-10-20 10:02 UTC, dj-34 commented
Goofy ah
![image](https://github.com/user-attachments/assets/49b3233e-b87c-4d47-84a8-4f936e01fd2a)

2024-10-20 10:11 UTC, dj-34 requested changes
Спрайты конечно не вау, но думаю минималки пойдет.
Касательно объекта, спрайт требуется увеличить, хотя бы немного.

![image](https://github.com/user-attachments/assets/8e8aed59-f91f-4648-9670-2cbb90ca9fcc)

2024-10-20 10:11 UTC, dj-34 commented on modular_ss220/clothing/code/helmet.dm
> +	actions_types = list(/datum/action/item_action/toggle_helmet_light)
```suggestion
	actions_types = list(/datum/action/item_action/toggle_helmet_light)
	var/on = FALSE
	var/brightness_on = 2
```

2024-10-20 10:11 UTC, dj-34 commented on modular_ss220/clothing/code/helmet.dm
> +		visible_message("<span class='danger'>[src]'s light fades and turns off.</span>")
Спаны в макросы (span_danger, или как там его)

2024-10-20 10:11 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +		)
sprite_sheets нужно обновить

2024-10-20 10:11 UTC, dj-34 commented on modular_ss220/clothing/code/helmet.dm
> +	)
Насколько я знаю, из-за хардкода нужно вставить полный список рас. Примеры в наших модулях в modular_ss220

2024-10-24 18:23 UTC, dj-34 commented
> > Спрайты конечно не вау, но думаю минималки пойдет. Касательно объекта, спрайт требуется увеличить, хотя бы немного.
> > ![image](https://private-user-images.githubusercontent.com/20109643/378176518-8e8aed59-f91f-4648-9670-2cbb90ca9fcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Mzc2NDIsIm5iZiI6MTcyOTQzNzM0MiwicGF0aCI6Ii8yMDEwOTY0My8zNzgxNzY1MTgtOGU4YWVkNTktZjkxZi00NjQ4LTk2NzAtMmNiYjkwY2E5ZmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE1MTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NWFkNmEyODAwZmE2M2Q5NTY4MzE2NTI3ZTE5YWYzODJjOTU3NzAzOGE3NjRjN2E3MmY4NjMwZWNjYzU2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f9xJgZYjLp36ZzgC6L8H_3Zecv8XaOO1N02xChymBYc)
> 
> у меня нет идей как увеличить спрайт

Буквально растянуть немного спрайт и добавить детали в спрайте

2024-10-25 04:13 UTC, dj-34 commented
> > > > Спрайты конечно не вау, но думаю минималки пойдет. Касательно объекта, спрайт требуется увеличить, хотя бы немного.
> > > > ![image](https://private-user-images.githubusercontent.com/20109643/378176518-8e8aed59-f91f-4648-9670-2cbb90ca9fcc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk0Mzc2NDIsIm5iZiI6MTcyOTQzNzM0MiwicGF0aCI6Ii8yMDEwOTY0My8zNzgxNzY1MTgtOGU4YWVkNTktZjkxZi00NjQ4LTk2NzAtMmNiYjkwY2E5ZmNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIwVDE1MTU0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NWFkNmEyODAwZmE2M2Q5NTY4MzE2NTI3ZTE5YWYzODJjOTU3NzAzOGE3NjRjN2E3MmY4NjMwZWNjYzU2YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f9xJgZYjLp36ZzgC6L8H_3Zecv8XaOO1N02xChymBYc)
> > > 
> > > 
> > > у меня нет идей как увеличить спрайт
> > 
> > 
> > Буквально растянуть немного спрайт и добавить детали в спрайте
> 
> Я уже пробовал это, получилось не очень хорошо

Стоит попытаться и приложить скрины того что вышло. Спрайт очень мизерный и халтурный для объекта

2024-10-26 23:44 UTC, dj-34 commented
> ![fucking_sprites](https://private-user-images.githubusercontent.com/174347315/380279203-6b5297eb-3a57-4618-9a88-8fe844509cb7.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk5ODY1NDQsIm5iZiI6MTcyOTk4NjI0NCwicGF0aCI6Ii8xNzQzNDczMTUvMzgwMjc5MjAzLTZiNTI5N2ViLTNhNTctNDYxOC05YTg4LThmZTg0NDUwOWNiNy5QTkc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNlQyMzQ0MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZDEwYTVlM2U3ZTYzZDdmZmQ0Y2YyNDQxMDFkOGQ3MjliZjZmMTRmY2U1MmFkMjUyNWEwZTRiZjg3Y2EzZGFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.H-rixQEXwNj_3zx53r8KJ-ssIj0ZN64VGwx1OMxYHus)

2 варик норм, остальное хз что это вообще

2024-10-30 01:23 UTC, SadestMage commented
я так то права слова тут не имею, но - почему рот в... этом? Спереди фильтры противогаза белые, сбоку они настолько серые и неконтрастные, что обойтись можно было и без них. Им бы чуууууть чуть аутлайна

2024-10-30 04:25 UTC, dj-34 commented
> я так то права слова тут не имею, но - почему рот в... этом? Спереди фильтры противогаза белые, сбоку они настолько серые и неконтрастные, что обойтись можно было и без них. Им бы чуууууть чуть аутлайна

Да, есть такая проблема

2024-11-05 16:51 UTC, dj-34 commented
какой-то клюв получается

![image](https://github.com/user-attachments/assets/c85545cc-0132-41aa-8b63-28a44331651f)

2024-11-05 17:02 UTC, dj-34 commented
> > какой-то клюв получается
> > ![image](https://private-user-images.githubusercontent.com/20109643/383239264-c85545cc-0132-41aa-8b63-28a44331651f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjU3NjcsIm5iZiI6MTczMDgyNTQ2NywicGF0aCI6Ii8yMDEwOTY0My8zODMyMzkyNjQtYzg1NTQ1Y2MtMDEzMi00MWFhLThiNjMtMjhhNDQzMzE2NTFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDE2NTEwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NTAxN2I3MWMyNDAyODNkOGEwNDljOWE3NzQ0ZGU3NTE3ZDE3ODQ3MzVhN2NkN2IxNWY5M2U4MGNmMDQzOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.9Q2MGNu4lPwxEixNtKEjdr9Svk5I6xu0uLs3oMiWUhQ)
> 
> вполне себе нормальный клюв

Ну я посоветовался с людьми, написали что это 👄 - я солидарен, мне кажется должно быть как-то так (без смещения глаз на противогазе, раз уж у нас глаза у кукл как у рыбы). А вообще тебе бы по хорошему получить где-нибудь фидбек
![image](https://github.com/user-attachments/assets/015567c1-b0ed-4034-8c93-ea6a0fff34c9)

![image](https://github.com/user-attachments/assets/4dc0bf92-93f3-4aec-86a2-3d79c847fc93)

2024-11-07 03:22 UTC, dj-34 commented
> @m-dzianishchyts @PhantornRU @dj-34 рецензенты, проверяйте

что проверять? изменений нет

2024-11-08 10:10 UTC, dj-34 commented
> > > @m-dzianishchyts @PhantornRU @dj-34 рецензенты, проверяйте
> > 
> > 
> > что проверять? изменений нет другие говорят обратное
> 
> В любом случае пора бы и одобрять, пр уже месяц лежит

апрув будет после правки спрайта маски

2024-11-09 15:12 UTC, dj-34 commented
> ![2dludi](https://private-user-images.githubusercontent.com/174347315/384494825-e96d7263-77c3-49cf-b059-339fea1ae13d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjUzNzUsIm5iZiI6MTczMTE2NTA3NSwicGF0aCI6Ii8xNzQzNDczMTUvMzg0NDk0ODI1LWU5NmQ3MjYzLTc3YzMtNDljZi1iMDU5LTMzOWZlYTFhZTEzZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTExMTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjIwMGZhYjcwM2MzNzNlNjMwMWNkMmEwNzE3ZTk4NGY1YmQ1NWMyOTU5NGQ1NDgzNDhiMGE3OTI3ZWEwNDZmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-qEvywWZVM9IIAH2alQFkvkX-XD1B76j0Kgw803qb9g)

претензия больше была к клюву, нежели к линзам.
ты бы не рисовал сразу расы до апрува, сначала на человечка

2024-11-18 10:41 UTC, PhantornRU approved these changes
Спрайты интересные в любом случае

2024-12-08 05:39 UTC, dj-34 approved these changes
Нейм в английский переделай, на шлем похуй крч (но можно посмотреть кстати на билдах хл2 получше спрайтик. здесь например https://github.com/HL2RP-City-13/HL2RP-City-13
Но смотреть опять же на лицензию

2025-01-15 15:16 UTC, merged