Vox shoes&gloves loadout
ss220club/Paradise-SS220 pull request #1597
Opened 2024-10-14 16:52 UTC by PhantornRU

## Что этот PR делает

Добавляем сандали и легкие рукавицы воксов в лодаут.
Добавляем воксовые изольки в тулвендор.

## Почему это хорошо для игры

Больше расовой косметики.

## Изображения изменений

![image](https://github.com/user-attachments/assets/471fc1e8-a580-4d69-8504-b372e6a3ab9b)

![image](https://github.com/user-attachments/assets/28748006-d1d2-48a8-bf3f-30094eac52c1)

## Тестирование

Да

## Changelog

:cl:
add: В расовый лодаут добавлены воксовые рукавички и сандалии
add: В инженерный вендор добавлены изоляционные рукавицы выксов - 1 штука
/:cl:

2024-10-14 17:00 UTC, dj-34 commented
фрик
![image](https://github.com/user-attachments/assets/e9690244-405a-4461-a9d4-8d4ece1b2780)

2024-10-14 17:07 UTC, dj-34 requested changes

2024-10-14 17:07 UTC, dj-34 commented on modular_ss220/loadout/code/racial.dm
> +// ================
```suggestion
```

2024-10-14 17:07 UTC, dj-34 commented on modular_ss220/vending/code/vending.dm
> +
```suggestion
```

2024-10-14 17:07 UTC, dj-34 commented on modular_ss220/vending/code/vending.dm
> +			/obj/item/clothing/gloves/color/yellow/vox = 1
Разве обычные изоляционные перчатки не надеваются на воксов?

2024-10-14 17:07 UTC, dj-34 commented on modular_ss220/loadout/code/racial.dm
> +//		vox jumpsuits
```suggestion
```

2024-10-14 17:07 UTC, dj-34 commented on modular_ss220/loadout/code/racial.dm
> +/datum/gear/racial/vox_sandal
```suggestion
// MARK: Vox

/datum/gear/racial/vox_sandal
```

2024-10-14 17:07 UTC, dj-34 commented on modular_ss220/loadout/code/racial.dm
> +	display_name = "vox gauntlets"
Везде прокинь первую букву с заглавной, чтобы было как с остальными
```suggestion
	display_name = "Vox gauntlets"
```
![image](https://github.com/user-attachments/assets/f93cf4b8-45d3-4025-99ed-79af1ac58cc5)

2024-10-14 17:08 UTC, dj-34 commented
Чет они неорганично здесь смотрятся..
![image](https://github.com/user-attachments/assets/1f37eeeb-66df-4f7f-9502-046eb9e900de)

2024-10-15 00:35 UTC, PhantornRU commented on modular_ss220/vending/code/vending.dm
> +			/obj/item/clothing/gloves/color/yellow/vox = 1
надеваются, только они бесплатны для всех, а воксовские - нет. Кстати подумал. А их ведь можно в контрабанду запихнуть.

2024-10-15 00:57 UTC, PhantornRU commented
@dj-34 запихал перчатки в контрабанду. + добавил бесплатные вендоры

2024-10-15 13:10 UTC, PhantornRU commented on modular_ss220/vending/code/vending.dm
> +	prices |= list(/obj/item/clothing/gloves/color/yellow/vox = 250)
```suggestion
	prices |= list(/obj/item/clothing/gloves/color/yellow/vox = 500)
```

2024-10-15 13:11 UTC, dj-34 approved these changes

2024-10-15 19:05 UTC, merged