Add more shelves on maps
ss220club/Paradise-SS220 pull request #1599
Opened 2024-10-18 06:00 UTC by AyIong

## Что этот PR делает
Насрал полками на всех картах (Пока на коробке онли)
Подвигал предметы на столах и раках
Возможно ещё что-то сделаю, потом напишу если сделаю

## Почему это хорошо для игры
Красива, удобна

## Изображения изменений
Потом

## Тестирование
В процессе

## Changelog

:cl:
add: На всех картах были раскиданы полки. В большинстве случаев заменены столы/раки на них. Плюс наведён порядок на столах/раках
tweak: В техах на всех картах теперь спавнятся случайные полки, плюс немного изменён лут в техах
/:cl:

2024-10-20 08:04 UTC, dj-34 requested changes
А умно это ты придумал, насрать так, чтобы это было впадлу ревьювить. Думал поленюсь, а вот и нет.
Кстати спасибо за добавление с десяток уязвимостей и дополнительных предметов, которых не было на картах.

Ты бушь заниматься этим?

![image](https://github.com/user-attachments/assets/53cc60e2-e530-4e70-9300-8a484d8f73c9)

<details>
<summary>РЕВЬЮ</summary>

1. Разве не логично размещение полок впритык к стене, чтобы стояли возле столов, ну и шоб не спотыкались о них.

![image](https://github.com/user-attachments/assets/59c7e941-5736-4859-8882-f98d4b9cefb1)

2. Что это за вид извращения такой, разделять столы полками. Ты в ИРЛ тоже столы берешь помельче и заставляешь их впритык к шкафам, вместо того чтобы взять 1 длинный стол и поставить возле шкафа.

![image](https://github.com/user-attachments/assets/4a56aaba-9968-41da-a9c0-20969bf5ef45)

3. Ну вот чем было обосновано убирать второй рак в Еве. Красиво-симметрично же стояло!

![image](https://github.com/user-attachments/assets/cf684d12-4c0d-4efd-9b5d-b16392fb24db)

4. Проклинаю тебя. Надеюсь это сделают и другие повара, которых ты заставил играть в ебучего поварёнка.

![image](https://github.com/user-attachments/assets/32907547-bc1a-4d50-a98f-1911f56ccdf8)

5. Ну для ЧЕГО РАЗБИВАТЬ РЯДЫ? Это бред блять!

![image](https://github.com/user-attachments/assets/7e8d5835-79c3-492d-a562-329976b4ed18)

6. Последняя полка возле стены как по мне не вписывается.

![image](https://github.com/user-attachments/assets/9877ada1-f0dd-4236-ae89-74cfaa08acd9)

7. Ну вот о чём я и говорил, появление новых предметов которых не было. Дай бог найти ПДА с аплинком в техах на полке.

![image](https://github.com/user-attachments/assets/83b3e89b-5016-41e6-bcb6-cd8fda19a4d1)

8. У вас маска валяется на полу

![image](https://github.com/user-attachments/assets/90daf9d7-ff29-4012-aae7-35dcb0029212)

9. Ещё одно изменение не описанное нигде.

![image](https://github.com/user-attachments/assets/cb0d6bc7-a7e3-4f19-8081-719754f424ba)

10. Мне бы в жизни (и в игре) было проще взять что-то со стола чем ковыряться в 4 полках РАЗНОГО ВИДА в комнате 20 м²!!!!!!! Ну было же хорошо со столами, там нужно было просто чуть подвинуть вещи!

![image](https://github.com/user-attachments/assets/735eaef0-0300-4e98-b3f7-0a74d82c2804)

11. Зачем в комнате хранения улик вообще когда-либо нужна будет полка, когда у тебя стоит более удобный стол снизу. Там и так быстро доступных шкафов две штуки, а теперь так вовсе одна.

![image](https://github.com/user-attachments/assets/80d75dc6-9650-4242-b71b-e7cc38ec10cc)

12. А нам точно нужно было добавлять полку на 3 разных предмета, которые спокойно можно разместить в рамках стола?

![image](https://github.com/user-attachments/assets/d182c40a-2f4d-46e9-9a94-a32d76573f31)

13. Каков шанс что здесь появились лишние платы, которых не было? Я думаю 99%

![image](https://github.com/user-attachments/assets/81ae2db1-8667-461c-b925-09981bdb4b87)

14. Флешки, аптечки... Это что за бафф такой?

![image](https://github.com/user-attachments/assets/17ad8c01-a338-4d0e-8aa0-f24988a83be3)

15. Ну просто сука маньяк, оборвать такой красивый разделитель в виде стола.

![image](https://github.com/user-attachments/assets/f46479d3-979e-4dc2-a337-7a8c7589aa7e)

16. Спасибо тебе бать за вонючую мусорку в церкви, это же так праведно. Мои любимые благовония не отходя от кассы.

![image](https://github.com/user-attachments/assets/aa8262ed-cee0-4ddd-8814-739c71555a45)

17. Здесь тоже самое. Что за извращение портить вид, ставя вкуснейшую мусорку прямо возле скамеек. Тебе бы в мэры города.

![image](https://github.com/user-attachments/assets/a3f0b1c1-a3db-4319-92dd-1757c6df55d5)

18. Ебать насрал контрабандой.

![image](https://github.com/user-attachments/assets/ab301780-08e8-4f62-ac62-c222f10e0c7d)

19. Ну хорошо, допустим нижние полки можно понять (хотя это нихера не удобно для проходимости), но вот это-то что за отщепенец?

![image](https://github.com/user-attachments/assets/91753a08-ab1d-4b09-9afa-e60f683f461e)

20. У вас кнопка ща упадёт со стола.

![image](https://github.com/user-attachments/assets/43c81fab-cccc-49f2-8f0e-454094301494)

21. Зачем Капитану еще один телевизор в каюте и для чего нужно было перемещать полотенца на пол в ванную комнату.

![image](https://github.com/user-attachments/assets/e980a653-b35f-4811-bd85-d01b21aff25e)

</details>

2024-10-20 08:39 UTC, AyIong commented on modular_ss220/maps220/code/mobs.dm
> +	loot = list(/obj/effect/spawner/random/maintenance = 1)
> почему поменял two и three?

Потому что они не работали и не использовались на картах после обновления тех. лута

2024-10-20 08:40 UTC, AyIong commented on code/_globalvars/lists/maint_loot_tables.dm
> +		/obj/item/melee/stylet, // SS220 ADDITION
Шансами и кривизной

2024-10-20 08:41 UTC, AyIong commented on modular_ss220/objects/code/closets.dm
> +		new /obj/item/storage/fancy/egg_box(src)
> ???

Чё? Донки со стола в ящик +1 сверху
Яйца с холодоса который удалён в угоду полкам

2024-10-20 20:55 UTC, AyIong commented on modular_ss220/objects/code/closets.dm
> +		new /obj/item/storage/fancy/egg_box(src)
А так в случае чего придётся добавлять строчку вместо изменения двойки

2024-10-20 20:57 UTC, AyIong commented on modular_ss220/maps220/code/mobs.dm
Пока да, если никто не хочет создать отдельный спавнер для мобов

2024-10-20 20:58 UTC, AyIong commented on code/_globalvars/lists/maint_loot_tables.dm
> +		/obj/item/melee/stylet, // SS220 ADDITION
> Оно реально кривое, но лучше доложить модульно с маленьким весом

Модульно тут максимально нечитабельно из-за того как это сделано

2024-10-20 21:21 UTC, AyIong commented
> А умно это ты придумал, насрать так, чтобы это было впадлу ревьювить. Думал поленюсь, а вот и нет. Кстати спасибо за добавление с десяток уязвимостей и дополнительных предметов, которых не было на картах.
> 
> РЕВЬЮ

1-2 - принято
3 - в рот я ебал симметрию когда всё в одной куче
4 - надеюсь ТЫ лично будешь запихивать всё это говно в ящик, и через ПКМ искать как раньше
5 - симметрия, полки по центру и витрины по бокам. Если челу нп онравится, он может переставить IC когда будет делать магазин
6 - может быть, есть идеи что туда воткнуть вместо пустоты? Только не цветочек
7 - даже дифф бот показывает что оно было, только всё в одном пикселе на столе
![image](https://github.com/user-attachments/assets/4a2dd745-9781-4573-850f-1d3e792cec06)

9 - всё что было в одном ящике, раскидано по двум полкам
10 - где ты там 4 полки разного вида увидел? 1 полка с мишенями и 2 полки с одинаковым содержимым которое было в куче
11 - ты заебал со своими столами, ну не удобно на столе хранить более трёх-четырёх вещей, в шкафу так вообще пиздец так как даже подвигать нельзя переставляя пол века
12 - там 5 предметов, я просто не пиксель-шифтил их. Но да, надо изменить содержимое
13 - высказался в дискорде, тут за такое могут забанить
14 - в этой куче вот тут это всё валяется, хотя как ты это увидишь не нажав ПКМ в редакторе или в игре. Справедливости ради, 1-2 штуки сверху накинул, имхо, на дельте должно быть чуть больше раундстарт говна в отделах чем на коробке
![image](https://github.com/user-attachments/assets/7de2fb01-af2c-4f24-9845-f26f36a2f377)

15 - без комментариев
16 - пожалуйста
17 - пон, мусорки в отдалённых частях карты - харам, по 1 мусорке в зоне, и ещё в труднодоступном месте, шоб все выбрасивали мусор на пол или таскали с собой
18 - где ты там блять контрабанду увидел? Обычный тех. лут спавнер в пустую комнату, чтоб хоть что-то было
19 - тебе для проходимости нужна огромная пустая комната? И полка для лута
20 - не упадёт
21 - телевизор там и был, просто передвинул

Доп. вопрос - да

2024-10-21 13:25 UTC, dj-34 commented
@AyIong 

3. Так где там все в одной куче? Размести магбутсы на полках, предметы одного типа (джетпаки) размести на раках как было. Тебе там ПКМить не нужно, заодно и симметрию вернешь.

5. Я в глаза долблюсь? Где там симметрия? Если ты соединишь стол и витрины, у тебя будет тоже самое, только в полноценный ряд.

6. Там ничего втыкать не нужно. Оно будет смотреться гармонично и с пустым пространством. На край туда можно впихнуть флаг карго, или мусорку.

10. Рак, полка, стойка для оружия и стол. У тебя все возможные вариации хранения предметов схлестнулись в таком малюсеньком помещении, только шкафа не хватает.

11. Зачем в комнате улик наличие полки, на которой никогда в жизни ничего не будут хранить? Эта комната нужна для одной задачи - зайти и положить в шкаф улику. Ты променял 1 быстро доступный шкаф на полку, которая там не нужна.

15. А стоило бы прокомментировать, потому что это тотальное унижение красоты.

17. У тебя есть мусорка в левой верхней части этого же помещения.

18. Тебе стоит посмотреть сколько лута в этих техах, это наверное самые богатые техи на карте.

19. Это может показаться что места много, на деле нихуя - ты забираешь 2 тайла в самой "горячей зоне". У тебя будет вся комната в ящиках, рычаги находятся как раз возле труднопроходимой зоны, особенно если включить конвейерную ленту.

20. В чем проблема ее нормально поставить а не так ублюдочно?

2024-10-21 19:28 UTC, AyIong commented
Иди ты нахуй короче, нихуя обьективного, одна вкусовая осталась и ебёт

2024-10-21 21:13 UTC, AyIong commented
> @AyIong

3. Тогда будет +- тоже самое, 4 там и 4 там, а так полка забита и 2 лишник джета на раке
4. Это вообще к чему?
5. Ладно
6. Всё выполняет свою функцию, оружейки для оружия, полки для вещей, столы для того что не влезает на полки или будет там лишним, рак для тренировочной бомбы
7. Откуда такая уверенность что не будут использовать? Если будут жаловаться, можно вернуть
8. Я не прокоментировал потому что убрал, ибо это миссклик, очевидно?
9. Я лично не хотел бы пиздовать в другой край помещения чтобы выкинуть мусор или клоуна
10. Какие именно? Ты не по порядку отвечаешь :xylipizdish:
11. C чего ты взял что эта стена самая проходная зона?
12. Да о чём ты блять? 12 пункт вообще про РнД

2024-10-21 21:30 UTC, dj-34 commented
@AyIong 

Короче я уже сам запутался в своих пунктах. про "В чем проблема ее нормально поставить а не так ублюдочно?" - было про кнопку у магистрата, про ряд продлить было в свободном магазине, про лут - на ринге, там во всех этих техах очень много лута.

По поводу двух полок карго - просто создал у себя хитмапу в голове примерного передвижения, как бы ходил я и как бы ходили другие. Там место такое, что ходить нужно много, на войне людей много, ящиком много и как раз это место заполняется всем подряд сильнее всего из-за наличия конвеерной ленты рядом.

По поводу 4 раков, дело твоё, но можно было сделать практичнее и более единообразно для такой небольшой комнаты. Могу потом показать.

Если всё, то я предварительно тыкаю галку и на этом всё.

2024-10-21 21:30 UTC, dj-34 approved these changes

2024-10-22 10:37 UTC, merged