Kekega
ss220club/Paradise-SS220 pull request #162
Opened 2023-09-08 19:03 UTC by Kar4es

## Что этот PR делает
Изменен инженерный отдел Дельты, добавлена новая зона.

- Немного переделана комната СМа, добавлены недостающие элементы для быстрого запуска двигателя. Немного переделан контур охлаждения, убран лишний аир алярм.
- В Атмосе убран ненужный охладитель, добавлены дополнительные риги и шкафчики, добавлено пара пустых канистр. Сделана новая зона для комнаты контроля атмосов.
- Изменено Фойе инженерного отдела, добавлен корпус машины и запчасти для автолата.
- В каюте СЕ добавлен монитор СМа, плата автолата, в шкаф СЕ добавлен БРПД.
- В инженерке немного изменена проводка двигателя, добавлены шкафы, рации и твердая плазма. На защищенный склад добавлено немного металла, риги стоят ближе друг к другу. Инженерный склад ВКД был расширен, добавлены инструменты, джетпаки и т.д. 
- На места доставки для МУЛов добавлено усиленное стекло с стеклянным шлюзом.

## Почему это хорошо для игры

Хорошая инженерка это всегда хорошо
## Изображения изменений

![2023-09-09 01 39 48](https://github.com/ss220club/Paradise-SS220/assets/144079671/32c7104c-2db0-4268-89f5-142dc0492643)
![2023-09-09 01 40 13](https://github.com/ss220club/Paradise-SS220/assets/144079671/d477b91c-9a8e-4772-bc55-b3312fc90e31)
![2023-09-09 01 52 38](https://github.com/ss220club/Paradise-SS220/assets/144079671/6e349005-efc1-410a-98e8-5b727d346828)
![2023-09-09 01 52 49](https://github.com/ss220club/Paradise-SS220/assets/144079671/e92bb2de-c759-4c4a-a99c-920ee14682aa)

## Тестирование

Запускал двигатели, нажимал кнопочки
## Changelog

:cl:
tweak: На Дельте немного доделан инженерный отдел.
/:cl:

2023-09-10 10:08 UTC, Aylong220 requested changes
Не мало рефлекторов?
Плюс к ним бы подвести венту с скраббером
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/f8949d76-1982-4e36-9245-61ba607b2646)

У тебя ещё провода на венте с скраббером
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/74537d89-9334-4bef-9ba3-e78efde7a5c5)

Нет венты со скраббером.
Я бы переместил монитор в комнатку правее, и добавил бы ещё пару ящиков с костюмом от радиации сюда.
Как на дельте рупары.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/c0e1a9f4-fdab-4c73-abe6-691d98a7d18e)

Немного бы расширить комнатку и поставить компутер для мониторинга СМа - /obj/machinery/computer/sm_monitor.
Я про это выше писал.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/705ea3de-3927-45a1-b7da-a87ab354056a)

Может добавишь сюда больше грязи?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/8e5424d0-36da-4c93-b2d4-d836b9729780)

2023-09-11 19:43 UTC, Aylong220 requested changes
Подвинь венты правее
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/427b9771-69be-414c-b581-0077cb9f8d43)
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/d66866ce-1073-4d04-bfcb-c4584b190694)

Верни стандартный слой
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/e5734f2d-d3b5-4781-a371-5dca68ad7723)

Ну и вроде всё, больше ничего такого не заметил.
Если готово - открывай ПР

2023-09-11 19:46 UTC, Aylong220 requested changes
Хотя нет, заметил
Нет иконки у зоны и название у неё хреновое да ещё и с ошибкой
Переименуй в AI Satellite Transfer Point
Как и путь с aienter в aitransit
![Uploading image.png…]()

2023-09-12 00:29 UTC, Aylong220 approved these changes
Для первого раза вполне

2023-09-12 01:54 UTC, Furrior approved these changes

2023-09-12 01:54 UTC, merged