Delta basic overhaul
ss220club/Paradise-SS220 pull request #1620
Opened 2024-10-27 20:10 UTC by dj-34

## Что этот PR делает
- Исправлены некоторые ошибки, недочеты.
- Визуальный импрувмент (по большей части того что меня бесило, такие дела).
- Все что возможно было сделать хелпером - сделано теперь хелпером (экстернал и locked аирлоки).
- Местами была переложена машинерия, незначительные перестановки в комнатах.

## Почему это хорошо для игры
Посмотрим

## Изображения изменений
MDB

## Тестирование
Проверил все экстерналы в игре, глянул изменения визуала на локалке.

## Changelog

:cl:
tweak: Дельта: Были проведены общие визуальные улучшения, незначительные перестановки и исправления недочетов.
/:cl:

2024-11-05 02:45 UTC, dj-34 commented
вроде готово

2024-11-09 15:59 UTC, AyIong requested changes
Пара мелочей, больше ничего не обнаружил
Я немного не доверяю external хелперам, но ладно

<details><summary> Как-то так </summary>

Миссклики?
![image](https://github.com/user-attachments/assets/512ebdc9-8c6e-4eb5-b054-e18c874482b7)

Над верхними шлюзами убрать бы эти линии, для симметрии, да и выглядят они не очень
![image](https://github.com/user-attachments/assets/91c74de3-68fa-4c2d-af23-82c7a794b2ae)

Тут тоже самое
![image](https://github.com/user-attachments/assets/9329c663-6674-4a82-94d9-b5713862a224)

Вообще, не понимаю зачем ты этими линиями насрал
![image](https://github.com/user-attachments/assets/6bf8a341-0a0c-4cb6-b2ce-2f33ac37b4ef)

В вирусологии полы с несуществующим стейтом
![image](https://github.com/user-attachments/assets/bfbdf0ab-361e-4c09-a2a7-02f25343aa58)

И тут
![image](https://github.com/user-attachments/assets/4fc2fcde-ee85-43ce-a524-012635122a51)

Вот тут тоже
![image](https://github.com/user-attachments/assets/f230dd11-2731-45bb-a3fa-9691515f0a25)

2024-11-09 18:00 UTC, dj-34 commented
@AyIong 

Я проверял все экстернал аирлоки. Касаемо полосок у эвак подов, то я просто подогнал все под единый стиль, так как у одних были полоски, у других нет.

2024-11-09 21:09 UTC, AyIong approved these changes

2024-11-09 21:09 UTC, merged