Robotics translation
ss220club/Paradise-SS220 pull request #1628
Opened 2024-10-30 16:25 UTC by don-pardon42

## Что этот PR делает

Переводит описания экзокостюмов, их модули и вооружение, описание фабрикатора, описание консоли и станции для зарядки мехов.

## Почему это хорошо для игры

Робототехникам будет проще собирать мехов , а так же понимать какой модуль что делает.

## Тестирование

Проверил на локальном сервере, всё работает.

## Changelog

:cl: don_pardon
add: Добавлен перевод описаний мехов и их модулей.
/:cl:

2024-11-01 16:30 UTC, larentoun commented on code/game/mecha/equipment/tools/janitor_tools.dm
> +		chassis.occupant.visible_message("<span class='warning'>[chassis.declent_ru(NOMINATIVE)] начинает мыть [target_turf] с помощью [declent_ru(INSTRUMENTAL)].</span>", "<span class='warning'>Вы начинае
Если деклен в начале предложения - используй capitalize()
```suggestion
		chassis.occupant.visible_message("<span class='warning'>[capitalize(chassis.declent_ru(NOMINATIVE))] начинает мыть [target_turf] с помощью [declent_ru(INSTRUMENTAL)].</span>", "<span class='warning'>Вы начинаете мыть [target_turf] с помощью [declent_ru(INSTRUMENTAL)].</span>")
```

2024-11-01 16:31 UTC, larentoun commented on code/game/mecha/equipment/tools/janitor_tools.dm
> +		chassis.occupant.visible_message("<span class='warning'>[chassis.declent_ru(NOMINATIVE)] начинает мыть [target_turf] с помощью [declent_ru(INSTRUMENTAL)].</span>", "<span class='warning'>Вы начинае
Также, /turf наследуется от /atom - надо добавить деклент

2024-11-01 16:32 UTC, larentoun commented on code/game/mecha/equipment/tools/mecha_mining_tools.dm
> +	target.visible_message("<span class='warning'>[chassis] начинает бурить [target].</span>",
декленты

2024-11-01 16:32 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		occupant_message("<span class='alert'>Информация о реактивах [A] не получена.</span>")
декленты

2024-11-01 16:32 UTC, larentoun commented on code/game/mecha/equipment/tools/other_tools.dm
> +			log_message("declent_ru(NOMINATIVE)] активирован.")
Логи не переводи - это админская информация, разберутся

2024-11-01 16:34 UTC, larentoun commented on code/game/mecha/equipment/weapons/weapons.dm
> +		R.occupant_message("\The [R] защитил вас от ХОНК [chassis] ценой части энергии.")
Макросы-хелперы для артиклей нужно будет удалить,а именно - \the, \a и \an

2024-11-01 16:35 UTC, larentoun commented on code/game/mecha/working/ripley.dm
> +			occupant_message("<span class='notice'>Вы выгрузили [O].</span>")
деклент

2024-11-03 19:36 UTC, larentoun requested changes
поверхностно пробежался

2024-11-03 19:36 UTC, larentoun commented on code/game/mecha/equipment/mecha_equipment.dm
> +		chassis.log_message("[src] initialized.")
деклент и капиталайз

2024-11-03 19:36 UTC, larentoun commented on code/game/mecha/equipment/tools/janitor_tools.dm
> +		chassis.occupant.visible_message("<span class='warning'>[capitalize(chassis.declent_ru(NOMINATIVE))] начинает мыть [target_turf.declent_ru(GENITIVE)] с помощью [declent_ru(GENITIVE)].</span>", "<sp
мыть (что?) винительный

2024-11-03 19:36 UTC, larentoun commented on code/game/mecha/equipment/tools/janitor_tools.dm
> +			"<span class='notice'>[chassis.occupant] опустошает [declent_ru(ACCUSATIVE)] в мусорку.</span>",
деклент и капиталайз на оккупанта

2024-11-03 19:36 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	chassis.visible_message("<span class='warning'>[chassis.declent_ru(NOMINATIVE)] начинает помещать [target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)].</span>")
капитазай

2024-11-03 19:36 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		chassis.visible_message("<span class='warning'>[chassis.declent_ru(NOMINATIVE)] помещает [target.declent_ru(ACCUSATIVE)] в [declent_ru(ACCUSATIVE)].</span>")
капиталайз

2024-11-04 12:08 UTC, larentoun commented on code/game/mecha/equipment/mecha_equipment.dm
> +		chassis.log_message("[capitalize(declent_ru(NOMINATIVE))] removed from equipment.")
почему частичный перевод?

2024-11-04 12:10 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +			target.visible_message("<span class='notice'>[chassis.declent_ru(NOMINATIVE)] аккуратно тыкает [declent_ru(NOMINATIVE)] в нос. В последний момент гидравлика шипит и предохранители смягчают жёсткий
Почему я всё ещё вижу отстутствие capitalize().
Я оставляю ревью на паре вещей, чтобы ты повторно осмотрел весь свой ПР на похожие ошибки. Вижу сразу две. Дальше не смотрю.

2024-11-06 12:03 UTC, larentoun commented on code/game/mecha/mech_fabricator.dm
> +				L.desc = "Запертая коробка. Закрыта на [lockbox_access]доступ"
Опечатка и на оффах, судя по всему.
```suggestion
				L.desc = "Запертая коробка. Закрыта на [lockbox_access] доступ"
```

2024-11-06 12:13 UTC, don-pardon42 commented on code/game/mecha/mech_fabricator.dm
> +				L.desc = "Запертая коробка. Закрыта на [lockbox_access]доступ"
Так пробел нужен или нет?

2024-11-06 12:13 UTC, larentoun commented on code/game/mecha/equipment/mecha_equipment.dm
> +		chassis.log_message("[capitalize(declent_ru(NOMINATIVE))] снят с оборудования.")
снятие чего-то с оборудования, обходим пол

2024-11-06 12:13 UTC, larentoun commented on code/game/mecha/equipment/weapons/weapons.dm
> +		R.occupant_message("[R] защитил вас от ХОНК [chassis] ценой части энергии.")
декленты.

2024-11-06 12:21 UTC, don-pardon42 commented on code/game/mecha/janitor/nkarrdem.dm
> +			occupant_message("<span class='warning'>[H.glasses] мешают вам использовать встроенный уборочный HUD [declent_ru(GENITIVE)].</span>")
Деклент не работает с [H.glasses]. Выдаёт ошибку при компиляции

2024-11-15 19:48 UTC, larentoun requested changes

2024-11-15 19:48 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	occupant_message("Пациент [patient] был извлечён. Функции жизнеобеспечения отключены.")
patient.declent_ru()

2024-11-15 19:48 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		occupant_message("Введение [patient] [to_inject] юнитов [R.name].")
patient - деклент

2024-11-15 19:48 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		occupant_message("[declent_ru(NOMINATIVE)] деактивирован - нет питания.")
капиталайз?

2024-11-15 19:48 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +				mechsyringe.visible_message("<span class='attack'> [capitalize(M.declent_ru(ACCUSATIVE))] был поражён шприцем!</span>")
был поражен - мужской род. Поражается шприцом? Шприц попадает в что-то?

2024-11-15 19:48 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +			occupant_message("Обработка реактивов начата.")
реагентов

2024-11-15 19:48 UTC, larentoun commented on code/game/mecha/equipment/tools/other_tools.dm
> +		occupant_message("<span class='warning'>[capitalize(fuel_name)] на минимуме! [I.declent_ru(NOMINATIVE)] не может использоваться в качестве топлива.</span>")
капиталайза нет

2024-11-15 19:48 UTC, larentoun commented on code/game/mecha/equipment/tools/work_tools.dm
> +			occupant_message("<span class='warning'>[capitalize(target.declent_ru(NOMINATIVE))] надёжно зафиксирован!</span>")
мужской род опять же

2024-11-15 19:48 UTC, larentoun commented on code/game/mecha/equipment/tools/work_tools.dm
> +		occupant_message("<span class='notice'>[capitalize(target.declent_ru(NOMINATIVE))] успешно загружен.</span>")
мужской род. загружается.

2024-11-17 15:30 UTC, larentoun requested changes

2024-11-17 15:30 UTC, larentoun commented on code/game/mecha/equipment/weapons/weapons.dm
> +		R.occupant_message("[capitalize(R.declent_ru(NOMINATIVE))] защитил вас от ХОНК [chassis.declent_ru(GENITIVE)] ценой части энергии.")
мужской род, защищает

2024-11-17 15:30 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		occupant_message("<span class='warning'>Пациент [target.declent_ru(ACCUSATIVE)] не может быть помещён в слипер, потому что пристегнут к [target.buckled.declent_ru(NOMINATIVE)]!</span>")
пристегнут к чему, неправильно
да и пациент именительный тоже

2024-11-17 15:30 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +		occupant_message("<span class='warning'>Пациент [target.declent_ru(ACCUSATIVE)] не может быть помещён в слипер из-за существ, прикреплённых к нему!</span>")
деклент неправильный

2024-11-17 15:30 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	occupant_message("Пациент [patient.declent_ru(NOMINATIVE)] был извлечён. Функции жизнеобеспечения отключены.")
деклент неправильный

2024-11-17 15:30 UTC, larentoun commented on code/game/mecha/equipment/tools/medical_tools.dm
> +				mechsyringe.visible_message("<span class='attack'> [capitalize(M.declent_ru(ACCUSATIVE))] поражается шприцом!</span>") //
Шприц попадает по [предложный]

2024-11-18 04:01 UTC, don-pardon42 commented on code/game/mecha/equipment/tools/medical_tools.dm
> +				mechsyringe.visible_message("<span class='attack'> [capitalize(M.declent_ru(ACCUSATIVE))] поражается шприцом!</span>") //
"Попадает по" требует дательный падеж (кому? чему?).  Так что дательный

2024-11-18 04:08 UTC, don-pardon42 commented on code/game/mecha/equipment/tools/medical_tools.dm
> +	occupant_message("Пациент [patient.declent_ru(NOMINATIVE)] был извлечён. Функции жизнеобеспечения отключены.")
Пациент именительный тут.

2024-11-18 23:10 UTC, larentoun requested changes

2024-11-18 23:10 UTC, larentoun commented on code/game/mecha/equipment/weapons/weapons.dm
> +		R.occupant_message("[capitalize(R.declent_ru(NOMINATIVE))] защищает вас от ХОНК [chassis.declent_ru(GENITIVE)] ценой части энергии.")
```suggestion
		R.occupant_message("[capitalize(R.declent_ru(NOMINATIVE))] защищает вас от ХОНКа [chassis.declent_ru(GENITIVE)] ценой части энергии.")
```

2024-11-18 23:11 UTC, larentoun approved these changes
Я не проверял описания, только действия.

2024-11-23 12:24 UTC, merged