add_plushie
ss220club/Paradise-SS220 pull request #1630
Opened 2024-10-31 13:49 UTC by PiotrTheTchaikowsky

## Что этот PR делает

- Добаваляет механ фраз для плюшевых игрушек котика рисовара и разумиста.
- Нарисовал и добавил спрайты игрушек в руках для котика разумиста, рисовара 
## Почему это хорошо для игры
Наш самый  креативный и творческий коллектив спрайтеров СС220 хочет оставить на себя приятную отсылку в виде игрушки котика, что носит шляпу из соломы, доули, а также разумисткий конус.

Имеют такие же свойства как и любые другие плюшевые игрушки
Название первой игрушки "Rice cat", а второй "Razumist cat".

Таким образом мы оставим довольно таки забавные спрайты в игре и вместе с ними отсылку на работников рисового поля, что пилят для билда новые 
## Изображения изменений
![image](https://github.com/user-attachments/assets/dd30451f-7fdf-4ee0-91e2-f29ec31920a8)
![image](https://github.com/user-attachments/assets/6b8405b5-5086-42a9-a52b-aa96b1e65a3d)
![image](https://github.com/user-attachments/assets/8b0a0245-2b31-48d0-8914-561b7be43788)
## Тестирование
Зашёл Игру, заспавнил котиков, походил с ними, посмотрел спрайты в руках, объекта, описания, а также механ фраз при нажатии кнопки взаимодействия
## Changelog

:cl:
add: Добавлены игрушки кота в соломенной шляпе и котика в конусе
/:cl:

2024-10-31 13:53 UTC, PiotrTheTchaikowsky commented
⣿⣿⣿⣿⣿⣿⣿⠿⠿⢛⣋⣙⣋⣩⣭⣭⣭⣭⣍⣉⡛⠻⢿⣿⣿⣿⣿
⣿⣿⣿⠟⣋⣥⣴⣾⣿⣿⣿⡆⣿⣿⣿⣿⣿⣿⡿⠟⠛⠗⢦⡙⢿⣿⣿ 
⣿⡟⡡⠾⠛⠻⢿⣿⣿⣿⡿⠃⣿⡿⣿⠿⠛⠉⠠⠴⢶⡜⣦⡀⡈⢿⣿ 
⡿⢀⣰⡏⣼⠋⠁⢲⡌⢤⣠⣾⣷⡄⢄⠠⡶⣾⡀⠀⣸⡷⢸⡷⢹⠈⣿ 
⡇⢘⢿⣇⢻⣤⣠⡼⢃⣤⣾⣿⣿⣿⢌⣷⣅⡘⠻⠿⢛⣡⣿⠀⣾⢠⣿ 
⣷⠸⣮⣿⣷⣨⣥⣶⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⢁⡼⠃⣼⣿ 
⡟⠛⠛⠛⣿⠛⠛⢻⡟⠛⠛⢿⡟⠛⠛⡿⢻⡿⠛⡛⢻⣿⠛⡟⠛⠛⢿ 
⡇⢸⣿⠀⣿⠀⠛⢻⡇⠸⠃⢸⡇⠛⢛⡇⠘⠃⢼⣷⡀⠃⣰⡇⠸⠇⢸ 
⡇⢸⣿⠀⣿⠀⠛⢻⡇⢰⣿⣿⡇⠛⠛⣇⢸⣧⠈⣟⠃⣠⣿⡇⢰⣾⣿ 
⣿⣿⣿⠘⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢋⣿⠙⣷⢸⣷⠀⣿⣿⣿ 
⣿⣿⣿⡇⢻⣿⣿⣿⡿⠿⢿⣿⣿⣿⠟⠋⣡⡈⠻⣇⢹⣿⣿⢠⣿⣿⣿ 
⣿⣿⣿⣿⠘⣿⣿⣿⣿⣯⣽⣉⣿⣟⣛⠷⠙⢿⣷⣌⠀⢿⡇⣼⣿⣿⣿ 
⣿⣿⣿⡿⢀⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣶⣤⡙⢿⢗⣀⣁⠈⢻⣿⣿ 
⣿⡿⢋⣴⣿⣎⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣦⡉⣯⣿⣷⠆⠙⢿
 ⣏⠀⠈⠧⠡⠉⠙⢿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠃⠉⢉⣁⣀⣀⣾

2024-11-02 08:49 UTC, PiotrTheTchaikowsky commented on code/game/objects/items/toys.dm
> +	user.visible_message("<span class='notice'>[razumisttext]</span>")
> И может выдать ттс через компонент

Можно, но хотелось бы просто выводить фразу в чат. Я бы настоял на вывод фразочки в чат, но гляну что будет если через атом, сам ПР я портировал свой старый ПР с сс1984

2024-11-02 08:51 UTC, PiotrTheTchaikowsky commented on code/game/objects/items/toys.dm
> +	desc = "Cat with warning cone on it. Wonder what do itself so smart?"
Если сегодня будет время с разрабами поговорю как делать модули, я в этом деле дебютант

2024-11-09 15:01 UTC, AyIong commented
well-well-well, дружище, давай-ка на апстрим это, либо модульно засунь, у нас есть модуль игрушек
Можешь по примеру игрушки лисы MacVulpix сделать, она по пути `modular_ss220\objects\code\plushies\macvulpix.dm`

2024-11-18 10:48 UTC, PhantornRU requested changes
Игрушки красивые, хочу.

Но есть одно "но". Это не модуль. Как делать модуль у нас есть на вики:
https://wiki.ss220.club/index.php/%D0%A0%D1%83%D0%BA%D0%BE%D0%B2%D0%BE%D0%B4%D1%81%D1%82%D0%B2%D0%BE_%D0%BF%D0%BE_%D1%80%D0%B0%D0%B7%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%BA%D0%B5

Если вкратце, то всё тоже самое что ты щас сделал, но засунуть в "нашу папочку"
Закинешь в модуль и можно в билд

2024-12-10 00:41 UTC, closed without merging