paramedic and cmo uniform
ss220club/Paradise-SS220 pull request #1637
Opened 2024-11-03 22:49 UTC by HecoWolff

## Что этот PR делает
Добавляет униформу для парамедика, а так же для СМО.
Парамедику:
-Сьют парамедика;
-Разгрузочный пояс;
-Берет парамедика.

Для СМО:
-Парадная форма СМО, женская;
-Парадная форма СМО, мужская;
-Берет СМО;
-Мантия СМО.

Униформа парамедика доступна в вендомате меда.
Униформа СМО доступна в его шкафу.

## Почему это хорошо для игры
У СМО и парамедика появится выбор в одежде.

## Изображения изменений
![image](https://github.com/user-attachments/assets/d503b51a-20e7-48e0-b798-a41aedbbf2e4)
![image](https://github.com/user-attachments/assets/2326bae4-6535-45b3-bd6b-ae511a3c4ca0)
![image](https://github.com/user-attachments/assets/063e3b7a-0ae0-4f2e-a8c6-e907abc77608)
![image](https://github.com/user-attachments/assets/8c1ac84a-8367-4d88-93b9-aee110f173a5)
![image](https://github.com/user-attachments/assets/319c8b30-ac91-4220-b830-78f357432484)

## Тестирование
Тестировалось на локалке, все работает, отображается и выдается.

## Changelog

:cl:
add: Добавил форму парамедика и СМО.
/:cl:

2024-11-03 22:55 UTC, dj-34 reviewed
Перебор контраста на парадной форме и недостаток глянца на обычной (очень плоские цвета, в частности на синих полосах и оттенках белого).

![image](https://github.com/user-attachments/assets/dc8aca94-d185-490d-836f-4321e0acffb4)
![image](https://github.com/user-attachments/assets/4be42088-b732-4a42-8d19-bfb03d103f02)

2024-11-03 23:06 UTC, dj-34 commented on modular_ss220/jobs/code/clothing/medical_clothing.dm
> +		"Abductor" 			= 	'modular_ss220/jobs/icons/clothing/mob/uniform.dmi',
это всё в modular_ss220/clothing

2024-11-03 23:09 UTC, dj-34 commented on modular_ss220/jobs/code/garment_bag.dm
> +	new /obj/item/clothing/head/beret/cmo(src)
в modular_ss220\clothing\code\garment_bag.dm

2024-11-03 23:10 UTC, dj-34 commented on modular_ss220/jobs/code/objects/wardrobe_vendors.dm
> +/obj/machinery/economy/vending/medidrobe/Initialize(mapload)
в modular_ss220\clothing\code\clothing_vendors.dm

2024-11-03 23:11 UTC, dj-34 commented on modular_ss220/jobs/code/clothing/medical_clothing.dm
> +/obj/item/clothing/under/rank/medical/chief_medical_officer/suit
suit?

2024-11-03 23:12 UTC, dj-34 commented on modular_ss220/jobs/code/clothing/medical_clothing.dm
> +/obj/item/clothing/under/rank/medical/paramedic/suit
тоже не suit

2024-11-18 10:49 UTC, PhantornRU requested changes
Заброшено?

2024-12-10 00:41 UTC, closed without merging