SpaceRuin - Infected Ship
ss220club/Paradise-SS220 pull request #165
Opened 2023-09-09 15:30 UTC by konushi

## Что этот PR делает
Добавление новой косморуины: ударный корабль синдиката, захваченный ксеноморфами (port/remap infested_frigate from Skyrat)
Лут: bloodred риг синдиката/ modsuit синдиката на трупе (рандом), игрушки, инструменты, документы синдиката, кейс с кредитами.

## Почему это хорошо для игры

Больше косморуин - больше косморуин

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/139562134/5f0a3cb7-ad8a-47fe-b09d-c41703f6e64e)

## Тестирование
Работает, молюсь на ребейз

## Changelog

:cl:
add: новая карта - infected_ship
/:cl:

2023-09-09 15:49 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/9aad0891-72d0-4627-8208-f0823e77eb45)
Почему до сих пор не снялось?

2023-09-09 15:56 UTC, Furrior commented
> ![image](https://user-images.githubusercontent.com/69762909/266790218-9aad0891-72d0-4627-8208-f0823e77eb45.png) Почему до сих пор не снялось?

Вопрос к гитхабу

2023-09-09 16:37 UTC, Aylong220 requested changes

2023-09-09 16:37 UTC, Aylong220 commented on config/example/config.toml
Тут конфликт по всей видимости, ветка старая. Ты же до этого маленький бар в космосе добавил...

2023-09-09 16:37 UTC, Aylong220 commented on modular_ss220/_maps220/code/RandomRuins/space_ruins.dm
И тут тоже

2023-09-09 22:31 UTC, Aylong220 commented
Проверяй пожалуйста тесты
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/7ffb1eb5-abdd-4967-b06f-770af584cb93)

2023-09-09 22:56 UTC, Aylong220 commented
Блять...

2023-09-09 22:58 UTC, konushi commented
> Блять...

Я понял че не так делаю, больше такого не будет xdd

2023-09-10 09:32 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/13d4e26a-cbc0-41bb-a48a-42b3d330c28d)
Денюжек оставь 200-300
Шкаф синдикатовский ставь вместо иконстейта
Убери одну коробку патронов

2023-09-10 09:34 UTC, Aylong220 commented
И ксеносов как-то слишком много

2023-09-10 09:41 UTC, Aylong220 commented
Сьют сторейджи не открываются.

2023-09-10 09:46 UTC, Aylong220 requested changes
Короче, уменьшаешь деньги до 200.
Убираешь со шкафов икон стейты.
Урезаешь ксеносов.
Придумай что-то с сьют сторейджами, они не открываются ни в какую.
Убери 2 турели вот тут
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/fdcf4bb4-0552-4eb8-809a-c70c2f02d310)
Они тригерятся на мамашу ксеносов.
Убери пачку потронов.
Да и вроде всё. Комбат перчаток многовато, я бы убрал в шкафу одни, ибо в тулбоксе есть.

2023-09-10 13:12 UTC, Aylong220 commented
А второй шкафчик?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/958c1cca-5d18-4445-8494-cef4b1f39737)

Сьют сторейджи открываются?

2023-09-10 16:09 UTC, konushi commented
> А второй шкафчик? ![image](https://user-images.githubusercontent.com/69762909/266837884-958c1cca-5d18-4445-8494-cef4b1f39737.png)
> 
> Сьют сторейджи открываются?

шкафчик забыл, исправил 
так света же нету, как они открываться будут gatto

2023-09-10 16:12 UTC, Aylong220 approved these changes
Ладно

2023-09-11 03:24 UTC, Furrior approved these changes

2023-09-11 03:25 UTC, merged