[Fix] Admins can now again spawn BloodBrothers and VoxRaders
ss220club/Paradise-SS220 pull request #1708
Opened 2024-12-22 14:58 UTC by Drsmail

## Что этот PR делает
Исправляет маленькую ошибку в коде, позволяет админам снова спавнить антагов из модулей sss220

## Почему это хорошо для игры
Баги - это плохо!

## Тестирование
Локалка, заспавнил пожирателя

## Changelog

:cl:
fix: Снова можно спавнить воксов и кровавых братьев, через панель Event
/:cl:

2024-12-22 15:12 UTC, Furrior commented on code/modules/admin/verbs/one_click_antag.dm
> +		<a href='byond://?src=[UID()];makeAntag=10'>Make Vox Raiders</a><br>
Лучше тогда уж занести в строку чуть выше это, чтоб гарантировано поймать конфликт, когда ее изменят

2024-12-22 15:48 UTC, PhantornRU requested changes
занеси внутрь для того шоб конфликт поймать когда он появится

2024-12-22 15:48 UTC, PhantornRU commented on code/modules/admin/verbs/one_click_antag.dm
>  	dat += {"
```suggestion
	// SS220 ADD - Start
```

2024-12-22 15:48 UTC, PhantornRU commented on code/modules/admin/verbs/one_click_antag.dm
>  	// SS220 ASS - End
```suggestion
	// SS220 ASS - End
		"}
```

2024-12-22 16:33 UTC, Drsmail commented
Вроде сделал, спасибо, всем за быстрые отзывы

2024-12-22 19:52 UTC, merged

2024-12-23 01:05 UTC, PhantornRU commented
Но я спаль... :(