Add: Platforms
ss220club/Paradise-SS220 pull request #178
Opened 2023-09-11 14:28 UTC by dj-34

## Что этот PR делает
Добавляет платформы (2 варианта), которые можно скрафтить
ПР был взят отсюда. Спрайты были перекрашены

## Почему это хорошо для игры
Больше декоративных решений

## Изображения изменений
(Примеры использования)

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/17690f12-b7e1-46f9-a7bd-072197463e76)
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/84e06745-48e1-44bb-95f1-326f6fd9ec52)

## Тестирование
Проверял в игре

## Changelog

:cl:
add: Платформы
/:cl:

2023-09-11 14:30 UTC, Aylong220 commented
Ебать стильно

2023-09-11 14:30 UTC, dj-34 commented
> Ебать стильно

сыглы

2023-09-12 01:53 UTC, Furrior requested changes
Пробелы после // в коментах и спаны через макрос сделай, а так, вроде, норм

2023-09-16 09:34 UTC, Furrior approved these changes

2023-09-16 09:34 UTC, merged