SpaceRuin - Convoy Ambush
ss220club/Paradise-SS220 pull request #185
Opened 2023-09-12 19:25 UTC by konushi

## Что этот PR делает
Добавление новой косморуины: засада на группу транспортных кораблей NT (port/remap caravanambush from Skyrat)
Лут: дизейблер, два списанных ретро лазергана, 760 кредитов, 3 мета по 10 u., 2 фраг гранаты, стечкин, c4, плазмакаттер.

## Почему это хорошо для игры

Больше косморуин - больше косморуин

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/139562134/eb3fc0d9-3aed-4ece-a0fd-ace8858cd4ab)

## Тестирование
Работает, молюсь на ребейз

## Changelog

:cl:
add: новая карта - convoy_ambush

/:cl:

2023-09-12 19:29 UTC, Aylong220 commented
>760 кредитов
Бля, ты решил сделать космос местом заработка? Чисто на каждой руине 1.5 начального капитала

2023-09-12 19:29 UTC, konushi commented
> > 760 кредитов
> > Бля, ты решил сделать космос местом заработка? Чисто на каждой руине 1.5 начального капитала

Да. (уберу хех)

2023-09-13 08:14 UTC, Aylong220 requested changes
Все бластдуры не привязаны к кнопкам, и наоборот.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/120e3f8d-0772-4299-b0df-b6d60ba2b69f)

Опять куча турелей, учитывая лут, это просто суицидальная миссия идти сюда, притом из-за турелей ты даже не поймёшь куда припёрся и что тебя убило. Убери их.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/571c3e44-fdac-48fa-ace8-08c4fe47b2fe)

Многовато врагов с СРками, они одной очередью могут уложить наглухо. умеьшай их общее количество, а ренджовых оставь 1-2 штуки.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/574e18b4-5f80-4084-b5fd-1c85a0c4f434)

Я в целом заметил что ты делаешь слишком крепкую оборону как для руин которые в космосе и в которых лута не то чтобы много.
Старайся соблюдать баланс а не втупую копировать с скайрата.
Плюс одни синдикековцы, когда там уже карпы :gatto:

2023-09-14 12:13 UTC, Aylong220 approved these changes

2023-09-14 12:25 UTC, merged