SpaceRuin - White Ship
ss220club/Paradise-SS220 pull request #190
Opened 2023-09-15 18:43 UTC by konushi

## Что этот PR делает

Замена оффовского  ̶н̶е̶д̶о̶р̶а̶з̶у̶м̶е̶н̶и̶я̶ ̶ медицинского корабля на новый (port from RuParadise)
Добавление в модули враждебных симплов - undead (на оффах они почему то retaliate)
Лут: медицина, мини лазерный пистолет, шаттл

## Почему это хорошо для игры

Больше косморуин - больше косморуин

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/139562134/cb5b6870-0531-4dfe-a84b-91ce64ac48bc)

## Тестирование
Кнопки жмутся, зомби дерутся

## Changelog

:cl:
add: враждебные симплмобы - undead
tweak: замена косморуины whiteship

/:cl:

2023-09-15 18:52 UTC, dj-34 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/f11a52c8-e95b-41ef-b091-60407800d2d6)

повтор

2023-09-15 18:52 UTC, dj-34 commented
пробовал перегонять вайтшип на картах? Нет с этим проблем?

2023-09-15 18:54 UTC, konushi commented
> пробовал перегонять вайтшип на картах? Нет с этим проблем?

у меня почему то нет секторов, но если спавнить ручками руину - летает

2023-09-15 18:59 UTC, Aylong220 commented
Ты в конфиг руину не вписал
Плюс в твоём личном конфиге космос может быть отключён, он по-умолчанию вырублен

2023-09-15 18:59 UTC, konushi commented
> Ты в конфиг руину не вписал Плюс в твоём личном конфиге космос может быть отключён, он по-умолчанию вырублен

в конфиг впишу, а space_ruin не трогать? оффовский остается?

2023-09-15 19:00 UTC, Aylong220 commented
> в конфиг впишу, а space_ruin не трогать? оффовский остается?
 
Фуриор выключит в конфиге на сервере, если не забудет :Clueless:

2023-09-15 19:01 UTC, Aylong220 commented
И вот тут впиши путь
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/c4f2f63b-b15b-4cce-b7eb-eff8ac651f98)
Ну то есть просто 220 допиши

2023-09-15 19:15 UTC, Aylong220 commented
Параметры маячка приведи к размеру карты
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/bd6dc3b1-029f-4f30-8215-fe7bdddb45e6)

2023-09-15 19:16 UTC, Aylong220 commented
dwidth - 8

2023-09-15 19:16 UTC, Furrior commented
> > в конфиг впишу, а space_ruin не трогать? оффовский остается?
> 
> Фуриор выключит в конфиге на сервере, если не забудет :Clueless:

Я рано или поздно сделаю вам тупо отдельный конфиг под выключение и включение карт модульно, тк меня это заебет

2023-09-15 19:22 UTC, Aylong220 requested changes

2023-09-15 19:22 UTC, Aylong220 commented on _maps/map_files220/RandomRuins/SpaceRuins/whiteship.dmm
> +	dheight = 30
Лишнее

2023-09-15 19:22 UTC, Aylong220 commented on _maps/map_files220/RandomRuins/SpaceRuins/whiteship.dmm
> -/obj/structure/window/full/shuttle,
Куда окно спиздил? xdd

2023-09-15 19:31 UTC, Aylong220 approved these changes

2023-09-16 09:36 UTC, Furrior requested changes

2023-09-16 09:36 UTC, Furrior commented on modular_ss220/_maps220/code/mobs.dm
> +//Undead
```suggestion
// Undead
```

2023-09-16 09:37 UTC, Furrior approved these changes

2023-09-16 09:37 UTC, merged