feat: NanoMap for Camera Console
ss220club/Paradise-SS220 pull request #197
Opened 2023-09-17 20:37 UTC by Aylong220

## Что этот PR делает
Копипизднул код с этих ПРов:
https://github.com/ss220-space/Paradise/pull/1033
https://github.com/ss220-space/Paradise/pull/22
И пары древних коммитов.
Работает, но какой ценой...

## Почему это хорошо для игры
Удобство, сидеть на камерах со списком - один из видов мазохизма

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/52127693-1c01-496d-8f0c-35ec7046403d)

## Тестирование
Ну да...

## Changelog

:cl:
add: Добавлена карта в консоль камер.
del: Выброшены остатки моей гордости.
/:cl:

2023-09-18 17:54 UTC, Furrior commented on tgui/packages/tgui/styles/components/NanoMap.scss
> +  overflow: hidden;
Ну это мем пиздец

2023-09-18 17:55 UTC, Aylong220 commented on tgui/packages/tgui/styles/components/NanoMap.scss
> +  overflow: hidden;
> Ну это мем пиздец

Хз как это работало, не должно же

2023-09-18 17:58 UTC, Furrior requested changes
Предположим

2023-09-18 17:58 UTC, Furrior commented on tgui/packages/tgui/components/NanoMap.js
> -      this.setState((state) => {
ТСММ

2023-09-18 17:58 UTC, Furrior commented on tgui/packages/tgui/components/NanoMap.js
> +    const mapSize = (510 * zoom) + 'px';
ТСММ

2023-09-18 17:58 UTC, Furrior commented on tgui/packages/tgui/components/NanoMap.js
> +          </Box>
ТСММ

2023-09-18 17:58 UTC, Furrior commented on tgui/packages/tgui/components/NanoMap.js
> +  const ry = ((y * 2 * zoom) - zoom) - 3;
2 строки нижние ТСММ

2023-09-18 17:58 UTC, Furrior commented on tgui/packages/tgui/components/NanoMap.js
> +            format={v => v + "x"}
ТСММ

2023-09-20 16:44 UTC, Aylong220 commented
Надо пересоздавать после ребейза

2023-09-20 16:44 UTC, closed without merging