Cyberiad: Bridge remap
ss220club/Paradise-SS220 pull request #199
Opened 2023-09-18 10:18 UTC by dj-34

## Что этот PR делает
**Ремап мостика**

-Добавлен дополнительный, "парадный" проход снизу.
-Добавлена лаунж зона в центре мостика.
-Добавлена статуя Кибериады.
-Новая переговорная.
-Небольшие изменения комнаты капитана и хопа (наполнение тоже самое).
-Более удобная расстановка машинерии.

## Почему это хорошо для игры
Unique

## Изображения изменений
![BRIDGE](https://github.com/ss220club/Paradise-SS220/assets/20109643/d794c292-3f65-4880-b825-6dc7ef7a0906)
![2023-09-18 15 17 52](https://github.com/ss220club/Paradise-SS220/assets/20109643/e26c13f4-60b7-44d6-b06d-eedbc5ad024f)

## Тестирование
Тестировал в игре

## Changelog

:cl:
add: Кибериада: Ремап мостика, новая переговорная, центральный проход
add: Добавлена статуя Кибериады
/:cl:

2023-09-18 12:45 UTC, Aylong220 requested changes
Провод лишний, может проведёшь трубу с мостика а не с офиса ГП? Больно смотреть на пересекающиеся и кривые трубы.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/17a5d817-72db-4e31-8a79-5818b724a1ac)

Узелки кстати у нас не такие
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/204035e3-c38f-4d31-a65d-01e5eb8f81d9)

А такие 
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/8f0b3b85-9e0a-46ff-b33d-de2c7773f81d)

Выглядят эстетичнее xdd

2023-09-18 15:30 UTC, Henri215 commented
Where is that statue from? It looks great 0-0

2023-09-18 17:39 UTC, Furrior commented
> Where is that statue from? It looks great 0-0

If you mean the cyberiad one, its drawn by the pr author when he got tired of waiting for some spriter to make it.

2023-09-18 17:50 UTC, Furrior commented
![изображение](https://github.com/ss220club/Paradise-SS220/assets/68264134/b66ed725-ac63-4446-aa49-d041e9cfe64e)
> "Had to draw it myself, it turned out pretty good"

2023-09-18 18:14 UTC, S34NW commented
8/10 will port this in some form, only downside is AI upload being impossible to reach quietly.

8 из 10 будут использовать это каким-либо образом, единственным недостатком является невозможность бесшумного доступа для преступников в помещение "AI upload".

2023-09-19 02:55 UTC, Aylong220 approved these changes
:mooniXorow:

2023-09-19 06:28 UTC, merged