feat: NanoMap for Camera Console
ss220club/Paradise-SS220 pull request #213
Opened 2023-09-20 17:52 UTC by Aylong220

## Что этот PR делает
Копипизднул код с парашизы и пары древних коммитов.
Работает, но какой ценой...

## Почему это хорошо для игры
Удобство, сидеть на камерах со списком - один из видов мазохизма

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/52127693-1c01-496d-8f0c-35ec7046403d)

## Тестирование
Ну да...

## Changelog

:cl:
add: Добавлена карта в консоль камер.
del: Выброшены остатки моей гордости.
/:cl:

2023-09-20 18:08 UTC, Furrior commented on tgui/packages/tgui/components/ByondUi.js
> +export const getBoundingBox = element => { // SS220 EDIT - ORIGINAL: const getBoundingBox = element => {
А чего тут написал сс220 едит, но не в других местах?

2023-09-20 18:09 UTC, Aylong220 commented on tgui/packages/tgui/components/ByondUi.js
> +export const getBoundingBox = element => { // SS220 EDIT - ORIGINAL: const getBoundingBox = element => {
Потому что это единственное изменение в этом файле.
В остальных я это буду писать долго и нудно...

2023-10-03 11:17 UTC, dj-34 commented
че там когда? может оффам закинуть?

2023-10-03 11:19 UTC, Aylong220 commented
> че там когда? может оффам закинуть?

Они вроде говорили что им не надо это, кто-то скидывал видос под твою ишую, где АА говорит что не добавляют это в целях баланса

2023-10-03 11:20 UTC, dj-34 commented
> > че там когда? может оффам закинуть?
> 
> Они вроде говорили что им не надо это, кто-то скидывал видос под твою ишую, где АА говорит что не добавляют это в целях баланса

мне кажется тогда речь шла немного про другое, но если учитывать что оффы говна поели...

2023-10-15 17:21 UTC, Furrior commented
Расконфликти, гляну потом

2023-10-15 18:03 UTC, Furrior requested changes

2023-10-15 18:03 UTC, Furrior commented on tgui/packages/tgui/components/NanoMap.js
> +    const Ycenter = (window.innerHeight / 2) - 256;
Как там я писал? Крч не влияет, так что лучше не трогать

2023-10-15 18:03 UTC, Furrior commented on tgui/packages/tgui/components/NanoMap.js
> +
?

2023-10-15 18:03 UTC, Furrior commented on tgui/packages/tgui/components/NanoMap.js
> +        />
Так себе, но ладно. Я слишком ебал жс, чтоб сказать тут что то

2023-10-19 15:53 UTC, Aylong220 commented
Оу, а тут ревью, уведомления то не было xdd

2023-10-19 16:23 UTC, dj-34 commented
> Тгуи конфликты бесят пиздец

как делал Азиз: все мержим, потом ребилдим ручками xdd

2023-10-19 16:24 UTC, Aylong220 commented
Перебилдил

2023-10-19 16:50 UTC, Furrior approved these changes

2023-10-19 16:50 UTC, merged