Feat: Port some of RuPara objects, part 1
ss220club/Paradise-SS220 pull request #218
Opened 2023-09-21 16:57 UTC by dj-34

## What Does This PR Do
Добавляет:
 - Зиппо
 - Штампы (ооо бля... как это сделано я того маму)
 - Трибуны
 - Брошюры
 - Офисные игрушки
 - Статуя Дельты
 - Измельчитель

## Why It's Good For The Game
...)

## Images of changes
не будет такого

## Testing
да

## Changelog
:cl:
add: Порт некоторых предметов с РуПары (часть 1)
/:cl:

2023-09-21 17:08 UTC, Aylong220 submitted a review, later dismissed

2023-09-21 17:08 UTC, Aylong220 commented on modular_ss220/objects/code/officetoys.dm
> +/obj/item/toy/desk/fan
Он есть
/obj/item/fan

2023-09-21 17:22 UTC, dj-34 commented on modular_ss220/objects/code/officetoys.dm
> +/obj/item/toy/desk/fan
> Он есть /obj/item/fan

оффовский старый код, у которого нет функционала. Ничего не могу поделать

2023-09-22 16:31 UTC, Furrior requested changes
Думаю, идею понял

2023-09-22 16:31 UTC, Furrior commented on modular_ss220/aesthetics/stamps/code/stamps.dm
> +	if(istype(S, /obj/item/stamp/custom))
```suggestion
	if(S.stampoverlay_custom_icon)
```

2023-09-22 16:31 UTC, Furrior commented on modular_ss220/aesthetics/stamps/code/stamps.dm
> +		var/image/stampoverlay_custom = image('modular_ss220/aesthetics/stamps/icons/stamps.dmi')
```suggestion
		var/image/stampoverlay = image(S.stampoverlay_custom_icon)
```

2023-09-22 16:31 UTC, Furrior commented on modular_ss220/aesthetics/stamps/code/stamps.dm
> +		stampoverlay_custom.icon_state = "paper_[S.icon_state]"
```suggestion
		stampoverlay.pixel_x = x
		stampoverlay.pixel_y = y
		stampoverlay.icon_state = "paper_[S.icon_state]"
```

2023-09-22 16:31 UTC, Furrior commented on modular_ss220/aesthetics/stamps/code/stamps.dm
> +/obj/item/paper/stamp(obj/item/stamp/S)
Обнобуквенник переименуй, как говорил Валлат

2023-09-22 16:31 UTC, Furrior commented on modular_ss220/aesthetics/stamps/code/stamps.dm
> +	item_color = "hosred"
```suggestion
/obj/item/stamp/warden
	name = "warden's rubber stamp"
	icon = 'modular_ss220/aesthetics/stamps/icons/stamps.dmi'
	icon_state = "stamp-ward"
	item_color = "hosred"
	stampoverlay_custom_icon = 'modular_ss220/aesthetics/stamps/icons/stamps.dmi'
```
И по аналогии дальше

2023-09-23 14:28 UTC, Furrior requested changes
Мог что то не заметить

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +	else
Тут елс не нужен же, в ифе выше ёрли ретерн

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +		if(paper_result)
```suggestion
		if(!paper_result)
			return
```
Соответственно, то что ниже, сместить

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +			playsound(src.loc, 'modular_ss220/objects/sound/pshred.ogg', 75, 1)
```suggestion
			playsound(loc, 'modular_ss220/objects/sound/pshred.ogg', 75, 1)
```
И звук мб в вар вынести

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +				to_chat(user, span_warning("\The [src] is full; please empty it before you continue."))
```suggestion
				to_chat(user, span_warning("[src] is full; please empty it before you continue."))
```
[src] автоматически the подставляет

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +				to_chat(user, span_danger("\The [src] was too full, and shredded paper goes everywhere!"))
Аналогично

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +				for(var/i=(paperamount-max_paper);i>0;i--)
```suggestion
				for(var/i in 1 to paperamount-max_paper)
```

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +	return
До сюда код никогда бы не дошел

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +		to_chat(usr, span_notice("\The [src] is empty."))
Аналогично

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +		to_chat(user, span_notice("\The [empty_into] is full."))
Аналогично с [src]

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +	if(empty_into && empty_into.contents.len >= empty_into.storage_slots)
```suggestion
	if(empty_into && length(empty_into.contents) >= empty_into.storage_slots)
```

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +		if(!SP) break
```suggestion
		if(!SP)
			break
```

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +	update_icon()
Тут аналогичные изменения

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +		user.visible_message(span_danger("\The [user] burns right through \the [src], turning it to ash. It flutters through the air before settling on the floor in a heap."), span_danger("You burn right t
И тут

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +	if(prob(65)) color = pick("#8b8b8b","#e7e4e4", "#c9c9c9")
```suggestion
	if(prob(65))
		color = pick("#8b8b8b","#e7e4e4", "#c9c9c9")
```

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/tribune.dm
> +	return 1
```suggestion
		return TRUE
	if(get_dir(loc, target) == dir)
		return !density
	return TRUE
```

2023-09-23 14:28 UTC, Furrior commented on modular_ss220/objects/code/tribune.dm
> +	return 1
```suggestion
	if(istype(O) && O.checkpass(PASSGLASS))
		return TRUE
	if(get_dir(O.loc, target) == dir)
		return FALSE
	return TRUE
```

2023-09-23 15:45 UTC, Furrior requested changes
Однобуквенники попереименовывай и пробелы перед коментами проставь и норм

2023-09-23 15:45 UTC, Furrior commented on modular_ss220/objects/code/officetoys.dm
> +		to_chat(user, span_notice("You flip the [src]."))
оно автоматом подставит the, тк в названии нет \improper

2023-09-23 15:45 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +			paper_result = shred_amounts[shred_type]
```suggestion
		if(W in shred_amounts)
			paper_result = shred_amounts[W]
```

2023-09-23 15:45 UTC, Furrior commented on modular_ss220/objects/code/papershredder.dm
> +	return
```suggestion

```

2023-09-23 17:18 UTC, Furrior approved these changes

2023-09-23 17:19 UTC, merged