Feat: Add ported items to Cyberiad, part 1
ss220club/Paradise-SS220 pull request #235
Opened 2023-09-23 22:17 UTC by dj-34

## Что этот PR делает
 - Добавляет портированные предметы из ПРа
 https://github.com/ss220club/Paradise-SS220/pull/218
 - Актуализирует изменения (отредактирован кабинет КМа в связи с тем что он теперь глава 💀, добавлены костыли в мед)

## Почему это хорошо для игры
Актуализация карты

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/0bd255aa-a17f-43d0-9ec9-59ef06deecbe)

## Тестирование
Проверял в игре

## Changelog

:cl:
add: Кибериада: Добавлены портированные предметы
tweak: Кибериада: Актуализация с изменениями оффов
/:cl:

2023-09-23 22:20 UTC, Aylong220 approved these changes
Не глядя

2023-09-24 02:25 UTC, Aylong220 commented
Имхо:
Трибуна тут выглядит неуместно
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/5fa24a99-a3d1-48c2-8e90-58d8de94249f)

Не нравится что всё в ящик просто закинул
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/d85d6245-018e-43b6-bf4a-7741c64aa576)

Может шреддер лучше сюда?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/81f7feec-67fc-441f-9686-2d09777e2015)

Костыли на столе выглядят... странно?
Обычно их где-то хранят, а не оставляют на виду, как насчёт шкафчика?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/30d2ed73-58b6-4163-92d5-368c47d3a2ab)

2023-09-24 10:30 UTC, Furrior commented
![изображение](https://github.com/ss220club/Paradise-SS220/assets/68264134/60d400d9-07ab-41a4-9957-68773c1237cb)
Гитхаб ишью?

2023-09-24 10:36 UTC, dj-34 commented
> ![изображение](https://user-images.githubusercontent.com/68264134/270158612-60d400d9-07ab-41a4-9957-68773c1237cb.png) Гитхаб ишью?

я новенький

2023-09-24 14:44 UTC, Aylong220 requested changes
Не много ты лута накидал в техи?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/e2ef11d0-eef5-4e4c-9183-25acfdb623f5)

2023-09-24 14:52 UTC, Aylong220 reviewed
Эта лестница выглядит странно тут
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/4d5ca8b5-96a5-4d53-a0a5-4b9997682f43)

2023-09-24 14:53 UTC, Aylong220 commented
> Эта лестница выглядит странно тут ![image](https://user-images.githubusercontent.com/69762909/270172716-4d5ca8b5-96a5-4d53-a0a5-4b9997682f43.png)

А всё, приблизил и понял, вопрос отпал

2023-09-24 14:55 UTC, Aylong220 approved these changes

2023-09-24 19:15 UTC, merged