GenericMap: SyndicateCentComm
ss220club/Paradise-SS220 pull request #244
Opened 2023-09-25 16:45 UTC by konushi

## Что этот PR делает

Перенос основы рупаровского СЦК без зон, шаттлов и некоторых объектов.
Что нужно: 

- [x] Зоны
- [x] Шаттлы
- [x] Синдикатовский принтер
- [x] Кресла для шаттла
- [x] Дюранд ровер
- [x] Декаль змеи на пол
- [x] Шкафчик синдимедика
- [x] Рольки СЦК (не смотрел, может они и есть). 
Ну и еще что по косметике, на ваш вкус.

## Почему это хорошо для игры

Больше СЦК - больше СЦК.

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/139562134/41b5fa79-1c3e-4f7b-9598-24bcc8a85cfd)

## Тестирование
Кнопки вроде жмутся, доступы как на рупаре. Че то надо делать со шторами.

## Changelog

:cl:
add: СЦК с рупары
/:cl:

2023-09-27 13:10 UTC, Furrior commented
А коробку с дельтой как задеть успели?

2023-09-27 13:15 UTC, dj-34 commented
> А коробку с дельтой как задеть успели?

метки для шаттлов изменены

2023-09-27 13:21 UTC, Furrior commented
Увидел. Не понял зачем. Ну и похуй

2023-09-28 16:19 UTC, Aylong220 requested changes
У вас раковины на полу лежат
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/516463bd-320f-4c60-8886-78511e09b82c)

Монитор смотрит в стену
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/b786e09d-2d7c-4421-8955-0ab9e05359e1)

Интеркомы не повёрнуты в нужное направление, я так понял вся машинерия не повёрнута
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/9427fb31-0a55-4cfa-a152-19c570765f25)

Почему слева есть источники света, а справа нет? hmmm
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/d046b3db-81a1-494d-96a9-6ab3fb901a6d)

Табуретки тоже не повернули
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/45d87c31-7ff4-4a40-bb10-ec4aed10cf8b)

Ну, пока так, ща на локалке буду проверять xdd

2023-09-28 16:44 UTC, Aylong220 requested changes
Лампочки ломаются, отключить бы как-то это...
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/672f94ab-e4bc-4f71-85b7-d9b31656b63b)

Как-то в целом мало света, имхо
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/f983e0ab-4b67-4978-afe9-674848a13917)

Факс забаган, мало того что отключён, так ещё и карту не забрать, это конечно не ваши проблемы, но наверное лучше убрать
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/2415ccc3-3b95-4df0-b6d3-0bc78d6f5430)

Нюковец не может открыть дроп-под, так и задуманно?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/6f88aa5b-2197-4f02-be01-8b85b45e008c)

Сам дроп-под не фурычит, может из-за режима, хз...
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/a2d76505-4bc8-43cd-84aa-7c6907e328f8)

Ладно, нюковец даже выйти не может, и шаттл позвать, чувствую это не должно так быть.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/19449c6c-3bae-4f22-965f-74cb12a295b7)

Отдалить бы консоль выбора места высадки, она кстати должна быть?
Шаттл кстати летит без звука.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/4833ed74-b51e-4e09-a519-cf703733497b)

Ебать того рот, не жирно? 1 бульдог продаётся в бандле за 45 ТК, вместе с 2-мя магазинами. А тут их 10(!) хоть и без магазов, но всё ещё 80 выстрелов.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/72282e4d-d5a5-4654-bc4a-a14e79e83d82)

2023-09-28 16:50 UTC, Aylong220 commented
Ну и пустая пицца, вроде больше ничего не заметил
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/18eeef2c-2ff1-4e3b-a6fa-2592e5e2fccb)

2023-09-28 21:27 UTC, Aylong220 approved these changes

2023-09-29 05:11 UTC, merged