Update tts_seed.dm
ss220club/Paradise-SS220 pull request #278
Opened 2023-10-03 10:04 UTC by Lime-7

Добавление vocal_cords_surgery.

## Что этот PR делает

Добавляет операцию, по изменению голоса

## Почему это хорошо для игры

потому что на ОФФах этого нет, а мы добавим :pepecopium:

## Изображения изменений
к сожалению нет :ratge:

## Тестирование
Нет :Clueless: , но Фурриор одобрил
## Changelog

:cl:
add: добавил операцию, по смене голоса
/:cl:

2023-10-03 10:06 UTC, Furrior requested changes

2023-10-03 10:09 UTC, Lime-7 commented on modular_ss220/text_to_speech/code/tts_seed.dm
> +	allowed_tools = list(/obj/item/multitool = 100, /obj/item/screwdriver = 55, /obj/item/kitchen/knife = 20, /obj/item/scalpel = 25)
тут на "allowed_tools = list(/obj/item/multitool = 100, /obj/item/screwdriver = 55, /obj/item/scalpel = 25, /obj/item/kitchen/knife = 20)" поменять надо, забыл сделать

2023-10-03 10:14 UTC, Aylong220 commented
Название ПРа - огонь xdd
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/e3a2fe23-d38a-4ea5-9fa9-c2d0c4b9986f)

2023-10-03 10:34 UTC, Lime-7 commented on modular_ss220/text_to_speech/code/tts_seed.dm
> +	allowed_tools = list(/obj/item/multitool = 100, /obj/item/screwdriver = 55, /obj/item/kitchen/knife = 20, /obj/item/scalpel = 25)
поменял

2023-10-03 13:39 UTC, Furrior commented
А остальное че спанами не сделал? Я для примера только на одну тыкнул, а там со всеми надо

2023-10-03 19:31 UTC, Furrior approved these changes

2023-10-03 19:32 UTC, Furrior commented
Только вот пробелы с табами не пофиксил

2023-10-04 13:02 UTC, Furrior commented
Все еще та же проблема. Пробелы с табами

2023-10-05 21:02 UTC, Furrior commented on modular_ss220/text_to_speech/code/tts_seed.dm
> -						 "span_warning("Your hand slips, tearing [target_vocal] in [target]'s throat with [tool]!"))
Лишние ", видно же, что билд не компилирует

2023-10-08 09:46 UTC, Furrior commented
Ты на результаты тестов то смотри

2023-10-14 10:52 UTC, Lime-7 commented
Проверил на локалке, работает

2023-10-14 19:41 UTC, Furrior approved these changes

2023-10-14 19:41 UTC, merged