Awaymission: Caves
ss220club/Paradise-SS220 pull request #366
Opened 2023-10-08 08:53 UTC by konushi

## Что этот PR делает

Добавление нового гейта: мрачные пещеры, землетрясение в которых разрушило маленький шахтерский аванпост и оголило бездонные расселины и пропасти (port/remap Caves from Skyrat).
В модули добавлено: зоны, новые симплмобы, разбитый под клонирования, декаль лого СолГова, могилы - ящики, проклятое колечко (да поможет мне Бог с его кодом).

Новые симплмобы: древний маг, клоунское отродье (когда-нибудь боссы перестануть быть просто симплами переростками..).

Лут: первые 3 пещеры - ресурсы, материалы, инструменты, энергобластер 1 штука, 2 КА, 3 модуля к КА, шахтерская утварь, 2 шахтерский МОДсьюта без модификаций, 3 модификации к шахтерским МОДсьютам, одежда, деньги в количестве 100 кредитов.
4 пещера - 2 энергобластера, бумажка с исследованиями, секретные документы, одежда СолГова, M1911, дизейблер, инструменты, материалы.
5 пещера - одежда, книги заклинаний (дым, призыв вещи, перезарядка), брюлики, лут с древнего мага.
6 пещера - вещи культа, искаженный металл, колечко.

Большую часть контента можно урезать/поменять.

## Почему это хорошо для игры

Больше гейтов - больше гейтов (это не хорошо)

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/139562134/e37c2de2-60c4-4ae2-8553-9c7e46d0db4e)

## Тестирование
На локалке работает, маленькие проблемы с просадкой фпс на Z уровне, возможно придется поменять там атмос на обычный.

## Changelog

:cl:
add: новая карта для гейта: caves; новые симплмобы; косметические объекты для карты.
/:cl:

2023-10-09 08:18 UTC, Aylong220 requested changes

2023-10-09 08:18 UTC, Aylong220 commented on modular_ss220/maps220/code/objects.dm
> +		to_chat(user, "<span class='cultitalic'> Ты чувствуешь чье-то ужасающее присутствие...</span>")
Спаны вместо span class='danger и подобного
В span_danger("текст")

2023-10-09 08:19 UTC, Aylong220 commented on modular_ss220/maps220/code/objects.dm
> +		to_chat(user, "<span class='cultitalic'> Ты чувствуешь чье-то ужасающее присутствие...</span>")
Так, пойду карту смотреть...
Так впадлу локалку грузить

2023-10-09 09:18 UTC, Aylong220 requested changes
color = COLOR_ANCIENT_ROCK -> color = COLOR_ROCK
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/de7d3be1-79e7-4c8c-aa98-dade52ee77bf)

Убери planetary atmos у камней, и пожалуйста, постарайся не использовать VV в таких вещах, это как редактировать VV зоны.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/c017f21a-8e09-4d42-9eaa-bf0e6f868135)

Одиночка неудачник в другой локе, звучит прикольно, на деле больно и у этого чела будет не самое лучшее впечатление, когда все +- в одном месте, а он в ебенях
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/cc84de71-eda7-4d9a-80a3-aaf1449c0d24)

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/67c1f19f-96d5-4dba-b906-afd8427ae4ff)

Бейзтурф в зоне где он не нужен, у тебя шо пол, что стены, при уроне разрушаются до лавы насколько я помню, он тут бесполезен
Лучше впихни его в зону с постройками
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/fd85efae-6600-4bef-94d4-799dd0041ff7)

Пройдись пожалуйста vars_to_subtypes скриптом
И поправь косячки которые всплывут после него, хотя если всё делал по стандартам, их быть не должно.
После пройдись вторым скриптом который заменяет окна без решёток, на окна с решётками.
Обязательно отмени все изменения после них, кроме своей карты.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/55b52ca3-52f6-4640-83a3-571a34ca3391)

Денег можно и побольше по карте раскидать, гейт кажется достаточно сложным
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/db267ca0-c5ac-421a-9091-9b17f3483715)

Oh no, cringe. Но да ладно...
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/5a014c46-c566-4b6c-91d6-ea4fadaac5a7)

Хмм, 60 ТК... Я вообще против гейтов для манча антагов. Но пока это вроде единственная контра которую заметил.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/32b7e98b-47c2-4ffe-ade1-c1373dc096f7)

Ух блять, админский 1911, хотя вроде без доп. магазов, так что ладно. 
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/a6ebf86e-2de0-4500-99cb-2fcb68731c69)

Ой не, эту спеллбуку убери
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/3031316d-388e-432a-abef-a1db97fc2d3f)

Выход не запитан
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/d50364ca-01bf-4d83-a80f-899e22039908)

2023-10-09 18:10 UTC, Aylong220 commented
Завтра гляну и на локалке пробегусь
Главное не забыть

2023-10-10 10:55 UTC, Aylong220 requested changes
Турель не может попасть, и её не видно
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/edc51a37-4506-4774-b58d-f627b774e14c)

Если подойти в упор то видно но попасть всё ещё не может
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/84140438-9076-49fb-978a-dacfd62cbdc5)

Окна без решёток, так и задуманно?
Плюс огнетушитель имеет спрайт будто там он есть, при открытии его нет, поменяй икон стейт на пустой
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/c5b708f9-10a9-45d0-8b20-f1f4992daedd)

Ломание камней создаёт разницу давления, из-за которой атмосу пизда, наверное стоит сделать их неломаемыми, или поставить бейз турф где при копании камня будет ставится нормальный турф не создавая проблем, однако на границах зоны всё равно неломаемый нужен будет.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/ab770942-e38b-4e59-b7cf-60ac451a8124)
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/5761a6b6-47df-4ebb-8a3b-84aab71c3ce8)

Комнату с пакманом окружить бы неломаемыми стенами, и поставить вентилятор под дверь, плюс лучше отдельную зону со своим бейзтурфом сделать
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/92b32c24-2d60-4a24-9f02-5672ba0a6403)
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/1369217e-a58a-45f4-8b3b-46371fc575a9)

Спиритическая доска не закреплена
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/0b555e1b-4b1a-4eab-824a-9d86e0da52f6)

Перевести бы описания и названия новых шмоток, если они твои.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/33ad3bb7-aa13-4817-a587-c8c025f64093)

2023-10-10 11:53 UTC, Aylong220 commented
Я ж просил убрать эту каку с камней
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/ab15bae1-70a6-44a9-a864-01196dc9b588)

2023-10-10 11:54 UTC, konushi commented
> Я ж просил убрать эту каку с камней ![image](https://user-images.githubusercontent.com/69762909/273890700-ab15bae1-70a6-44a9-a864-01196dc9b588.png)

а про эти то и забыл, цвет же поменял у неразрушаемого, их щас не отличить(

2023-10-12 10:46 UTC, Aylong220 approved these changes

2023-10-12 10:47 UTC, Aylong220 commented
Остальное в игре вычислим

2023-10-12 10:47 UTC, konushi commented
> Остальное в игре вычислим

База маппинга

2023-10-12 18:11 UTC, Furrior requested changes

2023-10-12 18:11 UTC, Furrior commented on modular_ss220/maps220/code/objects.dm
> +		cooldown = world.time + 1000
1000 вынести в вар

2023-10-12 18:11 UTC, Furrior commented on modular_ss220/maps220/code/objects.dm
> +		user.invisibility = 40
40 тоже

2023-10-12 18:11 UTC, Furrior commented on modular_ss220/maps220/code/objects.dm
> +		visible_message(span_danger ("[user] исчезает из реальности!"))
```suggestion
		visible_message(span_danger("[user] исчезает из реальности!"))
```
И в других похожих местах убрать пробелы

2023-10-12 18:11 UTC, Furrior commented on modular_ss220/maps220/code/objects.dm
> +		spawn(60)
Переделать на коллбэк

2023-10-12 18:11 UTC, Furrior commented on modular_ss220/maps220/code/objects.dm
> +		SEND_SOUND (user, sound('sound/hallucinations/i_see_you2.ogg'))
Вынести в прок

2023-10-12 21:11 UTC, konushi commented on modular_ss220/maps220/code/objects.dm
> +		cooldown = world.time + 1000
> 1000 вынести в вар

я из всего нижеперечисленного только про пробелы понял

2023-10-13 09:58 UTC, Aylong220 commented on modular_ss220/maps220/code/objects.dm
> +		cooldown = world.time + 1000
Да вот я тоже. Но что точно надо, так это вместо децисекунд, писать в секундах. 100 SECONDS. Или 2 MINUTES

2023-10-15 12:19 UTC, dj-34 commented
А если всем попросить Фуриора, он замержит пещеры?
С Кону плакало половины разрабской

2023-10-15 12:24 UTC, Aylong220 commented
> А если всем попросить Фуриора, он замержит пещеры? С Кону плакало половины разрабской

Я могу замержить, но получу палкой по голове :clueless:

2023-10-15 16:00 UTC, dj-34 approved these changes

2023-10-15 18:09 UTC, Furrior requested changes
Что то типа такого. Писал на гитхбе, так что может не скомпилироваться даже

2023-10-15 18:09 UTC, Furrior commented on modular_ss220/maps220/code/objects.dm
> +		to_chat(user, span_warning("[name] еще перезаряжается!"))
```suggestion
/obj/item/clothing/gloves/ring/immortality_ring
	name = "старое кольцо"
	icon_state = "shadowring"
	ring_color = "shadow"
	material = "shadow"
	desc = "Кольцо цвета оникса из неизвестного материала. Позолоченные надписи на внешней стороне причудливо пульсируют, испуская зловещую дымку. Надеть его кажется не лучшей идеей..."
	resistance_flags = INDESTRUCTIBLE | FIRE_PROOF | UNACIDABLE | ACID_PROOF
	actions_types = list(/datum/action/item_action/immortality)
	var/ability_delay = 100 SECONDS

/datum/action/item_action/immortality
	name = "Ring ability"

/obj/item/clothing/gloves/ring/immortality_ring/proc/ring_ability(mob/user)
	if(cooldown > world.time)
		to_chat(user, span_warning("[name] еще перезаряжается!"))
		return
		
	cooldown = world.time + ability_delay
	user.status_flags |= GODMODE
	user.invisibility |= INVISIBILITY_MAXIMUM
	visible_message(span_danger("[user] исчезает из реальности!"))
	to_chat(user, span_cultitalic("Ты чувствуешь чье-то ужасающее присутствие..."))
	SEND_SOUND (user, sound('sound/hallucinations/i_see_you2.ogg'))
	addtimer(CALLBACK(src, PROC_REF(ring_ability_end), user), 8 SECONDS)

/obj/item/clothing/gloves/ring/immortality_ring/proc/ring_ability_end(mob/user)
	user.status_flags &= ~GODMODE
	user.invisibility &= ~INVISIBILITY_MAXIMUM
	visible_message(span_danger("[user] возвращается в реальность!"))
	if(!ishuman(user))
		return
	var/mob/living/carbon/human/H = user
	H.apply_damage(rand(10, 40), BURN, pick("r_hand"))
	H.adjustBrainLoss(30, TRUE)
```

2023-10-15 18:52 UTC, Furrior requested changes

2023-10-15 18:52 UTC, Furrior commented on modular_ss220/maps220/code/objects.dm
> +	user.invisibility |= INVISIBILITY_MAXIMUM
invisibility - не битфлаговая переменнеая. В ней обычные числа

2023-10-15 18:52 UTC, Furrior commented on modular_ss220/maps220/code/objects.dm
> +	user.invisibility &= ~INVISIBILITY_MAXIMUM
Аналогично

2023-10-15 18:53 UTC, konushi commented on modular_ss220/maps220/code/objects.dm
> +	user.invisibility &= ~INVISIBILITY_MAXIMUM
щас поменяю

2023-10-17 13:30 UTC, Furrior approved these changes

2023-10-17 13:30 UTC, merged