Наполнение ЕРТ автоматов, СРТ, плащ синди офицера
ss220club/Paradise-SS220 pull request #419
Opened 2023-10-13 17:37 UTC by Fullonibus

## Что этот PR делает
Изменение оснащения ЕРТ автоматов уровня Амбер, Гамма, Эпсилон. Добавлен аутфит СРТ, куртка офицера Синдиката

- Амбер получили вместо тазеров дизейблеры и больше резины в свои автоматы
- Гамма получила вместо ARG SMG и бронебойные патроны к нему в свои автоматы
- [Данные Удалены] получили в свою оружейную B.S.G.
- Добавлен аутфит в меню админ спавна - Special Response Team Member
- Офицер Синдиката получил из химчистки свою куртку. Теперь он выглядит не как трудовик в алкашке, а как трудовик в крутой куртке.

## Почему это хорошо для игры
Баланс ЕРТ, немного удобства щитспавну админам.

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/38350888/ccec54fd-9c0c-4c47-8771-2b1e4acf2161)

## Тестирование

Автоматы работают, СРТ прохлаждаются, офицер Синдиката ходит довольный в своей куртке.
## Changelog

:cl:
add: Special Response Team Member
tweak: Syndicate Officer drip
tweak: Наполнение автоматов ЕРТ
/:cl:

2023-10-13 17:40 UTC, Aylong220 commented on modular_ss220/vending/code/vending.dm
> +		/obj/item/ammo_box/magazine/enforcer = 12,
Летал?

2023-10-13 17:40 UTC, Aylong220 commented on modular_ss220/vending/code/vending.dm
> +		/obj/item/gun/energy/bsg/prebuilt/admin = 4,
Кинь не админский варик

2023-10-14 03:18 UTC, dj-34 requested changes

2023-10-14 03:18 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	desc = "Длинная куртка из высокопрочного волокна на которой виднеются медали."
У нас есть функциональные медали. Обозначать "медали" которых физически нет - глупо
```suggestion
	desc = "Длинная куртка из высокопрочного волокна."
```

2023-10-14 03:18 UTC, dj-34 commented on modular_ss220/outfits/_outfits.dm
> +	. = ..()
Оформи нормально

2023-10-14 03:18 UTC, dj-34 commented on modular_ss220/outfits/code/outfits.dm
> +/datum/outfit/job/syndicateofficer
У нас нет аутфита синдикат офицера??? :xmm:

2023-10-14 19:42 UTC, Furrior commented on modular_ss220/outfits/code/outfits.dm
> +/datum/outfit/job/syndicateofficer
Есть

2023-10-15 09:21 UTC, dj-34 requested changes

2023-10-15 09:21 UTC, dj-34 commented on modular_ss220/outfits/_outfits.dm
> +	. = ..()
Придется :xylipizdish: почистить :xylipizdish: за тебя :xylipizdish:
```suggestion
/datum/modpack/outfits
	name = "Outfits"
	desc = "Аутфиты для админ спавна."
	author = "Grombila"
```

2023-10-15 11:00 UTC, Furrior commented
![изображение](https://github.com/ss220club/Paradise-SS220/assets/68264134/e9b167ef-d6d8-4cc5-91f2-71904aab9398)

2023-10-15 12:05 UTC, Aylong220 commented
> ![изображение](https://user-images.githubusercontent.com/68264134/275321177-e9b167ef-d6d8-4cc5-91f2-71904aab9398.png)

О бля, а мы и не заметили

2023-10-15 17:56 UTC, Furrior commented
Заодно рш12 добавь в аутфит сссп

2023-10-15 19:49 UTC, Fullonibus commented
переделаю на новую ветку

2023-10-15 19:49 UTC, closed without merging