Tweak: TTS core actualization
ss220club/Paradise-SS220 pull request #437
Opened 2023-10-15 11:47 UTC by dj-34

## Что этот PR делает
Актуализирует кор ТТСа в соответствии с коммитами
https://github.com/ss220-space/Paradise/commits?author=Bizzonium

## Почему это хорошо для игры
Хорошо для отладки и, возможно, работы ТТС
P.S. Я не заметил что tts_rps_limit на что-то влияет, ведь Силеро насколько я помню ограничивает возможность использования ТТС до 5 запросов в секунду, соответственно это вряд ли даёт хоть что-то. Вернул значение к тем, которые использует Азиз.

## Изображения изменений

## Тестирование
Нет возможности

## Changelog

:cl:
tweak: Изменения ТТС
/:cl:

2023-10-15 12:05 UTC, dj-34 commented
погодите, у нас реально кэшировалось "Да", "ДА", "да", "дА"? хуею 🥺

2023-10-15 12:06 UTC, Furrior requested changes

2023-10-15 12:06 UTC, Furrior commented on modular_ss220/text_to_speech/code/providers/silero.dm
> +		req_body["ckey"] = usr.ckey || ""
Зачем?

2023-10-15 12:06 UTC, Furrior commented on modular_ss220/text_to_speech/code/providers/silero.dm
> +
Не будет работать

2023-10-15 12:06 UTC, Furrior commented on modular_ss220/text_to_speech/code/tts_subsystem.dm
> +	return msg.Join("")
Аналогично

2023-10-15 12:06 UTC, Furrior commented on modular_ss220/text_to_speech/code/tts_subsystem.dm
> +	var/hash = rustg_hash_string(RUSTG_HASH_MD5, lowertext(text))
Ну мб, но надо бы еще в кэше тож самое сделать

2023-10-15 12:06 UTC, Furrior commented on modular_ss220/text_to_speech/code/tts_subsystem.dm
> +		message_admins(span_warning("Error connecting to [provider.name] TTS API. Please inform a maintainer or server host."))
Ну такое. Вот что надо - так это добавить чтоб спамило меньше ошибками, если их много становиться. Например, с какой то переодичностью только и просто писало раз в н минут, сколько было ошибок

2023-10-17 21:52 UTC, dj-34 commented on modular_ss220/text_to_speech/code/tts_subsystem.dm
> +		message_admins(span_warning("Error connecting to [provider.name] TTS API. Please inform a maintainer or server host."))
хз как сделать

2023-10-18 18:28 UTC, Furrior requested changes

2023-10-18 18:28 UTC, Furrior commented on modular_ss220/text_to_speech/code/tts_subsystem.dm
> +		message_admins(span_warning("Error connecting to [provider.name] TTS API. Please inform a maintainer or server host."))
Куда статус код ошибки украл?

2023-10-18 19:08 UTC, dj-34 commented
вроде перенес все что работало бы у нас

2023-10-19 16:17 UTC, Furrior commented on modular_ss220/text_to_speech/code/tts_subsystem.dm
> +	output = listener.playsound_local(turf_source, output, volume, S = output, wait = TRUE, channel = channel)
Порядок аргументов не трогай, он правильный был

2023-10-19 16:49 UTC, Furrior approved these changes

2023-10-19 16:49 UTC, merged