портирован мех с ру-пары Executioner (сделано по запросу @benedict5078)
ss220club/Paradise-SS220 pull request #496
Opened 2023-10-19 11:56 UTC by Lime-7

## Что этот PR делает
* Портирует меха Executioner для офф пары
* сделано по запросу @benedict5078

## Почему это хорошо для игры
Новый контент, не знаю почему это должно быть плохо.

## Тестирование

на локалке
## Changelog

:cl:
add: мех Executioner 
imageadd: добавлены спрайты меха Executioner и его способности
/:cl:

2023-10-19 11:58 UTC, dj-34 commented
охуеть, не в модуле

2023-10-19 12:00 UTC, Lime-7 reviewed
ты про что?

2023-10-19 12:01 UTC, larentoun commented
> ты про что?

У нас вся разработка модульная с минимальный внедрением в код оффпары

2023-10-19 12:02 UTC, FlutterSnedDraw commented
> ты про что?

Modular_220 ,там ПРы создаем

2023-10-19 12:04 UTC, larentoun commented
И не наследуйся от дюранда, а то будет две абилки теперь, вместо задуманной одной

2023-10-19 12:05 UTC, Lime-7 reviewed
так, это так и задумано, он на старо паре тоже как дюранд - не баг, а фича...

2023-10-19 12:14 UTC, Lime-7 commented
> И не наследуйся от дюранда, а то будет две абилки теперь, вместо задуманной одной

2023-10-19 12:15 UTC, Lime-7 commented
кхм, не туда нажал

2023-10-19 12:15 UTC, larentoun commented
> так, это так и задумано, он на старо паре тоже как дюранд - не баг, а фича...

А тут делаем красиво. Какие причины наследоваться от дюранда, а не создавать новый тип меха?

2023-10-19 12:16 UTC, Lime-7 commented
> А тут делаем красиво. Какие причины наследоваться от дюранда, а не создавать новый тип меха?

ну раз так будет лучше, то ок - сделаю

2023-10-21 10:40 UTC, Furrior requested changes
Ебать хуйня. Делай нормально. Модульно, слабее и по нашим стандартам

2023-10-21 17:41 UTC, Lime-7 commented
> Ебать хуйня. Делай нормально. Модульно, слабее и по нашим стандартам

Gatto, в этих модулях нефега непонятно... но сделаю

2023-10-21 19:31 UTC, Lime-7 commented
> Ебать хуйня. Делай нормально. Модульно, слабее и по нашим стандартам

сделал что-то. **_помогите! меня не держат в заложниках! я делаю это все по своей воле! прошу засуньте меня в подвал чтобы это было хотя бы логично!!_**

2023-10-21 19:34 UTC, Lime-7 commented
> > Ебать хуйня. Делай нормально. Модульно, слабее и по нашим стандартам
> 
> сделал что-то. **_помогите! меня не держат в заложниках! я делаю это все по своей воле! прошу засуньте меня в подвал чтобы это было хотя бы логично!!_**

я делал это все пока смотрел английский стендап....

2023-10-25 10:29 UTC, Lime-7 commented
ну что могу сказать, ща сделаю пул реквест заново и просто открою новый

2023-10-25 10:29 UTC, closed without merging