Borg Hats
ss220club/Paradise-SS220 pull request #497
Opened 2023-10-19 12:48 UTC by PhantornRU

## Что этот PR делает
На силиконов теперь можно надеть шапки.

Изменения:
- У каждого силикона и модуля имеются свои оффсеты и правила
- Хуманизированные борги могут носить шлема
- Хуманизированные борги с встроенными шляпами - не могут носить шляпы.
- Головной убор надевается в слот головы
- HELP-intent с шляпой в руке - надевает её на силикона.
- GRAB-intent с пустой рукой - снимает с силикона шляпу.
- ГИБ и деконструкт - роняет головной убор
- Смена модуля - изменяет ОФФсет под текущий модуль
- Готовые борги с модулями (синди, дезсквад, дестроеры) сразу имеют нужные оффсеты и правила.
- Дроны могут носить головной убор
- ИИ может носить не-шлемовые головные уборы
- Новые силиконы сразу корректно инициализируются, из-за чего можно создать сразу боргов со шляпами, если то требуется.
- Кувырок силикона снимает с него шляпу.

ПИИ ущемлены и не умеют носить шапки, так как у них имеются разные состояния анимации, а мне лень ими заниматься. 

## Почему это хорошо для игры
Ассистенты и экипаж получают возможности угнетать силиконов, у которых нет ручек снять шляпы.

Портируем нашу возможность надевать на боргов шапки.
Я накодил это кучу лет назад, я и портировал. Уот так уот.

## Изображения изменений

### Разные модули:
![image](https://user-images.githubusercontent.com/41479614/188896565-b8f47a7b-9d65-46f5-aab9-00bd6eb394ef.png)
Скриншот чутка устарел. Коробочные борги во второй колонне были поправлены.

### Написание в чате производимых действий
![image](https://user-images.githubusercontent.com/41479614/188897764-20f0f8b5-6d59-4012-b0c2-6ac91c3cbf5a.png)

## Тестирование
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/f04c4526-c3c2-48b5-a8cf-801668d1ce4a)
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/09f9ad5f-b7ee-4a45-8d03-9b888f9e118d)

## Changelog

:cl:
add: Силиконы могут носить шляпы
add: Обработка шляп, индивидуальные оффсеты для разных модулей боргов, установка шляпы хелп-интентом, снятие шляпы граб-интентом, разбор/гиб сбрасывают шляпу
add: Кувырок силикона снимает с него шляпу
/:cl:

2023-10-19 13:14 UTC, PhantornRU commented
Блять!

2023-10-19 13:15 UTC, larentoun requested changes

2023-10-19 13:15 UTC, larentoun commented on code/modules/mob/living/silicon/robot/robot_examine.dm
> +
Можно попробывать в модуль. Единственное, что в обсерварах шапочка будет после законов, но не так критично.

2023-10-19 13:15 UTC, larentoun commented on modular_ss220/silicon_hats/code/silicon_hats.dm
> +	var/isCentered = FALSE //центрирован ли синтетик. Если нет, то шляпа будет растянута
снейк кейс

2023-10-19 13:15 UTC, larentoun commented on modular_ss220/silicon_hats/code/silicon_hats.dm
> +	var/canBeHatted = FALSE
снейк кейс

2023-10-19 13:15 UTC, larentoun commented on modular_ss220/silicon_hats/code/silicon_hats.dm
> +	var/canWearBlacklistedHats = FALSE
снейк кейс

2023-10-19 13:15 UTC, larentoun commented on modular_ss220/silicon_hats/code/silicon_hats.dm
> +		user.visible_message("<span class='notice'>[user] похлопывает по голове [src].</span>", "<span class='notice'>Вы положили руку на голову [src].</span>")
span, ниже куча их на замену

2023-10-19 13:17 UTC, PhantornRU commented on code/modules/mob/living/silicon/robot/robot_examine.dm
> +
там дальше вывод идет, а весь мессежд инициализируется до этого.

Вставил в место которое я считаю меньше всего будет редачиться в будущем и легче будет отслежить, чем среди всего кода. Не представляю как это сделать модульно и красиво, не вмешиваясь в хардкод вообще никак.

2023-10-19 13:19 UTC, dj-34 commented on modular_ss220/silicon_hats/code/silicon_interactions.dm
> +	var/dat = 	{"<meta charset="UTF-8"><div align='center'><b>Inventory of [name]</b></div><p>"}
```suggestion
	var/dat = {"<meta charset="UTF-8"><div align='center'><b>Inventory of [name]</b></div><p>"}
```

2023-10-19 13:19 UTC, dj-34 commented on modular_ss220/silicon_hats/code/silicon_interactions.dm
> +	if (!canBeHatted)
```suggestion
	if(!canBeHatted)
```

2023-10-19 13:32 UTC, larentoun commented on code/modules/mob/living/silicon/robot/robot_examine.dm
> +
`. += "\nНосит [bicon(inventory_head)] [inventory_head.name].\n"` можно вставить

2023-10-19 13:33 UTC, PhantornRU commented on code/modules/mob/living/silicon/robot/robot_examine.dm
> +
Хммм. Сейчас тогда попробую!

2023-10-21 10:43 UTC, Furrior commented on modular_ss220/silicon_hats/code/silicon_interactions.dm
> +		return 1
1 -> TRUE и тп

2023-10-21 10:53 UTC, PhantornRU commented on modular_ss220/silicon_hats/code/silicon_interactions.dm
> +		return 1
Сделано

2023-10-21 11:07 UTC, Furrior requested changes
Пробелы перед // и норм, вроде

2023-10-21 11:10 UTC, Furrior approved these changes

2023-10-21 11:10 UTC, merged