removes grey's facid immunity
ss220club/Paradise-SS220 pull request #500
Opened 2023-10-19 15:50 UTC by larentoun

## Что этот PR делает

Убирает у греев иммун к facid (дамажная)

## Почему это хорошо для игры

Слишком жирный плюс + удерживает ручки абузерам

## Тестирование

Потыкал в грея пшикалкой

## Changelog

:cl:
tweak: У греев убран иммунитет к Fluorosulfuric Acid
/:cl:

2023-10-19 15:55 UTC, dj-34 reviewed
Перезаписывать весь прок ради одной строки? Звучит как heresy
Засунул бы не модульно и всё

2023-10-19 15:56 UTC, dj-34 commented
> Перезаписывать весь прок ради одной строки? Звучит как heresy Засунул бы не модульно и всё

да и не модульно это делать тоже такое себе, что то хуйня что это xdd

2023-10-19 16:01 UTC, larentoun commented
Есть такое. Но зато не сломается, если перепишут оффы facid. Сломается только у греев jokerge

2023-10-19 16:24 UTC, Furrior requested changes
Ты так переопределив и возвращая ..() удвоишь урон кислотой по хуманам

2023-10-19 16:43 UTC, Furrior commented
Туплю. В лобом случае, тут лучше в кор код, чем так

2023-10-26 21:07 UTC, larentoun commented
Вот это покрывает случай "очень интересных" триторов https://github.com/ss220club/Paradise-SS220/pull/578

2023-10-26 21:07 UTC, closed without merging