Lavaland Necropolis
ss220club/Paradise-SS220 pull request #502
Opened 2023-10-19 18:09 UTC by BR54FF

## Что этот PR делает

Добавление комнат с лутом и мобами в некрополь к легиону.

## Почему это хорошо для игры

Потому что всё хорошее старое должно быть и в новом билде. А ещё дополнительная награда шахтёрам, повергнувших легиона+древнего дрейка.

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/106420737/7c7152dc-27fc-4952-afbc-6e9748320f6c)
![image](https://github.com/ss220club/Paradise-SS220/assets/106420737/2040b54c-842c-4688-8e42-a32f2f76f8bd)

## Тестирование
на локалочке всё отлично, зона запрета телепорта даже работает... частично.

## Changelog

:cl:BR54FF
add: Комнаты в некрополь со старопары.
/:cl:

2023-10-19 21:05 UTC, dj-34 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/85b7c361-a309-4482-be69-223b25215f26)

Ересь, запрещено

2023-10-19 21:12 UTC, Aylong220 commented
Мне конечно по большей части насрать на лаву, но у тебя задета вся карта, плюс как написал диджей, зона отредактирована прямо в карте, а не в коде, ересь. А я говорил так не делать.
В общем зону редактируй только в коде, это вопервых
Почисти изменения зоны в карте, это во вторых
Почисти незатронутые тобой области, это в третьих.
Шоб диффбот показывал только то что лично ты задел, а не вот так...
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/f8ccba41-9083-4403-9db1-82c9659210cf)

2023-10-20 02:28 UTC, BR54FF commented
Чудо свершилось :prayge:

2023-10-20 02:29 UTC, Aylong220 requested changes

2023-10-20 02:29 UTC, Aylong220 commented on code/game/area/areas/mining_areas.dm
> +/area/lavaland/surface/outdoors/legion
В модуль. maps220

2023-10-20 02:36 UTC, BR54FF commented on code/game/area/areas/mining_areas.dm
> +/area/lavaland/surface/outdoors/legion
перенёс вроде

2023-10-20 02:44 UTC, Aylong220 commented on code/game/area/areas/mining_areas.dm
> +
Строчку убери. И добавь её в модуле в конце.

2023-10-20 02:51 UTC, BR54FF commented on code/game/area/areas/mining_areas.dm
> +
+, теперь тест не ругается

2023-10-20 02:52 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/away.dm
> +	tele_proof = 1
Ах, да.
Вместо 0/1 - FALSE/TRUE

2023-10-20 04:15 UTC, Aylong220 approved these changes

2023-10-20 17:54 UTC, dj-34 approved these changes
Вроде ок

2023-10-21 10:41 UTC, merged