TWEAK: Exosuit paintkits
ss220club/Paradise-SS220 pull request #517
Opened 2023-10-21 15:41 UTC by ErdGinalD

блять работай мудила
## Что этот PR делает

## Почему это хорошо для игры

## Изображения изменений

## Тестирование

## Changelog

:cl:
add: Что-то добавил
del: Что-то удалил
tweak: Поменял что-то по мелочи
fix: Что-то починил
wip: Какие-либо наработки в процессе
soundadd: Добавил новый звук
sounddel: Удалил старый звук
imageadd: Добавил новую картинку
imagedel: Удалил старую картинку
spellcheck: Исправил опечатку
experiment: Добавил эксперементальную функцию
/:cl:

2023-10-21 16:32 UTC, Furrior requested changes

2023-10-21 16:32 UTC, Furrior commented on modular_ss220/mecha_skins/code/fabricator_design.dm
> +	categories = list(
```suggestion
	categories |= "Exosuit Paintkits"
```

2023-10-21 16:32 UTC, Furrior commented on modular_ss220/mecha_skins/code/fabricator_design.dm
> +//Paintkits
```suggestion
// Paintkits
```

2023-10-21 16:32 UTC, Furrior commented on modular_ss220/mecha_skins/code/paintkit_install.dm
> +	icon = 'modular_ss220/mecha_skins/code/mecha.dmi'
Перенеси лучше в каждый врекадж

2023-10-21 16:32 UTC, Furrior commented on modular_ss220/mecha_skins/code/paintkit_install.dm
> +	icon = 'modular_ss220/mecha_skins/code/mecha.dmi'
Лучше при покраске меняй иконку

2023-10-21 16:58 UTC, ErdGinalD commented on modular_ss220/mecha_skins/code/fabricator_design.dm
> +	categories = list(
Стоп, так ведь смысл не просто запихнуть категорию, а в конкретное место в фабрикаторе. Скины нахер не нужны первой строчкой

2023-10-21 16:58 UTC, ErdGinalD commented on modular_ss220/mecha_skins/code/paintkit_install.dm
> +	icon = 'modular_ss220/mecha_skins/code/mecha.dmi'
понял, щас будет

2023-10-21 16:58 UTC, ErdGinalD commented on modular_ss220/mecha_skins/code/paintkit_install.dm
> +	icon = 'modular_ss220/mecha_skins/code/mecha.dmi'
ща будет

2023-10-22 15:48 UTC, Furrior approved these changes

2023-10-22 15:48 UTC, merged