New handgun Beretta M9
ss220club/Paradise-SS220 pull request #518
Opened 2023-10-21 16:08 UTC by TakeItEasyiloveyou

## Что этот PR делает
Добавляет новый пистолет Beretta M9 в игру.

## Почему это хорошо для игры
У службы безопасности появится возможность заказать неплохое оружие для борьбы с антагонистами. В карго можно заказать ящик с двумя пистолетами "Beretta M9" и ящики с боеприпасами для них. Летальные и другие виды боеприпасов можно создать в протолате РНД.

## Тестирование
Зашёл в игру, пострелял, ещё раз пострелял, умер, все работает.

## Изображения изменений
![2023-10-21_18-38-11](https://github.com/ss220club/Paradise-SS220/assets/134269426/ac6ce971-8561-462c-a354-d93f9e9ecb25)

## Changelog

:cl:
add: Добавлен новый пистолет Беретта М9. Временно добавлены ящики с патронами в карго. Добавлена возможность создать коробки с боеприпасами в РНД
/:cl:

2023-10-21 16:26 UTC, ErdGinalD commented
Давай еще нолик в цену всего, распечатка совсем бесплатная получается таким макаром.

2023-10-21 16:49 UTC, TakeItEasyiloveyou commented
Готово

2023-10-21 17:01 UTC, Furrior requested changes
И патроны переименуй получше

2023-10-21 17:01 UTC, Furrior commented on modular_ss220/beretta/code/weapons.dm
> +	armour_penetration_flat = 25
Не многовато?

2023-10-21 17:02 UTC, TakeItEasyiloveyou commented on modular_ss220/beretta/code/weapons.dm
> +	actions_types = list()
Что именно? Звук, глушитель или магазин?

2023-10-21 17:03 UTC, larentoun requested changes
В целом, осталось только по мелочи править. Цены в протолате поставь такие же, как и на WT. Я позже везде изменю то, как меняются патроны, ПРчик есть, надо просто модульно мне его сделать.

2023-10-21 17:03 UTC, larentoun commented on modular_ss220/beretta/code/weapons.dm
> +	return
Здесь просто меняется `icon_state`, в таких проках. Оставь только строку 16

2023-10-21 17:03 UTC, larentoun commented on modular_ss220/beretta/code/weapons.dm
> +	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
```suggestion
	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
```

2023-10-21 17:03 UTC, larentoun commented on modular_ss220/beretta/code/weapons.dm
> +	return
```suggestion
	icon_state = "[initial(icon_state)][chambered ? "" : "-e"]"
```

2023-10-21 17:03 UTC, larentoun commented on modular_ss220/beretta/code/weapons.dm
> +	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
```suggestion
	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
```

2023-10-21 17:03 UTC, larentoun commented on modular_ss220/beretta/code/weapons.dm
> +	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
```suggestion
	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
```

2023-10-21 17:03 UTC, larentoun commented on modular_ss220/beretta/code/weapons.dm
> +	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
```suggestion
	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
```

2023-10-21 17:04 UTC, TakeItEasyiloveyou commented on modular_ss220/beretta/_beretta.dme
> +// END_INCLUDE
Я его удалял, он мне снова насрал

2023-10-22 10:05 UTC, TakeItEasyiloveyou commented
вроде готово, могу ещё как-то оптимизировать?

2023-10-22 10:45 UTC, Furrior requested changes
И наверное, это все бы в пак с другим огнестрелом впихнуть

2023-10-22 10:45 UTC, Furrior commented on modular_ss220/beretta/code/beretta.dm
> +	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
Для этого уже есть функционал. Надо просто вар, название которого я не помню, задать на 2 и это будет само делаться

2023-10-22 10:45 UTC, Furrior commented on modular_ss220/beretta/code/beretta.dm
> +/obj/item/ammo_box/magazine/beretta/
```suggestion
/obj/item/ammo_box/magazine/beretta
```

2023-10-22 10:45 UTC, Furrior commented on modular_ss220/beretta/code/beretta.dm
> +	caliber = "919apmm"
А зачем везде калибр меняешь? Они же одного калибра, по идее, все

2023-10-22 10:46 UTC, TakeItEasyiloveyou commented on modular_ss220/beretta/code/beretta.dm
> +	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
Ну я пока так оставлю, я ещё не особо опытный... А насчет пака с другим огнестрелом, мне просто в папку к ревикам пихнуть?

2023-10-22 10:47 UTC, TakeItEasyiloveyou commented on modular_ss220/beretta/code/beretta.dm
> +	caliber = "919apmm"
Калибр нужен, чтобы не могли другие патроны впихнуть. Если оставлю дефолт, то по идее 10мм будут лететь в магазины

2023-10-22 12:26 UTC, larentoun commented
> И наверное, это все бы в пак с другим огнестрелом впихнуть

А если захотим отключить, то как именно?

2023-10-22 12:28 UTC, larentoun requested changes
Идеально было бы, кстати, разделить этот один большой .dm файл на несколько разных. В одном карго, в другом дизайны, в другом патроны и тд

2023-10-22 12:28 UTC, larentoun commented on modular_ss220/beretta/_beretta.dme
> +#define FILE_DIR .
Последняя единица мусора

2023-10-22 12:28 UTC, larentoun commented on modular_ss220/beretta/code/beretta.dm
> +
лишняя строка, так же исправль везде ниже

2023-10-22 12:28 UTC, larentoun commented on modular_ss220/beretta/code/beretta.dm
> +
Погоди, почему ты меняешь это у всех `pistol`, а не только у `beretta`?

2023-10-22 13:21 UTC, TakeItEasyiloveyou commented on modular_ss220/beretta/code/beretta.dm
> +
виноват, забыл дописать беретту или удалил её когда-то , когда менял патроны

2023-10-22 15:47 UTC, TakeItEasyiloveyou commented
Так мне отдельным модулем делать или к другим стволам кидать?

2023-10-22 18:05 UTC, closed without merging