add: Italian moustache
ss220club/Paradise-SS220 pull request #525
Opened 2023-10-21 18:40 UTC by Legendaxe

## Что этот PR делает
Добавлянто итальяно уситто

## Почему это хорошо для игры

Ноу комменто

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/102746941/95cc0c2f-8024-43fd-af46-8265ae4b40c5)

## Тестирование
Веритто на словито.

## Changelog

:cl:
add: Мамма-мия, девелоперито Дон-Джейо и Ащиа Лежендария портировали итальянно уситто
/:cl:

2023-10-21 18:41 UTC, dj-34 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/2c2d23ca-e6f9-4224-a81c-bb971d9c2466)
Чейнджлог почисти

2023-10-21 18:43 UTC, Legendaxe commented
> ![image](https://user-images.githubusercontent.com/20109643/277128035-2c2d23ca-e6f9-4224-a81c-bb971d9c2466.png) Чейнджлог почисти

Там сказано что бы указать имя автора нужно написать его справа от первого :cl:, походу не работает

2023-10-21 18:46 UTC, dj-34 requested changes
Можешь еще в лодаут повару добавить в слот маски?

2023-10-21 18:46 UTC, dj-34 commented on modular_ss220/_signals220/code/signals_mob/signals_mob_living.dm
> +	SEND_SIGNAL(src, COMSIG_MOB_SAY, args)
А это ничего не сломает?

2023-10-21 18:46 UTC, dj-34 commented on strings/italian_replacement.json
> +        "кто же": "кто же",
?

2023-10-21 18:46 UTC, dj-34 commented on strings/italian_replacement.json
> +        "чей же": "чей же",
?

2023-10-21 18:46 UTC, dj-34 commented on strings/italian_replacement.json
> +        "спагетти": "СПАГЕТТ",
?

2023-10-21 18:50 UTC, Aylong220 commented
> > ![image](https://user-images.githubusercontent.com/20109643/277128035-2c2d23ca-e6f9-4224-a81c-bb971d9c2466.png) Чейнджлог почисти
> 
> Там сказано что бы указать имя автора нужно написать его справа от первого :cl:, походу не работает

Работает же

2023-10-21 18:53 UTC, Legendaxe commented on strings/italian_replacement.json
> +        "спагетти": "СПАГЕТТ",
![image](https://github.com/ss220club/Paradise-SS220/assets/102746941/12e2434d-adfb-44aa-ad33-5034f7a8b6e8)
Забыл тебя пингануть когда кидал это в разраб чат, а потом еще и убрать забыл, джейсон я вообще не трогал - он с твоей ветки
![image](https://github.com/ss220club/Paradise-SS220/assets/102746941/99617a0a-ad28-40cc-8591-a410cd4bfe3a)

2023-10-21 18:55 UTC, Legendaxe commented on modular_ss220/_signals220/code/signals_mob/signals_mob_living.dm
> +	SEND_SIGNAL(src, COMSIG_MOB_SAY, args)
оно делает все изменения до родительских проков, так что не должно, к тому же фурриор сказал что норм

2023-10-21 19:19 UTC, Legendaxe commented
> Можешь еще в лодаут повару добавить в слот маски?

Ты его уже туда добавил в файле с усами, мб не очень красиво, но не вижу смысла создавать отдельный файл

2023-10-21 19:36 UTC, dj-34 commented
> > Можешь еще в лодаут повару добавить в слот маски?
> 
> Ты его уже туда добавил в файле с усами, мб не очень красиво, но не вижу смысла создавать отдельный файл

а, я и забыл совсем

2023-10-21 19:38 UTC, dj-34 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/927d6737-eb91-425e-b20e-e6d1e52ecde3)

2023-10-21 19:41 UTC, Legendaxe commented
> ![image](https://user-images.githubusercontent.com/20109643/277130347-927d6737-eb91-425e-b20e-e6d1e52ecde3.png)

Убрал лишнюю запятую минуту назад

2023-10-21 20:10 UTC, Furrior approved these changes

2023-10-21 20:11 UTC, Furrior approved these changes

2023-10-21 20:11 UTC, merged

2023-10-21 23:20 UTC, LearIlGatto commented
Чебуреки когда можно будет готовить?

2023-10-22 11:12 UTC, Legendaxe commented
> Чебуреки когда можно будет готовить?

Могу подумать только над добавлением равиоли