add: credits sound mixer
ss220club/Paradise-SS220 pull request #551
Opened 2023-10-23 07:32 UTC by Legendaxe

## Что этот PR делает
Добавляем настройку громкости синематиков

## Почему это хорошо для игры
Об этом просили игроки

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/102746941/ad09e6b5-0006-43c8-aa14-423712485890)

## Тестирование

Проверил на локалке, все работает
## Changelog

:cl:
add: Добавлен канал синематика в микшер громкости
/:cl:

2023-10-23 08:05 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/bec170e7-8122-45b9-8671-3e9304deb144)
Не добавил канал

2023-10-23 08:23 UTC, Legendaxe commented
> ![image](https://user-images.githubusercontent.com/69762909/277268924-bec170e7-8122-45b9-8671-3e9304deb144.png) Не добавил канал

Да вот вроде как сказано держать там самый низкий доступный канал, там 1010, канал который я добавил тоже 1010

2023-10-23 08:24 UTC, Aylong220 commented
> > ![image](https://user-images.githubusercontent.com/69762909/277268924-bec170e7-8122-45b9-8671-3e9304deb144.png) Не добавил канал
> 
> Да вот вроде как сказано держать там самый низкий доступный канал, там 1010, канал который я добавил тоже 1010

Один дополнительный должен быть

2023-10-24 13:50 UTC, Furrior requested changes

2023-10-24 13:50 UTC, Furrior commented on modular_ss220/cinematics/code/~undefs.dm
> +#undef CHANNEL_CINEMATIC
Не надо андефайнить то, что ты задефайнил не модульно

2023-10-24 15:51 UTC, Legendaxe commented on modular_ss220/cinematics/code/~undefs.dm
> +#undef CHANNEL_CINEMATIC
![image](https://github.com/ss220club/Paradise-SS220/assets/102746941/19f6672d-0809-4ab3-9598-2e77e1d40f8f)
По микшеру я копипастил с нашего ПРа с ттсом, щас удалю

2023-10-26 10:15 UTC, Furrior approved these changes

2023-10-27 10:29 UTC, merged