New handgun Beretta M9
ss220club/Paradise-SS220 pull request #552
Opened 2023-10-23 08:48 UTC by TakeItEasyiloveyou

## Что этот PR делает

Добавляет новый пистолет Beretta M9 в игру.

## Почему это хорошо для игры

У службы безопасности появится возможность заказать неплохое оружие для борьбы с антагонистами. В карго можно заказать ящик с двумя пистолетами "Beretta M9" и ящики с боеприпасами для них. Летальные и другие виды боеприпасов можно создать в протолате РНД.

## Изображения изменений

![277118313-ac6ce971-8561-462c-a354-d93f9e9ecb25](https://github.com/ss220club/Paradise-SS220/assets/134269426/c7e37eaf-76ec-4435-9d69-d64cc4e342f3)

## Тестирование

Зашёл в игру, пострелял, ещё раз пострелял, умер, все работает.

## Changelog

:cl:

add: Добавлен новый пистолет Беретта М9. Временно добавлены ящики с патронами в карго. Добавлена возможность создать коробки с боеприпасами в РНД

/:cl:

2023-10-24 14:03 UTC, Furrior requested changes

2023-10-24 14:03 UTC, Furrior commented on modular_ss220/objects/code/weapons.dm
> +	caliber = "919mmr"
Все еще стоит вопрос, почему калибры разные в пределах патрон для одной пушки, если это все один калибр должен быть? Глянь те же 9мм, там везде один калибр

2023-10-24 14:03 UTC, Furrior commented on modular_ss220/objects/code/weapons.dm
> +	icon_state = "[base_icon_state]-[round(ammo_count(),2)]"
```suggestion
/obj/item/ammo_box/magazine/beretta
	name = "beretta rubber 9x19mm magazine"
	icon = 'modular_ss220/objects/icons/ammo.dmi'
	icon_state = "berettar" // скопировать спрайт -10 без приписки
	multi_sprite_step = 2
	ammo_type = /obj/item/ammo_casing/beretta/mmrub919
	max_ammo = 10
	caliber = "919mmr"
```

2023-10-24 14:28 UTC, TakeItEasyiloveyou commented on modular_ss220/objects/code/weapons.dm
> +	caliber = "919mmr"
но ладно, я поменяю калибр под 919mm

2023-10-24 15:33 UTC, TakeItEasyiloveyou commented
Вроде готово, но так и не понял хули у меня пистолет то невидимый, то отображается нормально

2023-10-24 16:44 UTC, TakeItEasyiloveyou commented
Вот теперь все готово

2023-10-25 15:21 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +	req_tech = list("combat" = 3, "materials" = 2, "bluespace" = 3)
Поставь блуспейс хотя бы на 6-7, и комбат 6-7, по вкусу

2023-10-25 15:22 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +	materials = list(MAT_METAL = 8000, MAT_SILVER = 600, MAT_BLUESPACE = 5000)
А че так много, поставь 1000 блуспейса на коробку

2023-10-25 15:23 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +	req_tech = list("combat" = 3, "materials" = 2, "bluespace" = 3)
Если так считаешь, делай

2023-10-26 11:50 UTC, TakeItEasyiloveyou commented
Опять все пошло по пизде, перезалью.

2023-10-26 11:50 UTC, closed without merging