Feat: DBs can be holstered
ss220club/Paradise-SS220 pull request #554
Opened 2023-10-23 11:11 UTC by Yata9arasu

## Что этот PR делает
Добавляет возможность убрать в кобуру обрез двустволки и самострела

## Почему это хорошо для игры
Бафф бармена миноров и ассистух

## Изображения изменений
![донхтру3](https://github.com/ss220club/Paradise-SS220/assets/108077473/a4ab0007-4855-4e9d-825a-d3f5bedb94c5)

## Тестирование
Протестировано и работает как часы

## Changelog
:cl:
add: Добавлена возможность прятать sawn-off double-barreled shotgun и sawn-off improvised shotgun в кобуру
/:cl:

2023-10-25 04:18 UTC, Yata9arasu commented
> Код починишь, тогда и поговорим

Дело сделано дядя фуриор 👀

2023-10-26 11:01 UTC, Furrior requested changes
Я бы в баланс это запихнул

2023-10-26 11:26 UTC, Yata9arasu commented
> Я бы в баланс это запихнул

Дело сделано
![image](https://github.com/ss220club/Paradise-SS220/assets/108077473/ab37dd7a-3ffc-49f2-87a1-8c76daeb1d26)

2023-10-29 13:05 UTC, PhantornRU commented on modular_ss220/balance/_balance.dm
> +	author = "dj-34, larentoun, Yata9arasu, Aylong220, TakeItEasyiloveyou"
Автор один, а добавлено 3

2023-10-29 13:08 UTC, Aylong220 commented on modular_ss220/balance/_balance.dm
> +	author = "dj-34, larentoun, Yata9arasu, Aylong220, TakeItEasyiloveyou"
А я тут какого вообще

2023-10-31 02:33 UTC, Yata9arasu commented on modular_ss220/balance/_balance.dm
> +	author = "dj-34, larentoun, Yata9arasu, Aylong220, TakeItEasyiloveyou"
> Автор один, а добавлено 3

Вообще по факту там все кто мне конкретно помог с написанием кода, но хорошо. Убираю.

2023-11-02 14:31 UTC, merged