Fix: gate_lizard carboard box
ss220club/Paradise-SS220 pull request #559
Opened 2023-10-23 20:46 UTC by konushi

## Что этот PR делает

Картонная коробка больше не позволяет гулять по воде. 

## Почему это хорошо для игры

Фиксим за собой.

## Изображения изменений

## Тестирование
Локалка, работает.

## Changelog

:cl:
fix: В гейте gate_lizard теперь нельзя гулять в коробке по воде. 
/:cl:

2023-10-24 13:55 UTC, Furrior requested changes

2023-10-24 13:55 UTC, Furrior commented on modular_ss220/maps220/code/floors.dm
>  /turf/simulated/floor/beach/away/water/deep/dense_canpass/CanPass (atom/movable/mover, border_dir)
```suggestion
/turf/simulated/floor/beach/away/water/deep/dense_canpass/CanPass(atom/movable/mover, border_dir)
```

2023-10-24 13:55 UTC, Furrior commented on modular_ss220/maps220/code/floors.dm
> +	if(isliving(mover) || ismecha(mover) || istype(mover, /obj/structure/closet/cardboard))
```suggestion
	if(mover.density || isliving(mover))
```
Более общие случаи рассматриваем, чтоб не плодить сюда всякое. Ливинг тут на случай лежачего хумана оставил

2023-10-24 15:06 UTC, konushi commented
диффы странные, убрал только проводку и смес, все работает, trust me

2023-10-26 00:16 UTC, dj-34 commented on modular_ss220/maps220/code/floors.dm
>  	.=..()
```suggestion
	. = ..()
```

2023-10-27 10:32 UTC, Furrior approved these changes

2023-10-27 10:32 UTC, merged