Feat: Centcom overhaul
ss220club/Paradise-SS220 pull request #563
Opened 2023-10-24 09:32 UTC by dj-34

## Что этот PR делает
1. Глобальные улучшения:
 - Добавляет статуи основных карт
 - Исправляет некоторый визуал
 - Четкое деление на зоны/отделы
 
2. Админская зона ЦК:
 - Отделение ОБРа от остальной части
 - Опциональный телепорт у ОБР/Дедсквада (плиз донт абьюз)
 - Зал Верховного суда
 - Офис Верховного судьи/Капитана флота НТ
 - Крио
 - Туалеты и душевая
 - Лазарет
 - Сбшная
 - Библиотека с фонтанчиком
 - Добавил новое лого НТ в оружейную
 - Добавил недостающие штампы
 - Мелкие исправления и улушчения

## Почему это хорошо для игры
Больше опций для РП и администрирования

## Изображения изменений
![pepepopocheck](https://github.com/ss220club/Paradise-SS220/assets/20109643/98413d9b-2542-415c-bafa-efc73259798a)
![2023-10-24 13 12 54](https://github.com/ss220club/Paradise-SS220/assets/20109643/9a1cc810-7ad1-4230-8303-1a93284507f8)

## Тестирование
Побегал, понажимал кнопки

## Changelog

:cl:
tweak: Обновление ЦК (подробнее читать на Гитхабе)
/:cl:

2023-10-24 13:57 UTC, Furrior commented
Честно, мне не нравится. Выглядит как попытки просто вернуть не то что бы рабочие вещи с парашизы

2023-10-24 22:18 UTC, Aylong220 requested changes
Насколько я знаю, капсула клонирования должна быть в упор к компу
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/89439002-0946-46bb-b533-5c93c5ea9408)
+, я конечно не одобряю насирание кучей коробок в одно место, шоб без ПКМ никак, но да похуй, ЦК же.

Может в глаза долблюсь, но мне кажется ты забыл бейзтурф хелперы поставить
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/0fe60199-c90d-4c91-a721-b629d281430f)

Бумажка уволить клоуна удалена потому что клоун уже в космосе? xdd

Добавь тут дополнительный слов камня, а то странно выглядит одинарная скала.

Уберёшь ещё пожалуйста initialized со всего говна на карте?

2023-10-24 22:20 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/4d24d9d7-95cf-48ae-91a3-62bc799cece8)

2023-10-24 22:23 UTC, dj-34 commented
> ![image](https://user-images.githubusercontent.com/69762909/277818443-4d24d9d7-95cf-48ae-91a3-62bc799cece8.png)

так шаттловый свет же

2023-10-24 22:27 UTC, Aylong220 commented
> > ![image](https://user-images.githubusercontent.com/69762909/277818443-4d24d9d7-95cf-48ae-91a3-62bc799cece8.png)
> 
> так шаттловый свет же

А да? Похуй тогда Clueless

2023-10-25 02:37 UTC, Aylong220 approved these changes
А где полосочка камушков? xdd
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/c471d44d-43ec-430f-a9b9-d754fe84d4d9)

2023-10-27 12:01 UTC, Aylong220 approved these changes

2023-10-27 12:45 UTC, merged