tweak: Some toy weapons can be added to holster.
ss220club/Paradise-SS220 pull request #566
Opened 2023-10-24 12:45 UTC by TakeItEasyiloveyou

## Что этот PR делает
Заливаю за BR54FF: Доедаю за Ятой: Теперь от поясной кобуры, лежащей на коробке в старой детективской, есть толк, и в неё можно сунуть cap gun, находящийся в той же комнате. Ещё энерго арбалетик теперь можно совать в обычный холстер, как и игрушечные пистолеты(стреляющие дротиками).

## Почему это хорошо для игры
Больше толка от никому ненужного предмета в техах. Больше функционала обычному холстеру.

## Изображения изменений
Верьте мне.

## Тестирование
Локалка ис воркинг

## Changelog
🆑
add: Возможность сунуть в поясной холстер Cap Gun. 
add: Возможность сунуть в холстер энерго арбалетик. 
add: Возможность сунуть в холстер пенные пистолеты. 
/🆑

2023-10-24 13:58 UTC, Furrior commented
У вас файлы незаинклюжены

2023-10-24 14:05 UTC, Furrior commented
![изображение](https://github.com/ss220club/Paradise-SS220/assets/68264134/7630db1e-1a51-449a-ab45-3304a356c89d)
Из крайности в крайность

2023-10-24 15:31 UTC, BR54FF commented
Это всё домовой насрал в код, мы не причём Pepechill

2023-10-24 15:32 UTC, TakeItEasyiloveyou commented
Усе, убрал срач ДМа в код

2023-10-24 22:22 UTC, Aylong220 commented on modular_ss220/modular_ss220.dme
> +// END_INCLUDE
Удали какули

2023-10-25 11:54 UTC, TakeItEasyiloveyou commented on modular_ss220/modular_ss220.dme
> +// END_INCLUDE
"какули" удалил

2023-10-26 11:02 UTC, Furrior requested changes

2023-10-26 11:02 UTC, Furrior commented on modular_ss220/holsters/code/holsters.dm
> +/obj/item/gun/energy/kinetic_accelerator/crossbow
Арбалет и так сильный

2023-10-26 11:02 UTC, Furrior commented on modular_ss220/holsters/code/holsters.dm
> +	can_hold = list(
Добавь через инициализацию

2023-10-26 11:03 UTC, TakeItEasyiloveyou commented on modular_ss220/holsters/code/holsters.dm
> +/obj/item/gun/energy/kinetic_accelerator/crossbow
Блять, как он вообще туда попал, я его вырезал

2023-10-28 06:57 UTC, closed without merging