add: halloween credits
ss220club/Paradise-SS220 pull request #576
Opened 2023-10-26 13:37 UTC by Legendaxe

## Что этот PR делает
По мелочи пофиксил некоторые мелочи титров.
Добавил **крупный** хэллоуинский апдейт для титров.

## Почему это хорошо для игры
Хэллоуинские титры под хэллоуин это весело

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/102746941/d010c8fd-27c0-4636-b6ed-c2a8d2a1cbce)

## Тестирование

На локалочке проверил все что мог
## Changelog

:cl:
add: Хэллоуинские титры
add: Теперь донатеров показывает в титрах(при условии что донатер не админ)
fix: Починил подтягивание стримеров из бд
soundadd: Добавил хэллоунский саундтрек
imageadd: Добавил хэллоуинский задник для титров
/:cl:

2023-10-26 14:32 UTC, Gaxeer commented
Я тыква

2023-10-26 14:36 UTC, Gaxeer requested changes

2023-10-26 14:36 UTC, Gaxeer commented on modular_ss220/cinematics/code/cinematics/credits.dm
> +		icon_state = "halloween"
Родитель не должен думать о своих потомках 🤓

2023-10-27 10:30 UTC, Furrior approved these changes

2023-10-27 10:30 UTC, Furrior commented
Решай конфликты

2023-10-27 10:50 UTC, Legendaxe commented
> Решай конфликты

готово

2023-10-27 12:44 UTC, merged