DELETE: Gategun MK2
ss220club/Paradise-SS220 pull request #597
Opened 2023-11-01 09:24 UTC by ErdGinalD

## Что этот PR делает

Удаляет гейтган МК2 с его абсолютно сломанной механикой бесконечного боезапаса.

Удаляет емаг гейтгана при ЭМИ воздействии на него.

## Почему это хорошо для игры

Я не хочу скатить билд в парашизу, где можно печатать полновесный летал в рнд

## Изображения изменений

## Тестирование
Удалил МК2 пушку из анналов истории. Тесты не проводились, но в таком ПРе они и не нужны.

## Changelog

del: Удалил вторую модификацию гейтгана, оставив первую.
del: Удалил возможность емагнуть гейтган с помощью ЭМИ заряда.

2023-11-01 10:59 UTC, PhantornRU requested changes

2023-11-01 10:59 UTC, PhantornRU commented on modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
> -/obj/item/gun/energy/laser/awaymission_aeg/onTransitZ(old_z, new_z)
Ну и зачем ты удалил onTransitZ(old_z, new_z)?

2023-11-01 10:59 UTC, PhantornRU commented
И описание исправь.
И линтер глянь.
И помягче, не в сельском гитхабе.

2023-11-01 13:10 UTC, larentoun requested changes
Вот еще вприбавок

2023-11-01 13:10 UTC, larentoun commented on modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
> +	var/msg_recharge_user = span_notice("Вы со всей силы давите на рычаг зарядки [name], пытаясь зарядить её...")
Обычно используют [src], а не [name]

2023-11-01 13:10 UTC, larentoun commented on modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
> +	if(!do_after_once(user, 3 SECONDS, target = src))
Добавь прогресс бар

2023-11-01 13:10 UTC, larentoun commented on modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
убери лишнюю строку

2023-11-01 17:06 UTC, ErdGinalD commented on modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
> -/obj/item/gun/energy/laser/awaymission_aeg/onTransitZ(old_z, new_z)
бля, точно.

2023-11-01 17:08 UTC, ErdGinalD commented on modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
> +	var/msg_recharge_user = span_notice("Вы со всей силы давите на рычаг зарядки [name], пытаясь зарядить её...")
ладно, щас исправлю тогда ради красоты.

2023-11-01 17:10 UTC, ErdGinalD commented on modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
> +	if(!do_after_once(user, 3 SECONDS, target = src))
Он уже. Прогресс бар и вызывается !do_after, ровно как и do_after проком.

2023-11-01 17:10 UTC, ErdGinalD commented on modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
Какую? еду?

2023-11-01 17:45 UTC, PhantornRU commented on modular_ss220/awaymission_gun/code/items/awaymission_gun.dm
> -/obj/item/gun/energy/laser/awaymission_aeg/onTransitZ(old_z, new_z)
>Тесты не проводились, но в таком ПРе они и не нужны.

Вот поэтому тесты и нужны. Мелочь удалишь, а потом пол билда не работает xdd

2023-11-02 08:44 UTC, closed without merging

2023-11-02 08:44 UTC, Aylong220 commented
М: