Bounty: New donor item "Vi Jacket'
ss220club/Paradise-SS220 pull request #598
Opened 2023-11-01 16:01 UTC by Yata9arasu

## Что этот PR делает
Добавляет новый донорский предмет "Жакет Ви"

## Почему это хорошо для игры
Ещё одна вещь для тех кто хотят выделиться

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/108077473/1b225060-274b-46cc-b54c-399beed031fe)
![image](https://github.com/ss220club/Paradise-SS220/assets/108077473/7c5a4acc-b38f-4a18-b6ce-70eff9fb8f3d)

## Тестирование
Протестировано

## Changelog
:cl:
add: Добавлен донорский предмет "Куртка Ви"
/:cl:

2023-11-01 16:02 UTC, larentoun commented
Офигеть тут коммитов, конечно xdd

2023-11-01 16:05 UTC, larentoun commented on modular_ss220/clothing/code/suits.dm
> +	flags_inv = HIDEJUMPSUIT
А оно разве должно прятать джампсьюты?

2023-11-01 16:05 UTC, larentoun commented on modular_ss220/clothing/code/suits.dm
> +	min_cold_protection_temperature = FIRE_SUIT_MIN_TEMP_PROTECT
утепленная?

2023-11-01 16:06 UTC, Aylong220 requested changes

2023-11-01 16:06 UTC, Aylong220 commented on modular_ss220/clothing/code/suits.dm
> +	allowed = list(/obj/item/tank/internals/emergency_oxygen)
Ммм, донатная курточка которая позволяет засунуть за спину баллон, класс.
Вообще, как-то дохуя строк, неужто это всё от родителя не наследуется?

2023-11-01 16:06 UTC, Aylong220 commented on modular_ss220/clothing/code/suits.dm
> +	name = "Капюшон жакета"
Имена с маленькой буквы

2023-11-01 16:06 UTC, Aylong220 commented on modular_ss220/clothing/code/suits.dm
> +	name = " жакет Ви."
пробел лишний в имени

2023-11-01 16:06 UTC, larentoun commented on modular_ss220/clothing/code/suits.dm
> +	name = " жакет Ви."
лишний пробел?

2023-11-01 16:06 UTC, larentoun commented on modular_ss220/clothing/code/suits.dm
> +	name = "Капюшон жакета"
Капюшон Ви не лучше?

2023-11-01 16:07 UTC, larentoun commented on modular_ss220/clothing/code/suits.dm
> +	allowed = list(/obj/item/tank/internals/emergency_oxygen)
Очень похоже на зимнюю. И все сьюты носят этот эмердженси балон. Тут это в коде вообще не нужно из-за наследоания

2023-11-01 16:08 UTC, Aylong220 requested changes
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/24bc8735-a339-422b-99cc-ae7b7825a663)
Ты шо, кукурузнулся?

2023-11-01 20:41 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	desc = "Слегка потрёпанный жакет боевой девчушки Ви."
описание в целом кринж
это из киберпука я так понимаю? так там протагонист не обязательно девушка

2023-11-06 12:48 UTC, Aylong220 requested changes

2023-11-06 12:48 UTC, Aylong220 commented on modular_ss220/clothing/code/suits.dm
> +	name = "капюшон Вей"
Ой вэй, V (Ви), если что, не вэй.

2023-11-06 12:48 UTC, Aylong220 commented on modular_ss220/loadout/code/donor.dm
> +	display_name = "Куртка Вей"
Куртка Ви

2023-11-06 12:49 UTC, dj-34 commented on modular_ss220/loadout/code/donor.dm
> +	display_name = "Куртка Вей"
Уже выяснили что Вей, потому что из Аркейна

2023-11-06 12:50 UTC, larentoun commented on modular_ss220/loadout/code/donor.dm
> +	display_name = "Куртка Вей"
Разве не "Вай"?

2023-11-06 12:52 UTC, Aylong220 commented on modular_ss220/loadout/code/donor.dm
> +	display_name = "Куртка Вей"
> Разве не "Вай"?

А, я думал из киберпука xdd

2023-11-06 12:52 UTC, Aylong220 approved these changes

2023-11-06 12:52 UTC, dj-34 commented on modular_ss220/loadout/code/donor.dm
> +	display_name = "Куртка Вей"
тоже сначала так подумал

2023-11-06 12:53 UTC, dj-34 commented on modular_ss220/loadout/code/donor.dm
> +	display_name = "Куртка Вей"
Где нормальное описание-уточнение в ПРе :xylipizdish:

2023-11-07 11:06 UTC, Yata9arasu commented on modular_ss220/clothing/code/suits.dm
> +	desc = "Слегка потрёпанный жакет боевой девчушки Ви."
👌

2023-11-07 11:08 UTC, Yata9arasu commented on modular_ss220/loadout/code/donor.dm
> +	display_name = "Куртка Вей"
👌

2023-11-07 11:13 UTC, merged