Fix: Caves nerfs and fixes
ss220club/Paradise-SS220 pull request #599
Opened 2023-11-01 16:07 UTC by konushi

## Что этот PR делает

Небольшие фиксы карты, симплов и предметов.
Расширена арена с магом, у него самого - добавлен новый тип снаряда. 
Теперь с мага падает аналог камня некроманта с более слабым призывом шкилетов. 
Удалены некоторые перила в лаборатории (ломали ИИшку симплов), окна из укрепленного плазменного стекла заменены на обычные укрепленные. 
Заменил бейзтурф в лаборатории, больше разгрерм при взрыве генератора быть не должно.
Мелкие косметические изменения.

## Почему это хорошо для игры

Подчищаю свои гениальные решения.

## Изображения изменений

## Тестирование
Локалка.

## Changelog

:cl:
fix: Небольшие косметические изменения гейта "Caves". Камень некроманта теперь не дает клейморы на 45 брута, только на 20; количество призываемых камнем шкилетов уменьшено. 
/:cl:

2023-11-03 12:07 UTC, Legendaxe requested changes

2023-11-07 11:01 UTC, dj-34 requested changes

2023-11-07 11:01 UTC, dj-34 commented on modular_ss220/maps220/code/objects.dm
> +	desc = "Маленькая серебряная побрякушка, инкрустированная ярким изумрудом бриллиантовой огранки. На верхушечной площадке камня мелко выгравирован череп ."
```suggestion
	desc = "Маленькая серебряная побрякушка, инкрустированная ярким изумрудом бриллиантовой огранки. На верхушечной площадке камня мелко выгравирован череп."
```

2023-11-07 11:01 UTC, dj-34 commented on modular_ss220/maps220/code/objects.dm
> +	var/randomUndead = "roman"//defualt
```suggestion
	var/randomUndead = "roman" // default
```

2023-11-07 11:01 UTC, dj-34 commented on modular_ss220/maps220/code/objects.dm
> +	check_skeletons() //clean out/refresh the list
```suggestion
	check_skeletons() // clean out/refresh the list
```

2023-11-07 12:28 UTC, Legendaxe approved these changes

2023-11-07 12:28 UTC, merged