Add: NT gygax on Central Comand
ss220club/Paradise-SS220 pull request #664
Opened 2023-11-10 10:52 UTC by Kar4es

## Что этот PR делает
Добавил НТшный гигакс на ЦК.
Прелоады меха для рэд ОБР и дедов.
Характеристики в коде. 

## Почему это хорошо для игры
НТ это НТ, а не синдикат

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/5aac4645-7f62-4215-b0e3-5b19ab2e54f7)

## Тестирование

да.
## Changelog

:cl:
add: Говорят на ЦК появились новые мехи, а те странные чёрно-красные сдали на металлолом.
/:cl:

2023-11-10 10:57 UTC, PhantornRU commented
В игре протестировал?
ДЮРАНДам тоже стоит скин заменить. Как в ГАММА оружейной на ЦК например. Чтобы со станционными не путать.

2023-11-10 10:59 UTC, Kar4es commented
> В игре протестировал? ДЮРАНДам тоже стоит скин заменить. Как в ГАММА оружейной на ЦК например. Чтобы со станционными не путать.

в игре тестил, да. в оружейке там мародеры стоят а не дюры

2023-11-10 10:59 UTC, Kar4es commented
ааа, ты про те что на складе мехов

А я хз какой туда бахнуть. Мародёр для дедов же

2023-11-10 11:01 UTC, dj-34 commented on modular_ss220/mecha_skins/code/mecha_preloaded.dm
> +	ME.attach(src)
а че с отступами

2023-11-10 11:01 UTC, Kar4es commented on modular_ss220/mecha_skins/code/mecha_preloaded.dm
> +	ME.attach(src)
а че не так

2023-11-10 11:02 UTC, dj-34 commented on modular_ss220/mecha_skins/code/mecha_preloaded.dm
> +	desc = "Козырь Nanotrasen при решении проблем, легкий мех окрашенный в победоносные цвета НТ. Если вы видите этот мех, вероятно все проблемы уже решены."
Почему desc в самой жопе, под name его

2023-11-10 11:03 UTC, dj-34 commented on modular_ss220/mecha_skins/code/mecha_preloaded.dm
> +	ME.attach(src)
> а че не так

в самом низу у тебя /obj/... присосался

2023-11-10 11:14 UTC, dj-34 commented on modular_ss220/mecha_skins/code/mecha_preloaded.dm
> +	var/obj/item/mecha_parts/mecha_equipment/ME = new /obj/item/mecha_parts/mecha_equipment/weapon/energy/laser
```suggestion
	var/obj/item/mecha_parts/mecha_equipment/ME = new

/obj/item/mecha_parts/mecha_equipment/weapon/energy/laser
```

2023-11-10 12:42 UTC, dj-34 reviewed
Мне кажется mecha_skins не очень подходящая папка для этого - все таки это не кастомайз.
Предложил бы засунуть в modular_ss220\maps220\code\objects.dm к Роверу, но под коммент Центкома

2023-11-10 13:23 UTC, Kar4es commented
> Мне кажется mecha_skins не очень подходящая папка для этого - все таки это не кастомайз. Предложил бы засунуть в modular_ss220\maps220\code\objects.dm к Роверу, но под коммент Центкома

туда планировалось все мехи с спрайтами добавлять по необходимости. Уверен что хорошая идея?

2023-11-10 15:44 UTC, dj-34 commented
> > Мне кажется mecha_skins не очень подходящая папка для этого - все таки это не кастомайз. Предложил бы засунуть в modular_ss220\maps220\code\objects.dm к Роверу, но под коммент Центкома
> 
> туда планировалось все мехи с спрайтами добавлять по необходимости. Уверен что хорошая идея?

Уверен что хорошей идеей будет не разбрасываться кодом куда попало. Либо Ровер переместить в меха скины, либо НТ Гигакс закинуть к Роверу

2023-11-10 21:40 UTC, dj-34 requested changes

2023-11-11 05:07 UTC, Kar4es commented on modular_ss220/mecha_skins/code/mecha_preloaded.dm
> +/obj/mecha/combat/gygax/nt
ниже

2023-11-11 05:09 UTC, Kar4es commented on modular_ss220/mecha_skins/code/mecha_preloaded.dm
> +	wreckage = /obj/structure/mecha_wreckage/durand/rover
тут не шибко понял 
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/4520df80-c1a9-42e4-b5b1-1ee86b3bf949)

2023-11-11 05:13 UTC, Kar4es commented on modular_ss220/mecha_skins/code/mecha_preloaded.dm
> +	wreckage = /obj/structure/mecha_wreckage/durand/rover
они в коде у меня на 16 и 17 строке

2023-11-11 05:13 UTC, Kar4es commented on modular_ss220/mecha_skins/code/mecha_preloaded.dm
> +	wreckage = /obj/structure/mecha_wreckage/durand/rover
аа блять это ровер

2023-11-11 10:57 UTC, dj-34 approved these changes
Вроде норм

2023-11-12 20:14 UTC, Legendaxe approved these changes

2023-11-12 20:14 UTC, merged