Centcom Tactical Bat
ss220club/Paradise-SS220 pull request #671
Opened 2023-11-10 15:33 UTC by Fullonibus

Возвращает тактическую бейсбольную биту в игру.
## Что этот PR делает

## Почему это хорошо для игры
Ультимативное оружие правосудия вновь будет нести свою службу на благо Нанотрейзен. Бойтесь, колени!

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/38350888/02766729-129c-497f-b34a-c4029f157cbe)

## Тестирование

Функционал проверен в игре: иконки рабочие, куклы не с цк в руки не возьмут, складывается, раскладывается, хоумраны прописывает.
## Changelog

:cl:
add: Тактическая бита центрального командования.
/:cl:

2023-11-10 15:37 UTC, dj-34 commented on modular_ss220/objects/code/weapons.dm
> +
Коммент добавь разделяющий

2023-11-10 15:38 UTC, Fullonibus commented on modular_ss220/objects/code/weapons.dm
> +
типа //melee weapons ?

2023-11-10 15:38 UTC, larentoun reviewed
Такое ощущение, что следовало бы наследоваться от телескопички

2023-11-10 15:38 UTC, dj-34 commented
Линтер поправь

2023-11-10 15:39 UTC, Fullonibus commented
> Такое ощущение, что следовало бы наследоваться от телескопички

тогда бы пришлось прописывать хоумран. А у биты уже он есть

2023-11-10 15:39 UTC, dj-34 commented on modular_ss220/objects/code/weapons.dm
> +
> типа //melee weapons ?

нет, типа "// Название оружия"

2023-11-10 15:41 UTC, larentoun requested changes

2023-11-10 15:41 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +		to_chat(user, "<span class='cultlarge'>\"Это - оружие истинного правосудия. Тебе не дано обуздать его мощь.\"</span>")
Использовать спаны

2023-11-10 15:41 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +		user.Weaken(5)
5 децисекунд? Используй SECONDS, видимо, тут хотел `10 SECONDS`

2023-11-10 15:41 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +		w_class = WEIGHT_CLASS_SMALL
Тоже `initial()` бы

2023-11-10 15:41 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +		slot_flags = SLOT_FLAG_BELT
А это зачем? Не меняется же?

2023-11-10 15:41 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +		to_chat(user, "<span class='userdanger'>Вы активировали [src.name] - время для правосудия!</span>")
Использовать спаны

2023-11-10 15:43 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +/obj/item/melee/baseball_bat/homerun/central_command/attack_self(mob/user)
Не вызывается родитель, оно не готовит `homerun_ready`

2023-11-10 15:44 UTC, larentoun commented
> > Такое ощущение, что следовало бы наследоваться от телескопички
> 
> тогда бы пришлось прописывать хоумран. А у биты уже он есть

У тебя он все равно нету хоумрана, так как не вызываешь родителя. Предлагаю просто наследоваться от телескопички, и при ударе делать взрыв и толкать, если телескопичка открыта

2023-11-11 10:59 UTC, dj-34 approved these changes
вроде норм

2023-11-11 11:55 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +	homerun_ready = 1
Зачем при атаке это выставлять каждый раз? Если хочешь, чтобы оно не выключалось, сделай проверку, что бита вообще включена

2023-11-11 11:55 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +		return
лишний ретурн

2023-11-11 11:56 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +	homerun_able = on
Кстати, зачем эта часть кода вообще нужна? Бита спавниться с `on = FALSE` ведь

2023-11-11 11:58 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +	icon_state = on ? icon_state_on : initial(icon_state)
Эта строка тоже не нужна, так как стейт меняется ниже. А вообще, замени иф-елс на то, что сверху в ините у тебя, одно и тоже так и так.

2023-11-11 14:01 UTC, Fullonibus commented
Убрал ненужный код в инициализации, лишний ретурн, поправил иф-елс блок, добавил проверку в атаке.

2023-11-12 11:02 UTC, larentoun requested changes
Ты в игре точно проверил, что оно работает как бита, а не телескопичка?

И хомраны, и дефлекты, и подготовки к хомрану?

2023-11-12 11:02 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +/obj/item/melee/baseball_bat/homerun/central_command/pickup(mob/living/user)
А вообще, почему это в ините, а не сверху сразу указано?

2023-11-12 13:20 UTC, Fullonibus commented
> Ты в игре точно проверил, что оно работает как бита, а не телескопичка?
> 
> И хомраны, и дефлекты, и подготовки к хомрану?

Хоумраны работают 
![image](https://github.com/ss220club/Paradise-SS220/assets/38350888/b8108f6d-0a3a-4eaf-893c-d81e65bbd7a5)
Зарядку убрал, она на бите ни к чему. Режим дефлекта не дает делать удары, поэтому его не ставил.

2023-11-13 13:02 UTC, larentoun requested changes

2023-11-13 13:02 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +	homerun_able = on
В ините это никчему, оно и так `FALSE` стоит, вообще инит можешь убрать

2023-11-13 13:02 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +		w_class = WEIGHT_CLASS_HUGE //doesnt fit in backpack when its on for balance
Можно коммент убрать, это админ пушка, про какой баланс мы говорим?

2023-11-13 13:02 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +		homerun_ready = TRUE
`homerun_ready` нет смысла выставлять, так как оно всегда включено при атаке, разве не так?

2023-11-13 13:02 UTC, larentoun commented on modular_ss220/objects/code/weapons.dm
> +		homerun_ready = FALSE
тоже самое, что сверху

2023-11-13 13:32 UTC, larentoun approved these changes
Если работает в игре, то сойдет

2023-11-13 22:58 UTC, Gaxeer commented on modular_ss220/objects/code/weapons.dm
> +		homerun_ready = 1
```suggestion
		homerun_ready = TRUE
```

2023-11-13 23:01 UTC, Gaxeer approved these changes
На производительность не повлияет, чуток говнокода в модуле похуй. Как добавили, так и снесем, если надо будет.

2023-11-13 23:02 UTC, merged