[FIX] Разрешаем грипперам медборгов трогать химию.
ss220club/Paradise-SS220 pull request #677
Opened 2023-11-12 02:00 UTC by PhantornRU

## Что этот PR делает

Разрешает трогать бикеры боргам в химии.

## Почему это хорошо для игры

А то бикеры есть, а химии набрать гадости нет.
Люди больше не будут жаловаться.

## Изображения изменений

## Тестирование

![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/54101d0a-b176-430f-9baf-b0b9f06483ca)

## Changelog

:cl:
fix: Медборги могут взаимодействовать с химическим оборудованием
/:cl:

2023-11-12 02:01 UTC, Aylong220 commented
Реализация кринге, тем более что проблема была только с нагревателем, с диспенсером всё ок было

2023-11-12 02:24 UTC, PhantornRU commented
> Реализация кринге, тем более что проблема была только с нагревателем, с диспенсером всё ок было

Я потестил, там оказывается пол химии работало, а пол химии не работало для боргов. Борг может запихнуть в условный гридер бикер, наливать туда что хочет - но не может его оттуда вытащить. И также с остальным.

2023-11-12 08:58 UTC, Gaxeer requested changes
Реализация костыльная.

2023-11-12 08:58 UTC, Gaxeer commented on modular_ss220/silicons/code/items/gripper.dm
> +// т.к. хваталки у него не работала.
Комментарии на русском в коде это кринге

2023-11-12 09:13 UTC, PhantornRU commented on modular_ss220/silicons/code/items/gripper.dm
> +// т.к. хваталки у него не работала.
В модуле, это для внутреннего пользования, не для ОФФов.

2023-11-12 11:47 UTC, PhantornRU commented
@Gaxeer @Aylong220 товарищи CUMтрибьюторы. Шо ж. Хардкод так хардкод. Ибо иной реализации мне в голову не пришло как обойти простейшую и втупую сделанную проверку на робота, кроме как делать временную куклу хумана для обмана проверка и отправлять её в прок KEKW

2023-11-15 07:17 UTC, Gaxeer commented on modular_ss220/silicons/code/items/gripper.dm
> +	return attack_hand(user)
В чем суть этого? Выглядит ну очень странно

2023-11-15 07:33 UTC, PhantornRU commented on modular_ss220/silicons/code/items/gripper.dm
> +	return attack_hand(user)
Открытия машинерии где не было реализована возможность её открытия. 
Хиденпринт - для админов, чтобы знать кто трогал помимо органиков.

2023-11-15 11:54 UTC, Gaxeer approved these changes

2023-11-16 02:28 UTC, PhantornRU commented
@Legendaxe, даем разрешение?

2023-11-16 06:06 UTC, PhantornRU commented
@Aylong220 кстати. По твоему же ревью реализацию в итоге и переделали из переписывание всего прока в это.
Пора боргам дать возможность лапать то что не лапалось из-за отсутствия реализации

2023-11-16 12:16 UTC, Aylong220 submitted a review, later dismissed

2023-11-16 12:19 UTC, Aylong220 requested changes
Меньше строчек затронуто - меньше шанс на проблему

2023-11-16 12:19 UTC, Aylong220 commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +	// SS220 EDIT END
```suggestion
	//if(isrobot(user)) // SS220 EDIT
	// 	return
```

2023-11-16 12:20 UTC, PhantornRU commented on code/modules/reagents/chemistry/machinery/chem_dispenser.dm
> +	// SS220 EDIT END
Разве? Оно ж однофигственно будет смещаться. при добавлениях. Хммм. Надо будет уточнить.

2023-11-21 05:49 UTC, PhantornRU commented on code/modules/reagents/chemistry/machinery/chem_heater.dm
> +	// SS220 EDIT END
```suggestion
	//if(isrobot(user)) //SS220 EDIT
	//	return
```

2023-11-21 06:16 UTC, Aylong220 approved these changes

2023-11-23 08:25 UTC, PhantornRU commented
@Legendaxe заливаем?

2023-11-23 11:15 UTC, Legendaxe approved these changes

2023-11-23 11:15 UTC, merged