FEAT: Роли новичков добавлены в консоль ГП
ss220club/Paradise-SS220 pull request #678
Opened 2023-11-12 11:40 UTC by PhantornRU

## Что этот PR делает

Консоль ГП теперь может навешивать работающую иконку новичковой роли и перекрашивать карту.
Модульность позволяет потенциально работать с этим и в будущем.

## Почему это хорошо для игры

Да. Хорошо. Нужно больше набранных паровозиков кадетиков, а не то что мы сейчас видели, где ГП извращались с названиями. А ведь офицеры видят кадета-не-кадета, высказывают к ним требования как к офицерам и бедные кадетики перегружают свои головы и умирают задохнувшись от поступившей информации! Убережем кадетиков!

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/757820f3-bd7a-4937-b15f-4828c9c25d78)

## Тестирование
Да кому нужны эти тестирования когда есть такие прекрасные скриншоты. КОгда мы уже объединим эти 2 пункта.

Навешиваем роль, проверяем иконку:
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/6dc71b11-f2d3-4e17-9659-24f0413e4886)
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/4590b3d4-4096-40c3-b5bd-68096b43ef93)
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/4351d4ea-9bcd-4850-bec6-6f7bdbe121d2)
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/6e704c8a-e727-4aa6-8d8c-c30146b948a4)
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/61bb6f08-066c-4e08-ab5f-a46d61abec13)

## Changelog

:cl:
tweak: В консоли ГП теперь можно выдавать новичковые роли + перерисовывать их карты.
/:cl:

2023-11-12 20:19 UTC, Legendaxe approved these changes

2023-11-13 07:33 UTC, Gaxeer commented on modular_ss220/jobs/code/cards_ids.dm
> +		if(IDCOMPUTER_SCREEN_TRANSFER) // JOB TRANSFER
switch ради одного кейса не надо  использовать. Просто `if(mode == IDCOMPUTER_SCREEN_TRANSFER)`

2023-11-13 07:36 UTC, Gaxeer commented on modular_ss220/jobs/code/cards_ids.dm
> +					return data
```suggestion
			if(!modify || !scan)
				return data
```

2023-11-13 07:38 UTC, Gaxeer commented on modular_ss220/jobs/code/cards_ids.dm
> +				if(!target_dept)
```suggestion
			if(modify && scan && !target_dept)
```

2023-11-13 07:39 UTC, Gaxeer commented on modular_ss220/jobs/code/cards_ids.dm
> +	. = TRUE
убери

2023-11-13 12:19 UTC, PhantornRU commented on modular_ss220/jobs/code/cards_ids.dm
> +	. = TRUE
Не понял зачем. Эта конструкция везде в ui_act используется.

2023-11-14 13:29 UTC, PhantornRU commented
@Gaxeer повторно пересмотрел. Проблем не обнаружил

2023-11-15 07:06 UTC, Gaxeer commented on modular_ss220/jobs/code/cards_ids.dm
> +			return
return TRUE

2023-11-15 07:07 UTC, Gaxeer commented on modular_ss220/jobs/code/cards_ids.dm
> +			if(skin in skin_list)
в чем суть присваивания глобального списка локальной переменной? Просто
if(skin in GLOB.Jobs_SS220)

2023-11-15 07:13 UTC, Gaxeer requested changes

2023-11-15 07:13 UTC, Gaxeer commented on modular_ss220/jobs/code/cards_ids.dm
> +			return
```suggestion
			var/skin = params["skin_target"]
			if(!skin || !(skin in GLOB.Jobs_SS220))
				return FALSE

			modify.icon_state = skin
			return TRUE
```

2023-11-15 07:13 UTC, Gaxeer commented on modular_ss220/jobs/code/cards_ids.dm
> +			data["card_skins"] |= format_card_skins(GLOB.Jobs_SS220) // + format_card_skins(list("intern", "cadet", "trainee", "student"))
Убери лишние пробелы между переменной и оператором

2023-11-15 07:31 UTC, PhantornRU commented on modular_ss220/jobs/code/cards_ids.dm
> +			data["jobs_security"] 	|= "Security Cadet"
```suggestion
			data["jobs_engineering"] |= "Trainee Engineer"
			data["jobs_medical"] |= "Intern"
			data["jobs_science"] |= "Student Scientist"
			data["jobs_security"] |= "Security Cadet"
```

2023-11-15 11:52 UTC, Gaxeer approved these changes

2023-11-16 02:25 UTC, merged