FEAT: Clumsy Table
ss220club/Paradise-SS220 pull request #679
Opened 2023-11-12 13:23 UTC by PhantornRU

## Что этот PR делает

При залезании на стол, метание на стол мобов, танцевание на столу, бегание по столу - разлетаются предметы находящиеся на нём.

## Почему это хорошо для игры

Дополнительный повод чтобы повар и ученые могли уничтожить клоуна до атомов.
Хватит использовать столы как короткий путь.

## Изображения изменений
https://github.com/ss220-space/Paradise/pull/2353

## Тестирование
Проклятый клоун раскидал все мои 600 фигурок!!!!!
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/00084655-41ba-4388-9806-bd9f89a03683)

## Changelog

:cl:
add: Танцы, швыряние, бегания по столу - раскидывают вещи на нём.
/:cl:

2023-11-12 13:30 UTC, Aylong220 commented
Убери эту фишку у повара и бармена, они залезают на стол гораздо быстрее

2023-11-12 13:31 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/fec296f2-c1d1-4b2d-a65a-16feb77ddd8e)
Э, куда, в отдельном ПРе лучше, прикольная фишка так-то

2023-11-12 13:38 UTC, Gaxeer requested changes
Это бы всё в `datum/component` для структуры, и закрепить его на структуры

2023-11-12 13:38 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +		if(MOB_SIZE_TINY) 	slopchance = 10
не пиши if выражения в строку

2023-11-12 13:38 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	var/force_mult = 0.1 //коэффицент уменьшения урона при сбрасывании предмета
Вынеси в #define дефолтные значения

2023-11-12 13:45 UTC, PhantornRU commented
> Убери эту фишку у повара и бармена, они залезают на стол гораздо быстрее
Отслеживать по карте будем? KEKW
Да, понимаю про проверку изначальной профы. Но звучит все еще спорно.

2023-11-12 18:39 UTC, PhantornRU commented
Теперь красиво. 600 объектов спокойно "растоптало" без запинки. @Aylong220 @Gaxeer 
Перекидывание, топтание, залезание - всё работает.
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/2afe4302-4c18-42bf-98d2-a68c83825a85)
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/ed6618be-5ed8-4c18-b388-2aff579bfbd4)

2023-11-12 18:45 UTC, Aylong220 commented
> Теперь красиво. 600 объектов спокойно "растоптало" без запинки. @Aylong220 @Gaxeer Перекидывание, топтание, залезание - всё работает. ![image](https://user-images.githubusercontent.com/41479614/282318738-2afe4302-4c18-42bf-98d2-a68c83825a85.png) ![image](https://user-images.githubusercontent.com/41479614/282318902-ed6618be-5ed8-4c18-b388-2aff579bfbd4.png)

а есть видиво? xdd

2023-11-13 07:27 UTC, Gaxeer requested changes

2023-11-13 07:27 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +	var/force_mod = 0.1 	//коэффицент уменьшения урона при сбрасывании предмета
комментарии убрать, сверху над переменными через `///` написать что каждая переменная значит, и у туда можно вот эту инфу добавить. На английском языке

2023-11-13 07:27 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +	//RegisterSignal(parent, COMSIG_PARENT_ATTACKBY, PROC_REF(Repaint))
закоменченный код убрать

2023-11-13 07:27 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +	var/mob/living/user = climber
лишняя переменная. Просто используй `climber`

2023-11-13 07:27 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +	for(var/turf/T in range(0, user)) //Preventing from rotating stuff in an inventory
Здесь просто get_turf(user)

2023-11-13 07:27 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +					break
убери лесенку, назови нормально переменные, вместо `thrown_atoms.len` используй `length(thrown_atoms)`

2023-11-13 07:27 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +	var/atom/thrown_target
переменную обьяви внутри цикла

2023-11-13 07:27 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +		I.throwforce /= force_mod
`I` назови нормально

2023-11-13 07:27 UTC, Gaxeer commented on modular_ss220/emotes/code/emote.dm
> +		SEND_SIGNAL(T, COMSIG_CLIMBED_ON, user)
Создай новый сигнал `COMSIG_DANCED_ON` и отправляй его, без поиска стола под человеком. Те кто случают сигнал сами разберутся что делать

2023-11-13 17:16 UTC, Gaxeer commented on modular_ss220/emotes/code/emote.dm
> +	if(T)
Вот это убери

2023-11-13 17:20 UTC, Gaxeer commented on modular_ss220/emotes/code/emote.dm
> +	if(T)
```suggestion
	var/obj/structure/table/danced_on = locate() in user.loc
	if(danced_on)
```

2023-11-13 17:22 UTC, larentoun requested changes

2023-11-13 17:22 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +	UnregisterSignal(parent, list(COMSIG_MOVABLE_CROSSED, COMSIG_CLIMBED_ON))
А где `COMSIG_DANCED_ON`?

2023-11-13 17:22 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	AddComponent(/datum/component/clumsy_climb_component, 15)
Стоит выдавать компонент когда он нужен (когда начинают залезать, к примеру или входят в тайл), как мне кажется

2023-11-13 17:22 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +		SEND_SIGNAL(src, COMSIG_CLIMBED_ON, user)
Чем это не подходит? И просто там, где принимается, проверять юзера
```suggestion
	. = ..()
	SEND_SIGNAL(src, COMSIG_CLIMBED_ON, user)
```

2023-11-13 17:22 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +#define COMSIG_DANCED_ON "dance_on"
Стоит вынести дефайны в модуль `defines220` и вызовы в модуль `signals220`

2023-11-13 17:22 UTC, larentoun commented on modular_ss220/emotes/code/emote.dm
> +		SEND_SIGNAL(T, COMSIG_DANCED_ON, user)
В `signals220`

2023-11-13 17:22 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +#define COMSIG_DANCED_ON "dance_on"
Также напиши какие аргументы имеет сигнал

2023-11-13 17:22 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +	if(!table.contents)
```suggestion
/datum/component/clumsy_climb_component/proc/cross(atom/table, mob/living/user)
	SIGNAL_HANDLER
	
	if(!table.contents)
```

2023-11-13 17:25 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +		item.throwforce /= force_mod
```suggestion
	var/list/items_to_throw = list()

	for(var/obj/item/candidate_to_throw in get_turf(user))
		if(candidate_to_throw.anchored || !prob(thrown_chance))
			continue
			
		items_to_throw += candidate_to_throw 
		if(length(items_to_throw) >= max_thrown_objects)
			break

	for(var/obj/item/item_to_throw as anything in items_to_throw)
		var/atom/thrown_target = get_edge_target_turf(user, get_dir(user_turf, get_step_away(item, user_turf)))
		item_to_throw.throw_at(target = thrown_target, range = 1, speed = 1)
		item_to_throw.force *= force_mod
		item_to_throw.throwforce *= force_mod //no killing using shards :lul:
		item_to_throw.pixel_x = rand(-6, 6)
		item_to_throw.pixel_y = rand(0, 10)
		item_to_throw.force /= force_mod
		item_to_throw.throwforce /= force_mod
```

2023-11-13 17:31 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +	var/max_thrown_objects_low = 5
Здесь тоже комментарии над переменными

2023-11-13 17:32 UTC, Gaxeer commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +/datum/component/clumsy_climb_component
В названии компонента не надо слово `component`, то что это компонент понятно из иерархии и так

2023-11-13 18:06 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	AddComponent(/datum/component/clumsy_climb_component, 15)
Тоже самое, почему я добавлял компонент пиксель-шифта только когда он необходим, а не всем ливингам при ините. Лишние компоненты, которые не используются, ни к чему.

2023-11-13 18:07 UTC, PhantornRU commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	AddComponent(/datum/component/clumsy_climb_component, 15)
Нужно ли компонент убирать при завершении всей операции? Или можно повторно его "передобавлять" каждый раз?

2023-11-13 18:25 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	AddComponent(/datum/component/clumsy_climb_component, 15)
Можно добавить переменную, чтобы не создавались новые компоненты, вроде что-т типо `dupe_mode = COMPONENT_DUPE_UNIQUE`. Да, желательно удалять

2023-11-13 19:33 UTC, PhantornRU commented
@larentoun реализовал твой вариант с удалением-добавлением. Мне он всё еще кажется спорным. Но коль он есть, то теперь он есть. Протестировал. Работает.

2023-11-14 11:55 UTC, larentoun requested changes
Что вообще должно быть:
1. На стол переместился моб (нужна проверка, у тебя ее нет. Или у тебя и летающзий шкафчик должен кросс делать?)
2. Добавляем компонент на этот стол. Вызываем cross(), так как у нас по факту кто-то уже зашел на стол и должен растолкать приколы.
3. Добавляем сигналы на кросс - при танце.
4. Добавляем сигналы на удаление - при передвижении со стола, заодно проверить, есть ли на столе кто-то, кто еще может вызвать компонент.

Как-то так

2023-11-14 11:55 UTC, larentoun commented on modular_ss220/_defines220/code/signals_atom.dm
> +#define COMSIG_DANCED_ON 	"dance_on"
Сюда дай то, откуда сигнал приходит, и какие аргументы он принимает, примеры вроде есть в других сигналах в модуле

2023-11-14 11:55 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	remove_clumsy_climb()
Я имел ввиду удаление в компоненте делать.

2023-11-14 11:55 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	remove_clumsy_climb()
Тоже лучше в компоненте удалять себя

2023-11-14 11:55 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	. = ..()
А тут лучше сначала `. = ..()`, а потом добавлять компонент. В компоненте можно сразу вызывать `cross()` в ините

2023-11-14 11:55 UTC, larentoun commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	. = ..()
Ну и тут тоже самое, что я выше описал

2023-11-14 13:27 UTC, PhantornRU commented on modular_ss220/clumsy_table/code/clumsy_table.dm
> +	. = ..()
Сигналлеры решил оставить вместо вызова сразу прока при инициализации, ибо в Crossed все еще используется сигналлер.

2023-11-14 16:29 UTC, Gaxeer requested changes
линтер падает

2023-11-15 08:32 UTC, PhantornRU commented
> линтер падает

Кадия стоит. И Линтер теперь тоже стоит.

2023-11-15 08:38 UTC, Aylong220 commented on modular_ss220/clumsy_table/code/clumsy_climb_component.dm
> +		item_to_throw.pixel_y = rand(0, 10)
```suggestion
		item_to_throw.pixel_x = rand(-7, 7)
		item_to_throw.pixel_y = rand(-7, 7)
```

2023-11-15 09:36 UTC, Gaxeer approved these changes

2023-11-15 11:01 UTC, merged