TWEAK: official station goals translation
ss220club/Paradise-SS220 pull request #682
Opened 2023-11-12 19:08 UTC by mattgroy

## Что этот PR делает
Добавляет процедуры для перевода из [вики](https://wiki.ss220.club/index.php/%D0%9A%D0%B0%D0%BA_%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C_%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4_%D0%B8%D0%B3%D1%80%D1%8B) (кроме склонения по падежам — `declent_ru`)

Перевод офф. целей станции и интерфейсов (хранилище ДНК, метеоритные щиты и т.д.)

## Почему это хорошо для игры
Русский язык - это хорошо

## Тестирование
Скомпилировал, заспавнил изменённые объекты (в том числе тех, что обладают своим tgui), проверил работоспособность взаимодействий

## Changelog

:cl:
tweak: Перевод офф. целей станции
/:cl:

2023-11-12 19:42 UTC, Aylong220 requested changes

2023-11-12 19:42 UTC, Aylong220 commented on code/__HELPERS/pronouns.dm
> +
Вот это отдельным ПРом в модуль, и в мастер
И только потом перевод

2023-11-12 19:55 UTC, Aylong220 requested changes

2023-11-12 19:55 UTC, Aylong220 commented on tgui/packages/tgui/interfaces/SatelliteControl.js
> +                  content={sat.active ? 'Деактивировать' : 'Активировать'}
TGUI кстати не трогаем пока. Оно не пересобирается автоматом из-за чего будут вечные непонятные конфликты

2023-11-14 14:06 UTC, PhantornRU commented on code/__HELPERS/pronouns.dm
> +	return gender == MALE ? male_word : (gender == FEMALE ? female_word : (gender == NEUTER ? neuter_word : multiple_word))
Не стоит так делать. Раздели по пунктам и вынеси лучше в IF.
Одна строка не всегда круто.

2023-11-14 14:06 UTC, PhantornRU commented on code/game/gamemodes/game_mode.dm
> +	message_text += "<h3>Приказы АКН «Трурль»</h3></div><hr>"
Трурль? в данном случае "r" не читается и будет Труль же.

2023-11-14 14:11 UTC, PhantornRU requested changes
Перевод пока не успел детально посмотреть

2023-11-16 08:17 UTC, mattgroy commented on code/game/gamemodes/game_mode.dm
> +	message_text += "<h3>Приказы АКН «Трурль»</h3></div><hr>"
Перевод взят из [wiki ss220.club](https://wiki.ss220.club/index.php/Nanotrasen#%D0%90%D0%9A%D0%9D_%C2%AB%D0%A2%D1%80%D1%83%D1%80%D0%BB%D1%8C%C2%BB)

Оригинальная отсылка - [Кибериада](https://ru.wikipedia.org/wiki/%D0%9A%D0%B8%D0%B1%D0%B5%D1%80%D0%B8%D0%B0%D0%B4%D0%B0)

2024-01-05 19:54 UTC, Aylong220 commented
Месяц стоим, откроешь как будут сподвижки

2024-01-05 19:54 UTC, closed without merging