Delta-SM-Space-Drop
ss220club/Paradise-SS220 pull request #685
Opened 2023-11-12 21:02 UTC by GREG-MAP

## Что этот PR делает

1. Добавляет механику сброса СМ в космос, а именно под солярами на край карты при взрыве которого он даже их не задевает. Так же добавляет кнопку сброса и инструкцию по ее использованию.

2. Переделка зоны содержания СМ и прибытия под систему сброса.

3. Отдаляет от края карты ИИ.

## Почему это хорошо для игры

Позволяет в критической ситуации, а именно когда целостность СМ доходит до 10 или менее процентов, сбросить его в космос да бы не разносить весь атмос и не ебать с ним голову остаток раунда инженерам. Тем более большинство Капитанов после взрыва СМ сразу вызывают шатл хотя при взрыве СМ спокойно можно продолжать рауд.

ИИ теперь не так близко к краю карты. (Было 11 тайлов от края, теперь 15)

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/100868342/799c27f9-351d-4636-995a-c953347e0706)

![2023-11-13 01 43 32](https://github.com/ss220club/Paradise-SS220/assets/100868342/646c25ba-db5e-4c4d-88b8-0a744dd8d439)
![2023-11-13 01 43 40](https://github.com/ss220club/Paradise-SS220/assets/100868342/abe986a5-d9e1-47dc-9760-97523caccc6a)

![2023-11-13 01 42 04](https://github.com/ss220club/Paradise-SS220/assets/100868342/716f17ba-8cc2-4575-9c46-ff6f4d37470c)
![2023-11-13 01 42 22](https://github.com/ss220club/Paradise-SS220/assets/100868342/ddb7f3a2-515f-4ac9-82d4-dbf704f3d1fe)

https://github.com/ss220club/Paradise-SS220/assets/100868342/73c76512-3162-4d6b-bae9-2a0d8bc43f5b

https://github.com/ss220club/Paradise-SS220/assets/100868342/29336146-e0ab-4ae3-8b55-bb226728fcc1

## Тестирование

Сотню раз запускал на локалке и тестил все начиная от пути запуска до взрыва

## Changelog

:cl:
add: Систему сброса СМ
del: Камеру хранения эммиторов над СМ
imageadd: Иконка кнопки сброса СМ
/:cl:

2023-11-12 21:18 UTC, dj-34 requested changes
**Идея**: Казуальщина, лично мне было бы все равно, но на Кибериаду прошу такое не нести (по крайней мере пока что). Требуется голосование среди игроков Дельты.

**Кодстайл**: ОК

**Иконка**: НЕ ОК (абсолютно не уникальная, я бы подумал что это выключатель света. Спрайт стоило бы перерисовать).

**Кнопка сброса СМ**: Очень опасно, стоит переделать её под кнопку с доступом, и добавить может какую-нибудь закрывашку, как например в первой Халфе

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/d2d6f903-67b2-4baf-9e4e-33f259d6bfdb)

2023-11-12 21:18 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	icon = 'modular_ss220/sm_space_drop/icon/sm_buttons.dmi'
У нас путь не в "icon", а "icons"

2023-11-12 21:18 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	name = "SM Drop Controll"
Сразу на русском (еще и Control написал не правильно xdd)

2023-11-12 21:18 UTC, dj-34 commented on modular_ss220/sm_space_drop/sm_space_drop.dm
> +	author = "furior"
Нормально оформи

2023-11-12 21:18 UTC, dj-34 commented on modular_ss220/sm_space_drop/sm_space_drop.dm
> +	. = ..()
Лишнее

2023-11-12 21:18 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_mass_driver.dm
> +	name = "Пусковая установка СМ"
```suggestion
	name = "пусковая установка СМ"
```

2023-11-12 21:18 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	// Then make not active
Это здесь зачем?

2023-11-12 21:18 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	// ADD GREG
Это что?

2023-11-12 21:22 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	// Then make not active
Это с кнопки масс драйвера

2023-11-12 21:22 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	// ADD GREG
А блять это для меня было что бы не запутатся

2023-11-12 21:23 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	icon = 'modular_ss220/sm_space_drop/icon/sm_buttons.dmi'
У меня папка icon называется в модуле

2023-11-12 21:30 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_mass_driver.dm
> +	name = "Пусковая установка СМ"
Что имел в виду не понял

2023-11-12 21:37 UTC, Legendaxe requested changes
Комната ожидания переделки лишней копипасты кода в новую унаследованную кнопку

2023-11-12 21:37 UTC, Legendaxe commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	resistance_flags = INDESTRUCTIBLE | LAVA_PROOF | FIRE_PROOF | UNACIDABLE | ACID_PROOF
```suggestion
```

2023-11-12 21:52 UTC, Aylong220 commented
> **Идея**: Казуальщина, лично мне было бы все равно, но на Кибериаду прошу такое не нести (по крайней мере пока что). Требуется голосование среди игроков Дельты.


Так ставь дизлайк если идея не нравится, я вон въебал

2023-11-13 07:29 UTC, Gaxeer commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	icon = 'modular_ss220/sm_space_drop/icon/sm_buttons.dmi'
ну значит перенеси свою иконку в нашу папку

2023-11-13 07:31 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +	icon = 'modular_ss220/sm_space_drop/icon/sm_buttons.dmi'
Да переименовал под наш icons и все

2023-11-13 22:10 UTC, Legendaxe approved these changes

2023-11-13 22:10 UTC, Legendaxe commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +	name = "Инструкция по использованию СБСКС"
```suggestion
	name = "\improper инструкция по использованию СБСКС"
```

2023-11-13 22:14 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +	name = "Инструкция по использованию СБСКС"
Делаю, еще не загрузил прост

2023-11-13 22:51 UTC, dj-34 requested changes

2023-11-13 22:51 UTC, dj-34 commented on modular_ss220/sm_space_drop/sm_space_drop.dm
> +	author = "GREG"
```suggestion
/datum/modpack/sm_space_drop
	name = "Система сброса СМ"
	desc = "Позволяет сбросить СМ в критической ситуации."
	author = "GREG"
```

2023-11-14 00:38 UTC, Aylong220 commented
Днём внимательно гляну

2023-11-14 13:53 UTC, PhantornRU commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +"}
Имхо. Это необходимо выравнять по левому краю. Выравнивание по центру смотрится страшно. Очень страшно и неудобночитабельно. Вдовесок пропущенные строки в списке действий излишни.

2023-11-14 13:58 UTC, PhantornRU commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +			break
Вот не нравится такая реализация. Имхо. Нужно искать не сам кристалл, а mass_driver на котором стоит кристалл. И на этом mass_driver уже проверять, стоит ли на нем кристалл, после чего откручивать её.
Это на случай, если у нас будет несколько mass_driver (мало ли какие извращенцы есть).

Потом лучше проверять не в зоне атмоса, а в зоне в которой находится кнопка. Для этого на карте придется добавить +1 тайл для корректного считывания.
Это на случай если у нас будут кастомные зоны в которых стоят сбросы.

Универсальность pepeChill

2023-11-14 14:00 UTC, PhantornRU commented on modular_ss220/sm_space_drop/sm_space_drop.dm
> +	author = "GREG"
```suggestion
	name = "Система сброса СМ"
	desc = "Позволяет сбросить СМ в критической ситуации."
	author = "GREG"
```

2023-11-14 16:05 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +"}
Переделываю, сам посмотрел ну не то малеха, вниз перенесу нанторейзен и линию сделаю вроде можно е нас там по докам.

2023-11-14 17:05 UTC, ImJustKisik commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		user.custom_emote(EMOTE_VISIBLE, "Нажиамает кнопку сброса [src]!")
Нажиамает

2023-11-14 17:09 UTC, ImJustKisik commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			user.custom_emote(EMOTE_VISIBLE, "Хлопает по стеклу кнопки [src].")
дружески похлопывает по [src].

2023-11-14 17:10 UTC, ImJustKisik commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			user.custom_emote(EMOTE_VISIBLE, "Разбивает стекло кнопки [src]!")
Разбивает стекло

2023-11-14 17:11 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			user.custom_emote(EMOTE_VISIBLE, "Разбивает стекло кнопки [src]!")
?

2023-11-14 17:11 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			user.custom_emote(EMOTE_VISIBLE, "Разбивает стекло кнопки [src]!")
ПОн поправил

2023-11-14 17:20 UTC, dj-34 requested changes

2023-11-14 17:20 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		visible_message("<span class='notice'>Кнопка громко щелкает.</span>")
в span_notice

2023-11-14 17:20 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			user.custom_emote(EMOTE_VISIBLE, "Хлопает по стеклу кнопки [src].")
```suggestion
			user.custom_emote(EMOTE_VISIBLE, "хлопает по стеклу кнопки [src].")
```

2023-11-14 17:20 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			user.custom_emote(EMOTE_VISIBLE, "Хлопает по стеклу кнопки [src].")
все эмоуты с маленькой начинай

2023-11-14 17:20 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>2. Решение о сбросе кристала может принимать СЕ или его ВРиО и выше.<br>
```suggestion
<br>2. Решение о сбросе кристалла может принимать СЕ, или его ВРиО и выше.<br>
```

2023-11-14 17:20 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>3. Если целостность кристала равна 10 или мение процентов, должне быть произведен сброс кристала в кратчайшее время.<br>
```suggestion
<br>3. Если целостность кристалла равна 10 или менее процентов, должен быть произведен сброс кристалла в кратчайшее время.<br>
```

2023-11-14 17:20 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>4. В случае отсутствия СЕ и до назначения его ВРиО решение о сбросе кристала принимает Капитан.<br>
```suggestion
<br>4. В случае отсутствия СЕ и до назначения его ВРиО, решение о сбросе кристалла принимает капитан.<br>
```

2023-11-14 17:20 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>5. Создание помехи при неообходимости сброса кристала квалифицируется статьей 400 космического закона.<br>
```suggestion
<br>5. Создание помехи при необходимости сброса кристалла квалифицируется статьей 400 Космического Закона.<br>
```

2023-11-14 17:20 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>ПРИМЕЧАНИЕ Кнопка сброса СМ находится в его буферной зоне на стене возле правого вента.<br>
```suggestion
<br>ПРИМЕЧАНИЕ: Кнопка сброса СМ находится в его буферной зоне на стене возле правого вента.<br>
```

2023-11-14 17:20 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		user.custom_emote(EMOTE_VISIBLE, "Нажиамает кнопку сброса [src]!")
все эмоуты с маленькой начинай

2023-11-14 17:21 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		to_chat(user, "<span class='warning'>Кнопку уже нажали, процесс выброса СМ запущен.</span>")
Поправил

2023-11-14 17:21 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		user.custom_emote(EMOTE_VISIBLE, "Нажиамает кнопку сброса [src]!")
Понял делаю

2023-11-14 17:21 UTC, PhantornRU reviewed
ThumbsUp, но запрос на улучшение, центрирование и отступы все еще остался.

2023-11-14 17:21 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			to_chat(user, "<span class='warning'>Если вы пытаетесь разбить стекло, вам придется ударить по нему сильнее...</span>")
Так он и так в спане не ?

2023-11-14 17:22 UTC, ImJustKisik commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +	desc = "<font color='red'>ВНИМАНИЕ:</font>Сброс кристала суперматерии. Неправомерное использование может привести к тюремному заключению."
`desc = "<font color='red'>ВНИМАНИЕ:</font>Нажатие этой кнопки приведёт к сбросу кристала суперматерии. Использование не по назначению может привести к штрафам и тюремному заключению"`

2023-11-14 17:28 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +	desc = "<font color='red'>ВНИМАНИЕ:</font>Сброс кристала суперматерии. Неправомерное использование может привести к тюремному заключению."
Там перма нахуй или каторга но не штраф

2023-11-14 17:48 UTC, Aylong220 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/eae2a643-ef83-4475-b818-8c7a16b8b6e3)

2023-11-14 18:22 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button.dm
> +			break
Нуу проще так оставить т.к. он один а смы мага имеют другой подтим я это имел в виду

2023-11-14 18:23 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>5. Создание помехи при неообходимости сброса кристала квалифицируется статьей 400 космического закона.<br>
+

2023-11-14 19:42 UTC, dj-34 requested changes

2023-11-14 19:42 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		visible_message("<span_notice>Кнопка громко щелкает.</span>")
спаны делаются не так, смотри примеры

2023-11-14 19:42 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		user.custom_emote(EMOTE_VISIBLE, "нажемает кнопку сброса [src.name]!")
```suggestion
		user.custom_emote(EMOTE_VISIBLE, "нажимает кнопку сброса [src.name]!")
```

2023-11-14 19:42 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>2. Решение о сбросе кристала может принимать СЕ, или его ВРиО и выше.<br>
я же делал ревью... почему ты не жмешь commit suggestions
ошибки не пропали

2023-11-14 19:42 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			investigate_log("<font color='red'>delete</font> at ([area.name])","SM")
Почему delete?
```suggestion
			investigate_log("<font color='red'>delete</font> at ([area.name])","supermatter")
```

2023-11-14 19:42 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +	name = "supermatter launch trigger"
Зачем вернул на английское название?
```suggestion
	name = "supermatter launch trigger"
```

2023-11-14 19:42 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			user.custom_emote(EMOTE_VISIBLE, "разбивает стекло[src.name]!")
```suggestion
			user.custom_emote(EMOTE_VISIBLE, "разбивает стекло [src.name]!")
```

2023-11-14 19:45 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		visible_message("<span_notice>Кнопка громко щелкает.</span>")
Вот спан глист добавлял вот этот НАКАКАЛ МНЕ

2023-11-14 19:50 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +	name = "supermatter launch trigger"
Хэд сказал вернуть лучше и глист с ним

2023-11-14 19:51 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +	name = "supermatter launch trigger"
где? зачем? почему?

2023-11-14 19:51 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +	name = "supermatter launch trigger"
Да вот хуй

2023-11-14 19:52 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +	name = "supermatter launch trigger"
Их знает

2023-11-14 19:52 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>2. Решение о сбросе кристала может принимать СЕ, или его ВРиО и выше.<br>
Там же были пропущены запятые и т.д. я это исправил что тут еще ?

2023-11-14 19:54 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		visible_message("<span_notice>Кнопка громко щелкает.</span>")
Сделал

2023-11-14 20:01 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>2. Решение о сбросе кристала может принимать СЕ или его ВРиО и выше.<br>
Ну вот это сделано

2023-11-14 20:01 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>3. Если целостность кристала равна 10 или мение процентов, должне быть произведен сброс кристала в кратчайшее время.<br>
Делаю

2023-11-14 20:02 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>4. В случае отсутствия СЕ и до назначения его ВРиО решение о сбросе кристала принимает Капитан.<br>
Делаю

2023-11-14 20:02 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>5. Создание помехи при неообходимости сброса кристала квалифицируется статьей 400 космического закона.<br>
Делаю

2023-11-14 20:02 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +<br>Поздравляю! Теперь в случае вероятности взрыва кристала супер материи вы в состоянии сохранить целостность станции.<br>
Угу

2023-11-14 20:12 UTC, dj-34 requested changes

2023-11-14 20:12 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/paper_sm_info.dm
> +"}
Кристал -> Кристалл, перепроверь моё ревью, используй commit suggestions

2023-11-14 20:12 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			investigate_log("<font color='red'>active</font> at ([area.name])","supermatter")
```suggestion
			investigate_log("has been launched to space at ([area.name]) by [key_name(user)].","supermatter")
```

2023-11-14 20:12 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			message_admins("Supermatter crystal reset activated(<A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=[x];Y=[y];Z=[z]'>[area.name]</a>)")
```suggestion
			message_admins("Supermatter Crystal has been launched to space by [key_name_admin(user)] [ADMIN_JMP(src)].")
```

2023-11-14 20:12 UTC, dj-34 commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			log_game("Supermatter crystal reset activated([area.name])")
убери log_game, он лишний я думаю

2023-11-14 20:14 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +		to_chat(user, "<span class='warning'>Кнопку уже нажали.</span>")
Угу

2023-11-14 20:15 UTC, GREG-MAP commented on modular_ss220/sm_space_drop/code/sm_button_NEW.dm
> +			message_admins("Supermatter crystal reset activated(<A HREF='?_src_=holder;adminplayerobservecoodjump=1;X=[x];Y=[y];Z=[z]'>[area.name]</a>)")
Угу

2023-11-14 20:27 UTC, dj-34 approved these changes
Вроде норм, можно отправлять на голосование игрокам.
По хорошему еще проверить правильно ли работает логгирование админское

2023-11-14 20:34 UTC, Aylong220 approved these changes
FUCKIN FINALLY

2023-11-14 20:39 UTC, merged