Feat: ID card skins
ss220club/Paradise-SS220 pull request #695
Opened 2023-11-14 01:21 UTC by Aylong220

## Что этот PR делает
Добавляет новые скины на карты для донатеров, и улучшает старые.
Сортировка по тирам такая:
Т2 - Скин с возможностью выбрать цвет.
Т3 - Все старые скины + золотая.
Т4 - Анимированные скины.

## Почему это хорошо для игры
Больше приятных мелочей для поддержавших проект

## Изображения изменений
https://github.com/ss220club/Paradise-SS220/assets/69762909/1c3ce279-ebe2-4bcb-9a75-f85594b3d531

## Тестирование
В процессе, как и новые скины

## Changelog

:cl:
tweak: Поддержавшим проект теперь доступны скины на карты. 2 тир - скин с выбором цвета. 3 тир - без изменений, кроме золотой карты в нём. 4 тир - анимированные скины.
/:cl:

2023-11-15 05:44 UTC, PhantornRU commented on modular_ss220/objects/code/card_skins.dm
> +			return
лишняя лесенка, можно сделать прямую логическую цепочку

```suggestion
	if(istype(item, /obj/item/id_skin))
	        return FALSE
	        
        if(skin_applied)
	        to_chat(usr, span_warning("На карте уже есть наклейка, сначала соскребите её!"))
	        return FALSE
	        
        if(!skinable)
	        to_chat(usr, span_warning("Наклейка не подходит для [src]!"))
	        return FALSE
	        
        to_chat(user, span_notice("Вы начинаете наносить наклейку на карту."))
        if(!do_after(usr, 2 SECONDS, target = src, progress = TRUE, allow_moving = TRUE))
	        return FALSE
	        
	var/obj/item/id_skin/skin = item
	var/mutable_appearance/card_skin = mutable_appearance(skin.icon, skin.icon_state)
	card_skin.color = skin.color
	to_chat(user, span_notice("Вы наклеили [skin.pronoun_name] на [src]."))
	desc += "<br>[skin.info]"
	skin_applied = item
	user.drop_item()
	item.forceMove(src)
	skin_applied = item
	add_overlay(card_skin)
	return TRUE
```

2023-11-15 05:46 UTC, PhantornRU commented on modular_ss220/objects/code/card_skins.dm
> +		/obj/item/id_skin/colored,
Для colored карт при инициализации лучше выбирать рандомный цвет, в случае если ему целенаправленно при создании цвет не был назначен.

2023-11-15 05:48 UTC, PhantornRU commented on modular_ss220/objects/code/card_skins.dm
> +	/obj/item/id_skin/colored = 1,
Сколько цветов, столько и шансов на выпадение простой цветной карты. Не обесцениваем "крутые карты" равными шансами.
```suggestion
	/obj/item/id_skin/colored = 10,
```

2023-11-15 05:48 UTC, PhantornRU requested changes
Ура карточки с ушками. Но с цветастыми нужно добавить рандомность при инициализации, когда они не выбираются.

2023-11-15 05:56 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +	/obj/item/id_skin/colored = 1,
> 10,

Если так подумать, цветов гораздо больше, выбрать то можно xdd

2023-11-15 05:58 UTC, dj-34 commented on modular_ss220/objects/code/card_skins.dm
> +	/obj/item/id_skin/colored = 1,
сыглы

2023-11-15 05:58 UTC, dj-34 commented on modular_ss220/objects/code/card_skins.dm
> +/obj/effect/spawner/random_spawners/id_skins/no_chance
а в чем смысл?

2023-11-15 06:10 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +/obj/effect/spawner/random_spawners/id_skins/no_chance
Второй спавнер редко скин оставляет

2023-11-15 06:21 UTC, PhantornRU commented on modular_ss220/objects/code/card_skins.dm
> +	/obj/item/id_skin/colored = 1,
ну, суть та же. Обычная наклейка не должна стоять наравне с редкими наклейками.
А по цветастости - просто выдели те, которые могут инициализироваться.

2023-11-15 06:22 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +	/obj/item/id_skin/colored = 1,
Да уже сделяль

2023-11-15 06:42 UTC, Lime-7 commented
2 тысячи кридитов....
мех кор стоит 1500
самая дорогая цель станции стоит - 1500
кристал супер материи стоит - 750
РНД получают примерно 945 кридитов за все базовые технологии на 7
![fade-away-oooooooooooo](https://github.com/ss220club/Paradise-SS220/assets/142225267/b5a5d203-e63e-4457-86fa-bb0a79ce4dbe)

2023-11-15 06:43 UTC, Aylong220 commented
> 2 тысячи кридитов.... 

То есть ящик с дорогими шубами за 2к и розовое пальто тебя не смущают?

2023-11-15 06:46 UTC, Lime-7 commented
> > 2 тысячи кридитов....
> 
> То есть ящик с дорогими шубами за 2к и розовое пальто тебя не смущают?

я их не нашел на вики оффов, максимум, что нашел за 2500, так это криейт с коллекционируемыми предметами

2023-11-15 06:47 UTC, Aylong220 commented
> я их не нашел на вики оффов, максимум, что нашел за 2500, так это криейт с коллекционируемыми предметами

А ты в игре смотри, на вики оффов тоже люди, и информация может отсутствовать, на нашей же вики и нашей информации не хватает.

2023-11-15 06:51 UTC, PhantornRU commented
> > 2 тысячи кридитов....
> 
> То есть ящик с дорогими шубами за 2к и розовое пальто тебя не смущают?

меня смущает, хоть я и сделал. И там за 2к ты заказызываешь молей. Надо будет цену того лутбокса понизить... Может быть когда-нибудь. Но если захочешь заняться лутбоксами и понизишь ящик с дорогими шубами - будет хорошо

2023-11-15 06:53 UTC, Aylong220 commented
> меня смущает, хоть я и сделал. И там за 2к ты заказызываешь молей. Надо будет цену того лутбокса понизить... Может быть когда-нибудь. Но если захочешь заняться лутбоксами и понизишь ящик с дорогими шубами - будет хорошо Один фиг этот ящик добавлялся как шутка для карго.

Точно не в этом ПРе

2023-11-15 08:10 UTC, Legendaxe approved these changes

2023-11-15 23:14 UTC, larentoun commented on modular_ss220/objects/code/card_skins.dm
> +/obj/item/card/id/verb/remove_skin()
Вербы пытаемся минимизировать, раз на оффах тоже

2023-11-15 23:14 UTC, larentoun commented on modular_ss220/objects/code/card_skins.dm
> +	skinable = FALSE
Хотелось бы, чтобы наклейки вешались как и золотые/серебряные. Да, не будет на карте должности, но это цена, которую платят

2023-11-15 23:14 UTC, larentoun commented on modular_ss220/objects/code/card_skins.dm
> +	if(usr.stat || HAS_TRAIT(usr, TRAIT_UI_BLOCKED) || usr.restrained())
`HAS_TRAIT(usr, TRAIT_UI_BLOCKED)` проверка в данном случае дополнительно запретит только если пользователь лежит. `restrained()` блокирует руки, как и UI. Не думаю, что проверка на трейт нужна?

2023-11-15 23:17 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +/obj/item/card/id/verb/remove_skin()
То есть просто убрать из ПКМ? Пон, всё равно смысла в этом нет так как на альт удобнее

2023-11-15 23:18 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +	skinable = FALSE
Это как минимум не логично, что маленькая карточка превращается большую, я конечно гляну что можно сделать, но в целом затея так себе

2023-11-16 00:35 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +	skinable = FALSE
Увы, слишком много проблем, даже если пересрайтить гостевой, и двигать его при наклеивании наклейки. Всё равно выглядит как говно, а на некоторых ищё и дырка там где цвет отдела

2023-11-16 00:40 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +	if(usr.stat || HAS_TRAIT(usr, TRAIT_UI_BLOCKED) || usr.restrained())
Убрал

2023-11-16 02:34 UTC, Aylong220 commented
@larentoun @Gaxeer @PhantornRU 
Вроде сделал всё по вашим ревью, кроме возможности прилепить наклейки на гостевые, потому что выглядит как кринж, даже если перерисовать гостевой и двигать его левее (что я кстати сделал только в асеприте).
Если всё устраивает - жду галочки xdd

2023-11-16 03:40 UTC, PhantornRU approved these changes

2023-11-16 06:03 UTC, PhantornRU commented
> @larentoun @Gaxeer @PhantornRU Вроде сделал всё по вашим ревью, кроме возможности прилепить наклейки на гостевые, потому что выглядит как кринж, даже если перерисовать гостевой и двигать его левее (что я кстати сделал только в асеприте). Если всё устраивает - жду галочки xdd

Гостевые не заслужили + гостевыми почти никто не пользуется.

2023-11-16 12:52 UTC, larentoun reviewed
Единственный вопрос, в целом вроде остальное сойдет

2023-11-16 12:52 UTC, larentoun commented on modular_ss220/objects/code/card_skins.dm
> +		else if(usr.a_intent == INTENT_HELP)
Не совсем понимаю, почему нельзя на дизарме/грабе снимать наклейку? Чем это обосновано? У нас большинство взаимосвязей связано с "режим харма или не харма"

2023-11-16 13:22 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +		else if(usr.a_intent == INTENT_HELP)
Не продумано

2023-11-16 14:21 UTC, Gaxeer commented on modular_ss220/objects/code/card_skins.dm
> +/obj/item/card/id/attackby(obj/item/item as obj, mob/user as mob, params)
вот эти все `as что-то` нужны только для вёрбов. Убери

2023-11-16 18:43 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +/obj/item/id_skin/silver/colored/attack_self(mob/living as mob)
> И сделай другую иерархию чтобы убрать дупликат `change_color()`: /obj/item/id_skin/colored и от него наследуй /silver

Вот это я делать не хочу, в редакторе в группе будет срач ёбаный, изначально так и было

2023-11-16 19:16 UTC, Gaxeer commented on modular_ss220/objects/code/card_skins.dm
> +/obj/item/id_skin/silver/colored/attack_self(mob/living as mob)
так делать надо, увы

2023-11-16 19:50 UTC, Gaxeer commented on modular_ss220/objects/code/card_skins.dm
> +	if(user.stat || user.restrained())
HAS_TRAIT(user, TRAIT_HANDS_BLOCKED) вот это еще добавь

2023-11-16 19:54 UTC, Aylong220 commented
Готово

2023-11-16 20:01 UTC, Gaxeer commented on modular_ss220/objects/code/card_skins.dm
> +			color = color_list[choice]
```suggestion
			var/color_to_set = color_list[choice]
			if(!color_to_set)
				return
				
			color = color_to_set 
```

2023-11-16 20:10 UTC, Gaxeer commented on modular_ss220/objects/code/card_skins.dm
> +	return TRUE
у тебя есть `proc` `remove_skin`. Я бы это всё перенес в `add_skin` для лучшей читаемости

2023-11-16 20:10 UTC, Gaxeer commented on modular_ss220/objects/code/card_skins.dm
> +	return TRUE
всё, кроме первой строчки 
```if(!istype(item, /obj/item/id_skin))
		return .```

2023-11-17 01:10 UTC, Henri215 reviewed
kitty card?!
![image](https://github.com/ss220club/Paradise-SS220/assets/77684085/a908d6b0-b31d-422c-aca4-45c070bc2605)

2023-11-17 01:10 UTC, Henri215 commented on modular_ss220/objects/code/card_skins.dm
> +		playsound(user.loc, 'sound/items/poster_ripped.ogg', 50, 1)
```suggestion
		playsound(user.loc, 'sound/items/poster_ripped.ogg', 50, TRUE)
```

2023-11-17 15:01 UTC, Aylong220 commented
> kitty card?! ![image](https://user-images.githubusercontent.com/77684085/283638164-a908d6b0-b31d-422c-aca4-45c070bc2605.png)

Yes.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/80ac73ef-7b5d-4968-8ae2-7a29311d35a5)

2023-11-17 17:22 UTC, Gaxeer commented on modular_ss220/objects/code/card_skins.dm
> +		remove_skin(delete = TRUE)
```suggestion
		remove_skin(TRUE)
```

2023-11-17 17:23 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +		remove_skin(delete = TRUE)
Это разве так будет работать? Просто тру во что-то отправляет

2023-11-17 18:08 UTC, Gaxeer approved these changes

2023-11-17 18:13 UTC, merged