Breath scarf
ss220club/Paradise-SS220 pull request #702
Opened 2023-11-14 19:41 UTC by FlutterSnedDraw

## Что этот PR делает

Добавляет шарфик-дыхательную маску в донат,который одевается в слот маски и является более модным способом спасти себя при разгерметизации. Выполняется по просьбе murken4ik.

## Почему это хорошо для игры

Теперь даже при разгерметизации можно быть модным.

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/131897374/fd89aa47-af77-4215-b949-924547f73c8b)

## Тестирование
Проверил наличие на локалке.

## Changelog

:cl:
add: Шарфик для дыхания.
/:cl:

2023-11-14 19:45 UTC, dj-34 requested changes

2023-11-14 19:45 UTC, dj-34 commented on modular_ss220/clothing/code/mask.dm
> +	name = "Шарф с системой дыхания"
```suggestion
	name = "шарф с системой дыхания"
```

2023-11-14 19:45 UTC, dj-34 commented on modular_ss220/clothing/code/mask.dm
> +	desc = "Стильный и инновационный шарф, который не только обогревает вас в холод, но и служит дыхательной маской в экстремальных ситуациях."
Лучше не упоминать, что "он обогревает в холод", когда это не является правдой (нет cold_protection, и не надо).
Лучше напиши что это дыхательная маска, стилизованная под шарф

2023-11-14 19:49 UTC, dj-34 commented
сук, еще икондифф сломался, не проверить

2023-11-14 20:15 UTC, dj-34 approved these changes
Нет возможности проверить иконки (икондифф сдох), по коду и кодстайлу все ок должно быть

2023-11-14 20:17 UTC, dj-34 requested changes
Хотя я кое-что заметил. Нет иконки шарфа в руках и нет иконки шарфа в инвентаре.

2023-11-14 23:00 UTC, FlutterSnedDraw commented
> Хотя я кое-что заметил. Нет иконки шарфа в руках и нет иконки шарфа в инвентаре/на полу.

![image](https://github.com/ss220club/Paradise-SS220/assets/131897374/3a0dd006-c29a-4477-a0a6-efa98311455f)
Хм,на полу и в инвентаре у меня есть спрайт ,а вот в руках нет спрайта ,потому что у нас никакие шарфы и маски не имеют спрайт в руках,да и выглядеть в руках она скорее как черное месиво.

2023-11-15 01:21 UTC, dj-34 commented
> > Хотя я кое-что заметил. Нет иконки шарфа в руках и нет иконки шарфа в инвентаре/на полу.
> 
> ![image](https://user-images.githubusercontent.com/131897374/282955222-3a0dd006-c29a-4477-a0a6-efa98311455f.png) Хм,на полу и в инвентаре у меня есть спрайт ,а вот в руках нет спрайта ,потому что у нас никакие шарфы и маски не имеют спрайт в руках,да и выглядеть в руках она скорее как черное месиво.

это не спрайт "на полу", это отвратительный юз иконки с моба

2023-11-16 06:08 UTC, PhantornRU requested changes

2023-11-16 06:08 UTC, PhantornRU commented on modular_ss220/clothing/code/mask.dm
> +	icon_override = 'modular_ss220/clothing/icons/mob/mask.dmi'
OBJ (иконка) должен браться из файла в папке OBJ
А то что на MOB'е уже соответственно так как ты и сделал, из MOB

2023-11-17 12:08 UTC, FlutterSnedDraw commented
> > > Хотя я кое-что заметил. Нет иконки шарфа в руках и нет иконки шарфа в инвентаре/на полу.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/131897374/282955222-3a0dd006-c29a-4477-a0a6-efa98311455f.png) Хм,на полу и в инвентаре у меня есть спрайт ,а вот в руках нет спрайта ,потому что у нас никакие шарфы и маски не имеют спрайт в руках,да и выглядеть в руках она скорее как черное месиво.
> 
> это не спрайт "на полу", это отвратительный юз иконки с моба

![image](https://github.com/ss220club/Paradise-SS220/assets/131897374/4fd54002-291a-4fdf-9b4f-43f167f060d9)
переделал

2023-11-19 10:31 UTC, dj-34 commented
Разконфликть

2023-11-19 10:32 UTC, dj-34 requested changes

2023-11-19 10:32 UTC, dj-34 commented on modular_ss220/loadout/code/donor.dm
> +/datum/gear/donor/breathscarf
```suggestion

/datum/gear/donor/breathscarf
```

2023-11-21 05:45 UTC, Aylong220 commented
Расконфликтуй и добавь отступ как диджей написал

2023-11-21 17:23 UTC, FlutterSnedDraw commented
> Расконфликтуй и добавь отступ как диджей написал

done

2023-11-21 22:25 UTC, Aylong220 approved these changes

2023-11-22 08:05 UTC, PhantornRU approved these changes
13 строчек - 100 правок для шмоточки

2023-11-22 08:07 UTC, merged

2023-11-22 09:48 UTC, FlutterSnedDraw commented
И не говори :garold: