Перевод голосовалок и панели
ss220club/Paradise-SS220 pull request #704
Opened 2023-11-15 03:54 UTC by BR54FF

## Что этот PR делает

перевод панели голосований

## Почему это хорошо для игры

ФАРГУС
неПОЛНОСТЬЮ НА РУССКОМ

## Изображения изменений
поверьте мне

## Тестирование
ну локалка

## Changelog

:cl:
tweak: Перевод голосований
/:cl:

2023-11-15 04:28 UTC, dj-34 commented
логи на русском, серьезно?

2023-11-15 04:29 UTC, BR54FF commented
Фаргус

2023-11-15 04:30 UTC, Aylong220 reviewed
Лучше бы перевёл это
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/6bf3b47b-22d5-4b6d-bb99-edcc2192ddc7)

2023-11-15 04:30 UTC, Aylong220 commented on code/modules/vote/vote_datum.dm
> +	var/initiator = "серверу"
```suggestion
	var/initiator = "сервер"
```

2023-11-15 04:32 UTC, BR54FF commented on code/modules/vote/vote_datum.dm
> +	var/initiator = "серверу"
Там разве не будет тогда писаться "голосование за n начато благодаря сервер"? Я в расчёт на это писал с окончанием.

2023-11-15 04:33 UTC, BR54FF commented
Могу и это перевести, если узнаю где это лежит в файлах

2023-11-15 04:36 UTC, Aylong220 commented on code/modules/vote/vote_datum.dm
> +	var/initiator = "серверу"
Ну... да xdd

2023-11-15 04:37 UTC, Aylong220 commented
> Могу и это перевести, если узнаю где это лежит в файлах

Поиск твой лучший друг

2023-11-15 04:45 UTC, BR54FF commented on code/modules/vote/vote_datum.dm
> +	var/initiator = "серверу"
так может нафик тогда......... sadge

2023-11-16 06:12 UTC, PhantornRU requested changes

2023-11-16 06:12 UTC, PhantornRU commented on code/modules/vote/vote_datum.dm
> +			stack_trace("Голосование типа [type] завершилось недопустимым ответом. Ответом был [sanitize(res)], выбором был [json_encode(choices)]")
В первом ты перевел valid как "правильный, а во второй строке invalid - как недопустимым?
Конкретизируй. Используй там допустимый и там недопустимый.

 choices were  - были варианты, были выбраны?, варианты которых:, варианты:
 Но не "выбором был". там же несколько выборов, разве нет?

2023-11-16 16:26 UTC, BR54FF commented on code/modules/vote/vote_datum.dm
> +			stack_trace("Голосование типа [type] завершилось недопустимым ответом. Ответом был [sanitize(res)], выбором был [json_encode(choices)]")
Не помню абсолютно такого типа воута в игре, поэтому не особо вник. Подправил.

2023-11-21 05:47 UTC, Aylong220 commented on code/modules/vote/vote_datum.dm
> +	var/initiator = "сервер"
```suggestion
	var/initiator = "серверу"
```
Ладно, был не прав

2023-11-24 15:02 UTC, PhantornRU approved these changes

2023-11-25 10:37 UTC, Aylong220 approved these changes
Долго валяется, а так, вроде ок

2023-11-25 10:37 UTC, merged