Add: New keys for departments
ss220club/Paradise-SS220 pull request #705
Opened 2023-11-15 07:10 UTC by Kar4es

## Что этот PR делает
Добавляет ключики к отделам.
Так же ключ к вакантному магазину, который будет чуть позже.

## Почему это хорошо для игры
интересный способ попасть в отдел, больше работы для ГП.

## Изображения изменений

## Тестирование

## Changelog

:cl:
add: Теперь у ГП есть ключи для отделов.
/:cl:

2023-11-15 07:13 UTC, Aylong220 commented
Как ты тестил если даже key.dm не заинклюдил в модуль?

2023-11-15 07:13 UTC, Kar4es commented
> Как ты тестил если даже key.dm не заинклюдил в модуль?

блять я его удалил случайно

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		to_chat(user, "<span class='danger'>[src] похоже не подходит к [D] airlock's access panel!</span>")
```suggestion
		to_chat(user, "<span class='danger'>[src] похоже не подходит к панели доступа [D]!</span>")
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:21 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
```suggestion
		return FALSE
```

2023-11-15 07:23 UTC, Kar4es commented on modular_ss220/objects/code/key.dm
> +		return
а зачем? вопрос такой простой

2023-11-15 07:24 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +		return
> а зачем? вопрос такой простой

Понятно что ретурн делает? Мне самому толком не объяснили xdd

2023-11-15 07:26 UTC, Kar4es commented on modular_ss220/objects/code/key.dm
> +		return
да, он возвращает обратно. FALSE там не нужен.

2023-11-15 07:27 UTC, PhantornRU commented on modular_ss220/objects/code/key.dm
> +		return
> > а зачем? вопрос такой простой
> 
> Понятно что ретурн делает? Мне самому толком не объяснили xdd

Если проще, то возвращает данные.
Или булевый статус. Аля "False" - функция чем-то прервалась. "True" - функция дошла до логического завершения и выполнила необходимую операцию.
После чего из прока можно получить значения после выполнения из return, аля return DATA или всё тот же return TRUE. Это же можно использовать для проверок выполнения функции.

2023-11-15 07:29 UTC, Kar4es commented on modular_ss220/objects/code/key.dm
> +		return
> > > а зачем? вопрос такой простой
> > 
> > 
> > Понятно что ретурн делает? Мне самому толком не объяснили xdd
> 
> Если проще, то возвращает данные. Или булевый статус. Аля "False" - функция чем-то прервалась. "True" - функция дошла до логического завершения и выполнила необходимую операцию. После чего из прока можно получить значения после выполнения из return, аля return DATA или всё тот же return TRUE. Это же можно использовать для проверок выполнения функции.

ну необходимости добавлять FALSE нет, правильно?

2023-11-15 07:32 UTC, Gaxeer requested changes

2023-11-15 07:32 UTC, Gaxeer commented on modular_ss220/objects/code/key.dm
> +	var/hack_speed = 5 SECONDS
Комментарии на английский переведи

2023-11-15 07:33 UTC, Gaxeer commented on modular_ss220/objects/code/key.dm
> +	if(!istype(D))
Что такое `D`? Дай нормальное, понятное название переменной, по которому будет понятно что это за перемення

2023-11-15 07:35 UTC, Kar4es commented on modular_ss220/objects/code/key.dm
> +	if(!istype(D))
переменная взята от родителя. D - Door

2023-11-15 07:38 UTC, Gaxeer commented on modular_ss220/objects/code/key.dm
> +	if(!istype(D))
Это не оправдание. Жду исправления

2023-11-15 07:39 UTC, Gaxeer commented on modular_ss220/objects/code/key.dm
> +		return
В этом нет смысла

2023-11-15 07:40 UTC, Gaxeer reviewed
везде где есть return, заменять на return FALSE не имеет смысла, так как это только будет запутывать, по той причине, что результат этого прока не проверяется. А вот возвращаемое конкретное значение, будет создавать иллюзию, что результат обрабатывается

2023-11-15 18:06 UTC, dj-34 requested changes

2023-11-15 18:06 UTC, dj-34 commented on modular_ss220/objects/code/key.dm
> +	name = "\improper Ключ от свободного офиса"
все названия с маленькой буквы
```suggestion
	name = "\improper ключ от свободного офиса"
```

2023-11-15 18:06 UTC, dj-34 commented on modular_ss220/objects/code/key.dm
> +	name = "Коробка с ключами"
```suggestion
	name = "коробка с ключами"
```

2023-11-15 18:06 UTC, dj-34 commented on modular_ss220/objects/code/key.dm
> +	desc = "Обычный немного ржавый ключ"
```suggestion
	desc = "Обычный немного ржавый ключ."
```

2023-11-15 18:06 UTC, dj-34 commented on modular_ss220/objects/code/key.dm
> +		to_chat(user, "<span class='warning'>Ты уже используешь [src] на панели доступа [attacked_airlock]!</span>")
в макросы, проделать также все
```suggestion
		to_chat(user, span_warning("Ты уже используешь [src] на панели доступа [attacked_airlock]!"))
```

2023-11-17 15:39 UTC, Aylong220 approved these changes
Вроде всё ок

2023-11-17 15:39 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +#define ACCESS_VACANT_STORE 401
Вот это только удали

2023-11-17 15:40 UTC, Aylong220 commented on modular_ss220/objects/code/key.dm
> +	new /obj/item/door_remote/key/vacant(src)
```suggestion
```
И это

2023-11-17 17:30 UTC, Gaxeer commented on modular_ss220/objects/code/key.dm
> +		to_chat(user, span_danger ("[src] не хочет вставлятся в панель доступа [attacked_airlock], тут повсюду слизь!"))
кто не хочет?
и что делатЬ - `вставляться`. С мягким знаком

2023-11-17 17:31 UTC, Gaxeer commented on modular_ss220/objects/code/key.dm
> +		to_chat(user, span_danger ("[src] не может поместится в панель доступа [attacked_airlock]!"))
просто `не помещается`

2023-11-17 17:32 UTC, Kar4es commented on modular_ss220/objects/code/key.dm
> +		to_chat(user, span_danger ("[src] не хочет вставлятся в панель доступа [attacked_airlock], тут повсюду слизь!"))
не хочет ключ который src

2023-11-17 17:35 UTC, Gaxeer commented on modular_ss220/objects/code/key.dm
> +	var/cooldown = 0
нигде не используется. И у нас есть отдельные макросы для работы с `cooldown`, а именно в:
code/_DEFINES/tg_cooldowns.dm
ознакомься и потом использую

2023-11-17 18:14 UTC, Gaxeer approved these changes

2023-11-18 10:36 UTC, dj-34 requested changes
Че за грязь у спрайтов по бокам?
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/acd44506-1eeb-467e-b538-bb3b44e14914)

Разве door_remote не будет открывать двери дистанционно?

2023-11-18 13:32 UTC, Kar4es commented
> 1. Че за грязь у спрайтов по бокам?
>    ![image](https://user-images.githubusercontent.com/20109643/283993665-acd44506-1eeb-467e-b538-bb3b44e14914.png)
> 2. Разве door_remote не будет открывать двери дистанционно?

я убрал дистанционную активацию. Если грязь у спрайта синего ключа - он будет потом исправлен. Это можно сказать заготовка на будущее, я его все равно поменять планирую

2023-11-18 13:33 UTC, dj-34 commented
> > 1. Че за грязь у спрайтов по бокам?
> >    ![image](https://user-images.githubusercontent.com/20109643/283993665-acd44506-1eeb-467e-b538-bb3b44e14914.png)
> > 2. Разве door_remote не будет открывать двери дистанционно?
> 
> я убрал дистанционную активацию. Если грязь у спрайта синего ключа - он будет потом исправлен. Это можно сказать заготовка на будущее, я его все равно поменять планирую

убери грязь сейчас, моветон

2023-11-18 13:37 UTC, dj-34 approved these changes

2023-11-18 23:44 UTC, PhantornRU approved these changes

2023-11-20 05:43 UTC, Aylong220 commented
4 галки, думаю можно лить

2023-11-20 05:44 UTC, merged