add: ru-translation procs from wiki
ss220club/Paradise-SS220 pull request #717
Opened 2023-11-16 12:30 UTC by mattgroy

## Что этот PR делает
Добавляет процедуры-хелперы для перевода текста.

Сигнатуры процедур отличаются от описанных в [wiki](https://wiki.ss220.club/index.php/%D0%9A%D0%B0%D0%BA_%D0%B4%D0%B5%D0%BB%D0%B0%D1%82%D1%8C_%D0%BF%D0%B5%D1%80%D0%B5%D0%B2%D0%BE%D0%B4_%D0%B8%D0%B3%D1%80%D1%8B#%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B_%D0%BB%D0%BE%D0%BA%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0%D1%86%D0%B8%D0%B8):

* Гендеризация — `genderize_ru` -> `genderize`
Склонение слова по грамматическому роду является особенностью многих языков и не привязана исключительно к русскому языку.
* Плюрализация — `pluralize_ru` -> `pluralize`
По той же причине, что и предыдущая процедура.
* Склонение единиц измерения — `declension_ru` -> `declension_number`
Склонение слова по грамматическому числу является особенностью многих языков.
* Склонение по падежам — `declent_ru` -> `declension_case`
Глагола declent не существует ("склонять слово" - это "to decline a word", однако название процедуры `decline` может в дальнейшем запутать). Падежи - общее лингвистическое понятие, и они существуют не только в русском языке.
* `ru_names` -> `name_cases`

## Почему это хорошо для игры
Позволяет делать правильный и красивый перевод.

## Тестирование
Задал список name_cases у случайного объекта на карте и добавил все возможные вызовы процедур в коде `/atom/proc/build_base_description()`, выводящего текст при изучении объекта через Shift+Click

2023-11-16 12:49 UTC, mattgroy commented
эт чо блэт
```
[2023-11-16T12:33:06] Runtime in simple_animal.dm,639: type mismatch: null -= the legion (/mob/living/simple_animal/hostile/asteroid/hivelord/legion/tendril)
  proc name: onTransitZ (/mob/living/simple_animal/onTransitZ)
  usr: The legion () (/mob/living/simple_animal/hostile/asteroid/hivelord/legion/tendril)
  usr.loc: The chasm depths (234,33,4) (/obj/effect/abstract/chasm_storage)
  src: the legion (/mob/living/simple_animal/hostile/asteroid/hivelord/legion/tendril)
  src.loc: the chasm depths (/obj/effect/abstract/chasm_storage)
  call stack:
  the legion (/mob/living/simple_animal/hostile/asteroid/hivelord/legion/tendril): onTransitZ
  the legion (/mob/living/simple_animal/hostile/asteroid/hivelord/legion/tendril): forceMove
  the legion (/mob/living/simple_animal/hostile/asteroid/hivelord/legion/tendril): forceMove
  the chasm (234,33,4) (/turf/simulated/floor/chasm/straight_down/lava_land_surface): drop
  the chasm (234,33,4) (/turf/simulated/floor/chasm/straight_down/lava_land_surface): drop
  ImmediateInvokeAsync(the chasm (234,33,4) (/turf/simulated/floor/chasm/straight_down/lava_land_surface), "drop", the legion (/mob/living/simple_animal/hostile/asteroid/hivelord/legion/tendril))
```

2023-11-17 15:19 UTC, Aylong220 requested changes
Всё в модуль перенеси

2023-11-18 11:53 UTC, mattgroy commented
> Всё в модуль перенеси

Я перенёс дефайны в модуль, но при попытке их использования в оригинальном коде (т.к. строчки переводов в конце концов накладываются на оригинальный код), компилятор их не распознаёт:
![image](https://github.com/ss220club/Paradise-SS220/assets/32338709/394b534c-cd54-4558-8dbb-4e60b30e85ab)

Если использовать реальное значение дефайна, то всё работает. Ровно как и если вынести объявление дефайнов из модуля в оригинальный код. Как поступать?

2023-11-21 12:35 UTC, mattgroy commented
Решение с модулем не особо удобное получается в итоге, т.к. заполнение списка `name_cases` нужно будет (по хорошему) заливать ПР-ом в master (с заполнением в модуле), а использование его значений в переводе - ПР-ом в translate.

Кроме того, решение то нихера не модульное, т.к. если отключить созданный модуль, то ссылающиеся на его методы строчки перевода перестанут работать.

2023-11-21 12:37 UTC, Aylong220 commented
> Решение с модулем не особо удобное получается в итоге, т.к. заполнение списка `name_cases` нужно будет (по хорошему) заливать ПР-ом в master (с заполнением в модуле), а использование его значений в переводе - ПР-ом в translate.
> 
> Кроме того, решение то нихера не модульное, т.к. если отключить созданный модуль, то ссылающиеся на его методы строчки перевода перестанут работать.

Модули отключаются только когда (и если) это появляется на оффах

2023-11-21 12:38 UTC, Aylong220 commented
И то не всегда

2023-11-24 15:06 UTC, PhantornRU commented on paradise.dme
> +#include "code\__DEFINES\translation.dm"
не туда занес. Нужно в модуляр подключить

2023-11-24 15:07 UTC, PhantornRU requested changes

2023-11-24 15:07 UTC, PhantornRU commented on code/__DEFINES/translation.dm
> +#define PREPOSITIONAL 6
Вынеси это в модуляр дефайнов

2023-11-24 15:25 UTC, mattgroy commented on paradise.dme
> +#include "code\__DEFINES\translation.dm"
https://github.com/ss220club/Paradise-SS220/pull/717#issuecomment-1817487962

Я же пишу, что дефайны, объявленные в модуле, не видны в скоупе оригинального кода (а это нужно, т.к. перевод накладывается поверх оригинального кода). Объявлял как в своём модуле, так и в модуле `_defines220`, ошибка одна и та же - компилятор не видит этот дефайн.

2023-11-24 15:25 UTC, mattgroy commented on code/__DEFINES/translation.dm
> +#define PREPOSITIONAL 6
https://github.com/ss220club/Paradise-SS220/pull/717#issuecomment-1817487962

Я же пишу, что дефайны, объявленные в модуле, не видны в скоупе оригинального кода (а это нужно, т.к. перевод накладывается поверх оригинального кода). Объявлял как в своём модуле, так и в модуле `_defines220`, ошибка одна и та же - компилятор не видит этот дефайн.

2023-11-27 13:02 UTC, PhantornRU commented
Мерж конфликт :(

2023-11-27 14:30 UTC, mattgroy commented
> Мерж конфликт :(

Resolved :)

2023-12-06 07:39 UTC, PhantornRU commented
В принципе всё устраивает, кроме файла Translation и вынесение файла в общий .dme. Все же попробуй в дефайны просто вписать свои элементы.

2023-12-06 12:49 UTC, mattgroy commented
> В принципе всё устраивает, кроме файла Translation и вынесение файла в общий .dme. Все же попробуй в дефайны модуля просто вписать свои элементы. (в папке модуляра наших дефайнов найди уже работающий файл)

Ну ёшкин кот, я же писал, что если так сделать, то дефайны не будут работать, если обращаться к ним извне модуляра, тупо проект не скомпилируется.

Ради теста, попробуй сам объявить в модуляре какой-нибудь дефайн (или взять уже существующий), а потом обратиться к нему где-нибудь в core коде.

Повторюсь, что обращение к этим дефайнам будет происходить в первую очередь из кор кода, так как перевод осуществляется посредством редактирования оригинального кода, а не оверрайдом всех переводимых методов где-нибудь в модуляре.

Если файл Translation и эдит общего .dme так мозолит глаза, так может нахрен тогда убрать эти дефайны, и к падежам обращаться по цифрам 1-6? Я про это спрашивал [вот здесь](https://github.com/ss220club/Paradise-SS220/pull/717#issuecomment-1817487962) почти МЕСЯЦ назад -_-

2023-12-06 13:26 UTC, PhantornRU commented
В разраб чате нас пингани, будем эту проблему решать, а то мы тебя найти не можем

2023-12-15 06:13 UTC, PhantornRU commented
Всё еще жду

2024-01-05 19:54 UTC, Aylong220 commented
Месяц стоим, откроешь как будут сподвижки х2

2024-01-05 19:54 UTC, closed without merging