Кошели
ss220club/Paradise-SS220 pull request #719
Opened 2023-11-16 16:53 UTC by Sivirus

Добавил в игру 3 кошелька, НТ и СССП. 

## Что этот PR делает
Добавляет в игру 3 кошеля (2 кошеля)

## Почему это хорошо для игры
Потому что не плохо. 

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/142601348/01363a8c-7919-4288-9ef9-459c4109a5e2)

## Тестирование

Не знаю как тестить кошельки. Вопрос: Надо ли?
## Changelog

:cl:
add: Три кошелька, пока только через админ панельку можно получить, если пойму как, кину донатерам.
imageadd: Целых 7 спрайтов
/:cl:

2023-11-16 16:54 UTC, Sivirus commented
Я понимаю что заспрайтил кал. Муне понравилось, я доделал. Все вопросы к Муне.

2023-11-16 16:59 UTC, Aylong220 requested changes
Короче, это пиздец. Ещё и не модульный
Для начала перенеси всё в модуль

2023-11-16 16:59 UTC, Aylong220 commented on code/game/objects/items/weapons/storage/wallets.dm
> +
Во первых, зачем такой большой отступ?

2023-11-16 16:59 UTC, Aylong220 commented on code/game/objects/items/weapons/storage/wallets.dm
> +		/obj/item/screwdriver/power
Во вторых, это явно лишнее, ибо в родителе всё есть, ты добавляешь только скин

2023-11-16 17:00 UTC, Aylong220 commented
И линтер пал
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/16e52ca1-0287-4604-b56f-1d192703b633)

2023-11-16 17:06 UTC, Sivirus commented on code/game/objects/items/weapons/storage/wallets.dm
> +
Отступ, принято. Что значит перенести всё в модуль?

2023-11-16 17:06 UTC, Sivirus commented on code/game/objects/items/weapons/storage/wallets.dm
> +		/obj/item/screwdriver/power
понял.

2023-11-16 17:07 UTC, Sivirus commented on code/game/objects/items/weapons/storage/wallets.dm
> +		/obj/item/screwdriver/power
Что за линтер?

2023-11-16 17:08 UTC, Aylong220 commented on code/game/objects/items/weapons/storage/wallets.dm
> +
> Отступ, принято. Что значит перенести всё в модуль?

У нас всё модульно. Папка modular_ss220

2023-11-16 17:08 UTC, Aylong220 commented on code/game/objects/items/weapons/storage/wallets.dm
> +		/obj/item/screwdriver/power
Внизу тесты

> Что за линтер?

2023-11-17 01:00 UTC, Henri215 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/77684085/37ecd352-1093-49c1-8205-27a79ad147f2)
NT Wallet positioning is wrong

2023-11-21 05:36 UTC, Aylong220 commented
@Sivirus давай в модуль пхай. modular_ss220/objects

2023-11-28 05:00 UTC, PhantornRU requested changes
ПР лежит 2 недели в драфте. Доделываться будет?
Нужно перенести всё в модуль. Пример модуля в коде можешь глянуть, если до сих пор не понятно что это такое - напиши в разрабский чат, мы ж не просто так там сидим.

2023-11-28 05:01 UTC, PhantornRU commented
Сами спрайты хорошие. Нужно разобраться с добавлением через код. Давай это сделаем, заодно научишься. Это не сложно, просто забивать на это не надо

2023-12-02 17:24 UTC, Aylong220 commented
Не создавай новый ПР, лей в этот
Откатывай то что ты сделал и заливай новый вариант, не плодите ПРы в конце концов

2023-12-03 19:03 UTC, Aylong220 requested changes
Молодец, вот так бы сразу.
Исправь пару моментов и почини конфликт, можно мержить.
Плюс там тебе выше говорили что спрайт 1 кошелька на пиксель выше других, починил?

2023-12-03 19:03 UTC, Aylong220 commented on code/game/objects/items/weapons/storage/wallets.dm
> +	var/photo_overlay = "photo"		//edit ss220
В модуль, я ж писал тебе как это сделать в модуле, просто пишешь дерево объекта и под ним добавляешь переменную, как редактировать но добавить

2023-12-03 19:03 UTC, Aylong220 commented on code/game/objects/items/weapons/storage/wallets.dm
> +		name = "[name] displaying [front_id]"		//edit ss220
Не обязательно было писать SS220 EDIT через таб, но да ладно
Однако сам коммент написал не так, во первых, после // пробел
Во вторых, SS220 EDIT большими буквами

2023-12-03 19:03 UTC, Aylong220 commented on modular_ss220/clothing/code/wallets.dm
> +
```suggestion
```
Отступ - 1 строчка
2 уже много

2023-12-03 22:23 UTC, Aylong220 reviewed
Ты добавил предмет, но его никак не достать
Закидывай в лоадаут, там уже есть обычный кошель, естественно это в модуле, так что ищи

2023-12-03 22:23 UTC, Aylong220 commented on modular_ss220/clothing/code/wallets.dm
> +/obj/item/storage/wallet/wallet_NT
```suggestion
	var/photo_overlay = "photo"

/obj/item/storage/wallet/wallet_NT
```

2023-12-03 22:24 UTC, Sivirus commented on modular_ss220/clothing/code/wallets.dm
> +/obj/item/storage/wallet/wallet_NT
Эйлонг. Ты сказал сам будешь в лодаут кидать. Когда я спрашивал надо ли на карту и в лодауты пихать. Что за дела?

2023-12-03 22:25 UTC, Aylong220 commented on modular_ss220/clothing/code/wallets.dm
> +/obj/item/storage/wallet/wallet_NT
Хмм, и правда, ладно, не буду мучать, ужа помучать нельзя

2023-12-05 12:56 UTC, Aylong220 commented
Никто не будет это проверять (скорее всего)
Пока ты не ведёшь ПР с драфта

2023-12-06 07:41 UTC, PhantornRU approved these changes

2023-12-06 10:46 UTC, merged