Awaymission: Black Mesa
ss220club/Paradise-SS220 pull request #724
Opened 2023-11-17 21:44 UTC by konushi

## Что этот PR делает

Пу-пу-пу...
Добавление новой карты для гейта - исследовательский комплекс Black Mesa, в котором произошли не самые приятные метаморфозы с персоналом. Виной тому - пытливый ум ученых, открывший портал в измерение Зен... Лор и некоторые детали были смещены в более космическо-шизофренический мир парадизовского билда. (port/remap "black_mesa" from Skyrat). 
Это ПАРАДИЗОВСКИЙ ремейк от НЕ САМОГО рукастого человека. За бортом оставлены механики атмоса, науки, готовки, оружия, дверей - головоломок, гострольки (возможно будут позднее) и т.д. и т.п. 
Портированы противники, бОльшая часть объектов и структур (и связанных с ними механик), HEV костюм (на момент релиза - не полностью законченный), та самая фомка, поверхности, стены и ОЧЕНЬ надеюсь, что общая атмосфера. 
Портирование оружия было решено отменить и выставить парадизовские аналоги. 
В целом, общая направленность гейта сместилась с головоломок к КСочке, но гейт будет допиливаться и дополняться, возможно даже механиками.
Лут: HEV костюм, та самая фомка, огнестрельное оружие (энфорсеры, ВТ550, m90, беретты, мосинка, наган, дробовики) и боеприпасы к ним, энергетическое оружие (экспериментальные пушки из РНД, иммолятор, темературка, энергетический арбалет), денюжка (5000-7000 тысяч), секретные документы, ядра аномалий, бумажки с технологиями, фраг гранаты, ксено-кристаллы и много еще чего.

## Почему это хорошо для игры

Больше гейтов - больше гейтов. Зачем портировать карты, если можно портировать билд?

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/139562134/7720b6bf-88b7-4b9c-92f3-d1a34000b04c)

## Тестирование
Побегал на локалке, но по прошлому опыту - сейчас будет ужас.

## Changelog

:cl:
fix: С билда Skyrat портирована карта для гейта - Black Mesa. Половина механик, к сожалению, увы. 
/:cl:

2023-11-21 13:54 UTC, konushi commented
блять какой ужас, надеюсь все нормально

2023-11-22 15:56 UTC, Legendaxe requested changes

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +		for(var/k in funny_signals)
Переименовать k из однобуквенной

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +			add_queue('modular_ss220/aesthetics_sounds/sound/hev/blip.ogg',2 SECONDS,purge_queue=TRUE)
```suggestion
			add_queue('modular_ss220/aesthetics_sounds/sound/hev/blip.ogg', 2 SECONDS, purge_queue=TRUE)
```
Мы не платим за пробелы, ниже тоже так сделай

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +		for(var/k in funny_signals)
Переименовать k

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +	for(var/k in funny_signals)
Переименовать k

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +
```suggestion
```
Лучше без пустой строки

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +
```suggestion
```
Лучше без пустой строки

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +			"You try to talk, but the suit restricts your throat..."
в теории конечно мог бы и перевести, но ладно

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +/obj/item/clothing/suit/space/hev/proc/handle_speech(datum/source, mob/speech_args)
тут точно должен быть mob?

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +
```suggestion
```
Лучше без пробела

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +	SOUND_BEEP ('modular_ss220/aesthetics_sounds/sound/hev/beep_3.ogg')
```suggestion
	SOUND_BEEP('modular_ss220/aesthetics_sounds/sound/hev/beep_3.ogg')
```
Тут пробел лучше убрать

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +
```suggestion
```
Лучше без пустой строки

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +	add_queue('modular_ss220/aesthetics_sounds/sound/hev/shok.ogg',3 SECONDS)
```suggestion
	SOUND_BEEP('modular_ss220/aesthetics_sounds/sound/hev/beep_3.ogg')
	add_queue('modular_ss220/aesthetics_sounds/sound/hev/shok.ogg', 3 SECONDS)
```

2023-11-22 15:56 UTC, Legendaxe commented on modular_ss220/clothing/code/hev_suit.dm
> +// //Morphine
А тебе точно нужна такая гора закомментированого  кода?

2023-11-22 16:07 UTC, konushi commented on modular_ss220/clothing/code/hev_suit.dm
> +// //Morphine
я очень надеюсь, что у меня получится эти сигналы переделать. Но уберу

2023-11-22 16:09 UTC, konushi commented on modular_ss220/maps220/code/mobs.dm
> +			if(3000 to 6000)
хп поменял, а числа не поменял, исправлю

2023-11-22 16:11 UTC, konushi commented on modular_ss220/maps220/code/objects.dm
> +	else if(access_list==ACCESS_AWAY01)
а этого не должно было быть вообще, уничтожу

2023-11-22 19:11 UTC, konushi commented on modular_ss220/clothing/code/hev_suit.dm
> +/obj/item/clothing/suit/space/hev/proc/handle_speech(datum/source, mob/speech_args)
да

2023-11-22 19:19 UTC, Legendaxe approved these changes

2023-11-23 05:53 UTC, Aylong220 requested changes
Так, ну начнём потихоньку.
1. Слишком много рандомных спавнеров, как грязи так и крови.
Сделай вручную расставленную грязь, и либо уменьши рандом кровь, либо так же ручками её расставь, ибо это пиздец
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/cfe2d28d-9e0c-48e8-be92-1d0700b2dfa7)
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/6eccada3-6def-4a14-844f-44bcb5443051)

2. Я не знаю, задуман ли тут комп выдающий доступы, но это странно. Хотя учитывая то что гейт на ВЕСЬ раунд, думаю ок.

3. Предлагаю сделать бейзтурф хелперы как в пещерах, где-то в уголку раскидать их все, удобно.

4. Странные места расположения HEV Suit'ов, притом что врагов пиздец как много, мне кажется большая часть кексплореров будет откисать ещё вначале.
Сами же HEV сьюты не в отдельном сторейдже, а через VV, что не хорошо, сделай в отдельном
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/0d805f22-d5d7-42c0-b140-f2d145da1dd9)

5. Турели, ты поставил эммитеры, они стреляют гитсканом, это значит что нет шанса увернуться от плюхи в 30 урона. У самих же турелей 120 прочности, уничтожить её при таком раскладе ОЧЕНЬ сложно. И таких ебанутых противников 14(!)
Поставь им какие-то слабенькие пульки, как в самой халфе, какой-то пистолетный.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/da335b40-0f56-4843-b06e-01fd3f55e5dc)

6. Я бы уменьшил количество врагов, или урон который они дают, их слишком дохуя и шмаляют очередью которая если вся влетит, вводит в крит, я конечно понимаю что гейт сложный пиздец, но он должен быть проходимый, хотя-бы за 2-3 часа.
И желательно быть при этом приятным а не Souls Like

7. Медицины как-то маловато.

8. Нет бейзтурфа
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/bc108c99-4c96-45ca-a38a-c46f406e4b9e)

Пока так, ща в игре посмотрю и ещё напишу

2023-11-23 06:05 UTC, Aylong220 commented
XEN пиздец какой тёмный, сделай подтип к хелперу света, и расставь нужный свет, а то хоть глаз выколи

2023-11-23 06:08 UTC, Aylong220 commented
А доступ зачем?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/5b32ec19-581a-4123-97b9-b1ddde6554d7)

2023-11-23 13:36 UTC, konushi commented
> XEN пиздец какой тёмный, сделай подтип к хелперу света, и расставь нужный свет, а то хоть глаз выколи

накидал фонарей + растений

2023-11-24 13:03 UTC, Aylong220 commented on _maps/map_files220/RandomZLevels/blackmesa.dmm
> +	layer = 10
КХЕМ, в подтип, возможно где-то ещё будет использоваться, а так просто про него никто не ущнает

2023-11-24 13:08 UTC, konushi commented on _maps/map_files220/RandomZLevels/blackmesa.dmm
> +	layer = 10
yes honey...

2023-11-24 13:30 UTC, Aylong220 approved these changes
@Legendaxe будь добр, Когда это замержишь, закомменть гейт на основных серверах, пускай на прайме недельку другую прогонится

2023-11-26 12:06 UTC, dj-34 requested changes
Ты что-то сломал fire_fly2

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/3bf3042f-67b5-48a8-af32-31af72e38345)

2023-11-26 12:19 UTC, dj-34 requested changes
Наслоение декалей по бокам

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/2b4d4a48-3f48-4a29-87b0-8a4f71ad611e)

2023-11-26 14:56 UTC, dj-34 approved these changes
_перекрестился_
остаётся надеяться что с кодом порядок

2023-11-26 20:55 UTC, merged