add: Field Officer
ss220club/Paradise-SS220 pull request #731
Opened 2023-11-18 18:03 UTC by Fullonibus

## Что этот PR делает
Добавляет в игру ПОЦК. 

## Почему это хорошо для игры
Больше боевых вертолётов админам не ломая цепочку верховного командования.

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/38350888/0a20db25-3a06-4029-9212-24cf14a63d37)

## Тестирование

Протестировал иконки, доступы, амуницию, импланты. Хотел сделать через job, но появились проблемы у консоли ХОПа. Остановился на outfit. 
## Changelog

:cl:
add: Добавлен ПОЦК
/:cl:

2023-11-19 05:25 UTC, dj-34 commented on modular_ss220/clothing/code/suits.dm
> +	name = "Полевая форма Офицера Флота Nanotrasen"
```suggestion
	name = "полевая форма офицера флота Нанотрейзен"
```

2023-11-20 19:11 UTC, dj-34 requested changes

2023-11-20 19:11 UTC, dj-34 commented on modular_ss220/outfits/code/outfits.dm
> +	icon_state = "beret_centcom_officer"
Почему полевая форма в clothing, а это здесь?

2023-11-20 20:53 UTC, Fullonibus commented on modular_ss220/outfits/code/outfits.dm
> +	icon_state = "beret_centcom_officer"
я там просто иконку поменял уже у существующей вещи. Тоже поместить в clothing?

2023-11-20 21:02 UTC, dj-34 commented on modular_ss220/outfits/code/outfits.dm
> +	icon_state = "beret_centcom_officer"
> я там просто иконку поменял уже у существующей вещи. Тоже поместить в clothing?

ладно, пофиг - в аутфитах и так насрано, что нужно будет упорядочивать

2023-11-20 21:02 UTC, dj-34 approved these changes
Вроде нормально

2023-11-21 05:33 UTC, Aylong220 approved these changes

2023-11-21 05:33 UTC, merged