More skins
ss220club/Paradise-SS220 pull request #734
Opened 2023-11-19 00:22 UTC by Aylong220

## Что этот PR делает
Добавлено ещё 2 скина на карты
Магическая и без текстуры
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/84865436-f443-4a5d-a530-62413bc6811e)
Первая с анимацией - 4 тир
Вторая без - 3 тир
Так же возвращена старая декаль золотой карты, которая фейкует её

## Почему это хорошо для игры

## Изображения изменений

## Тестирование
Нет конечно

## Changelog

:cl:
add: Добавлено ещё 2 скина на карты. Магический и без текстуры (Чёрно-розовый)
tweak: Вернул золотую наклейку, которая триггерит СБ.
/:cl:

2023-11-19 10:05 UTC, dj-34 requested changes

2023-11-19 10:05 UTC, dj-34 commented on modular_ss220/objects/code/card_skins.dm
> +	name = "\improper магическая наклейка на карту"
магическая наклейка на карту x2

2023-11-19 10:08 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +	name = "\improper магическая наклейка на карту"
Проёб, сделаншь сагест?

2023-11-19 10:26 UTC, dj-34 commented on modular_ss220/objects/code/card_skins.dm
> +	name = "\improper магическая наклейка на карту"
> Проёб, сделаншь сагест? Я уже в постельке просто

название напиши - сделаю

2023-11-19 19:54 UTC, dj-34 requested changes
у вас в pronoun накакано

2023-11-19 19:54 UTC, dj-34 commented on modular_ss220/objects/code/card_skins.dm
> +	pronoun_name = "чёрно-розовую наклейку"
сам ты черно-розовый

2023-11-19 19:54 UTC, dj-34 commented on modular_ss220/objects/code/card_skins.dm
> +	pronoun_name = "кото-клейку"
сам ты кото-клейка

2023-11-19 20:03 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +	pronoun_name = "чёрно-розовую наклейку"
Есть идеи лучше?

2023-11-19 20:03 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +	pronoun_name = "кото-клейку"
Посмотри хоть что pronoun делает

2023-11-19 20:03 UTC, dj-34 commented on modular_ss220/objects/code/card_skins.dm
> +	pronoun_name = "чёрно-розовую наклейку"
> Есть идеи лучше?

при чем тут черно-розовое на уиджи?

2023-11-19 20:04 UTC, Aylong220 commented on modular_ss220/objects/code/card_skins.dm
> +	pronoun_name = "чёрно-розовую наклейку"
А блять, я еблан

2023-11-19 20:19 UTC, dj-34 requested changes

2023-11-19 20:19 UTC, dj-34 commented on modular_ss220/loadout/code/donor.dm
> +/datum/gear/donor/id_decal_kitty_colored
у вас тут дубликат китти колоред на анимешной

2023-11-19 20:54 UTC, Aylong220 commented on modular_ss220/loadout/code/donor.dm
> +/datum/gear/donor/id_decal_kitty_colored
Да ебать мой рот

2023-11-19 20:57 UTC, Aylong220 commented
Вот теперь ТОООЧНО готово

2023-11-19 21:00 UTC, dj-34 requested changes

2023-11-19 21:00 UTC, dj-34 commented on modular_ss220/loadout/code/donor.dm
> +	display_name = "Наклейка на карту в виде терминала "
клуелесс
```suggestion
	display_name = "Наклейка на карту в виде терминала"
```

2023-11-19 21:00 UTC, dj-34 approved these changes
анимешная хуйня выглядит стремно, но все остальное збс

2023-11-20 02:00 UTC, PhantornRU commented
А киберпанк? А стимпанк? А дизельпанк? А биопанк? А атомпанк? А панкпанк? >:C

2023-11-20 02:09 UTC, Aylong220 commented
> А киберпанк? А стимпанк? А дизельпанк? А биопанк? А атомпанк? А панкпанк? >:C

Нарисуй! Ксылипиздишь

2023-11-20 02:27 UTC, PhantornRU commented
> Нарисуй! Ксылипиздишь

и пончик для СБух нужен!

2023-11-21 05:22 UTC, PhantornRU approved these changes

2023-11-21 05:31 UTC, merged