Remap: Delta/Brig/Cargo/Dorms/Procedure/Maintenance/Psych
ss220club/Paradise-SS220 pull request #737
Opened 2023-11-19 13:07 UTC by Hearstrings

## Что этот PR делает
Delta. Изменения отделов карго/бриг/процедурный/дормы. Офисов Детектива, психолога. Технических тоннелей.
На карту добавлены:
1. Вакантный магазин
2. Приемная стойка АВД
3. Камера временного содержания процедурной брига
4. Церковь пермабрига
5. Офис почтальона
6. Заброшенные офисы:
- Механик
- Под пилот
- Психиатрия
- Склад карго
7. Технические тоннели:
- Атриум 
- Аптека
- СУ
- Другие помещения.
Наполнение измененных вышеуказанных отделов и помещений.

## Почему это хорошо для игры
Делает помещения более просторными, логичными и практичными. Имеющиеся отделы получают больше возможностей. Технические тоннели расширены и имеют больше выходов.

## Изображения изменений
![2023-11-20 13 12 27](https://github.com/ss220club/Paradise-SS220/assets/104691597/7eb96649-9fbe-446f-b284-b753f0c53a3f)
![2023-11-20 13 12 31](https://github.com/ss220club/Paradise-SS220/assets/104691597/fb115116-560e-416b-bade-7e8c4c8a638c)

## Тестирование
Все изменения проверяются на локальном сервере.

## Changelog

:cl:
add: 
1. Вакантный магазин
2. Новые помещения в бриге и карго.
3. Заброшенные офисы.
4. Новые теха карго, брига. Небольшие ихменения техов дорм.

del: 
1. Комната визита брига
5. Отдельный blast door спальни ГСБ

tweak: Добавлены шаттеры и/или выключаемые окна в отдехал карго, бриг, процедурны. Небольшие измения тех тоннелей дормов.

fix: Добавлено ограничение по доступы в бриге. Исправлены унылые теха (:::

wip: Потенциал для добавления Бизнесмена в пул ролей (сервис) с последующим выделением отдельного доступа
/:cl:

2023-11-19 19:28 UTC, dj-34 commented
конфликт надо починить

2023-11-19 19:37 UTC, Aylong220 commented
Ебать чейнджлог, кто такое будет читать? Давай покороче

2023-11-19 19:42 UTC, dj-34 commented
Да, вынеси что написал в чейнджлоге в "Что делает этот PR", в чейнджлоге напиши кратко, типа "add: Дельта: Переработка восточной части станции"

2023-11-19 19:44 UTC, Aylong220 commented
Кхм, обнови ветку и почини конфликты.
Хотя судя по тому насколько твоя ветка старая, лучше выдели кусок карты который ты поменял, сохрани в отдельный файл, обнови ветку, закинь в ветку дельту с мастера, и наложи на неё свои изменения
https://affectedarc07.blob.core.windows.net/mdb2/images/661116452/18825454789/m/_maps_map_files220_delta_delta/0-diff.png

2023-11-20 07:55 UTC, Aylong220 requested changes

2023-11-20 07:55 UTC, Aylong220 commented on icons/turf/areas.dmi
Иконку в "modular_ss220\maps220\icons\areas.dmi"

2023-11-20 10:54 UTC, dj-34 requested changes
### Пошло первое ревью, потом посмотрю в редакторе еще

В зале суда пропали затемненные окна, аирлоки так и не были перекрашены, зачем нужно было перемещать НТшные флаги от статуи? Это выглядит странно.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/436d041e-d38a-4799-9368-852e66257c8d)

Ты как умудрился повернуть монитор на мостике?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/415b375a-ebba-482f-9b58-8edeed52c30b)

У вас зеркало на полу оказалось, почему вообще техи южно-восточные были затронуты? Так и должно быть?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/7984bcde-88bf-4f74-bdb1-199769bd0d7c)
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/6e333ae8-9014-4557-bae5-a8dfc08fb89e)

Нет аирлока

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b4eb5c10-903e-4582-9a61-4707e22771a9)

Мб сюда воткнуть стульчик и автомат с сигами?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b0c7823b-4c7b-4f74-bc79-85d9c21178c3)

А где рычаг управления конвеерными лентами?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/8a699c84-25f2-495a-8f0a-afd40e74f395)

Верхние декальки выглядят лишними, сюда можно засунуть marker beacon (docking marker beacon)

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/987a43bc-1c2c-4d75-9bb1-e3cb6204cdc3)
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/0805eff1-6c66-45fb-8fa6-81064ad8e957)

Заслонку забыл

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/004bdcdf-dfde-4439-8827-a1c66be57744)

Наверное здесь было бы логичнее убрать забор где проходит стеклянный пол

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/015d4d94-ff17-46ae-95ef-ed65a862ac99)

Не думаю что нужен доступ на внешнюю дверь

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b0848f2d-4e40-4e89-8f65-ed0e4dfcff8b)

2023-11-20 13:08 UTC, dj-34 commented
А чоу, зачем?
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/783756d9-02a7-4d69-abeb-d50c9ca3d630)

А здесь чего аирлоки не покрасил? И где кнопка затемнения окон в зале суда?
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/5fcd25fa-3f5c-46ea-ac95-09bd8dedfc8e)

2023-11-20 19:49 UTC, dj-34 requested changes
Добавь с Кибериады Nanomob

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/6a49c005-c742-48ac-90b3-3c3311a9c024)

Ты если ставишь name на аирлок, то убирай autoname helper, или наоборот

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/e90a52a1-3e86-4ea9-8da7-02d2fc991117)

Паутинку можно было бы заменить на её спавнер

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/0f52ef73-48b7-4c0b-a1a2-45f17d9cbe0c)

Bedroom?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/565b340b-b87f-41c8-bc86-e2bc0188b3fb)

Дубликат cell 1

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/1505143f-30d9-4341-aecc-66b0301a8d03)

Замени напольный прожектор на dock_marker

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/10646990-f890-4305-ad35-584e3e06dc68)

Убери name, уже есть autoname helper

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/3ff151b1-c10c-4855-a961-e448a06b914a)

Corpse disposal unit?... :jokerge:

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/d3a80499-f605-4e96-91ab-8baac9313765)

Мусорная труба проебалась

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/033a1e4d-0fb5-4c72-a54d-b8fc2f368596)

desc с большой буквы

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/10a9c571-51a6-4156-85f3-9f631c62ad18)

windoor без доступов и имени... и второй у печки зачем?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/d180bb75-742c-4d34-97a5-c0d0b65d5f46)

Лишний скраббер у каргонцев

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/fa990907-ab80-43bb-9ad2-d754d1464d2c)

Труба в никуда

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/c5a1f885-7fe3-4834-bb3b-e35fc7bb6778)

Массовые обрывы труб аиринжекторов в перме

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/527e5b95-363c-4dcc-b41e-d2f02eb8a89c)
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/88101a03-c048-454c-8402-7bdb41d68eb7)

Лишний кабель

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/7b7c4455-3f99-4680-8cf6-c83d9f4a4846)

Обрывы проводки в перме

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/4e206cd1-714a-4bf9-b862-070e1a157a31)

Пиздорез на окнах

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/3dda2bfe-a460-4d33-bd59-f5b1db2de9c9)

В перме окна без электрификации

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b4899ac9-a271-4b0c-b8ba-9dd6438c849a)

Обрыв проводки

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/f71efcb1-5009-4737-8ccd-7e5e2aa01dd3)

Аирлоки в туалетные цвета можно покрасить, название прописать

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/90fabe6c-1643-4b9b-9312-6e779b4820db)

Аирлоки в перме без доступов

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/660cf0da-d754-4272-9047-c4afb57f2c69)

2023-11-20 19:49 UTC, dj-34 commented on modular_ss220/maps220/code/Areas/station.dm
> +	icon_state = "vacantoffice"
Похоже ты забыл
```suggestion
	icon_state = "vacantstore"
```

2023-11-20 20:26 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
> +	icon_state = "vacantoffice"
Аирлоке в перме без доступов, потому что это спальни пермовцев, там вообще нигде доступы не надо кроме техов и выхода

2023-11-23 06:58 UTC, Aylong220 requested changes
Первая часть, техи меда/дорм и сами дормы

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
> +/area/station/security/podpilot
```suggestion
/area/station/security/podpilot
```
Вылезает зона техов в космос
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/d57128c5-2136-47e1-b76c-17acee44a48f)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "\improper Pod Pilot Bay"
```suggestion
	name = "\improper Pod Pilot Bay"
```
Давай так, а то шкаф можно будет случайно подвинуть
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/50e97a2e-7b56-41ad-9b56-7ecf5c815e5e)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
> +	icon_state = "security"
```suggestion
	icon_state = "security"
```
Куда лампу стырил?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/5296a745-b176-4fb4-acde-500a4368a726)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
> +
```suggestion

```
Сейф под скраббером
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/4789e973-5343-4639-9c87-958b5aefdb9c)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
>  /area/station/bridge/checkpoint
```suggestion
/area/station/bridge/checkpoint
```
Цветок в угол
Убрать спавнер ржавчины с пола
Добавить нехватающий кусочек зоны
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/d7e976d7-7400-4744-addc-4ce2078894e0)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
>  	name = "\improper Command Checkpoint"
```suggestion
	name = "\improper Command Checkpoint"
```
3 рандомных напитка на одном столе, дохуя как-то
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/cd591d3c-03b1-490b-a861-0cc50eefa281)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
```suggestion

```
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/378a6ba7-8bfe-4b90-b83f-44e8738b4df2)
Активный скраббер, не надо.

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
>  	name = "\improper Engineering Utility Room"
```suggestion
	name = "\improper Engineering Utility Room"
```
Вот этот цветок тут лишний, раздражать только будет,
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/a0d7ea7b-046b-448d-8793-217c815230c1)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
>  	icon_state = "engimaint"
```suggestion
	icon_state = "engimaint"
```
Отдельную зону поставь в заброшенную дурку.
Возьми с дурки на коробке.
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/ba1eb224-efa3-456e-b5a2-a4e9e5756b6f)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
```suggestion

```
Не то АПЦ, для крио специально ставится, на 25к - /obj/machinery/power/apc/cryo/south
Так же, не используй - /obj/machinery/cryopod/right
Просто поменяй dir у обычного
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/05018ce6-c7f1-42e3-b43d-fb0475d22bac)

Туда же, странное название камеры, возьми с коробки
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/66361cda-f260-4bb3-9107-9d5ba63af5e0)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
> +/area/station/engineering/mechanic
```suggestion
/area/station/engineering/mechanic
```
А где?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/8ae1a965-ee7c-4abb-a790-e936d853a691)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "\improper Pod Mechanic Bay"
```suggestion
	name = "\improper Pod Mechanic Bay"
```
Хмм, халявное мыло кэпа...
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/74870c7b-fbbd-4cfd-bc12-ce4970035b84)

2023-11-23 06:58 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
> +	icon_state = "engi"
```suggestion
	icon_state = "engi"
```
Чёт у тебя маркеры ботов не по центру, брал с офф карты?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/5013c24e-854f-4c32-bab2-e859d188eeab)

2023-11-23 07:14 UTC, Hearstrings commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "\improper Pod Mechanic Bay"
убрал

2023-11-23 07:15 UTC, Hearstrings commented on modular_ss220/maps220/code/Areas/station.dm
исправил

2023-11-23 07:43 UTC, Aylong220 requested changes
По техам СБ.
1. Убери флаффи наручники
2. Слишком много лута
3. Зона в космосе (2 пикча)

![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/fdbca9ec-7fdf-41fb-8e09-d12c9e7b541e)
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/7c67e5b3-cb47-4adf-ab2e-a3169bef46f7)

По суду.
1. Провода подвинь правее, шоб не были под статуей
2. Голопад центрируй
3. У магистрата было какое-то животное. Фенёк, песчаная лисичка
4. Расположение выключателя света странное, поставь его под лампу напротив двери.
5. Помойка не подключена
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/a2d1d519-8e05-43e8-b013-3c3ac00816ed)

Дефектив.
1. Пустовато, добавь автомат с кофе и стульчик на входе
2. Стекло лишнее
3. Камеру подвинь пониже
4. Ставни лишние
6. Передвинь выключатель света
7. Передвинь файр алярму на старое место выключателя, и удали вторую
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/01bd6ff9-b25d-40fe-8eb8-6eb93254f590)

Камеру повыше, стак машинерии в одном тайле, желательно избегать
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/eb0a3d74-a36b-4803-9b35-d1f4a3bec389)

Убери вторую алярму
Раздвинь пониторы, шоб спрайты не стакались
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/3fb04f4b-f6b8-472f-988a-d220471e68e5)

Убери со спальни файр алярму
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/5fd0d117-5d18-47e1-a582-8ff98f682c4a)

Не подключён распылитель газа
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/f2f33f30-e31d-4d96-b9cf-098508ea358b)

Передвинуть
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/e283a158-21b3-4d18-a602-4f4c30f5029a)

Я бы заменил лампочки с обычных на маленькие, и поставил их напротив, для гнетущей атмосферы
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/fefeeb4e-2b80-4320-8e94-77ce2b18b584)

Передвинуть
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/4e42fa2c-9f5f-4928-88b2-e4ccde2ecc64)

Окна в оружейку без липиздричества
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/d51e3992-798d-4168-8725-bf2fdbe281a5)

В техах между СБ и Карго, слишком дохуя лута, подрезай половину.

2023-11-23 22:46 UTC, Aylong220 approved these changes
Больше проблем не вижу, ждём диджея

2023-11-25 09:58 UTC, Aylong220 commented
Конфликт? Откуда ёпт?

2023-11-26 09:16 UTC, dj-34 requested changes
Покрасить бы аирлоки в белый и дать названия

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/17598c6e-9aca-434c-b3d7-d6e2f614160d)

Что за аирлоки с названием "Cabin"? Это что вообще значит?
Также стоит поменять их на "public" вариант с стёклами

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/5de776b7-4ac8-484c-9ec5-13ec470096c7)

Мб аирлоки голодека стоило бы перекрасить в "public"?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/128c645f-6635-41b3-ad92-5efd5b994b78)

В перме так и просятся цикличные аирлоки по кнопке (по примеру с Кибериады)

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b09b9929-3d12-41fd-9762-787fa1e93fe2)

На самом деле странно что вот эти румы у тебя выполняют функцию спален, когда на Кибериаде это что-то вроде изолятора внутри пермабрига... Впрочем, дело твоё
Также в перме все еще не названы аирлоки, например: Chapel, Shower, Garden и т.п.

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/ba360a8d-9a5d-419d-b8a2-1570d24faf64)

Шторки будут просвечивать, потому что ты не назначил им opacity 1

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/dafb0812-3894-4ecd-9003-40538e041ab1)

Вот эти полоски по прежнему выглядят не к месту

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/723ff351-e33a-475e-b4c8-caf08f40cfbf)

2023-11-26 09:17 UTC, dj-34 commented
Пойду в игре еще гляну

2023-11-26 09:52 UTC, dj-34 requested changes
### Надеюсь финальное ревью

Почему здесь так светло? Вроде бы оно заброшено, куда столько энергии тратить...

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/a9dfd984-72cc-4ae0-b5f6-c4d068c6b89f)

Выглядит странно, может просто плейтинги поставить?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/3f05cef9-968d-4495-be99-cdbcc48c7c8e)

Нет решетки в стекле. Так и задумано?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/54a58bb2-1a1f-4a44-a0a8-eea8ce56a252)

Вот эта мусорку ведущая экскурсию через всю станцию - это ПИЗДЕЦ

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/da5e619b-2d2e-4dde-8813-474d1df82e83)

Поставь двойные аирлоки в подтип glass (у нас без glass толком не работают нормально)

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b3f295d6-14f3-4050-86d6-c83285c80d7d)

Замени двойные на подтип glass, либо сделай просто два одинарных аирлока (я бы предпочёл два одинарных ради side helper'а)

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/d79d253a-1111-43d9-b40f-33533826d6aa)

Очень много паутины, её бы в спавнер

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/f926f403-dad0-46f5-80ed-c6ea471d0c96)

А куда marker beacon'ы пропали? Я же просил тип docking beacon поставить

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/9cc70f2f-cc4d-493c-83d9-d2a7524c1ee1)
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/9524202e-0261-46e9-af37-5973b7331fc5)

Нет затемнения у стёкл

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/e912b3cd-8d64-429b-a9c3-da5989c04921)

Может разнообразить наполнение камер по примеру с Кибериады? Например где-то ссаный матрас, где то обычный, где-то кровать, коврик...

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/eb4a2397-a9e9-4a4c-9c67-b3ae0c9cb1e5)

На КПП всегда была консоль менеджмента Гулага? Че она там делает...

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/2baaf237-d6e7-4139-b6f3-ddb9c0b5198b)

Зону nearstation ебани на catwalk

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/e11f4730-5679-49d6-8cd3-9d361a7b4c47)

2023-11-27 13:05 UTC, PhantornRU approved these changes

2023-11-27 13:07 UTC, PhantornRU commented
Осмотрел, меня устраивает.
Разве что по камерам соглашусь, но нужно наполнение аля беговые дорожки/ковры/ссаные матрасы.

2023-11-27 13:35 UTC, dj-34 requested changes
Лишний opacity 1

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/049de544-fe27-488c-9897-5288132d10ff)

Пропали имена у дверей Голодека

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/dc2c1929-d3f7-4c42-af47-a1b0f3bc91f1)

Хелпер автонейма проебался?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/ae9d53e0-06b7-4d73-a6fa-f3bf8f624d2f)

Здесь забыл в подтип glass засунуть двойной

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/cfc78e61-7c16-4996-b73d-1e326b7d9e3c)

Вот этот двойной аирлок будет просвечивать с затемнением (возвращаемся к тому, что двойной аирлок дырявый)

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/48a39e7e-b959-4e84-b779-e470aa499878)

2023-11-27 14:05 UTC, dj-34 approved these changes

2023-11-27 14:16 UTC, Aylong220 commented
Тесты почини
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/f52aa7d6-3a4e-498f-bc13-b0c57fabbfdd)

2023-11-27 14:27 UTC, merged