Some translates
ss220club/Paradise-SS220 pull request #741
Opened 2023-11-20 03:17 UTC by Aylong220

## Что этот PR делает
Переводит следующие вещи:

- Черноглазое варево
- Забаненный плод
- Слоганы вендоров
- Синдром Туретта
- Поли
- Ступид спич при повреждении мозга

Возможно будет дополняться

## Почему это хорошо для игры

## Изображения изменений

## Тестирование

## Changelog

:cl:
add: Что-то добавил
del: Что-то удалил
tweak: Поменял что-то по мелочи
fix: Что-то починил
wip: Какие-либо наработки в процессе
soundadd: Добавил новый звук
sounddel: Удалил старый звук
imageadd: Добавил новую картинку
imagedel: Удалил старую картинку
spellcheck: Исправил опечатку
experiment: Добавил эксперементальную функцию
/:cl:

2023-11-20 03:23 UTC, PhantornRU commented on code/game/dna/mutations/disabilities.dm
> +				H.say("[prob(50) ? ";" : ""][pick("ДЕРЬМО", "МОЧА", "БЛЯТЬ", "ПИЗДА", "ХУЕСОС", "УБЛЮДОК", "СИСЬКИ", "ХУЙ", "ЖОПА", "КОКПИТАН", "ХОС ХУЕСОС", "РД УЁБОК", "ПОШЁЛ НАХУЙ", "ВЫБЛЯДОК", "ОТСОСИ", "ДОЛ
Заносим пару цитат из Крови и Бетона
```suggestion
				H.say("[prob(50) ? ";" : ""][pick("ДЕРЬМО", "МОЧА", "БЛЯТЬ", "ПИЗДА", "ХУЕСОС", "УБЛЮДОК", "СИСЬКИ", "ХУЙ", "ЖОПА", "КОКПИТАН", "ХОС ХУЕСОС", "РД УЁБОК", "ПОШЁЛ НАХУЙ", "ВЫБЛЯДОК", "ОТСОСИ", "ДОЛБОЁБ", "КУКУРУЗА", "УБЛЮДОК", "МАТЬ ТВОЮ", "ГОВНО СОБАЧЬЕ", "ЕБАТЬ ТЕБЯ", "ОНАНИСТ ЧЕРТОВ", "ЕБАТЬ")]!")
```

2023-11-20 03:25 UTC, Aylong220 commented on code/game/dna/mutations/disabilities.dm
> +				H.say("[prob(50) ? ";" : ""][pick("ДЕРЬМО", "МОЧА", "БЛЯТЬ", "ПИЗДА", "ХУЕСОС", "УБЛЮДОК", "СИСЬКИ", "ХУЙ", "ЖОПА", "КОКПИТАН", "ХОС ХУЕСОС", "РД УЁБОК", "ПОШЁЛ НАХУЙ", "ВЫБЛЯДОК", "ОТСОСИ", "ДОЛ
Бля, вот бы с некоторым шансом добавить фулл цитату

2023-11-20 03:52 UTC, PhantornRU commented on code/game/machinery/vendors/contraband_vendors.dm
> +					"Не верьте исследованиям - курите сегодня!")
Цитаты из фильмов и не только
```suggestion
	slogan_list = list("Космосигареты хороши на вкус, какими они и должны быть.",
					"Курение убивает, но не сегодня!",
					"Курите!",
					"Не верьте исследованиям - курите сегодня!",
					"Обслужите даме рот!",
					"Сигаретку, спичку, коробок?",
					"Минздраву на заметку. Люди, покупающие сигареты поштучно, не знают, что курение убивает.",
					"Кури - убей в себе коня!",
					"Ты уже бросаешь? Тогда начни вновь курить!",
					"Сегодня мужчина считается джентльменом, если перед поцелуем он вынимает сигарету изо рта.",
					"Если есть в кармане пачка сигарет - значит всё не так уж плохо на сегодняшний день!",
					"И билет на самолёт с серебристым крылом, что, взлетая, оставляет земле лишь тень.",
					"Что мне больше всего нравится в работе - это перекуры!",
					"Своим здоровьем и долголетием я обязан тому, что ни разу не прикоснулся ни к сигарете, ни к рюмке, ни к женщине, пока мне не стукнуло десять.",
					"Если стрелять, то максимум сигареты. Если взрывать, то минимум танцпол!",
					"Пока у человека есть сигареты - он многое вынесет.",
					"Гаси свою вспышку гнева разжигая сигарету!",
					"Окурок — это сигарета с богатым жизненным опытом.",
					"Водка, хлеб, сигареты — без этого люди не проживут, мы этим предприятиям помогаем!", // реальная цитата Лукашенко
					"В своей нелёгкой жизни, я два «безбашенных» поступка совершил. Не закурил от беса сигарету и тату на тело не набил!",
					)
```

2023-11-20 03:53 UTC, Aylong220 commented on code/game/machinery/vendors/contraband_vendors.dm
> +					"Не верьте исследованиям - курите сегодня!")
Ты же в курсе что это ПЕРЕВОД?

2023-11-20 03:54 UTC, Aylong220 commented on code/game/machinery/vendors/contraband_vendors.dm
> +					"Не верьте исследованиям - курите сегодня!")
Если так это хочешь
То создавай отдельный ПР и перезаписывай слоган лист xdd

2023-11-20 03:59 UTC, PhantornRU commented on code/game/machinery/vendors/contraband_vendors.dm
> +					"Вдвое больше калорий за полцены!")
```suggestion
	slogan_list = list("Попробуйте наш новый батончик с нугой!",
					"Вдвое больше калорий за полцены!",
					"Один мальчик прожил без еды три года, потому что бутерброды — это не еда.",
					"Смертность от хачапури намного выше, чем смертность от харакири.",
					"Самая чистая и простая любовь — это любовь к еде.",
					"Сыр – это труп молока.",
					"Нет плохих блюд, есть плохо приготовленные.",
					"Чаще аппетит приходит во время отсутствия еды.",
					"Курица — это не птица, курица — это еда такая.",
					"Назло врагам, съешь ужин сам.",
					"Курица — существо, которое едят либо до его рождения, либо после его смерти.",
					)
```

2023-11-20 04:00 UTC, PhantornRU commented on code/game/machinery/vendors/contraband_vendors.dm
> +					"Не верьте исследованиям - курите сегодня!")
А ведь точно, верно подметил

2023-11-20 04:29 UTC, PhantornRU commented on code/game/machinery/vendors/departmental_vendors.dm
> +					"Также доступны некоторые сорта грибов для специалистов! Станьте им уже сегодня!")
```suggestion
					"Доступны разнообразные сорта грибов для специалистов! Станьте им уже сегодня!")
```

2023-11-20 05:28 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"БВАААК джордж меллонс гриффит меня"
Гриффит - у нас не используйется. Джордж меллонс непонятная хуйата.
```suggestion
		"БВАААК повар хочет жареного попугая!"
```

2023-11-20 05:30 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"Не ешь запретный начо!",
Чиво...

2023-11-20 05:30 UTC, Aylong220 commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"БВАААК джордж меллонс гриффит меня"
> Гриффит - у нас не используйется. Джордж меллонс непонятная хуйата.

Джордж Меллонс - известный грифер СС13

2023-11-20 05:30 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/parrot.dm
> +	clean_speak += "Опасность! Нарушение целостности гиперструктуры кристалла! Целостность: [rand(75, 99)]%" // Has to be here cause of the `rand()`.
Я думал оно у нас переведено уже

2023-11-20 05:31 UTC, Aylong220 commented on code/modules/mob/living/simple_animal/parrot.dm
> +	clean_speak += "Опасность! Нарушение целостности гиперструктуры кристалла! Целостность: [rand(75, 99)]%" // Has to be here cause of the `rand()`.
Это фраза Поли

2023-11-20 05:31 UTC, Aylong220 commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"Не ешь запретный начо!",
Хз, перевёл чё было

2023-11-20 05:31 UTC, PhantornRU commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +		to_chat(M, "<span class='notice'>Вы на мгновение чувствуете себя сверхтяжёлым, как чёрная дыра. Возможно, это просто ваше воображение...</span>")
Какая же тупая фраза на английском. Сверхтяжелым как черная дыра звучит тупо.

2023-11-20 05:31 UTC, PhantornRU commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +		to_chat(M, "<span class='notice'>Вы чувствуете себя слегка помолодевшим!</span>")
```suggestion
		to_chat(M, "<span class='notice'>Вы чувствуете себя помолодевшим!</span>")
```

2023-11-20 05:32 UTC, PhantornRU commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +		to_chat(M, "<span class='notice'>Вы чувствуете себя слегка помолодевшим!</span>")		//meta this!
```suggestion
		to_chat(M, "<span class='notice'>Вы чувствуете себя помолодевшим!</span>")		//meta this!
```

2023-11-20 05:33 UTC, PhantornRU commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "БЭДМИН", "ПУНПУН")]!",
```suggestion
									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "ОЦИФЕР ЦК", "ПУНПУН")]!",
```

2023-11-20 05:34 UTC, PhantornRU requested changes
Посмотрел, в принципе нормалды. Мелкие замечания только

2023-11-20 05:34 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/parrot.dm
> +	clean_speak += "Опасность! Нарушение целостности гиперструктуры кристалла! Целостность: [rand(75, 99)]%" // Has to be here cause of the `rand()`.
точно

2023-11-20 05:34 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"Не ешь запретный начо!",
так нужно ж не прямой перевод, но и адаптацию

2023-11-20 05:35 UTC, Aylong220 commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "БЭДМИН", "ПУНПУН")]!",
Буду стоять до конца за БЭДМИНа

2023-11-20 05:40 UTC, PhantornRU commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "БЭДМИН", "ПУНПУН")]!",
Да хоть БЭД БОЯ, но админ - это ООС термин, он не должен использоваться в игре.

2023-11-20 05:41 UTC, PhantornRU commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "БЭДМИН", "ПУНПУН")]!",
Вдовесок у нас БЭДМИН даже в ООС не используется. Это НЕ НАШЕ слово. Ты даже не попытался его локализовать под нас.

2023-11-20 05:41 UTC, Aylong220 commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "БЭДМИН", "ПУНПУН")]!",
Исключительный случай XyliPizdish

2023-11-20 08:37 UTC, PhantornRU commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "БЭДМИН", "ПУНПУН")]!",
Я запрещаю исключительные случаи. Нужно локализовать!

2023-11-20 08:37 UTC, Aylong220 commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "БЭДМИН", "ПУНПУН")]!",
> Я запрещаю исключительные случаи. Нужно локализовать!

Тогда убирай "щиткур" XyliPizdish

2023-11-20 08:38 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"БВАААК джордж меллонс гриффит меня"
Кому известный KEKW? Первый раз о нем услышал. Буквально.

2023-11-20 08:38 UTC, Aylong220 commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"БВАААК джордж меллонс гриффит меня"
> Кому известный KEKW? Первый раз о нем услышал. Буквально.

Загугли, в наших кругах не известный, но колоритную отсылку не хочется губить

2023-11-20 08:42 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"БВАААК джордж меллонс гриффит меня"
Проблема в том что в русскоязычном сообщества нельзя губить то, чего нет. Буквально, практически все шусстайдовцы не знают кто это такой и никогда не узнают. Дорогу молодым!

2023-11-20 08:42 UTC, Aylong220 commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"БВАААК джордж меллонс гриффит меня"
> Проблема в том что в русскоязычном сообщества нельзя губить то, чего нет. Буквально, практически все шусстайдовцы не знают кто это такой и никогда не узнают. Дорогу молодым!

Нуэно помнить старое XyliPizdish

2023-11-20 08:43 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/parrot.dm
> +		"БВАААК джордж меллонс гриффит меня"
Это чужая культура! XyliPizdish

2023-11-20 10:19 UTC, dj-34 requested changes

2023-11-20 10:19 UTC, dj-34 commented on code/game/machinery/vendors/generic_vendors.dm
>  					"Award-winning chocolate bars!",
```suggestion
	ads_list = list("Самые полезные!",
					"Удостоенные наград шоколадные плитки!",
```

2023-11-20 10:19 UTC, dj-34 commented on code/game/machinery/vendors/generic_vendors.dm
> +					"Шоколад со множеством наград!",
```suggestion
	ads_list = list("Самые полезные!",
					"Удостоенные наград шоколадные плитки!",
```

2023-11-20 10:19 UTC, dj-34 commented on code/game/machinery/vendors/generic_vendors.dm
> +					"На здоровье!")
Вообще, речь идет конкретно о наркотиках, но не уверен что это будет легально переводить LUL

2023-11-20 10:19 UTC, dj-34 commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +		to_chat(M, "<span class='notice'>Вы чувствуете себя слегка помолодевшим!</span>")
```suggestion
		to_chat(M, "<span class='notice'>Вы чувствуете себя немного моложе!</span>")
```

2023-11-20 10:19 UTC, dj-34 commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +		to_chat(M, "<span class='notice'>Вы чувствуете себя слегка помолодевшим!</span>")		//meta this!
```suggestion
		to_chat(M, "<span class='notice'>Вы чувствуете себя немного моложе!</span>")		//meta this!
```

2023-11-20 10:19 UTC, dj-34 commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +	to_chat(M, chat_box_red("<span class='adminhelp'>ЛС от <b>Администратор</b>: БВОНЬК!</span>"))
Возможно не стоит переводить

2023-11-20 10:19 UTC, dj-34 commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"СЕКРЕТНАЯ ТЕХНИКА: НА СТОЛ И В МУСОРКУ!",
Возможно так будет правильнее
```suggestion
									"СЕКРЕТНАЯ ТЕХНИКА: ОБ СТОЛ И В МУСОРКУ!",
```

2023-11-20 10:19 UTC, dj-34 commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "БЭДМИН", "ПУНПУН")]!",
распизделись тут xylipizdish

2023-11-20 14:59 UTC, PhantornRU commented on code/modules/reagents/chemistry/reagents/paradise_pop.dm
> +									"ЭТО СДЕЛАЛ [pick("МОЙ БРАТ", "МОЙ ПЁС", "МОЙ ЛУЧШИЙ ДРУГ", "БОРЕР", "ДЖОРДЖ МЕЛЛОНС", "БЭДМИН", "ПУНПУН")]!",
одобряю убрать щиткура

2023-11-20 20:45 UTC, PhantornRU approved these changes

2023-11-21 16:58 UTC, ImJustKisik commented on code/game/machinery/vendors/generic_vendors.dm
> +					"Зачем бросать стиль на воле судьбы? Воспользуйтесь ClothesMate!")
Очепятка

2023-11-21 22:53 UTC, Legendaxe approved these changes

2023-11-21 22:57 UTC, dj-34 approved these changes
По переводу должно быть ок

2023-11-21 23:21 UTC, merged