Port shuttle sounds from RuPara
ss220club/Paradise-SS220 pull request #767
Opened 2023-11-25 19:31 UTC by BoryaYeltsin

## Что этот PR делает
Добавляет микрошаттлам звук перелёта. Меняет звук эвакуационному шаттлу.
Где-то ещё вроде был ишью на эту тему

## Почему это хорошо для игры
Звук микрошаттлам меняется модульно, как сделать то же у эвакуационного не додумался. Посмотрел прошлые ПРы на изменение звука, путь меняли хардкодом xdd
Если критично, можно зарезать немодульные изменения и оставить звук микрошаттлам.

## Тестирование
Trust me bro

## Changelog

:cl:
soundadd: Портировал звук шаттлу шахты и каторги. Портировал звук Харону
/:cl:

2023-11-25 22:53 UTC, dj-34 requested changes
Перенеси shuttle_sounds в модуль aesthetics_sounds, не нужно создавать для этого отдельный модуль

2023-11-25 22:53 UTC, dj-34 commented on code/modules/shuttle/emergency.dm
> +				var/hyperspace_end_sound = sound('modular_ss220/shuttle_sounds/sound/hyperspace_end_new.ogg')
```suggestion
				var/hyperspace_end_sound = sound('modular_ss220/shuttle_sounds/sound/hyperspace_end_new.ogg') // SS220 EDIT
```

2023-11-25 22:53 UTC, dj-34 commented on code/modules/shuttle/emergency.dm
> +				var/hyperspace_progress_sound = sound('modular_ss220/shuttle_sounds/sound/hyperspace_progress_new.ogg') //SS220 EDIT
```suggestion
				var/hyperspace_progress_sound = sound('modular_ss220/shuttle_sounds/sound/hyperspace_progress_new.ogg') // SS220 EDIT
```

2023-11-25 22:53 UTC, dj-34 commented on code/modules/shuttle/emergency.dm
> +				var/hyperspace_sound = sound('modular_ss220/shuttle_sounds/sound/hyperspace_begin_new.ogg') //SS220 EDIT
```suggestion
				var/hyperspace_sound = sound('modular_ss220/shuttle_sounds/sound/hyperspace_begin_new.ogg') // SS220 EDIT
```

2023-11-26 05:41 UTC, Aylong220 commented on modular_ss220/shuttle_sounds/_shuttle_sounds.dm
> +	author = "HelmsDeepState, Captainelly, Furrior"
Я бы делал это в модуле aesthetics_sound, дабы не срать отдельными модулями

2023-11-26 11:35 UTC, Aylong220 approved these changes

2023-11-26 11:35 UTC, Aylong220 commented on code/modules/shuttle/emergency.dm
> +				var/hyperspace_end_sound = sound('modular_ss220/aesthetics_sounds/sound/hyperspace_end_new.ogg')
```suggestion
				var/hyperspace_end_sound = sound('modular_ss220/aesthetics_sounds/sound/hyperspace_end_new.ogg') //SS220 EDIT
```

2023-11-26 13:44 UTC, BoryaYeltsin commented on code/modules/shuttle/emergency.dm
> +				var/hyperspace_end_sound = sound('modular_ss220/shuttle_sounds/sound/hyperspace_end_new.ogg')
Готово

2023-11-27 09:44 UTC, dj-34 requested changes
Зачем создавать отдельный файл SSshutles.dm? Засунь его код в shuttle.dm

2023-11-27 09:50 UTC, dj-34 commented
не забывай resolve conversation под реквестами прожимать

2023-11-27 13:04 UTC, dj-34 commented
В следующий раз заливай ПР через отдельную ветку, а не с master'а

2023-11-27 13:08 UTC, PhantornRU approved these changes
Модульно. Ок.
То что в мастере - не ок.

2023-11-27 14:18 UTC, merged