Bounty: New donor item "PRS-1"
ss220club/Paradise-SS220 pull request #783
Opened 2023-11-28 01:57 UTC by Yata9arasu

## Что этот PR делает
Добавляет новый донорский предмет "ПРС-1"

## Почему это хорошо для игры
Ещё одна вещь для тех , кто хочет выделиться

## Изображения изменений
![assist1](https://github.com/ss220club/Paradise-SS220/assets/108077473/7673f75e-5401-4741-af4b-50ea4443003f)
![assist2](https://github.com/ss220club/Paradise-SS220/assets/108077473/9fa5f095-4747-494d-8fe0-07f07601d362)
![assist3](https://github.com/ss220club/Paradise-SS220/assets/108077473/4e797ce0-f2eb-49af-855f-83f87979bce5)

## Тестирование
Протестировано

## Changelog
:cl:
add: Добавлен донорский предмет "ПРС-1"
/:cl:

2023-11-28 02:05 UTC, Yata9arasu commented
Этачё

![image](https://github.com/ss220club/Paradise-SS220/assets/108077473/90e34b55-8f1e-45e6-8c25-632dc25794d6)

2023-11-28 02:06 UTC, Yata9arasu commented
И почему оно руинит мой абсолютн чистый ПР. Я даже репо пересоздал чтобы мусора и лишних коммитов не было

2023-11-28 04:29 UTC, dj-34 requested changes

2023-11-28 04:29 UTC, dj-34 commented on modular_ss220/clothing/code/mask.dm
> +	desc = "Модульный противогаз, предназначен в основном для совместного использования с имплантироваными кибер лёгкими."
Отступы
```suggestion
/datum/outfit/job/chef
	mask = /obj/item/clothing/mask/fakemoustache/chef

/obj/item/clothing/mask/gas/red_gas
	name = "ПРС-1"
	desc = "Модульный противогаз, предназначен в основном для совместного использования с имплантироваными кибер лёгкими."
```

2023-11-28 04:29 UTC, dj-34 commented on modular_ss220/loadout/code/donor.dm
> +	display_name = "ПРС-1"
ОТСТУ ПЫЫЫЫ
```suggestion
	path = /obj/item/clothing/mask/breath/breathscarf
	cost = 2

/datum/gear/donor/red_gas
	display_name = "ПРС-1"
```

2023-11-28 04:29 UTC, dj-34 commented on modular_ss220/clothing/code/mask.dm
> +	desc = "Модульный противогаз, предназначен в основном для совместного использования с имплантироваными кибер лёгкими."
Описание предмета не соответствует действительности, поменяй

2023-11-28 04:30 UTC, dj-34 commented
> И почему оно руинит мой абсолютн чистый ПР. Я даже репо пересоздал чтобы мусора и лишних коммитов не было

зареранил работку, нормально

2023-11-28 05:04 UTC, PhantornRU commented
Так, остановись теперь на этом ПРе и больше их не создавай.

2023-11-28 09:10 UTC, Gaxeer commented on modular_ss220/clothing/code/mask.dm
> +	desc = "Модульный противогаз, предназначен в основном для совместного использования с имплантироваными кибер лёгкими."
Плюсую, никакого механа для киберлёгких нет. По этому это будет только запутывать

2023-11-29 19:29 UTC, Aylong220 commented
Неделю добавляем ссанный предмет Clueless

2023-11-30 11:52 UTC, Aylong220 commented on modular_ss220/loadout/code/donor.dm
> -
Куда спиздил отступ?

2023-11-30 13:16 UTC, dj-34 requested changes
Газмаска которая скрывает полностью лицо, но фактически

2023-12-01 04:59 UTC, Yata9arasu commented on modular_ss220/loadout/code/donor.dm
> +	donator_tier = 2
> Во-первых, **почему маска, скрывающая ебало стоит в лодауте дешевлее чем шарф не делающий этого?** Сумму стоит делать в таком случаи либо равнозначную, либо выше. Во-вторых donator_tier = 2 уже обозначен в /datum/gear/donor

Не актуально (https://github.com/ss220club/Paradise-SS220/pull/802)

2023-12-02 04:33 UTC, Yata9arasu commented
> Кстати, а с расовыми спрайтами что? Будем терпеть что какой-нибудь клюв или морда выпирает за текстурку? LUL

Да

2023-12-02 10:29 UTC, Aylong220 commented
Ммм, низкокачественные донат шмотки, которые ещё и добавили за деньги, кайф
Как же хочется закрыть эту хуйню

2023-12-02 14:19 UTC, Aylong220 requested changes
И такой вопрос, ебало скрывает?

2023-12-02 14:19 UTC, Aylong220 commented on modular_ss220/loadout/code/donor.dm
> +	donator_tier = 2
```suggestion
```

2023-12-02 16:12 UTC, BR54FF commented
> И такой вопрос, ебало скрывает?

```
/obj/item/clothing/mask/gas/red_gas
```
Написано gas, закрывает, у того же шарфа по коду ниже - breath

2023-12-05 19:05 UTC, Aylong220 commented
3 дня на то шоб сделать её не скрывающей ебало

2023-12-05 19:11 UTC, Yata9arasu commented
> 3 дня на то шоб сделать её не скрывающей ебало

А что насчёт баунти где мне заплатили, чтобы шарф донорский скрывал его?

2023-12-05 19:12 UTC, Aylong220 commented
> > 3 дня на то шоб сделать её не скрывающей ебало
> 
> А что насчёт баунти где мне заплатили, чтобы шарф донорский скрывал его?

Отклонено, надо было обсуждать это с разрабами, а не в соляново всё делать

2023-12-05 19:13 UTC, Yata9arasu commented
> Collaborator

Понятненько. В общем более не скрывает личико

2023-12-05 19:19 UTC, Aylong220 commented on modular_ss220/clothing/code/mask.dm
> +	desc = "Модульный противогаз с защитой глаз от внешней среды."
```suggestion
	desc = "Стильная дыхательная маска в виде противогаза, не скрывает лицо."
```

2023-12-05 19:20 UTC, Aylong220 approved these changes
Пойдёт

2023-12-06 07:42 UTC, PhantornRU approved these changes

2023-12-06 10:52 UTC, merged