translate motd when join game
ss220club/Paradise-SS220 pull request #794
Opened 2023-11-30 11:28 UTC by BR54FF

## Что этот PR делает

Перевод motd при заходе на профу

## Почему это хорошо для игры

перевод

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/106420737/2884de0a-6041-497d-b52d-9545800d4af8)
![image](https://github.com/ss220club/Paradise-SS220/assets/106420737/b2f44bcb-43c6-4c14-9ba4-bdc6a0d0a5dd)

## Тестирование
локалка

## Changelog

:cl:
tweak: Перевод приветственных сообщений при заходе на роль
/:cl:

2023-11-30 16:58 UTC, Gaxeer approved these changes

2023-11-30 18:34 UTC, dj-34 reviewed
Почему у тебя разнобой в СРП? Где-то с маленьких начинается, где-то с больших. Также и с КЗ

2023-11-30 18:34 UTC, dj-34 commented on code/game/jobs/job/supervisor.dm
> +	important_information = "Эта роль требует, чтобы вы консультировали командование по стандартным рабочим процедурам, цепочке командования и отчитывались перед Центральным командованием по различным в
```suggestion
	important_information = "Эта роль требует, чтобы вы консультировали командование по Стандартным Рабочим Процедурам, цепочке командования и отчитывались перед Центральным Командованием по различным вопросам. От вас требуется действовать так, как подобает человеку, представляющему Nanotrasen."
```

2023-11-30 18:34 UTC, dj-34 commented on code/game/jobs/job/supervisor.dm
> +	important_information = "Эта роль требует, чтобы вы консультировали командование по стандартным рабочим процедурам, цепочке командования и отчитывались перед Центральным командованием по различным в
это лишь один пример

2023-12-01 09:08 UTC, Legendaxe approved these changes

2023-12-02 06:59 UTC, BR54FF commented
наконец выдалось время, исправил

2023-12-02 14:20 UTC, Aylong220 approved these changes
Красиво

2023-12-02 17:38 UTC, dj-34 requested changes

2023-12-02 17:38 UTC, dj-34 commented on code/game/jobs/job/support.dm
> +	to_chat(H, "<span class='notice'>Вы сосредоточились и теперь можете регулярно использовать оружие.</span>")
```suggestion
	to_chat(H, "<span class='notice'>Вы сосредоточились и теперь можете эффективно пользоваться оружием.</span>")
```

2023-12-02 17:38 UTC, dj-34 commented on code/game/jobs/job/supervisor.dm
> +	important_information = "Эта роль требует, чтобы вы консультировали командование по Стандартным Рабочим Процедурам, цепочке командования и отчитывались перед Центральным командованием по различным в
Ксенорасы спросить забыли LUL
```suggestion
	important_information = "Эта роль требует, чтобы вы консультировали командование по Стандартным Рабочим Процедурам, цепочке командования и отчитывались перед Центральным Командованием по различным вопросам. От вас требуется действовать так, как подобает лицу, представляющему Nanotrasen."
```

2023-12-02 17:38 UTC, dj-34 commented on code/controllers/subsystem/SSjobs.dm
> +		remembered_info += "Как руководитель отдела, вы имеете доступ к денежному счету вашего отдела через НаноБанк вашего КПК или банкоматы на станции<br>"
Раз уж ты решил не переводить Нанотрейзен, то и это переводить тоже не нужно
```suggestion
		remembered_info += "Как руководитель отдела, вы имеете доступ к денежному счету вашего отдела через NanoBank вашего КПК или банкоматы на станции<br>"
```

2023-12-02 17:39 UTC, Aylong220 commented on code/game/jobs/job/supervisor.dm
> +	important_information = "Эта роль требует, чтобы вы консультировали командование по Стандартным Рабочим Процедурам, цепочке командования и отчитывались перед Центральным командованием по различным в
Да и хуй с ними Clueless

2023-12-02 17:44 UTC, dj-34 requested changes

2023-12-02 17:44 UTC, dj-34 commented on code/controllers/subsystem/SSjobs.dm
> +		remembered_info += "Как руководитель отдела, вы имеете доступ к денежному счету вашего отдела через НаноБанк вашего КПК или банкоматы на станции<br>"
> Нанотрейзен бы кстати перевести

Думают стоит

2023-12-02 17:44 UTC, dj-34 commented on code/controllers/subsystem/SSjobs.dm
> +	to_chat(H, "<span class='boldnotice'>Как сотрудник Nanotrasen, вы будете получать зарплату в размере $[account.payday_amount] кредитов каждые 30 минут</span>")
```suggestion
	to_chat(H, "<span class='boldnotice'>Как сотрудник Нанотрейзен, вы будете получать зарплату в размере $[account.payday_amount] кредитов каждые 30 минут</span>")
```

2023-12-02 17:44 UTC, dj-34 commented on code/game/jobs/job/supervisor.dm
> +	supervisors = "Официальными лицами Nanotrasen"
```suggestion
	supervisors = "Официальными лицами Нанотрейзен"
```

2023-12-02 17:44 UTC, dj-34 commented on code/game/jobs/job/supervisor.dm
> +	supervisors = "представителем Nanotrasen"
```suggestion
	supervisors = "представителем Нанотрейзен"
```

2023-12-02 17:44 UTC, dj-34 commented on code/game/jobs/job/supervisor.dm
> +	important_information = "Эта роль требует, чтобы вы обеспечивали безопасность руководителей персонала, а не всего экипажа. Вы можете производить аресты только в том случае, если нарушитель напрямую
```suggestion
	important_information = "Эта роль требует, чтобы вы обеспечивали безопасность руководителей персонала, а не всего экипажа. Вы можете производить аресты только в том случае, если нарушитель напрямую угрожает члену командования, представителю Нанотрейзен, или магистрату."
```

2023-12-02 17:44 UTC, dj-34 commented on code/game/jobs/job/supervisor.dm
> +	supervisors = "верховным судом Nanotrasen"
```suggestion
	supervisors = "верховным судом Нанотрейзен"
```

2023-12-02 17:47 UTC, dj-34 commented
Кстати чтобы не переписывать все ручками, просто жми commit suggestions под ревью @BR54FF

2023-12-03 21:57 UTC, dj-34 approved these changes

2023-12-03 22:25 UTC, merged