Refactor: Sechailer dispatch
ss220club/Paradise-SS220 pull request #807
Opened 2023-12-02 03:12 UTC by dj-34

## Что этот PR делает
 - Рефактор (в силу моих знаний, возможно и "де-рефактор" LUL), повышение читаемости и чистоты кода.
 - Добавление влияния ЕМП воздействия (уход на перезарядку)

Есть проблемы которые мне необходимо решить **И МНЕ НУЖНА ПОМОЩЬ**:

- [ ] Не понимаю как лучше сделать таймер и брать обновляющееся время для уведомления в чате
- [ ] Почему-то после emp_act, перестают выводиться сообщения в чате от секхайлера, хотя звук проигрывается (и я не могу понять почемууууууууууууууууууууу)

## Почему это хорошо для игры
Ну а чо нет

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/07e3f4f7-6ac9-46e3-85c9-89dad494e863)

## Тестирование
Проверял в игре

## Changelog

:cl:
tweak: Рефактор диспатча секхайлера
/:cl:

2023-12-02 03:15 UTC, dj-34 commented on modular_ss220/sechailer/code/sechailer.dm
> +		return
ЗНАЛ БЫ Я, как можно этот код лучше написать - я бы написал

2023-12-03 09:47 UTC, dj-34 commented
Сука, уле=еле но готово, пойдет. Не в полной мере как бы я хотел, но имхо значительно лучше. Теперь надо шоб кто-нибудь сделал ревью...

2023-12-05 09:41 UTC, Legendaxe requested changes

2023-12-05 09:41 UTC, Legendaxe commented on modular_ss220/sechailer/code/sechailer.dm
> +	actions_types = list(/datum/action/item_action/dispatch, /datum/action/item_action/halt, /datum/action/item_action/selectphrase)
А в чем смысл 4-ех подтипов маски если они отличаются только названием, может оставить один единственный? Потому что я вижу различие только в actions_types и как будто оно не нужно

2023-12-05 09:41 UTC, Legendaxe commented on modular_ss220/sechailer/code/sechailer.dm
> +	radio.autosay("Центр, Код [message], офицер [user] запрашивает помощь в [A].", "Система Оповещения", "Security", list(z))
Проверь нет ли у нас дефайна для "Security Radio Channel"

2023-12-05 09:41 UTC, Legendaxe commented on modular_ss220/sechailer/code/sechailer.dm
> +					if(channel_name == "Security")
Как и выше - проверь нет ли дефайна

2023-12-05 09:41 UTC, Legendaxe commented on modular_ss220/sechailer/code/sechailer.dm
> +			if(security_channel_found)
Немного странно выглядит, ты до этого вызываешь radio.autosay а через пару строк(здесь) делаешь проверку есть ли у человека рация и есть ли у нее доступ к каналу СБ

2023-12-05 10:03 UTC, dj-34 commented on modular_ss220/sechailer/code/sechailer.dm
> +	actions_types = list(/datum/action/item_action/dispatch, /datum/action/item_action/halt, /datum/action/item_action/selectphrase)
Чтобы остальным маска не назначать /datum/action/item_action/adjust

2023-12-05 10:23 UTC, Legendaxe commented on modular_ss220/sechailer/code/sechailer.dm
> +	actions_types = list(/datum/action/item_action/dispatch, /datum/action/item_action/halt, /datum/action/item_action/selectphrase)
А почему бы просто не убрать adjust у sechailer-а?

2023-12-05 10:44 UTC, dj-34 commented on modular_ss220/sechailer/code/sechailer.dm
> +	actions_types = list(/datum/action/item_action/dispatch, /datum/action/item_action/halt, /datum/action/item_action/selectphrase)
> А почему бы просто не убрать adjust у sechailer-а?

Непон...
Ну.. Чтобы маску СБшники могли опускать.

2023-12-05 11:06 UTC, Legendaxe commented on modular_ss220/sechailer/code/sechailer.dm
> +	actions_types = list(/datum/action/item_action/dispatch, /datum/action/item_action/halt, /datum/action/item_action/selectphrase)
А для чего его убирать у производных масок?

2023-12-05 11:15 UTC, dj-34 commented on modular_ss220/sechailer/code/sechailer.dm
> +	actions_types = list(/datum/action/item_action/dispatch, /datum/action/item_action/halt, /datum/action/item_action/selectphrase)
> А для чего его убирать у производных масок?

потому что у других такая функция не предусмотрена, там полноценный шлем

2023-12-05 11:18 UTC, Legendaxe approved these changes

2023-12-06 07:46 UTC, PhantornRU approved these changes
До тупого просто, не вижу даже до чего докопаться

2023-12-09 23:51 UTC, Gaxeer approved these changes

2023-12-09 23:52 UTC, Gaxeer requested changes
Выше написал

2023-12-10 15:46 UTC, Gaxeer commented on modular_ss220/sechailer/code/sechailer.dm
> +	var/is_emped = FALSE
```suggestion
	var/on_cooldown = FALSE
	var/emped = FALSE
```

2023-12-10 17:11 UTC, Gaxeer approved these changes

2023-12-10 19:34 UTC, merged