Tweak: Pick Darkness List
ss220club/Paradise-SS220 pull request #809
Opened 2023-12-02 14:06 UTC by Aylong220

## Что этот PR делает
Заменяет ввод числа в Pick Darkness на список.
Первое осталось, только теперь в виде выбора Custom
Имхо, так гораздо удобнее нежели каждый раз вписывать нужное значение при переключении с темноты/отсутствия темноты на полу-мрак и обратно

## Почему это хорошо для игры
УДОБНО

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/e8f9f3dc-3dd7-4c1a-8894-047bc8155b8c)

## Тестирование
Йеп

## Changelog

:cl:
tweak: Pick Darkness теперь список, должно быть удобнее. Точное число всё так же можно вписать, оно - Custom выбор
/:cl:

2023-12-02 17:20 UTC, Gaxeer commented on modular_ss220/verbs/code/verbs.dm
> +			client.prefs.ghost_darkness_level = new_darkness
```suggestion
	var/new_darkness
	switch(darkness_level)
		if("Darkness")
			new_darkness = 255
		if("Twilight")
			new_darkness = 210
		if("Brightness")
			new_darkness = 0
		if("Custom")
			new_darkness = input(usr, "Введите новое значение (0 - 255). Больше - темнее.", "Pick Darkness") as null|num
			
	if(!new_darkness)
		return
		
	client.prefs.ghost_darkness_level = new_darkness
```

2023-12-06 07:48 UTC, PhantornRU requested changes

2023-12-06 07:48 UTC, PhantornRU commented on modular_ss220/verbs/code/verbs.dm
> +			new_darkness = input(usr, "Введите новое значение (0 - 255). Больше - темнее.", "Pick Darkness") as null|num
вверху тгуи инпут, а тут не тгуи?

2023-12-06 10:23 UTC, Aylong220 commented on modular_ss220/verbs/code/verbs.dm
> +			new_darkness = input(usr, "Введите новое значение (0 - 255). Больше - темнее.", "Pick Darkness") as null|num
Потому что TGUI Input у нас пока что только в виде листов, а не чисел, алёртов и текста

2023-12-06 10:24 UTC, Aylong220 commented on modular_ss220/verbs/code/verbs.dm
> +			new_darkness = input(usr, "Введите новое значение (0 - 255). Больше - темнее.", "Pick Darkness") as null|num
XyliPizdish

2023-12-07 14:18 UTC, Gaxeer commented on modular_ss220/verbs/code/verbs.dm
> +	if(new_darkness == null)
```suggestion
	if(isnull(new_darkness))
```

2023-12-07 14:22 UTC, Gaxeer approved these changes

2023-12-08 18:04 UTC, merged