Кошачьи ушки для Т2 донов
ss220club/Paradise-SS220 pull request #820
Opened 2023-12-05 19:40 UTC by Foenk

## Что этот PR делает

Добавляет кошачьи ушки в донорские Т2 итемы

## Почему это хорошо для игры

Почему бы и нет? Поддержим донов

## Тестирование

Да?

## Changelog

:cl:
tweak: Добавил ушки в modular_ss220/loadout/code/donors.dm
/:cl:

2023-12-06 08:10 UTC, PhantornRU requested changes

2023-12-06 08:10 UTC, PhantornRU commented on modular_ss220/loadout/code/donor.dm
> +	cost = 1
Шарф имеет цену 2, а ушки 1? Несбалансировано.
```suggestion
	cost = 2
```

2023-12-06 10:31 UTC, Foenk commented on modular_ss220/loadout/code/donor.dm
> +	cost = 1
В шарф можно дышать, ушки же - чистая косметика.

2023-12-06 10:38 UTC, Foenk commented on modular_ss220/loadout/code/donor.dm
> +	cost = 1
Отказано, Ащиа сказал 1 поинт :jokerge:

2023-12-06 10:46 UTC, Foenk commented on modular_ss220/loadout/code/donor.dm
> +	donator_tier = 2
Изначально во второй тир попросил сунуть Nateyoko, Ащиа утвердил второй тир и 1 поинт. Что скажет по итогу - то и сделаю

2023-12-07 07:24 UTC, PhantornRU commented
Без COST = 2 не одобрю, нефиг ушкам быть у всех подряд. Это должен быть ответственный выбор xdd

2023-12-07 14:16 UTC, merged