Donor jobs update
ss220club/Paradise-SS220 pull request #824
Opened 2023-12-06 18:59 UTC by PhantornRU

## Что этот PR делает

Добавляет 5 ТИРов профессий по запросам и с одобрения стримеров.

Принцип работы
Заключается в том, что у игроков на каждый ТИР будет выделена отдельная кнопка, где они могут выбрать 1 специальную должность наподобии ассистентской в каждом ТИРе и от этого выставить свой приоритет.
Данные должности предназначены для расширения игрового опыта, минимизации ожидания в очереди ХОП’а, когда ХОП находится в ССД, отсутствует или его забрал Капитан, а также для создания интересных ивентовых ситуаций не нацеленных на резню, а только на выполнение должностных обязанностей и отыгрыша на космической станции за определенную профессию.
Так как на станции могут присутствовать различные туристы, а Космический Закон на них по прежнему распространяется, то любая роль подчиняется текущему КЗ и не дает право нарушать правила, логику персонажей, РП отыгрыш и сам КЗ.
Каждая профессия получает справку о своей роли, униформу, профессиональный хлам и необходимые минимальные доступы.

4-5 должности в связи с имением небольших "преимуществ" - не имеют возможности стать антагонистом.

## Почему это хорошо для игры

Поощрение донатеров, возможность жития проекта.

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/6d32fe00-d861-48f6-be0a-b4755110682a)

## Тестирование

Долго и муторно

## Changelog

:cl:
add: Добавлены РП-профессии для донатеров.
tweak: Рефактор кода модульных профессий
/:cl:

2023-12-06 19:08 UTC, PhantornRU commented
Я кончил. В принципе всё работает. 
Только у манифеста нужно будет некорректное отображение в отделе доделать, ибо там нужно как-то запустить его автообновление... Но с этим разберусь завтра. Если манифест не нужен, то можно тестировать.

А да, Лендмарки пока не раставлял из-за работ с картами, но они у меня есть.

2023-12-07 04:01 UTC, dj-34 requested changes
1. Много разнобоя, как в отступах, так и в тексте.
2. Нон-РП названия джобок.

2023-12-07 04:04 UTC, dj-34 commented
Чиниииииииииииииии
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/1e1cab03-3c52-4445-b7de-bd28c5b35a79)

2023-12-07 04:09 UTC, dj-34 commented
Вот эта обводка выглядит очень харамно, словно на нём стоит какой-то статус.
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/2cc8aea5-19d9-4eb0-8108-954a525bea70)

2023-12-07 04:28 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +	"
Ну так это и не работка, а РП ролька. А коль взяли её - то пускай читают xdd

2023-12-07 04:31 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/2_tier_jobs.dm
> +	\nВы ХУДОЖНИК. Данная роль нацелена на демонстрацию вашей тонкой натуры. Найдите себе красильщик полов, создайте искусство! \
Ибо эта профа "общая", каким бы ты искуствоведом не был, ты все еще остаешься художником.
А если брать профу, то появится еще +100 строк с /New() где мы уже будем указывать 
. = ..()
important information = "Вы [alt_name], бла бла бла"

2023-12-07 04:32 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/2_tier_jobs.dm
> +	Возможно вы захотите наложить инсталяцию посреди мостика?"
Низкосортная шутка с наложить теряется и отсылками к некоторым "плохим инсталяторам и художникам" xdd

2023-12-07 04:33 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/3_tier_jobs.dm
> +	\nСССП является, по большому счету, политически нейтральной организацией, в отличие от большинства планетарных правительств, несмотря на их обиды с транс-Солнечной Федерацией. Одним из немногих искл
Буквально вики xdd

2023-12-07 04:34 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/2_tier_jobs.dm
> +
разделение чтобы не теряться в горе однотипного текста.

2023-12-07 04:35 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/2_tier_jobs.dm
> +
Но в некоторых разделение куда-то съел, поправлю

2023-12-07 04:44 UTC, PhantornRU commented on modular_ss220/jobs/code/landmarks.dm
> +	name = "Prisoner_arrive"
метка прибытия заключенного после старта раунда

2023-12-07 04:45 UTC, PhantornRU commented
> Вот эта обводка выглядит очень харамно, словно на нём стоит какой-то статус.
Да, обводку уже давно сменил, просто на этом скрине старая

2023-12-07 04:47 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/3_tier_jobs.dm
> +	ru_title = "Забытый Ассистент"
Он сам себе в напоминание :Chad:
Али ИИ при отлетах

2023-12-07 04:56 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/2_tier_jobs.dm
> +/datum/job/donor/courier
Те курьеры прямые каргонцы с разгрузками шаттла. Данный курьер по запросу является доставщиком пиццы и мальчиком на побегушках.

2023-12-07 06:14 UTC, Furrior commented
Передавали привет с дарк рп. Спрашивали, когда можно будет админку купить.

2023-12-07 08:19 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/2_tier_jobs.dm
> +/datum/job/donor/courier
А ведь точно. Переименую в "Delivery", доставку.

2023-12-07 08:31 UTC, dj-34 commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +	"
Нужно ли игроку столько инфы которую он и так не прочтет?

2023-12-07 09:15 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/2_tier_jobs.dm
> +/datum/job/donor/courier
Точно

2023-12-07 13:56 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/3_tier_jobs.dm
> +	ru_title = "Забытый Ассистент"
Теперь он безработный.

2023-12-07 14:00 UTC, PhantornRU commented
@dj-34 правки внёс, ЛОР выпилил, повыпиливал названия работок, поправил сами названия работок.
Альт-Названия остаются на русском. Увынск. Но внутри разумеется остаются английские для удобств.
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/3f2a7553-38b6-4444-9d43-1ebd5d3ea056)

2023-12-07 14:01 UTC, dj-34 commented
> @dj-34 правки внёс, ЛОР выпилил, повыпиливал названия работок, поправил сами названия работок. Альт-Названия остаются на русском. Увынск. Но внутри разумеется остаются английские для удобств. ![image](https://private-user-images.githubusercontent.com/41479614/288780877-3f2a7553-38b6-4444-9d43-1ebd5d3ea056.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE5NTc5NjAsIm5iZiI6MTcwMTk1NzY2MCwicGF0aCI6Ii80MTQ3OTYxNC8yODg3ODA4NzctM2YyYTc1NTMtMzhiNi00NDQ0LTlkNDMtMWViZDVkM2VhMDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA3VDE0MDEwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU1NWFlNWM4OTYzODQ2NzVlNjFkNmRlMzdmYjU0ZjIwN2VkNTNhNTViZDU5MTljZTkxMWYwNWJjZDk3NDg2YWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3mmzmBN6PXFMPT_7HVDiaLGA7hNbeANB-tCLq9VP5iw)

А русские названия в манифесте нормально будут, или в Misc?...

2023-12-07 14:13 UTC, dj-34 commented
может где-то в коре нужно изменить на _char что-нибудь чтоб русские отображались где нужно

2023-12-07 15:02 UTC, PhantornRU commented
@dj-34 потестил. Да, всё ок. 
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/cd839a1a-bdb6-41b6-9809-e83f7357b8ee)

2023-12-07 16:25 UTC, dj-34 requested changes

2023-12-07 16:25 UTC, dj-34 commented on modular_ss220/jobs/code/donor/job/1_tier_jobs.dm
> +	. = ..()	// сначала отправляем, а уже потом "даем выбрать должность"
Что за адский отступ
```suggestion
	. = ..() // Сначала отправляем, а уже потом "даем выбрать должность"
```

2023-12-07 16:25 UTC, dj-34 commented on modular_ss220/jobs/code/donor/job/2_tier_jobs.dm
> +
```suggestion


```

2023-12-07 16:25 UTC, dj-34 commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +	supervisors = "the head of security"
```suggestion
	supervisors = "главой службы безопасности"
```

2023-12-07 17:45 UTC, dj-34 approved these changes
Вроде норм

2023-12-11 13:39 UTC, Furrior commented
Представляю, как челы заплатили 10к за донат тир, чтоб узнать, что другой такой же донатер переролил у них джобку

2024-01-07 17:39 UTC, firstghost commented
Осталось им всем СРП прописать

2024-01-07 17:41 UTC, Aylong220 commented
> Осталось им всем СРП прописать

Они остаются фишкой прайма, пока пупс их не переделает

2024-01-10 14:29 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +	implants = list(/obj/item/implant/mindshield)
```suggestion
	bio_chips = list(/obj/item/implant/mindshield)
```

2024-01-10 14:29 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +	implants = list(/obj/item/implant/mindshield,
```suggestion
	bio_chips = list(/obj/item/implant/mindshield,
```

2024-01-10 14:29 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +	implants = list(/obj/item/implant/mindshield,
```suggestion
	bio_chips = list(/obj/item/implant/mindshield,
```

2024-01-10 14:29 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +	implants = list(/obj/item/implant/mindshield,
```suggestion
	bio_chips = list(/obj/item/implant/mindshield,
```

2024-01-10 14:29 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +	implants = list(/obj/item/implant/mindshield,
```suggestion
	bio_chips = list(/obj/item/implant/mindshield,
```

2024-01-10 14:29 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +	implants = list(/obj/item/implant/sad_trombone, /obj/item/implant/mindshield)
```suggestion
	bio_chips = list(/obj/item/implant/sad_trombone, /obj/item/implant/mindshield)
```

2024-01-10 14:30 UTC, PhantornRU reviewed
ОФФы переименовали implants -> bio_chips

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +	bio_chips = list(/obj/item/implant/mindshield)
```suggestion
	bio_chips = list(/obj/item/bio_chip/mindshield)
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +		/obj/item/implanter/death_alarm = 1,
```suggestion
		/obj/item/bio_chip_implanter/death_alarm = 1,
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +	bio_chips = list(/obj/item/implant/mindshield,
```suggestion
	bio_chips = list(/obj/item/bio_chip/mindshield,
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +		/obj/item/implant/death_alarm
```suggestion
		/obj/item/bio_chip/death_alarm
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +		/obj/item/implanter/death_alarm = 1,
```suggestion
		/obj/item/bio_chip_implanter/death_alarm = 1,
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +		/obj/item/implant/death_alarm
```suggestion
		/obj/item/bio_chip/death_alarm
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +		/obj/item/implanter/death_alarm = 1,
```suggestion
		/obj/item/bio_chip_implanter/death_alarm = 1,
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +	bio_chips = list(/obj/item/implant/mindshield,
```suggestion
	bio_chips = list(/obj/item/bio_chip/mindshield,
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +		/obj/item/implant/death_alarm
```suggestion
		/obj/item/bio_chip/death_alarm
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +		/obj/item/implant/death_alarm
```suggestion
		/obj/item/bio_chip_implanter/death_alarm = 1,
		/obj/item/lighter/zippo/engraved = 1,
		/obj/item/clothing/under/rank/procedure/lawyer/black = 1,
		/obj/item/clothing/mask/cigarette/cigar/havana = 6,
	)

	bio_chips = list(/obj/item/bio_chip/mindshield,
		/obj/item/bio_chip/death_alarm
```

2024-01-11 00:45 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +	bio_chips = list(/obj/item/implant/sad_trombone, /obj/item/implant/mindshield)
```suggestion
	bio_chips = list(/obj/item/bio_chip/sad_trombone, /obj/item/bio_chip/mindshield)
```

2024-01-11 01:10 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/4_tier_jobs.dm
> +	bio_chips = list(/obj/item/implant/mindshield,
```suggestion
	bio_chips = list(/obj/item/bio_chip/mindshield,
```

2024-01-22 10:17 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +		/obj/item/reagent_containers/food/drinks/bottle/bottleofbanana = 1,
```suggestion
		/obj/item/reagent_containers/drinks/bottle/bottleofbanana = 1,
```

2024-01-22 10:17 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/5_tier_jobs.dm
> +		/obj/item/reagent_containers/food/snacks/grown/banana = 1,
```suggestion
		/obj/item/food/snacks/grown/banana = 1,
```

2024-01-22 10:17 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/3_tier_jobs.dm
> +		/obj/item/reagent_containers/food/snacks/cubannachos = 3,
```suggestion
		/obj/item/reagent_containers/drinks/bottle/tequila = 1,
		/obj/item/food/snacks/taco = 6,
		/obj/item/food/snacks/nachos = 3,
		/obj/item/food/snacks/cheesenachos = 3,
		/obj/item/food/snacks/cubannachos = 3,
```

2024-01-22 10:17 UTC, PhantornRU commented on modular_ss220/jobs/code/donor/job/3_tier_jobs.dm
> +		/obj/item/clothing/head/flatcap = 1,
```suggestion
		/obj/item/reagent_containers/drinks/bottle/vodka = 1,
		/obj/item/storage/fancy/cigarettes/cigpack_random = 2,
		/obj/item/food/snacks/doshik = 3,
		/obj/item/food/snacks/doshik_spicy = 3,
		/obj/item/clothing/suit/mantle/old = 1,
		/obj/item/clothing/head/flatcap = 1,
```

2024-02-06 00:49 UTC, PhantornRU commented
Убраны 3 работы: Подмастерье, Художник и Дворецкий.
Будут возвращены после рефактора. Критических ошибок не заметил.

2024-02-06 14:56 UTC, PhantornRU commented
Закрыто, я больше не хочу ими заниматься, ибо требуется рефактор проф. А рефактор проф идет в жопу.
Я заебался в тестмердже ловить ошибки от малейших изменений в карте

2024-02-07 13:41 UTC, PhantornRU commented
Работа над работками продолжается по ОЧЕНЬ НАСТОЙЧИВОЙ просьбе.

2024-02-07 13:42 UTC, Furrior commented
Да забей хуй, это лучше даже не делать без рефактора проф

2024-02-07 13:43 UTC, PhantornRU commented
> Да забей хуй, это лучше даже не делать без рефактора проф

Я понимаю. Поэтому пока забиты имеющиеся слоты. Рефактор профф никто не сделает. Лучше это время потратим на Бандастейшин, а люди пока пускай с этими профами развлекаются. На Прайме они себя хорошо показали.

2024-02-07 13:46 UTC, PhantornRU commented
Если что из дополнительных флагов я оставил флаги для: Механика(MECHANIC), под пилота (PILOT).

Если нужны будут дополнительные слоты, то следующие на выпил: Горничная(Maid), Доставщик (Deliverer).
Уже были выпилены: Дворецкий, Подмастерье (Грейтайдовец-Механик), Художник

2024-02-07 14:01 UTC, Gaxeer approved these changes

2024-02-07 17:23 UTC, PhantornRU commented
Можно в тестмердж. Закинул новые лендмарки на Кибериаду, Дельту, Мету.

2024-02-15 13:23 UTC, merged

2024-06-25 13:39 UTC, PhantornRU commented
```GLOBAL_LIST_INIT(donor_tier_1_jobs, list(
    "Prisoner",    // Заключенный
))

GLOBAL_LIST_INIT(donor_tier_2_jobs, list(
    "Barber",    // Парикмахер
    "Bath",        // Банщик
    "Casino",    // Крупье
    "Waiter",    // Официант
    "Acolyte",    // Послушник
    "Wrestler",    // Боксёр, Рефери
    "Musician",    // Музыкант
    "Actor",    // Актёр
))

GLOBAL_LIST_INIT(donor_tier_3_jobs, list(
    "Administrator",    // Сервис-Администратор
    "Tourist TSF",        // Турист ТСФ
    "Tourist USSP",        // Турист ССП
    "Cleaning Manager",    // Менеджер по Клинингу
    "Guard",            // Охранник Шестерочки
    "Migrant",            // Мигрант
    "Uncertain",        // Забытый Ассистент
))

GLOBAL_LIST_INIT(donor_tier_4_jobs, list(
    "Adjutant",            // Адъютант
    "Representative TSF",    // Представитель ТСФ
    "Representative USSP",    // Представитель ССП
    "Dealer",            // Независимый Торговец
))

GLOBAL_LIST_INIT(donor_tier_5_jobs, list(
    "VIP Corporate Guest",    // VIP гость - Важно! Это НЕ админский VIP Guest с ЦК.
    "Banker",    // Банкир
    "Security Clown",    // Клоун Службы Безопасности
))```