Частичный перевод контента игры.
ss220club/Paradise-SS220 pull request #833
Opened 2023-12-07 17:40 UTC by KovoranPlay

## Что этот PR делает
Переводит часть контента игры.

## Почему это хорошо для игры
Приятно же, когда всё на русском? Вот и я считаю, что да.

## Изображения изменений
Всё в изменённых файлах.

## Тестирование
Запуск на локалке дал положительный результат, но не все части перевода удалось проверить, нужны тесты нюкеров.

## Changelog

:cl: V.E.R.G
add: Перевод некоторых вещей аплинка Трейтора.
add: Перевод некоторых модулей сбойного ИИ.
add: Перевод целей учёных.
add: Перевод контента
/:cl:

2023-12-07 19:00 UTC, dj-34 commented
завтра оставлю ревью

2023-12-07 19:15 UTC, KovoranPlay commented
> завтра оставлю ревью

Я тогда буду дальше переводить и чекать на очепятки и прочее

2023-12-08 03:23 UTC, KovoranPlay commented
В коде есть опечатки, которые будут тсисправлены после завершения работы над переводом. Для меня пока приоритетная цель - перевод контента. После этого будет его полировка и исправление мелких ошибок, только если по ошибкам будут жалобы со стороны игроков

2023-12-08 04:13 UTC, PhantornRU commented
Если еще не допереводил, лучше переведи в ДРАФТ, чтобы ревьюверы понимали что сюда лучше пока не заглядывать. Потом из ДРАФТа выведешь когда закончишь

2023-12-08 04:56 UTC, KovoranPlay commented
На самом деле, подумывал закончить свой перевод антагами (в основном, аплинк и культисты), но если хватит сил и времени на что-то ещё, возможно сделаю это. Но это уж скорее нет, чем да.

2023-12-08 06:44 UTC, dj-34 requested changes
Так переводы не нужно делать, это сложно ревьювить, в случаи чего и откатывать неприятно, а также ты переводишь все не скопом, из за чего в одном месте у тебя есть русский перевод, а строкой ниже у тебя идет фулл английский.
В таком случаи, советую оставить все что связано с ИИ, доперевести где нужно (если требуется), все остальное открыть в отдельном ПРе, переведя все целиком, 
**не трогая**:
1. Админ логи (это нужно перевести вообще все повсюду, если уж переводить)
2. Вкладки и тамошние кнопки (та же самая тема что и с логами)
3. Названия абилок (та же самая тема что и с логами)

**То что следует трогать**:
1. Все что связано с выводом в чат
2. Описание, законы, уведомления

2023-12-08 06:44 UTC, dj-34 commented on code/datums/ai_law_sets.dm
> +	name = "ТерминаорОС 3.1"
```suggestion
	name = "ТерминаторОС 3.1"
```

2023-12-08 06:44 UTC, dj-34 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law(" Вы не можете ранить члена Клана Паука или своим бездействием допустить, чтобы члену Клана Паука был нанесён вред.")
```suggestion
	add_inherent_law("Вы не можете ранить члена Клана Паука или своим бездействием допустить, чтобы члену Клана Паука был нанесён вред.")
```

2023-12-08 06:44 UTC, dj-34 commented on code/datums/ai_law_sets.dm
> +	add_inherent_law("You must protect your own existence as long as such does not conflict with the First or Second Law. Вы должны защищать своё существование в той мере, в которой это не противоречит
Внимательнее
```suggestion
	add_inherent_law("Вы должны защищать своё существование в той мере, в которой это не противоречит Первому или Второму закону.")
```

2023-12-08 06:44 UTC, dj-34 commented on code/datums/ai_law_sets.dm
> +	name = "Дроновые протоколы"
```suggestion
	name = "Протоколы техобслуживания"
```

2023-12-08 15:04 UTC, Aylong220 commented on code/datums/ai_law_sets.dm
> +	name = "Дроновые протоколы"
Протоколы тех. обслуживания

2023-12-08 15:14 UTC, Aylong220 commented on code/game/jobs/job_objectives/science.dm
> +	objective_name = "Проводите исследования для NanoTrasen"
```suggestion
	objective_name = "Проводите исследования для Нанотрейзен"
```

2023-12-08 15:15 UTC, Aylong220 commented on code/datums/ai_law_sets.dm
> +	name = "NT Стандарт"
```suggestion
	name = "НТ Стандарт"
```

2023-12-08 15:16 UTC, Aylong220 commented on code/datums/ai_law_sets.dm
> +	name = "NT Агрессивный"
```suggestion
	name = "НТ Агрессивный"
```

2023-12-08 15:16 UTC, Aylong220 commented on code/datums/ai_law_sets.dm
> +	name = "Директивы клана паука"
```suggestion
	name = "Директивы клана Паука"
```

2023-12-08 15:17 UTC, Aylong220 commented on code/game/verbs/ooc.dm
> +		to_chat(src, "<span class='danger'>Вы замутили ООС-чат.</span>")
Ничего я не мутил
```suggestion
		to_chat(src, "<span class='danger'>Вы заглушили ООС чат.</span>")
```

2023-12-08 15:17 UTC, Aylong220 commented on code/game/verbs/ooc.dm
> +			to_chat(src, "<span class='danger'>ООС-чат выключен на сервере..</span>")
```suggestion
			to_chat(src, "<span class='danger'>ООС чат выключен на сервере..</span>")
```

2023-12-08 15:18 UTC, Aylong220 commented on code/game/verbs/ooc.dm
> +			message_admins("[key_name_admin(src)] попытался прорекламировать в ООС: [msg]")
```suggestion
			log_admin("[key_name(src)] попытался прорекламировать сервер в ООС: [msg]")
			message_admins("[key_name_admin(src)] попытался прорекламировать сервер в ООС: [msg]")
```

2023-12-08 15:19 UTC, Aylong220 commented on code/game/verbs/ooc.dm
> +		to_chat(world, "<B>ООС-чат был глобально включён!</B>")
```suggestion
		to_chat(world, "<B>ООС чат был включён на сервере!</B>")
```

2023-12-08 15:19 UTC, Aylong220 commented on code/game/verbs/ooc.dm
> +		to_chat(world, "<B>ООС-чат был глобально выключен!</B>")
```suggestion
		to_chat(world, "<B>ООС чат был выключён на сервере!</B>")
```

2023-12-08 15:20 UTC, Aylong220 commented on code/game/verbs/randomtip.dm
> +	set desc = "Даёт рандомную подсказку"
```suggestion
	set name = "Случайная подсказка"
	set desc = "Даёт случайную подсказку"
```

2023-12-08 15:23 UTC, Aylong220 commented on code/game/verbs/webmap.dm
>  		to_chat(usr, "<span class='warning'>The current map has no defined webmap. Please file an issue report.</span>")
```suggestion
		to_chat(usr, "<span class='warning'>Текущая карта отсутствует на веб-картах.</span>")
```

2023-12-08 15:25 UTC, Aylong220 commented on paradise.dme
> -// SS220 ADDITION END
Верни

2023-12-08 17:42 UTC, KovoranPlay commented on code/datums/ai_law_sets.dm
>  	law_header = "Comedy Routine"
Не перестал, просто подумал, что пока так оставлю, вернусь может быть завтра-послезавтра. Сил моих пока не хватает на перевод ВООБЩЕ всего контента. Позже, возможно, допилю перевод, но сейчас пока лучше так оставить, а не растягивать этот ПР на 2-3 месяца.

2023-12-08 18:17 UTC, KovoranPlay commented on code/datums/ai_law_sets.dm
> +	name = "ТерминаорОС 3.1"
Окей, оставлю только законы и абилки малфа в таком случае, раз уж они переведены и к ним нареканий вроде бы нет.

А вот откатывать щас будет проблемно...

2023-12-08 22:46 UTC, Aylong220 commented
Не понимаю что ты делаешь

2023-12-08 22:50 UTC, KovoranPlay commented
Хотел откатить до [ревью](https://github.com/ss220club/Paradise-SS220/pull/833#pullrequestreview-1771611221), чтобы вернуть предметы из аплинка и прочее дерьмо, что я там трогал в изначальное состояние и остановиться только на переводе законов ИИ, но видимо во время отката что-то пошло не так и, наверное, проще просто откатиться в самое начало и начать сначала всё переводить.

2023-12-09 21:51 UTC, KovoranPlay commented
Наконец-то откатил всё нормально и доперевёл только ИИ и все связанные с ним способности. Осталось в переводе 2-3 строки, может быть чуть-чуть больше, сяду за них примерно в среду/четверг.

Переведены:
1. Названия и описания способностей.
2. Связанные с этим сообщения в чате.
3. Вступление за предателя (прокачанная гарнитура, кодовые формулировки)

НЕ было переведено:
1. Весь стафф из аплинка.
2. Контент за остальные профессии (в том числе борги)
3. Обычный интерфейс ИИ (Камеры, сенсоры, кнопки уведомлений и прочего

Сделаю это уже отдельными ПРами чтобы этот не забивать.
Тесты были успешны, всё отображается корректно и в чате, и в интерфейсе.

2023-12-09 22:09 UTC, Aylong220 commented
То что не перевёл до конца, лучше откатить
Если уж задишься за перевод определённой вещи, переводи до конца или не переводи вовсе, а то странная ситуация что пару вещей в аплинке переведены, а остальное нет

2023-12-10 01:59 UTC, KovoranPlay commented
Перевод ИИ вроде закончен, если вдруг остались непереведённые куски ИИ, быстренько с утра исправлю, сил уже не хватает. ББ короче

2023-12-11 13:44 UTC, Aylong220 commented
Конфликты, обнови ветку и реши их, будем посмотреть

2023-12-11 16:34 UTC, VERG-SS220 commented
> Конфликты, обнови ветку и реши их, будем посмотреть

Сейчас бы я еще знал, как решить их в пользу ai-translate вообще

2023-12-11 16:40 UTC, VERG-SS220 commented
Конфликты  мержей вроде решил

2023-12-12 03:08 UTC, VERG-SS220 commented
Перевод вроде полностью завершён, щас буду проверять на орфографические ошибки и очепятки

2023-12-12 07:04 UTC, VERG-SS220 commented
Теперь контент за ИИ полностью переведен, тесты показали положительный результат. Ожидаем ревью и возможного мержа

2023-12-12 15:17 UTC, dj-34 requested changes
Как это ревьювить? Что за бесконечный ПР

2023-12-12 15:17 UTC, dj-34 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
>  	var/display_choices = list(
Выбор иконок это не только перевод но и затрагивание кода, это стоит убрать

2023-12-12 15:17 UTC, dj-34 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
> +			queueAlarm("--- Тревога [class]  обнаружена в [A.name]! (<A HREF=?src=[UID()];switchcamera=[O[1]]>[C.c_tag]</A>)", class)
Раз типа то везде типа
```suggestion
			queueAlarm("--- Тревога типа [class]  обнаружена в [A.name]! (<A HREF=?src=[UID()];switchcamera=[O[1]]>[C.c_tag]</A>)", class)
```

2023-12-12 15:17 UTC, dj-34 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
> +		if("Животное")
тоже самое, затрагивание кода

2023-12-12 15:17 UTC, dj-34 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
> +			user.visible_message("<span class='notice'>\The [user] начинает прикручивать [src] к полу...</span>")
Убрать везде \the
```suggestion
			user.visible_message("<span class='notice'>[user] начинает прикручивать [src] к полу...</span>")
```

2023-12-12 15:17 UTC, dj-34 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
>  	set desc = "Allows you to change settings of your radio."
А desc чего не переведен?

2023-12-12 15:17 UTC, dj-34 commented on code/modules/mob/living/silicon/ai/freelook/eye.dm
> +/mob/camera/aiEye/hear_say(list/message_pieces, verb = "говорит", italics = 0, mob/speaker = null, sound/speech_sound, sound_vol, sound_frequency, use_voice = TRUE)
по моему это поможет поломать логи

2023-12-12 15:17 UTC, dj-34 commented on code/modules/mob/living/silicon/silicon_mob.dm
> +			msg += "ПРОНИКНОВЕНИЕ: Обнаружено [alarm_types_show["Burglar"]] тревог. - "
я не помню и не уверен есть ли у нас проверка на множественное число, в целом, можно и так 🤷‍♂️ 
```suggestion
			msg += "ПРОНИКНОВЕНИЕ: Обнаружено [alarm_types_show["Burglar"]] тревог(а). - "
```

2023-12-12 15:17 UTC, dj-34 commented on code/modules/mob/living/silicon/silicon_mob.dm
> +// Функия показывает здоровье пИИ на панели Статуса.
Зачем переводить комментарий?

2023-12-12 15:23 UTC, VERG-SS220 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
>  	set desc = "Allows you to change settings of your radio."
А я вот не совсем понимаю, в какой момент времени этот desc вообще показывают

2023-12-12 15:23 UTC, VERG-SS220 commented on code/modules/mob/living/silicon/silicon_mob.dm
> +// Функия показывает здоровье пИИ на панели Статуса.
Для себя, чтобы просто понимать что за что отвечает без поломки мозга с переключением на английский (не то, чтобы мне это было полезно)

2023-12-12 15:25 UTC, VERG-SS220 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
>  	var/display_choices = list(
Ну, у меня выбор иконок работает исправно, но если надо убрать, то окей, уберу

2023-12-12 15:27 UTC, VERG-SS220 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
>  	var/display_choices = list(
Да и плюс там дальше идёт огромный список if выражений в том же файле, так что мне всё таки кажется, что можно это и оставить, наверное

2023-12-12 15:28 UTC, VERG-SS220 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
> +		if("Животное")
Вот животные да, там они чутка поломанные из-за того, что либо некоторых голограмм просто нет, либо по какой-то другой причине. Вот перевод животины я откачу, наверное

2023-12-12 15:29 UTC, dj-34 commented on code/modules/mob/living/silicon/ai/ai_mob.dm
>  	var/display_choices = list(
Это ебала потом искать-выискивать почему иконки не работают, если добавят новые. Это затрагивание кода, и работает оно или нет тут не при чём

2023-12-12 21:06 UTC, VERG-SS220 commented
Можно было бы пересобрать ветку и пересоздать ПР, чтобы не было такого дикого количества коммитов (там все можно уложить буквально в 5-6 штук), но сейчас уже имеем что имеем

2023-12-12 21:55 UTC, Aylong220 commented
> Можно было бы пересобрать ветку и пересоздать ПР, чтобы не было такого дикого количества коммитов (там все можно уложить буквально в 5-6 штук), но сейчас уже имеем что имеем

да похуй на коммиты, при мерже всё сольётся в 1 который будет называться как твой ПР

2023-12-12 22:32 UTC, VERG-SS220 commented
> да похуй на коммиты, при мерже всё сольётся в 1 который будет называться как твой ПР

Да просто самому не удобно проверять потом перевод и откатывать в случае обсёров, поэтому если б я знал, то сделал бы просто намного меньше коммитов, на которые было бы проще откатываться, но уже похуй, на самом деле

2023-12-14 02:07 UTC, VERG-SS220 commented
Билд работает, все компилится. Остаётся, наверное, только интегрировать перевод в игру, но тут уж неизвестно, когда это произойдет

2023-12-14 02:15 UTC, Aylong220 commented
> Билд работает, все компилится. Остаётся, наверное, только интегрировать перевод в игру, но тут уж неизвестно, когда это произойдет

Когда бригада оценит и будет 3 галочки

2023-12-14 02:16 UTC, Aylong220 requested changes

2023-12-14 02:16 UTC, Aylong220 commented on code/_onclick/hud/ai_hud.dm
> +
И удали строчку, напрягает крестик

2023-12-14 02:16 UTC, Aylong220 commented on code/_onclick/hud/ai_hud.dm
> +
Надо было предложение сделать

2023-12-14 02:19 UTC, dj-34 commented
Линтер транслейшена не проходит. Где-то ты здесь ввел новую строчку, или удалил одну из
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/c58ddf3a-d29c-4c9f-a66d-aa8d24653108)

2023-12-14 02:21 UTC, dj-34 commented
Короче гиблое дело это так все скопом переводить рандомно, и трейторы и это тут зачем то
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/50e847a6-3de3-48e9-83db-d4ffe5c7416e)

Пересоздать бы сконцентрированный ПР, да не такой большой

2023-12-14 03:07 UTC, VERG-SS220 commented
Короче давай по новой, все хуйня

2023-12-14 03:09 UTC, closed without merging