feat: add `antag-mix` gamemode. Add blood brothers
ss220club/Paradise-SS220 pull request #840
Opened 2023-12-09 16:22 UTC by Gaxeer

## Что этот PR делает

Добавляем новый режим `Antag Mix`, который позволяет совмешать без лишних проблем разных антагонистов раундстартом. 
Так же добавлены `Antag Scenarios`, которые собственно и представляют отдельных антагонистов в `Antag-Mix`.
Поправлены баги, которые я так же поправлю на оффах, и лично решу мерж конлфликт, как он возникнет.
Так же, особенностью этого режима есть то, что раунд всегда будет заполнен антагонистами, если они есть.
Допустим, что есть `changeling` и `traitor`. Если у всех игроков отключен `changeling`, то в раунд смогут попасть только `traitor` и займут все доступные слоты, и наоборот. Если будут включены и те, и те - выбор будет происходит из тех и других, беря во внимание `weight` сценариев.

Так же добавлен новый антагонист `Blood Brothers`, из-за которого, собственно, и возникла причина добавить режим `Antag Mix`, потому что создавать комбинации режимов для каждого антагониста - это за гранью моих сил :clueless:

## Почему это хорошо для игры

Больше контроля за раундстарт антагонистами, достаточно гибкая настройка каждого антаг сценария.
Новый Кооп антагонист - Blood Brothers. О нём вы сможете прочитать детальнее на [вики](https://wiki.ss220.club/index.php/Blood_Brothers), а короткая сводка выводится при старте игры за этого антагониста. 

## Изображения изменений
Всё в коде.

## Тестирование

## Changelog

:cl:
add: Добавлен антагонист `Blood Brothers`. Включать, как обычно, в префах
add: Режим `Antag Mix`, который позволяет раундстартом вводить в раунд разных антагонистов. Пока миксуются только трейторы, генокрады, вампиры и новые `Братья по крови`
/:cl:

2023-12-09 16:47 UTC, dj-34 commented
а че за хардкод

2023-12-09 16:48 UTC, Gaxeer commented
> а че за хардкод

Необходимость, чтобы не рантаймило. Я параллельно на оффах рефакторы делаю. Как туда зальют - порешаю конфликты у нас.

2023-12-09 17:00 UTC, Aylong220 reviewed
Я хз чё ты запросил моё ревью, я код из 200-300 строчек еле перевариваю, а тут он ещё и сложный для моей горошины. Глазами пробежался, ничего не заметил проблемного

2023-12-09 17:05 UTC, Gaxeer commented
> Я хз чё ты запросил моё ревью, я код из 200-300 строчек еле перевариваю, а тут он ещё и сложный для моей горошины. Глазами пробежался, ничего не заметил проблемного

Документация ли понятная, переводы ли нормальные.

2023-12-11 06:51 UTC, PhantornRU commented on code/modules/antagonists/_common/antag_team.dm
> +	if(add_antag_datum && antag_datum_type)
а зачем "add_antag_datum", если можно просто проверять что в него подается "antag_datum_type"?

2023-12-12 09:05 UTC, Gaxeer commented on code/modules/antagonists/_common/antag_team.dm
> +	if(add_antag_datum && antag_datum_type)
Потому что иногда не надо добавлять антаг датум.

2023-12-12 20:00 UTC, Legendaxe requested changes

2023-12-12 20:03 UTC, Gaxeer commented on modular_ss220/antagonists/code/__HELPERS/_logging.dm
> +/proc/log_antag_mix(text)
Чтобы в ручную не писать `[ANTAG_MIX]` в каждом логе

2023-12-12 20:10 UTC, Legendaxe commented on modular_ss220/antagonists/code/__HELPERS/_logging.dm
> +/proc/log_antag_mix(text)
Но вызывается он только из antag_mix, и не думаю что в будущем потребуется логировать его извне

2023-12-12 20:15 UTC, Gaxeer commented on modular_ss220/antagonists/code/__HELPERS/_logging.dm
> +/proc/log_antag_mix(text)
окэй

2023-12-12 20:32 UTC, Legendaxe approved these changes

2023-12-13 13:28 UTC, PhantornRU approved these changes

2023-12-13 13:29 UTC, PhantornRU commented on modular_ss220/antagonists/code/antag_mix/scenarios/antag_scenario.dm
> +	return length(assigned) - assigned_before > 0
заметил уже к концу когда апрув тыркнул...
```suggestion
	return (length(assigned) - assigned_before) > 0)
```

2023-12-13 13:32 UTC, PhantornRU commented on modular_ss220/antagonists/code/antag_mix/scenarios/antag_scenario.dm
> +	return FLOOR(population / (antag_cap["denominator"] || 1), 1) + (antag_cap["offset"] || 0)
Это на случай если значения будут null?
`antag_cap["offset"] || 0`

2023-12-13 13:32 UTC, Gaxeer commented on modular_ss220/antagonists/code/antag_mix/scenarios/antag_scenario.dm
> +	return FLOOR(population / (antag_cap["denominator"] || 1), 1) + (antag_cap["offset"] || 0)
да

2023-12-13 13:33 UTC, PhantornRU commented on modular_ss220/antagonists/code/antag_mix/scenarios/antag_team_scenario.dm
> +	var/datum/team/antag_team = /datum/team
Просто присваивание типа? `new /datum/team` в таких случаях тебе не нужен если собираешься смотреть на внутреннюю кухню? Иначе проще оставить эту переменную пустой

2023-12-13 13:34 UTC, PhantornRU commented on modular_ss220/antagonists/code/antag_mix/scenarios/antag_team_scenario.dm
> +	return length(picked_teams) - teams_before > 0
```suggestion
	return (length(picked_teams) - teams_before) > 0
```

2023-12-13 13:34 UTC, Gaxeer commented on modular_ss220/antagonists/code/antag_mix/scenarios/antag_team_scenario.dm
> +	var/datum/team/antag_team = /datum/team
читай комментарий над переменной.
`Path of team, that antags will be joined to.`

2023-12-13 13:35 UTC, PhantornRU commented on modular_ss220/antagonists/code/blood_brothers/blood_brothers_datum.dm
> +			Лучшую возможность бороться с ней предоставляет Синдикат, так что вы со своим напарником, разделяющим подобные чувства, связались с ними, чтобы вступить в их ряды.
Если всё это единый текст, оно не засчитает такие пробелы и считает это как `\` в обычном тексте?

2023-12-13 13:36 UTC, Gaxeer commented on modular_ss220/antagonists/code/blood_brothers/blood_brothers_datum.dm
> +			Лучшую возможность бороться с ней предоставляет Синдикат, так что вы со своим напарником, разделяющим подобные чувства, связались с ними, чтобы вступить в их ряды.
Это табы гитхаба. Нет, всё нормально отображает

2023-12-13 13:36 UTC, PhantornRU commented on modular_ss220/antagonists/code/blood_brothers/blood_brothers_datum.dm
> +		antag_memory += "<b>Ваши братья</b>: [brother_names]<br>"
```suggestion
		antag_memory += "<b>Ваши братья</b>: <br>[brother_names]</br>"
```

2023-12-13 13:36 UTC, Gaxeer commented on modular_ss220/antagonists/code/blood_brothers/blood_brothers_datum.dm
> +		antag_memory += "<b>Место встречи</b>: [meeting_area]<br>"
<br> - это лайн брейк ПОСЛЕ текста. Чтобы следующая строчка была с новой строки

2023-12-13 13:36 UTC, Gaxeer commented on modular_ss220/antagonists/code/blood_brothers/blood_brothers_datum.dm
> +		antag_memory += "<b>Ваши братья</b>: [brother_names]<br>"
Тут то же самое

2023-12-13 13:37 UTC, PhantornRU commented on modular_ss220/antagonists/code/blood_brothers/blood_brothers_datum.dm
> +		if(!mind_to_check || mind_to_check == first_brother || !can_be_owned(mind_to_check))
```suggestion
		if((!mind_to_check || mind_to_check) == (first_brother || !can_be_owned(mind_to_check)))
```

2023-12-13 13:38 UTC, Gaxeer commented on modular_ss220/antagonists/code/blood_brothers/blood_brothers_datum.dm
> +		if(!mind_to_check || mind_to_check == first_brother || !can_be_owned(mind_to_check))
Ты неправильно сгрупировал

2023-12-13 13:38 UTC, Gaxeer commented on modular_ss220/antagonists/code/blood_brothers/blood_brothers_datum.dm
> +		if(!mind_to_check || mind_to_check == first_brother || !can_be_owned(mind_to_check))
не надо тут скобки вообще

2023-12-13 13:39 UTC, PhantornRU requested changes
Посмотрел, есть только мелкие замечания

2023-12-13 13:41 UTC, PhantornRU approved these changes

2023-12-15 06:15 UTC, PhantornRU commented
акадамерж

2023-12-15 21:10 UTC, merged