Translate species info in character preferences menu
ss220club/Paradise-SS220 pull request #852
Opened 2023-12-12 23:41 UTC by dj-34

## Что этот PR делает
Перевод информации о расах (я не лоровед, поэтому могут быть логические ошибки)

## Почему это хорошо для игры
Все допереведено тама будет

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/8069f3a3-791b-4046-96fc-fc87098f8bba)

## Тестирование
Проверил в игре

## Changelog

:cl:
spellcheck: Перевод информации о расах в настройках персонажа
/:cl:

2023-12-13 05:56 UTC, BR54FF commented
Ну, у оффов и у нас разный лор рас, и для примера различий - у наших унатей есть единое образование в виде империи и они не страдают от междуусобиц. Так что надо шлифовать

2023-12-13 05:57 UTC, Aylong220 commented
> Ну, у оффов и у нас разный лор рас, и для примера различий - у наших унатей есть единое образование в виде империи и они не страдают от междуусобиц. Так что надо шлифовать

Ну вот пускай лороведы свяжутся с нами, а лучше сами напишут xdd

2023-12-13 05:59 UTC, dj-34 commented
> Ну, у оффов и у нас разный лор рас, и для примера различий - у наших унатей есть единое образование в виде империи и они не страдают от междуусобиц. Так что надо шлифовать

скажи где и как подправить - я поправлю

2023-12-13 20:14 UTC, dj-34 commented
Сделал правки от лороведов, которые мне отписали. Где-то может что-то проёбано, где-то не так описано - но думаю ниче страшного, поправить потом можно будет.

2023-12-13 20:18 UTC, Gaxeer approved these changes

2023-12-15 06:45 UTC, PhantornRU requested changes

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/diona_species.dm
> +	blurb = "Дионы - растениеподобные существа, состоящие из гештальта более мелких Нимф. \
Я думаю так будет корректнее. Т.к. нимфы не гештальты, но в гештальте нимфы.
```suggestion
	blurb = "Дионы - растениеподобные существа, являющиеся гештальтом состоящим из Нимф. \
```

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/kidan.dm
> +	Они являются относительно незначительными игроками на галактической арене и в настоящее время полностью порабощены людьми и лишены самостоятельности в политических делах, \
Относительно кого?
```suggestion
	Они являются незначительными игроками на галактической арене и в настоящее время полностью порабощены людьми и лишены самостоятельности в политических делах, \
```

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/kidan.dm
> +	вынуждая их пытаться бороться с оккупантами за свою независимость."
убираем косоязычие
```suggestion
	вынуждая их предпринимать попытки борьбы с оккупантами за свою независимость."
```

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/kidan.dm
>  	brute_mod = 0.8
Вот поэтому киданы и проиграли.

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/machine.dm
> +	Мнения о КПБ сильно различаются: от дискриминационных до поддерживающих их права во всем секторе \"Орион\". \
-ющих
```suggestion
	Мнения о КПБ сильно различаются: от дискриминирующих до поддерживающих их права во всем секторе \"Орион\". \
```

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/machine.dm
> +	КПБ заключили множество дипломатических договоров с различными видами, повысив свой статус от простого инструмента до признанных небольших фигур в галактических делах."
Ыыыых. Не нравится "простого инструмента". Прям виден перевод через гугл. Но корректно не могу придумать как бы литературно завернуть. Тут в принципе везде виден гугл. Вот был бы у нас литератор какой...

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/moth.dm
> +	blurb = "Нианы - вид насекомоподобных двуногих, родом с неизвестной планеты. \
```suggestion
	blurb = "Нианы - вид крупных насекомоподобных беспозвоночных, родом с неизвестной планеты. \
```

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/moth.dm
> +	установив вместо этого тесные дипломатические отношения с Союзом Советских Социалистических Планет."
Моли коммунисты, охуеть. Только сейчас об этом узнал.

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/skrell.dm
> +	blurb = "Скреллы - вид гуманоидных амфибий, родом с Кверрбалака, влажной тропической планеты, полной болот и архипелагов. \
Или гуманоидных или амбифиеподобных.
Но в других текстах "гуманоидов" нету. Антропоморфов кстати тоже. :_:

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/slimepeople.dm
> +	blurb = "Слаймомены - желеобразные и полупрозрачные существа из обширных океанов Ксарксиса 5. \
И вновь. Железообразные, а не желеподобные.
Нужно с единой структурой подумать или просто забить на это.

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/tajaran.dm
> +	В их религиозной практике преобладают учения С'рандарра и солнечная иконография, \
Странноразделение. Если это разделители названий, то возможно с больших букв должны быть?
```suggestion
	В их религиозной практике преобладают учения С'Рандарра и солнечная иконография, \
```

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +	Организовавшись в высококонкурентные феодальные королевства, Унатхи не имеют какого-либо широкомасштабного объединения.<br/><br/> \
Звучит плохо. Нужно переформулировать. Можно попробовать добавить "изрядно"

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +	Они скитаются по пустошам Лаваленда, поклоняются мертвому городу и похищают ничего не подозревающих шахтеров."
Мертвому городу... Но там же бог?

2023-12-15 06:45 UTC, PhantornRU commented on code/modules/mob/living/carbon/human/species/vulpkanin.dm
> +	blurb = "Вульпканины - двуногие собакоподобные существа из системы Каппа Кита, подверженной клановым войнам за объединение вида под началом доминирующего. \
Антропоморфов вижу в текстах изрядно избегают

2023-12-16 09:49 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/diona_species.dm
> +	Как гештальт-сущность, каждая Нимфа обладает индивидуальностью, но общаются они коллективно. \
Не согласен

2023-12-16 09:57 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/kidan.dm
> +	Они являются относительно незначительными игроками на галактической арене и в настоящее время полностью порабощены людьми и лишены самостоятельности в политических делах, \
Относительно других видов

2023-12-16 10:00 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/machine.dm
> +	КПБ заключили множество дипломатических договоров с различными видами, повысив свой статус от простого инструмента до признанных небольших фигур в галактических делах."
А что не так с инструментом? Они буквально использовались как инструмент

2023-12-16 10:04 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/tajaran.dm
> +	В их религиозной практике преобладают учения С'рандарра и солнечная иконография, \
В лоре описывается именно как "S'randarr"/"С'рандарр"

2023-12-16 10:06 UTC, dj-34 commented on code/modules/mob/living/carbon/human/species/unathi.dm
> +	Они скитаются по пустошам Лаваленда, поклоняются мертвому городу и похищают ничего не подозревающих шахтеров."
Некрополис

2023-12-18 15:06 UTC, PhantornRU approved these changes

2023-12-18 15:07 UTC, merged