FIX: TTS Рандомизация голоса заспавненного гуманоида
ss220club/Paradise-SS220 pull request #885
Opened 2023-12-26 08:52 UTC by PhantornRU

## Что этот PR делает

Теперь голоса заспавненных кукол случайны, а не являются null.
Также добавлено ограничение в выборе голоса по ПОЛу для ЕРТ и Гиммик команд.
Зеркало теперь может тоже менять голос.

## Почему это хорошо для игры

Педалям больше не придется лезть каждый раз в VV чтобы изменить ТТС голос кукле.
Не будет бегать мужикобаб, не понявшие кто они или чей это голос.

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/ca5b3571-06cf-46c0-b6c5-3d6d57b58287)

## Тестирование

## Changelog

:cl:
tweak: Магическое зеркало может менять голос.
fix: Заспавненные куклы имеют случайный ТТС-голос в зависимости от пола.
fix: ЕРТ группы также получают половое ограничение голоса.
add: Мулботы и хонк боты получили голоса.
/:cl:

2023-12-26 13:50 UTC, Gaxeer requested changes

2023-12-26 13:50 UTC, Gaxeer commented on modular_ss220/text_to_speech/code/tts_seed.dm
>  		return null
```suggestion
	if(!new_tts_seed)
		var/tts_gender = get_converted_tts_seed_gender(user.gender)
		new_tts_seed = input(user, "Выберите голос вашего персонажа", "Преобразуем голос") as null|anything in SStts220.tts_list_names_gender[tts_gender]
		if(!new_tts_seed)
			return null
```

2023-12-26 13:50 UTC, Gaxeer commented on modular_ss220/text_to_speech/code/tts_seed.dm
> +			new_tts_seed = user.client.prefs.active_character.tts_seed
```suggestion
	var/datum/character_save/active_character = user?.client?.prefs.active_character
	var/new_tts_seed
	if(active_character.tts_seed && (user.gender == active_character.gender))
		if(alert(user || src, "Оставляем голос вашего персонажа [active_character.real_name]?", "Выбор голоса", "Нет", "Да") ==  "Да")
			new_tts_seed =active_character.tts_seed
```

2023-12-26 13:50 UTC, Gaxeer commented on modular_ss220/text_to_speech/code/base_seeds/objs/objs.dm
> +		H.change_voice(H)
```suggestion
/obj/structure/mirror/magic/proc/tts_choose(choice, mob/living/carbon/human/human_to_update)
	if(choice == "Voice TTS")
		human_to_update.change_voice(human_to_update)
```

2023-12-26 13:50 UTC, Gaxeer commented on modular_ss220/text_to_speech/code/tts_seed.dm
> +	return seed.name
```suggestion
	var/tts_choice = pick_tts_seed_gender(gender)
	var/datum/tts_seed/seed = SStts220.tts_seeds[tts_choice]
	if(!seed)
		return null
		
	return seed.name
```

2023-12-26 16:41 UTC, dj-34 commented
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/29a8808b-d394-421d-a53d-3f653bce1ab8)

2023-12-26 18:56 UTC, PhantornRU commented
@dj-34 пофиксил и вернул реализацию проверок на донат-тир

2023-12-29 11:17 UTC, Furrior commented on modular_ss220/text_to_speech/_tts.dm
> -/datum/modpack/example
Блять

2023-12-29 11:17 UTC, Furrior commented on modular_ss220/text_to_speech/code/tts_seed.dm
> +	return seed.name
Any гендер подходит всем полам, по задумке, а не только чему то бесполому

2023-12-29 19:03 UTC, PhantornRU commented on modular_ss220/text_to_speech/_tts.dm
> -/datum/modpack/example
Ага

2023-12-29 19:04 UTC, PhantornRU commented on modular_ss220/text_to_speech/code/tts_seed.dm
> +	return seed.name
Четкое разграничение сделал чтобы не было с этим мозгоебли в будущем

2023-12-29 22:29 UTC, dj-34 approved these changes
ватевер

2023-12-29 22:29 UTC, dj-34 commented on code/modules/admin/verbs/gimmick_team.dm
> +		H.change_voice(H)	// SS220 ADD
```suggestion
		H.change_voice(H) // SS220 ADD
```

2023-12-29 22:29 UTC, dj-34 commented on code/game/objects/structures/mirror.dm
> +	tts_choose(choice, H)	// SS220 ADD
```suggestion
	tts_choose(choice, H) // SS220 ADD
```

2024-01-09 09:02 UTC, Legendaxe approved these changes

2024-01-09 09:36 UTC, Gaxeer approved these changes

2024-01-09 09:36 UTC, merged