Add: Новые предметы группы Саундхэнд и барабаны.
ss220club/Paradise-SS220 pull request #890
Opened 2024-01-02 12:17 UTC by Kar4es

## Что этот PR делает
Добавлено:
- Куртки группы Саундхэнд, 3 цвета, 2 вариации - с тэгом группы и без.
- Новый коктейль - Саундхэнд. Вызывает при метаболизации эмоут гитары.
- Добавлена новая аудио машина - барабаны. Функционал как у музыкального автомата.

## Почему это хорошо для игры
Крутые барабаны и шмот рок группы, чем не гуд? Так еще и новый коктейль, ммм.

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/12996481-6f98-4785-99aa-6f8ed789faee)
Более детально - в боте.
## Тестирование

Все было заспавнено, выпито, сыграно, сожжено, одето.
## Changelog

:cl:
add: Появились новый музыкальный "автомат" - барабаны.
add: Новая курта группы Саундхэнд - 2 варианта по 3 цвета.
add: Новый коктейль - Саундхэнд. Делается из 2 частей водки, 1 виски, 1 ягодного сока, 1 юнита черного перца.
add: Новый флаг группы Саундхэнд.
/:cl:

2024-01-02 12:34 UTC, Legendaxe requested changes

2024-01-02 12:34 UTC, Legendaxe commented on modular_ss220/food/code/drinks.dm
> +	return ..()
Зачем два раза родительский прок вызываешь?

2024-01-02 12:34 UTC, Legendaxe commented on modular_ss220/jukebox/code/jukebox.dm
> +		icon_state = "[initial(icon_state)]_anchored"
```suggestion
	icon_state = "[initial(icon_state)][active ? "-active" : "_anchored"]"
```
Только проверь что работает, может опечатку сделал

2024-01-02 12:34 UTC, Legendaxe commented on modular_ss220/jukebox/code/jukebox.dm
> +	if(!active && !(resistance_flags & INDESTRUCTIBLE))
Переделай под early return, что бы уменьшить вложенность ифов

2024-01-02 12:38 UTC, HMBGERDO commented on modular_ss220/food/code/drinks.dm
> +	return ..()
```suggestion
```
после указания 
`. = ..()`
функция уже вернет значение по умолчанию, если не указано другого. Ни `return`, ни `..()` далее писать уже не нужно

2024-01-02 12:42 UTC, Kar4es commented on modular_ss220/jukebox/code/jukebox.dm
> +	if(!active && !(resistance_flags & INDESTRUCTIBLE))
тут не понял что нужно :c

2024-01-02 20:48 UTC, Legendaxe approved these changes

2024-01-02 20:48 UTC, Legendaxe commented on modular_ss220/food/code/drinks.dm
> +		M.emote("airguitar")
```suggestion
		M.emote("airguitar")
		
```

2024-01-03 00:38 UTC, Aylong220 approved these changes
Сойдёт, всё равно жукбокс надо будет рефакторить, когда-нибудь

2024-01-03 00:38 UTC, Aylong220 commented on modular_ss220/jukebox/code/jukebox.dm
> +//Drum
```suggestion
// Drum
```

2024-01-03 00:38 UTC, Aylong220 commented on modular_ss220/jukebox/code/jukebox.dm
> +	playsound(src, 'sound/items/deconstruct.ogg', 50, 1)
```suggestion
		update_icon()

	playsound(src, 'sound/items/deconstruct.ogg', 50, 1)
```

2024-01-04 11:47 UTC, merged