Add: Напитки и коктейли с рупары
ss220club/Paradise-SS220 pull request #898
Opened 2024-01-09 02:39 UTC by Ingakem

## Что этот PR делает
Переносит напитки и коктейли с рупары
Некоторые имеют свои уникальные эффекты

## Почему это хорошо для игры
Новые рецепты и геймплей для барменов
Больше разнообразия напитков

## Изображения изменений

![Screenshot_128](https://github.com/ss220club/Paradise-SS220/assets/146962612/41afde58-f37f-4273-9cd0-cb62a340b18e)

## Тестирование

Проверял на локалке
## Changelog

:cl:
add: Коктейли с рупары
imageadd: Спрайты напитков и коктейлей
:cl:

2024-01-09 02:45 UTC, dj-34 commented
Линтер

2024-01-09 08:20 UTC, PhantornRU requested changes

2024-01-09 08:20 UTC, PhantornRU commented on paradise.dme
> -// SS220 ADDITION END
Ну и зачем убираешь их? Верни обратно.

2024-01-09 08:21 UTC, PhantornRU commented
Коммиты нормально называй, а не цифрами.

2024-01-09 19:23 UTC, Aylong220 commented
Я изначально был против переноса коктейлей с рупары, как раз по причине их... бессмысленности? На оффах почти каждый коктейль имеет уникальный эффект, на рупаре же от силы 5 уникальных и 5 с прикольным спрайтом

2024-01-09 19:25 UTC, Aylong220 commented
Плюс, многие коктейли на рупаре - просто реколор и ренейм существующих, с немного другим рецептом, было бы неплохо если бы ты такие либо удалил, либо перекрасил взяв за основу существующие коктейли с оффов

2024-01-09 19:26 UTC, Aylong220 commented
Плюс, имя и описание можешь перевести сразу

2024-01-12 10:39 UTC, Aylong220 commented
Обнови пикчу засунув все коктейли, если не сложно :xdd:
Хотя смысла в этом мало

2024-01-12 11:35 UTC, PhantornRU approved these changes

2024-01-14 09:38 UTC, merged