Translate areas
ss220club/Paradise-SS220 pull request #913
Opened 2024-01-17 20:15 UTC by Kar4es

## Что этот PR делает

## Почему это хорошо для игры

## Изображения изменений

## Тестирование

## Changelog

:cl:
add: Что-то добавил
del: Что-то удалил
tweak: Поменял что-то по мелочи
fix: Что-то починил
wip: Какие-либо наработки в процессе
soundadd: Добавил новый звук
sounddel: Удалил старый звук
imageadd: Добавил новую картинку
imagedel: Удалил старую картинку
spellcheck: Исправил опечатку
experiment: Добавил эксперементальную функцию
/:cl:

2024-01-17 22:58 UTC, RuslanM commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "\improper Конференц Зал Командования"
Конференц-зал

2024-01-17 23:08 UTC, RuslanM commented on code/game/area/ss13_areas/ai_areas.dm
>  	sound_environment = SOUND_ENVIRONMENT_ROOM
Зона есть на Дельте, что вообще странно, т.к. все зоны спутника - это спутник. Нелогично иметь зону "Спутник ИИ"

2024-01-17 23:40 UTC, RuslanM reviewed
Привет. Большая часть комментариев - вкусовщина, просто предложения.

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Таможня"
Я понимаю, что "Customs" буквально "Таможня", но кто поймёт, что это прибытие? Нет никакой механики растаможки. Может быть, перевести как "Блокпост охраны в прибытии"? Или заменить зону.
Даже иконка у зоны "Checkpoint sec"

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "\improper Инженерное Фойе"
Обычно говорят "Фойе чего-то там". Предлагаю "Фойе Инженерного Отдела"

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "\improper Двигатель Супер Материи"
"Суперматерии" в одно слово

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/legal_areas.dm
> +	name = "\improper Офис Юриста"
Учитывая, что АВД может быть больше одного, предлагаю "Юридический офис".
А вообще, "Офис АВД" будет даже понятнее

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "Хранилище Медбея"
Странно перевести "Medbay" как медицинский отдел, а потом везде использовать транслит "медбей"
Игроки поймут, но ради последовательности, либо мед. отдел так и перевести "медбей", либо везде "медбей" заменить на "медицинский отдел"

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "Парамедик"
"Офис Парамедика", может быть? В основном зоны лаборатория, тоннель, кухня, а тут как будто одушевленный человек - это целая зона.
Можно "Каморка Парамедика"

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "\improper Основной Коридор"
"Носовой Основной Коридор" + ниже тоже "носовой"

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "\improper Основной Коридор Кормы"
Если Fore будет "носовой", то тут можно "Кормовой Основной Коридор"

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "\improper Офис Мистера Чанга"
Разве это офис, а не забегаловка? Можно "У Мистера Чанга" или "Кафе...". Или даже "Забегаловка..."

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/service_areas.dm
> +	name = "\improper Офис Уборщика"
Для уборщика слово "офис" слишком громкое. "Каморка Уборщика"?

2024-01-17 23:40 UTC, RuslanM commented on code/game/area/ss13_areas/supply_areas.dm
> +	name = "\improper Мех Отсек Шахты"
Выше "Мех. отсек" с точкой. Нужно оба раза точку или оба раза без точки

2024-01-18 01:20 UTC, PhantornRU commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "\improper Офис Мистера Чанга"
Поддержу забегаловку.

2024-01-18 01:48 UTC, dj-34 commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "\improper Конференц Зал Командования"
Тогда уж Конференц-зал Командования

2024-01-18 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Таможня"
это Контрольно-Пропускной Пункт, и судя по всему Командный

2024-01-18 01:52 UTC, dj-34 commented on code/game/area/ss13_areas/legal_areas.dm
> +	name = "\improper Офис Юриста"
Юридический Отдел

2024-01-18 01:55 UTC, dj-34 commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "Парамедик"
Офис Парамедика подойдет

2024-01-18 01:57 UTC, dj-34 commented on code/game/area/ss13_areas/supply_areas.dm
> +	name = "\improper Мех Отсек Шахты"
Почему шахты?

2024-01-18 03:34 UTC, dj-34 requested changes

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "\improper Комната Для Фитнеса"
```suggestion
	name = "\improper Фитнес-зал"
```

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "\improper Магазин Питомцев"
```suggestion
	name = "\improper Зоомагазин"
```

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "\improper Лаболатория E.X.P.E.R.I-MENTOR"
```suggestion
	name = "\improper Лаборатория E.X.P.E.R.I-MENTOR"
```

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "\improper Лаболатория Генетики"
Да ты со своими лаболаториями бля
```suggestion
	name = "\improper Лаборатория Генетики"
```

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/science_areas.dm
>  	name = "\improper Supermatter Lab"
```suggestion
	name = "\improper Лаборатория Суперматерии"
```

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "\improper Лаболатория Ксенобиологии"
```suggestion
	name = "\improper Лаборатория Ксенобиологии"
```

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "\improper Серверная Комната"
```suggestion
	name = "\improper Серверная"
```

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "\improper Холодильник Серверной Комнаты"
```suggestion
	name = "\improper Холодильная Камера Серверной"
```

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/security_areas.dm
>  	name = "\improper Brig Secure Hallway"
А это че не перевёл?

2024-01-18 03:34 UTC, dj-34 commented on code/game/area/ss13_areas/supply_areas.dm
> +	name = "\improper Офис Квартермейстера"
```suggestion
	name = "\improper Офис Квартирмейстера"
```

2024-01-18 06:55 UTC, Kar4es commented on code/game/area/ss13_areas/security_areas.dm
>  	name = "\improper Brig Secure Hallway"
не используется на Дельте и Кибериаде :/

2024-01-18 06:55 UTC, Kar4es commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "Технические Тоннели Носовой Части. Порт"
Ну вот насчет этой фигни тоже так подумал, сделоем

2024-01-18 06:59 UTC, Kar4es commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Таможня"
вот тут и были вопросы как перевести правильно

Ибо это по факту - таможня, только вот юзлес штука которую юзают только антаги :/

2024-01-18 07:02 UTC, Kar4es commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "Хранилище Медбея"
я старался как можно меньше буков использовать, ибо хз как это будет выглядеть, например, в тех же тревогах

2024-01-18 07:05 UTC, Kar4es commented on code/game/area/ss13_areas/supply_areas.dm
> +	name = "\improper Мех Отсек Шахты"
Я прикинул и понял что по идее эта зона используется на лаве, но у нас есть уже идентичная зона с таким же названием

2024-01-18 07:17 UTC, Kar4es commented on code/game/area/ss13_areas/supply_areas.dm
> +	name = "\improper Мех Отсек Шахты"
Сейчас глянул - юзлесс зона

2024-01-18 07:29 UTC, Kar4es commented on code/game/area/ss13_areas/security_areas.dm
>  	name = "\improper Brig Secure Hallway"
А стоп

2024-01-18 07:49 UTC, Kar4es commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "\improper Серверная Комната"
Почему бы серверной не быть комнатой?

2024-01-18 07:50 UTC, Kar4es commented on code/game/area/ss13_areas/security_areas.dm
>  	name = "\improper Brig Secure Hallway"
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/34453b50-0ad1-4cff-835d-cf6c6e94bd5b)
прикол гита?

2024-01-19 01:51 UTC, dj-34 requested changes
1. Почему-то ты не всё перевел. Оправдание такой зоны нет на Дельте - такое себе, потому что появление новых зон не редкое явление, и у нас играют не только на Дельте (на Кибериаде будет разнобой английского и русского), лучше доперевести всё, тем более что тут немного.
2. Попробуй везде убрать \improper и \proper. Оно должно хендлить автоматически зависимо от того, написано ли название с большой или маленькой буквы. Если написано с большой, то The по идеи не должно быть. 
Перепроверь чтобы не было "the Бассейн" и тому подобное.
3. Резолв конверсейшена без резолва проблемс

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/ai_areas.dm
> +	name = "\improper Атмосферная Комната Спутника ИИ"
Звучит странно, чего там атмосферного? LUL
```suggestion
	name = "\improper Атмос Спутника ИИ"
```

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "Северо-Восточные Технические Тоннели "
```suggestion
	name = "Северо-Восточные Технические Тоннели"
```

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "Старая Комната Генетики"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "Старая Комната Электрооборудования"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name ="Электроника Дэна"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/maintenance_areas.dm
>  	name = "Gambling Den"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "\improper Комната ожидания Медицинского Отдела"
```suggestion
	name = "\improper Комната Ожидания Медицинского Отдела"
```

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/medical_areas.dm
>  	name = "Isolation Access"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/medical_areas.dm
>  	name = "\improper Surgery"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "Первая Хирургия"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "Вторая Хирургия"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/medical_areas.dm
>  	name = "Surgery Observation"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/science_areas.dm
>  	name = "\improper Supermatter Lab"
Не исправлено

2024-01-19 01:51 UTC, dj-34 commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "\improper Серверная Комната"
Потому что серверная уже изначально предполагает комнату где хранятся сервера

2024-01-19 05:32 UTC, Kar4es commented
@dj-34 У тебя Гит как то странно показывает изменения. Почти все что ты указал - изменено

2024-01-19 05:43 UTC, Aylong220 reviewed
Почему не перевёл?
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/37f7dff3-69aa-4f7a-a9d9-ebf462445e92)

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "Старый Бар"
```suggestion
	name = "Заброшенный Бар"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "Старая Библиотека"
```suggestion
	name = "Заброшенная Библиотека"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "\improper Старый Театр"
```suggestion
	name = "\proper Заброшенный Театр"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "\improper Северо-Восточные Солнечные Панели"
```suggestion
	name = "\proper Северо-Восточные Солнечные Панели"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "\improper Юго-Восточные Солнечные Панели"
```suggestion
	name = "\proper Юго-Восточные Солнечные Панели"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "\improper Юго-Западные Солнечные Панели"
```suggestion
	name = "\proper Юго-Западные Солнечные Панели"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "\improper Северо-Восточные Солнечные Панели"
```suggestion
	name = "\proper Северо-Восточные Солнечные Панели"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "\improper Комната Сборочной Линии"
```suggestion
	name = "\proper Комната Сборочной Линии"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "\improper Старый Сад"
```suggestion
	name = "\proper Старый Сад"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "\improper Медицинский Отдел"
```suggestion
	name = "\proper Медицинский Отдел"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "\improper Медицинский Отдел"
Расставь проперы там где меняешь

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "Хранилище Медицинского Отдела"
```suggestion
	name = "Склад Медицинского Отдела"
```

2024-01-19 05:43 UTC, Aylong220 commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "\proper Криохранилище Дормиторий"
```suggestion
	name = "\proper Криохранилище Дормитория"
```

2024-01-19 05:46 UTC, Aylong220 commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "\proper Зона Для Строительства"
```suggestion
	name = "\proper Зона для Строительства"
```

2024-01-21 12:52 UTC, m-dzianishchyts requested changes

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Спальня Капитана"
```suggestion
	name = "Каюта Капитана"
```
Возможно, раз на станции экипаж, то и комнатам стоит быть каютами

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Гейт"
```suggestion
	name = "Врата"
```
Русские вперед

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Распределительный Контур Атмосферии"
```suggestion
	name = "Атмосферный Распределительный Контур"
```
Атмосферный отдел, Атмос, Атмосферия... Это влезет?

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Инженерные СМЕСы"
```suggestion
	name = "Инженерные СКАНы"
```
Ну раз ВКД, то СКАН

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Второе Фойе Инженерного Отдела"
Было уже "Дополнительное", стоит что-то одно, наверное

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Южно-Восточные Солнечные Панели"
```suggestion
	name = "Юго-Восточные Солнечные Панели"
```

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Южно-Западные Солнечные Панели"
```suggestion
	name = "Юго-Западные Солнечные Панели"
```

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "Второстепенные Северо-Западные Технические Тоннели"
Как-то странновато звучит... Наверное, "дополнительные" или "вспомогательные"

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/maintenance_areas.dm
> +	name = "Заброшеный Театр"
```suggestion
	name = "Заброшенный Театр"
```

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "Комнаты Пациентов"
```suggestion
	name = "Палаты Пациентов"
```

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/medical_areas.dm
> +	name = "Офис Парамедик"
```suggestion
	name = "Офис Парамедика"
```

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "Южно-Западный Коридор"
```suggestion
	name = "Юго-Западный Коридор"
```

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "Южно-Восточный Коридор"
```suggestion
	name = "Юго-Восточный Коридор"
```

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "Южно-Северный Коридор"
Так стоп....

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "Вакантный Офис"
```suggestion
	name = "Пустой Офис"
```
Имхо

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "Мех. Отсек РНД"
```suggestion
	name = "Мех-отсек РНД"
```
Ну будто так лучше, но РНД сомнительно, русские недовольны

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "Комната Отдыха РНД"
```suggestion
	name = "Комната Отдыха Отдела Исследований"
```
Ну так значит так

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "Тестовая Комната Токиснов РНД"
```suggestion
	name = "Тестовая Комната Плазмы РНД"
```
Вроде уже как-то токсины и из кода выводят

2024-01-21 12:52 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/security_areas.dm
> +	name = "Стрельбище"
```suggestion
	name = "Тир"
```
Ну реально

2024-01-21 12:52 UTC, m-dzianishchyts commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "Южный Контрольно-Пропускной Пункт Службы Безопасности"
```suggestion
	name = "Южный КПП Службы Безопасности"
```
Ну наверное

2024-01-21 12:52 UTC, m-dzianishchyts commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "Гараж Под Пилота Службы Безопасности"
```suggestion
	name = "Гараж Пилота Пода Службы Безопасности"
```
А как под... Ну пока так

2024-01-21 12:52 UTC, m-dzianishchyts commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "Syndicate Forward Base"
а где

2024-01-21 12:55 UTC, Kar4es commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Спальня Капитана"
у капитана буквально спальня, каюты у глав

2024-01-21 12:55 UTC, Kar4es commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Инженерные СМЕСы"
Это обсуждалось, решено оставить СМЕСы

2024-01-21 12:56 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Спальня Капитана"
офисы же

2024-01-21 12:57 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Спальня Капитана"
загугли просто каюту, вроде это как раз то самое

2024-01-21 13:45 UTC, m-dzianishchyts commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "Мех. Отсек РНД"
Русские все же достаточно довольны

2024-01-22 10:14 UTC, dj-34 requested changes

2024-01-22 10:14 UTC, dj-34 commented on code/game/area/ss13_areas/ai_areas.dm
> +	name = "Аплоуд ИИ"
Сомнительнооо, нооо, оукей?

2024-01-22 10:14 UTC, dj-34 commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Спальня Капитана"
Все правильно, это каюта. Поправь

2024-01-22 10:14 UTC, dj-34 commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Гейт"
Не надо.

2024-01-22 10:14 UTC, dj-34 commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Комната Сервера Мессенджера"
```suggestion
	name = "Серверная Комната Обработки Сообщений"
```

2024-01-22 10:14 UTC, dj-34 commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Распределительный Контур Атмосферии"
Согласен

2024-01-22 10:14 UTC, dj-34 commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Южно-Восточные Солнечные Панели"
Согласен

2024-01-22 10:14 UTC, dj-34 commented on code/game/area/ss13_areas/engineering_areas.dm
> +	name = "Южно-Западные Солнечные Панели"
Согласен

2024-01-22 10:16 UTC, dj-34 commented on code/game/area/ss13_areas/command_areas.dm
> +	name = "Гейт"
Не надо.

2024-01-22 10:17 UTC, dj-34 commented on code/game/area/ss13_areas/public_areas.dm
> +	name = "Вакантный Офис"
Тогда уж Свободный

2024-01-22 10:17 UTC, dj-34 commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "Мех. Отсек РНД"
через точку

2024-01-22 10:17 UTC, dj-34 commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "Южный Контрольно-Пропускной Пункт Службы Безопасности"
И так нормально

2024-01-27 12:58 UTC, Kar4es commented on code/game/area/ss13_areas/science_areas.dm
> +	name = "Тестовая Комната Токиснов РНД"
Не уверен что стоит менять, ибо у нас все таки токсины изучают

2024-01-27 12:58 UTC, Kar4es commented on code/game/area/ss13_areas/security_areas.dm
> +	name = "Стрельбище"
Не вижу особой разницы между первым и вторым, но первое звучит круче :/

2024-01-27 13:04 UTC, Kar4es commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "Гараж Под Пилота Службы Безопасности"
Тут хз, стоит ли

2024-01-28 01:42 UTC, dj-34 approved these changes
Надеюсь теперь точно пойдет

2024-01-28 01:58 UTC, Kar4es commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "Syndicate Forward Base"
Не важно, есть он или нет

2024-01-28 13:25 UTC, Aylong220 approved these changes

2024-01-28 13:25 UTC, Aylong220 commented on modular_ss220/maps220/code/Areas/station.dm
> +	name = "Гараж Под Пилота Службы Безопасности"
```suggestion
	name = "Гараж Под-пилота Службы Безопасности"
```

2024-01-29 00:37 UTC, dj-34 commented
А про контрактора с его хардкод названиями зон забыли?

2024-01-29 00:39 UTC, Kar4es commented
> А про контрактора с его хардкод названиями зон забыли?

че его еще переводить?

2024-01-29 00:40 UTC, dj-34 commented
> > А про контрактора с его хардкод названиями зон забыли?
> 
> че его еще переводить?

Ну я не знаю где еще захардкожено по названиям зон, но ему точно требуется перевод зоны доставки в соответствии с переводом твоим

2024-01-29 00:41 UTC, Kar4es commented
> > > А про контрактора с его хардкод названиями зон забыли?
> > 
> > 
> > че его еще переводить?
> 
> Ну я не знаю где еще захардкожено по названиям зон, но ему точно требуется перевод зоны доставки в соответствии с переводом твоим

а можешь скинуть путь где нужно глянуть?

2024-01-29 00:47 UTC, dj-34 commented
> > > > А про контрактора с его хардкод названиями зон забыли?
> > > 
> > > 
> > > че его еще переводить?
> > 
> > 
> > Ну я не знаю где еще захардкожено по названиям зон, но ему точно требуется перевод зоны доставки в соответствии с переводом твоим
> 
> а можешь скинуть путь где нужно глянуть?

![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/b9df9310-87a9-4640-ad2f-db706b85be00)

2024-01-29 00:54 UTC, dj-34 commented
Кажется мне была еще проверка у турелей ИИ, но надо искать смотреть

2024-01-29 01:19 UTC, Kar4es commented
> > > > > А про контрактора с его хардкод названиями зон забыли?
> > > > 
> > > > 
> > > > че его еще переводить?
> > > 
> > > 
> > > Ну я не знаю где еще захардкожено по названиям зон, но ему точно требуется перевод зоны доставки в соответствии с переводом твоим
> > 
> > 
> > а можешь скинуть путь где нужно глянуть?
> 
> ![image](https://private-user-images.githubusercontent.com/20109643/300306484-b9df9310-87a9-4640-ad2f-db706b85be00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0ODk1NTQsIm5iZiI6MTcwNjQ4OTI1NCwicGF0aCI6Ii8yMDEwOTY0My8zMDAzMDY0ODQtYjlkZjkzMTAtODdhOS00NjQwLWFkMmYtZGI3MDZiODViZTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAwNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYWFjZmQ2NzcyOThjZjk2MTUxNWE5ZDkyMmQzZmRkMjczYTgwNzg4ZTIxNjVmNzU2OTFiNmIzN2Q5ZmNkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1EOJ6pqErD4asOyEMseoBKHtI8japWlM8mg2CWT0Jc)

Пиздец

2024-01-29 01:20 UTC, Kar4es commented
> > > > > > А про контрактора с его хардкод названиями зон забыли?
> > > > > 
> > > > > 
> > > > > че его еще переводить?
> > > > 
> > > > 
> > > > Ну я не знаю где еще захардкожено по названиям зон, но ему точно требуется перевод зоны доставки в соответствии с переводом твоим
> > > 
> > > 
> > > а можешь скинуть путь где нужно глянуть?
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/20109643/300306484-b9df9310-87a9-4640-ad2f-db706b85be00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0ODk1NTQsIm5iZiI6MTcwNjQ4OTI1NCwicGF0aCI6Ii8yMDEwOTY0My8zMDAzMDY0ODQtYjlkZjkzMTAtODdhOS00NjQwLWFkMmYtZGI3MDZiODViZTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAwNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYWFjZmQ2NzcyOThjZjk2MTUxNWE5ZDkyMmQzZmRkMjczYTgwNzg4ZTIxNjVmNzU2OTFiNmIzN2Q5ZmNkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1EOJ6pqErD4asOyEMseoBKHtI8japWlM8mg2CWT0Jc)
> 
> Пиздец

Контрактор судя по коду сейчас вообще не работает, ибо он зоны не находит, а он их ищет от имени

2024-01-29 03:33 UTC, dj-34 commented
> > > > > > > А про контрактора с его хардкод названиями зон забыли?
> > > > > > 
> > > > > > 
> > > > > > че его еще переводить?
> > > > > 
> > > > > 
> > > > > Ну я не знаю где еще захардкожено по названиям зон, но ему точно требуется перевод зоны доставки в соответствии с переводом твоим
> > > > 
> > > > 
> > > > а можешь скинуть путь где нужно глянуть?
> > > 
> > > 
> > > ![image](https://private-user-images.githubusercontent.com/20109643/300306484-b9df9310-87a9-4640-ad2f-db706b85be00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0ODk1NTQsIm5iZiI6MTcwNjQ4OTI1NCwicGF0aCI6Ii8yMDEwOTY0My8zMDAzMDY0ODQtYjlkZjkzMTAtODdhOS00NjQwLWFkMmYtZGI3MDZiODViZTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAwNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYWFjZmQ2NzcyOThjZjk2MTUxNWE5ZDkyMmQzZmRkMjczYTgwNzg4ZTIxNjVmNzU2OTFiNmIzN2Q5ZmNkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1EOJ6pqErD4asOyEMseoBKHtI8japWlM8mg2CWT0Jc)
> > 
> > 
> > Пиздец
> 
> Контрактор судя по коду сейчас вообще не работает, ибо он зоны не находит, а он их ищет от имени

Все работает

2024-01-29 03:33 UTC, Kar4es commented
> > > > > > > > А про контрактора с его хардкод названиями зон забыли?
> > > > > > > 
> > > > > > > 
> > > > > > > че его еще переводить?
> > > > > > 
> > > > > > 
> > > > > > Ну я не знаю где еще захардкожено по названиям зон, но ему точно требуется перевод зоны доставки в соответствии с переводом твоим
> > > > > 
> > > > > 
> > > > > а можешь скинуть путь где нужно глянуть?
> > > > 
> > > > 
> > > > ![image](https://private-user-images.githubusercontent.com/20109643/300306484-b9df9310-87a9-4640-ad2f-db706b85be00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0ODk1NTQsIm5iZiI6MTcwNjQ4OTI1NCwicGF0aCI6Ii8yMDEwOTY0My8zMDAzMDY0ODQtYjlkZjkzMTAtODdhOS00NjQwLWFkMmYtZGI3MDZiODViZTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAwNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYWFjZmQ2NzcyOThjZjk2MTUxNWE5ZDkyMmQzZmRkMjczYTgwNzg4ZTIxNjVmNzU2OTFiNmIzN2Q5ZmNkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1EOJ6pqErD4asOyEMseoBKHtI8japWlM8mg2CWT0Jc)
> > > 
> > > 
> > > Пиздец
> > 
> > 
> > Контрактор судя по коду сейчас вообще не работает, ибо он зоны не находит, а он их ищет от имени
> 
> Все работает

такс, значит я сейчас зря час ебался?

2024-01-29 03:34 UTC, dj-34 commented
> > > > > > > > > А про контрактора с его хардкод названиями зон забыли?
> > > > > > > > 
> > > > > > > > 
> > > > > > > > че его еще переводить?
> > > > > > > 
> > > > > > > 
> > > > > > > Ну я не знаю где еще захардкожено по названиям зон, но ему точно требуется перевод зоны доставки в соответствии с переводом твоим
> > > > > > 
> > > > > > 
> > > > > > а можешь скинуть путь где нужно глянуть?
> > > > > 
> > > > > 
> > > > > ![image](https://private-user-images.githubusercontent.com/20109643/300306484-b9df9310-87a9-4640-ad2f-db706b85be00.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY0ODk1NTQsIm5iZiI6MTcwNjQ4OTI1NCwicGF0aCI6Ii8yMDEwOTY0My8zMDAzMDY0ODQtYjlkZjkzMTAtODdhOS00NjQwLWFkMmYtZGI3MDZiODViZTAwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI5VDAwNDczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhYWFjZmQ2NzcyOThjZjk2MTUxNWE5ZDkyMmQzZmRkMjczYTgwNzg4ZTIxNjVmNzU2OTFiNmIzN2Q5ZmNkYTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.x1EOJ6pqErD4asOyEMseoBKHtI8japWlM8mg2CWT0Jc)
> > > > 
> > > > 
> > > > Пиздец
> > > 
> > > 
> > > Контрактор судя по коду сейчас вообще не работает, ибо он зоны не находит, а он их ищет от имени
> > 
> > 
> > Все работает
> 
> такс, значит я сейчас зря час ебался?

так блять, я тебе написал что контрактор берет названия зон для поиска места. Ты сказал что "контрактор не работает", я тебе говорю что работает

2024-01-29 04:23 UTC, Kar4es commented on code/game/area/areas/mining_areas.dm
> +	name = "Складское Помещение Шахтерского Аванпоста"
я бы понял подсобка, но почему уборщика то

2024-01-29 04:24 UTC, Kar4es commented on code/game/area/areas/mining_areas.dm
> +	name = "Просторы Лаваленда"
тут вообще не уверен был как перевести, ибо там не пустошей нет, ни просторов. Надо другое слово какое то

2024-01-30 11:35 UTC, dj-34 commented on code/game/area/areas/mining_areas.dm
> +	name = "Лаваленд Трудового Лагеря"
А почему пометил решенным? Это Трудовой Лагерь Лаваленда, а оно не исправлено :/

2024-01-30 11:47 UTC, Kar4es commented on code/game/area/areas/mining_areas.dm
> +	name = "Лаваленд Трудового Лагеря"
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/149de1aa-58d8-49bf-a0bc-5eddfc0738b5)

2024-01-30 11:47 UTC, Kar4es commented on code/game/area/areas/mining_areas.dm
> +	name = "Лаваленд Трудового Лагеря"
> А почему пометил решенным? Это Трудовой Лагерь Лаваленда, а оно не исправлено :/

кто знает, кто знает...

2024-01-31 16:55 UTC, Aylong220 commented on code/modules/antagonists/traitor/contractor/datums/objective_contract.dm
>  			"Escape Shuttle Hallway Podbay",
Чё это не перевёл кстати?

2024-01-31 16:55 UTC, Aylong220 commented on code/modules/antagonists/traitor/contractor/datums/objective_contract.dm
>  			"Holodeck Alpha",
И это

2024-02-07 07:53 UTC, PhantornRU approved these changes
Устраивает.

2024-02-07 14:31 UTC, merged