Translate: Bot translations and fixes of previous translations
ss220club/Paradise-SS220 pull request #921
Opened 2024-01-19 06:55 UTC by dj-34

## Что этот PR делает
- Перевод сообщений от ботов
- Фиксы того что просрал в своем прошлом ПРе

## Почему это хорошо для игры
Приятно слушать ТТС, меньше ошибок, больше переводов

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/326a0618-397f-46c8-b101-19a4f717beff)

## Тестирование
Глянул в игре

## Changelog

:cl:
add: Перевод сообщений от ботов (секботы, медботы, хонкбот, флурбот)
tweak: Доперевел слот-машину и заголовки станционных оповещений (надеюсь)
spellcheck: Грамматические исправления перевода у оповещений
/:cl:

2024-01-21 12:11 UTC, Gaxeer commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +			speak("Назад! Я сам разберусь с свиньей <b>[C]</b> с уровнем угрозы [threat] в [location]!.", radio_channel)
```suggestion
			speak("Назад! Я сам разберусь со свиньей <b>[C]</b> с уровнем угрозы [threat] в [location]!.", radio_channel)
```

2024-01-21 12:12 UTC, Gaxeer approved these changes

2024-01-21 12:19 UTC, PhantornRU requested changes

2024-01-21 12:19 UTC, PhantornRU commented on code/game/gamemodes/miniantags/pulsedemon/pulsedemon_interactions.dm
> +		speak("Внимание, обнаружена угроза уровня 10!")
```suggestion
		speak("Внимание, обнаружена угроза 10 уровня!")
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/bot/bot.dm
> +		speak("Включение режима патрулирования.")
```suggestion
		speak("Включен режим патрулирования.")
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/bot/bot.dm
> +		speak("Отключение режима патрулирования.")
```suggestion
		speak("Отключен режим патрулирования.")
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/bot/ed209bot.dm
> +			speak("Внимание, обнаружена угроза уровня [threatlevel]!")
```suggestion
			speak("Внимание, обнаружена угроза [threatlevel] уровня!")
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +			speak("Назад! Я сам разберусь с свиньей <b>[C]</b> с уровнем угрозы [threat] в [location]!.", radio_channel)
Свинья у нас не особо ругательство и звучит косоязычно, никто свиньями друг друга не называет. А вот ублюдками - вполне.
```suggestion
			speak("Назад! Я сам разберусь с ублюдком <b>[C]</b> [threat] уровня угрозы в [location]!.", radio_channel)
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +			speak("Назад! Я сам разберусь с свиньей <b>[C]</b> с уровнем угрозы [threat] в [location]!.", radio_channel)
Или другой вариант. Засранец.
```suggestion
			speak("Назад! Я сам разберусь с засранцем <b>[C]</b> [threat] уровня угрозы в [location]!.", radio_channel)
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +					speak("Болван и неудачник.")
Болван - лишнее и не вписывается.
```suggestion
					speak("Неудачник.")
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +			speak("Смелый дохуя?")
А вот тут хорошо xdd

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +			speak("Внимание, обнаружена угроза уровня [threatlevel]!")
```suggestion
			speak("Внимание, обнаружена угроза [threatlevel] уровня !")
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/mob/living/simple_animal/bot/secbot.dm
> +		speak("Внимание, проводится [arrest_type ? "задержание" : "арест"] преступного отродья <b>[C]</b> с уровнем угрозы [threat] в [location]!", radio_channel)
```suggestion
		speak("Внимание, проводится [arrest_type ? "задержание" : "арест"] преступного отродья <b>[C]</b> с [threat] уровнем угрозы в [location]!", radio_channel)
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/response_team/ert.dm
> +	GLOB.major_announcement.Announce("Внимание, [station_name()]. Мы направляем усиленный отряд быстрого реагирования кода «РЭД». Ожидайте.", "ОБР в пути.")
```suggestion
	GLOB.major_announcement.Announce("Внимание, [station_name()]. Мы направляем усиленный отряд быстрого реагирования кода «RED». Ожидайте.", "ОБР в пути.")
```

2024-01-21 12:19 UTC, PhantornRU commented on code/modules/response_team/ert.dm
> +	GLOB.major_announcement.Announce("Внимание, [station_name()]. Мы направляем элитный отряд быстрого реагирования кода «ГАММА». Ожидайте.", "ОБР в пути.")
```suggestion
	GLOB.major_announcement.Announce("Внимание, [station_name()]. Мы направляем элитный отряд быстрого реагирования кода «GAMMA». Ожидайте.", "ОБР в пути.")
```

2024-01-21 12:20 UTC, dj-34 commented on code/modules/response_team/ert.dm
> +	GLOB.major_announcement.Announce("Внимание, [station_name()]. Мы направляем команду высококвалифицированных ассистентов для оказания помощи(?) вам. Ожидайте.", "ОБР в пути.")
```suggestion
	GLOB.major_announcement.Announce("Внимание, [station_name()]. Мы направляем команду высококвалифицированных ассистентов для оказания помощи(?). Ожидайте.", "ОБР в пути.")
```

2024-01-21 12:23 UTC, dj-34 commented on code/game/gamemodes/miniantags/pulsedemon/pulsedemon_interactions.dm
> +		speak("Внимание, обнаружена угроза уровня 10!")
Я нарочно сделал именно так, что бы хорошо отрабатывало склонения и не было "Внимание, обнаружена угроза десять уровня"

2024-01-21 12:25 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/bot.dm
> +		speak("Включение режима патрулирования.")
Зачем?

2024-01-21 13:18 UTC, dj-34 commented on code/modules/mob/living/simple_animal/bot/griefsky.dm
> +			speak("Назад! Я сам разберусь с свиньей <b>[C]</b> с уровнем угрозы [threat] в [location]!.", radio_channel)
Мне нравится свин, опрос показал все-таки хоть и на одного, но больше в свина
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/ac2d7007-9c0c-4191-98f6-ceb157ce57ee)

2024-01-21 13:18 UTC, dj-34 commented on code/modules/response_team/ert.dm
> +	GLOB.major_announcement.Announce("Внимание, [station_name()]. Мы направляем усиленный отряд быстрого реагирования кода «РЭД». Ожидайте.", "ОБР в пути.")
ТТС плохо озвучивает. Только ради этого.

2024-01-22 10:38 UTC, PhantornRU approved these changes

2024-01-22 10:39 UTC, Aylong220 approved these changes

2024-01-22 10:42 UTC, merged