Translate: DNA блок генетика.
ss220club/Paradise-SS220 pull request #923
Opened 2024-01-19 23:03 UTC by azym76

## Что этот PR делает
Переводит сообщения активации генов, а также описание генов. Консоль генетика не затрагивалась в переводе. 

## Почему это хорошо для игры
Локализация на русский язык

## Изображения изменений

## Тестирование
В игре проблем не заметил, но после обновления билда сервера невозможно было протестировать оставшуюся часть перевода из-за ошибки компиляции. Проверял на чистом билде сервера - ошибка при компиляции осталась.

## Changelog

:cl:
add: Перевод контента за генетика. 
/:cl:

2024-01-20 08:21 UTC, dj-34 commented
Тяжело... тяжело...
![image](https://github.com/ss220club/Paradise-SS220/assets/20109643/31ed841a-9f3d-4a24-bd70-4721bdd245a6)

Позже гляну

2024-01-31 17:24 UTC, Aylong220 requested changes
Я бы ещё заменил все "Вы" и прочие формальности на "Ты"
Так как "You" это и ты и вы, в общем нет разделения, и переводчик как правило переводит "Вы"
Так легко раскусить того кто использует машинный перевод xdd

Плюс, НАСТАИВАЮ на проверке этого всего в игре, а то будет бред ебаный а не перевод, спасибо английским местоимениям

Я проверил далеко не всё, остановился там где последний коммент, так как вижу что не тестировал в игре а просто перевёл в переводчике

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/disabilities.dm
> +	activation_messages = list("Вы чувствуете головокружение.")
```suggestion
	activation_messages = list("Вы чувствуете легкомысленность.")
```
Наверное так? Сомневаюсь что тут имелось ввиду головокружение

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/disabilities.dm
> +	activation_messages = list("Вы чувствуете нервозность.")
```suggestion
	activation_messages = list("Вы начинаете нервничать.")
```

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/disabilities.dm
> +	activation_messages = list("Вы ничего не можете увидеть.")
```suggestion
	activation_messages = list("Кто-то выключил свет?")
```
Простор для отсебятины Clueless
Ну или "Вы ничего не видите."

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/disabilities.dm
> +	activation_messages = list("Ваши глаза чувствуют себя странно...")
```suggestion
	activation_messages = list("Всё вокруг стало мутным...")
```
Не обязательно 1в1 переводить, желательно шоб было понятно, что вообще ты активировал, без вики

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/disabilities.dm
> +	desc = "Интересно, как это происходит?"
```suggestion
	desc = "Интерешно, как это проишходит?"
```

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/disabilities.dm
> +	activation_messages = list("Что-то здесь не так.")
```suggestion
	activation_messages = list("Что-то ждешь не так.")
```

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/disabilities.dm
> +	activation_messages = list("<span class='sans'>Упс!</span>")
```suggestion
	activation_messages = list("<span class='sans'>Ух ох!</span>")
```
Это в целом хз как переводить, наверное вообще не стоит, так как мем SS13

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/disabilities.dm
> +	activation_messages = list("Вы чувствуете себя шведом, как бы это не звучало.")
```suggestion
	activation_messages = list("Ты чувствуешь себя по-шведски, как бы это не звучало.")
```

2024-01-31 17:24 UTC, Aylong220 commented on paradise.dme
> -// SS220 ADDITION END
Очисти эти изменения, файл не должен быть тронут

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/mutation_powers.dm
> +	selection_activated_message		= "<span class='notice'>Твой разум становится холодным. Нажмите на цель, чтобы применить заклинание.</span>"
```suggestion
	selection_activated_message		= "<span class='notice'>Твой разум становится холодным. Нажмите на цель, чтобы применить способность.</span>"
```
Мы чё, маги?

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/mutation_powers.dm
> +			to_chat(user, "<span class='warning'>Ты не можешь съесть эту часть их тела!</span>")
```suggestion
			to_chat(user, "<span class='warning'>Ты не можешь съесть эту часть тела!</span>")
```

2024-01-31 17:24 UTC, Aylong220 commented on code/game/dna/mutations/mutation_powers.dm
> +			to_chat(user, "<span class='warning'>Ты пытаешься положить [the_item.p_their()] [limb] в рот, но он слишком велик, чтобы влезть!</span>")
```suggestion
			to_chat(user, "<span class='warning'>Ты пытаешься положить [limb] [the_item] в рот, но он слишком велик, чтобы влезть!</span>")
```

2024-01-31 17:24 UTC, Aylong220 commented
Дабы билд собирался - обнови Byond до беты (515)

2024-01-31 18:24 UTC, azym76 commented
> Дабы билд собирался - обнови Byond до беты (515)

Окей, попробую завтра проверить и обновить файлы.

2024-02-26 16:53 UTC, AyIong commented
Месяц, и никаких изменений кроме того что я предложил, а ведь попросил протестировать и избавиться от машинного перевода, увы. Переоткроешь если соберёшься допилить

2024-02-26 16:53 UTC, closed without merging