Adds rave wizard
ss220club/Paradise-SS220 pull request #928
Opened 2024-01-22 02:40 UTC by HelmsDeepState

## Что этот PR делает

Добавляет рейв мага

## Почему это хорошо для игры

Баунти, забавный антаг

## Изображения изменений

## Тестирование

## Changelog

:cl:
add: Добавлен рейв маг
/:cl:

2024-01-23 01:20 UTC, Furrior requested changes
Еще следует заменить спаны на дефайны

2024-01-23 01:20 UTC, Furrior commented on code/modules/events/event_container.dm
> +		//SS 220 EDIT - END
Можно сделать модульно

2024-01-23 01:20 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/code/rave_wizard_event.dm
> +		return // Let's not steal someone's soul here
Заняло у меня больше секунды, чтоб понять, что G значит Ghost, учитывая, что в коде они обсерверы. Вероятно, плохое название.

2024-01-23 01:20 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/code/rave_wizard_event.dm
> +			magic.products[key] = 20 // and so, there was prosperity for mages everywhere
Волшебное число

2024-01-23 01:20 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/code/rave_wizard_event.dm
> +/datum/mind/proc/make_rave_wizard()
Не очень нравится, что это место будет частичным повторением скрипта спавна обычного мага. Еще было бы неплохо разделить одевание, выдачу целей и тп по разным функциям, чтоб сократить эту

2024-02-06 02:17 UTC, Furrior requested changes
Досмотрю вечером

2024-02-06 02:17 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/beer_missiles.dm
> +#define HIT_MISSILE_EFFECT_DURATION 10 SECONDS
Такое лучше выносить не в дефайн, а в вар спелла. Расширяет щитспавн

2024-02-06 02:17 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/dancing_field.dm
> +				if(prob(50))
Мб тоже в вары спелла

2024-02-06 02:17 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/dancing_field.dm
> +	return
Лучше коллбэк с таймером кнш

2024-02-06 02:17 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/great_revelry.dm
> +		H.drop_item() //drops item in active hand
Спасибо, кэп

2024-02-06 02:17 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/great_revelry.dm
> +		to_chat(H, "<span class='warning'>\A [B] appears [in_hand ? "in your hand" : "at your feet"]!</span>")
Спаны через дефайны

2024-02-06 02:17 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/rave_wizard_event.dm
> +#define WIZARD_WIKI ("<span class='motd'>На вики-странице доступна более подробная информация: ([GLOB.configuration.url.wiki_url]/index.php/Wizard)</span>")
По идее, тут тоже макрос можно использовать на спан, но лучше затестить

2024-02-06 02:17 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/rave_wizard_event.dm
> +	src.spell_categories -= "Rituals"
Src лишнее

2024-02-06 02:17 UTC, Furrior commented on modular_ss220/antagonists/code/rave_wizard/rave_wizard_event.dm
> +/datum/game_mode/proc/greet_rave_wizard(datum/mind/wizard, you_are=1)
```suggestion
/datum/game_mode/proc/greet_rave_wizard(datum/mind/wizard, you_are=TRUE)
```

2024-02-26 17:45 UTC, HelmsDeepState commented on modular_ss220/antagonists/code/rave_wizard/rave_wizard_event.dm
> +#define WIZARD_WIKI ("<span class='motd'>На вики-странице доступна более подробная информация: ([GLOB.configuration.url.wiki_url]/index.php/Wizard)</span>")
Так не работает :madge:

2024-04-13 20:29 UTC, HelmsDeepState commented
Эх, вот бы... @Furrior -сенпай обратил на меня внимание...

2024-04-14 05:20 UTC, Furrior commented
Твоя проблема в том, что пр не на тг

2024-05-26 20:07 UTC, Legendaxe requested changes

2024-05-26 20:07 UTC, Legendaxe commented on modular_ss220/antagonists/code/rave_wizard/dancing_field.dm
> +	return
```suggestion
```

2024-05-26 20:07 UTC, Legendaxe commented on modular_ss220/antagonists/code/rave_wizard/great_revelry.dm
> +			return
Уверен что тут должен быть return а не continue?

2024-05-26 20:07 UTC, Legendaxe commented on modular_ss220/antagonists/code/rave_wizard/great_revelry.dm
> +/datum/spell/great_revelry/proc/give_alcohol(mob/living/carbon/human/H)
однобуковка aga

2024-05-26 20:07 UTC, Legendaxe commented on modular_ss220/antagonists/code/rave_wizard/great_revelry.dm
> +	for(var/mob/living/carbon/human/H in GLOB.player_list)
Однобуковка aga

2024-05-26 20:07 UTC, Legendaxe commented on modular_ss220/antagonists/code/rave_wizard/dancing_field.dm
> +	for(var/mob/living/M in stopped_atoms)
Однобуковка aga

2024-05-26 20:07 UTC, Legendaxe commented on modular_ss220/antagonists/code/rave_wizard/dancing_field.dm
> +	for(var/A in orange (freezerange, loc))
Однобуковка aga

2024-05-26 20:07 UTC, Legendaxe commented on modular_ss220/antagonists/code/rave_wizard/rocker_touch.dm
> +	var/datum/effect_system/smoke_spread/s = new
Однобуковка aga

2024-06-17 00:31 UTC, closed without merging