Feat: Respawn cooldown
ss220club/Paradise-SS220 pull request #944
Opened 2024-01-26 05:22 UTC by dj-34

## Что этот PR делает
 - Добавляет перезарядку на респавн
 - Убирает возможность возродиться с включенным антагхудом

## Почему это хорошо для игры
Больше никаких смерть -> респавн -> смерть -> респавн

## Изображения изменений

## Тестирование
Проверил в игре

## Changelog

:cl:
add: Добавлена перезарядка на Респавн
tweak: Включенный antagHUD больше не позволяет возрождаться
/:cl:

2024-01-27 23:25 UTC, Gaxeer commented on modular_ss220/verbs/code/verbs.dm
> +	var/deathtime = world.time - src.timeofdeath
```suggestion
	var/deathtime = world.time - timeofdeath
```

2024-01-31 17:21 UTC, Furrior approved these changes
Осталось высрать запрет на заход одинаковыми куклами, но это уже другая история

2024-01-31 18:01 UTC, Aylong220 requested changes

2024-01-31 18:01 UTC, Aylong220 commented on modular_ss220/verbs/code/verbs.dm
> +	to_chat(usr, span_boldnotice("Make sure to play a different character, and please roleplay correctly!"))
```suggestion
	to_chat(usr, span_boldnotice("Make sure to play a different character, and please roleplay correctly!"))
```
Перевёл бы сообщения в to_chat
А то потом снова блять в ветку переводов перевод модуля заливать будем

2024-02-05 07:21 UTC, Aylong220 commented on modular_ss220/verbs/code/verbs.dm
> +		to_chat(usr, span_notice("Вы мертвы[pluralcheck] [deathtimeseconds] секунд(-ы)."))
```suggestion
		to_chat(usr, span_notice("Вы мертвы [pluralcheck] [deathtimeseconds] секунд(-ы)."))
```

2024-02-05 07:22 UTC, Aylong220 commented on modular_ss220/verbs/code/verbs.dm
> +	to_chat(usr, span_boldnotice("Убедитесь, что Вы играете другим персонажем, и, пожалуйста, отыгрывайте корректно!"))
```suggestion
	to_chat(usr, span_boldnotice("Убедитесь, что Вы играете другим персонажем, и пожалуйста, отыгрывайте корректно!"))
```

2024-02-07 04:30 UTC, dj-34 commented on modular_ss220/verbs/code/verbs.dm
> +		to_chat(usr, span_notice("Вы мертвы[pluralcheck] [deathtimeseconds] секунд(-ы)."))
оно спецом

2024-02-07 05:32 UTC, PhantornRU commented on config/example/config.toml
> +respawn_delay = 20
```suggestion
respawn_delay = 20 MINUTES
```

2024-02-07 05:33 UTC, Aylong220 commented on config/example/config.toml
> +respawn_delay = 20
В конфиге нельзя так

2024-02-07 05:33 UTC, Aylong220 commented on config/example/config.toml
> +respawn_delay = 20
Да и тут уже написано что в минутах

2024-02-07 05:35 UTC, PhantornRU commented
Нужно к дрону прикрутить 5-минутный кулдаун и в конфиге включить проверку по дням

2024-02-10 10:15 UTC, Legendaxe commented
Обновил конфиг на всех трех серверах

2024-02-10 10:15 UTC, merged