Terror spider spawn refactor
ss220club/Paradise-SS220 pull request #957
Opened 2024-01-28 13:26 UTC by Fullonibus

## Что этот PR делает
Новая логика для спавна пауков террора. Теперь можно более гибко настраивать численность пауков при спавне.

## Почему это хорошо для игры
Легче подкрутить баланс

## Изображения изменений

## Тестирование

Пауки спавнятся. Для более точных тестов нужен онлайн.
## Changelog

:cl:
experiment: Новый алгоритм спавна пауков террора
/:cl:

2024-02-24 07:15 UTC, PhantornRU requested changes
Нужно выкатить на тестмердж

2024-02-24 07:16 UTC, PhantornRU commented on modular_ss220/events/code/spider_terror.dm
> +	var/list/spider_counts = list("TERROR_GREEN" = 0, "TERROR_WHITE" = 0, "TERROR_PRINCESS" = 0, "TERROR_PRINCE" = 0, "TERROR_QUEEN" = 0)
Убери дефайны и сделай список, каждое значение - с новой строки.

2024-03-24 12:23 UTC, PhantornRU approved these changes

2024-04-04 05:09 UTC, AyIong commented
Долго оно в ТМе?

2024-04-04 12:33 UTC, AyIong approved these changes

2024-04-04 12:33 UTC, merged