Add: New lavaland ruins
ss220club/Paradise-SS220 pull request #973
Opened 2024-01-30 17:14 UTC by Kar4es

## Что этот PR делает
Добавляет три руины в игру. (пока две)

## Почему это хорошо для игры
Много руин - интереснее игра.

## Изображения изменений

![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/d7e11ec8-cdf0-4ff7-b2ad-cdcc633caffd)
![image](https://github.com/ss220club/Paradise-SS220/assets/144079671/7706b114-3785-4fd3-96e7-8d22a175bcef)

## Тестирование

никак
## Changelog

:cl:
add: Что-то добавил
/:cl:

2024-01-31 09:07 UTC, Kar4es commented
> Подпиши тут хотя бы, что вторая взята с эксов. А то это портирование, хотя бы билд надо указать хехе. Первая прикольная, но чуть побольше разрушений, доски, песчаник, на месте тендрила можно сделать чазму, добавить какую нибудь редкую эшевскую штучку (оружие, одежку, лодку, можно даже бесполезную побрякушку любую). А так прикольна

я ничего не портировал, все оригинальное kekw

2024-01-31 13:48 UTC, konushi commented
я шиз, че то похожее видел значит...

2024-01-31 16:28 UTC, Aylong220 reviewed
Небольшие изменения, ща карты пойду гляну

2024-01-31 16:28 UTC, Aylong220 commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	description = "Перенесенная в результате БС аномалии церковь Чизуза."
```suggestion
	description = "Перенесённая в результате БС аномалии церковь Чизуза."
```

2024-01-31 16:28 UTC, Aylong220 commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	cost = 25 // В себе имеет платы консоли заключенных и хим раздратчик, так же пнв модуль
```suggestion
	cost = 10 // В себе имеет платы консоли заключенных и хим раздратчик, так же пнв модуль
```

2024-01-31 16:47 UTC, Aylong220 requested changes
Нет зоны
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/cdfa7a35-1ff4-45a7-a909-f644915e7ffb)

Поставь сундучки эшей, а то странно что просто на полу валяется, они как никак складируют
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/bdc14c62-7606-446d-ba27-463965cffe67)

В целом, как-то пустовато у эшей, я понимаю что они съебали и забрали самое ценное, но нет бардака, накинь какого-то хлама, камней там, чисто декораций, и может каких-то безделушек как сказал кону

Далее...
Зоны, зона в руине должна покрывать всю руину, кроме пустоты естессна
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/913a1e09-3b97-452c-bb95-076b2ea64ef3)

Вот так
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/9856449b-9c31-46c6-87b7-9a12c79801b9)

Все плитки пола не lavaland_air
Это значит что атмос будет активен если руина выпалдет - не хорошо
Создай lavaland air аналог для травы, и используй lavaland air полы, с изменённым стейтов, дерево если что есть лавалендское
![image](https://github.com/ss220club/Paradise-SS220/assets/69762909/b60562e7-2ee3-4509-bd51-07027a93280b)

Ну и побольше бардака бы, разрушений, как минимум пол слегка поломать, а то только пыль

2024-01-31 17:16 UTC, Kar4es commented
> Нет зоны ![image](https://private-user-images.githubusercontent.com/69762909/301236064-cdfa7a35-1ff4-45a7-a909-f644915e7ffb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjE2MjksIm5iZiI6MTcwNjcyMTMyOSwicGF0aCI6Ii82OTc2MjkwOS8zMDEyMzYwNjQtY2RmYTdhMzUtMWZmNC00NWE3LWE5MDktZjY0NDkxNWU3ZmZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE3MTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4MDYyNzQ2MjM4N2Q0YTM0YzYyMGE4OWYyZDY0ZTkwNTFlMTZlMmNmOWRhNTEzZDJmOGRjYmVhOTQyNTAzOTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u5onF-cz0UbqJMayq4fqudDnDt7BqMCifvRijMFGS3M)
> 
> Поставь сундучки эшей, а то странно что просто на полу валяется, они как никак складируют ![image](https://private-user-images.githubusercontent.com/69762909/301236342-bdc14c62-7606-446d-ba27-463965cffe67.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjE2MjksIm5iZiI6MTcwNjcyMTMyOSwicGF0aCI6Ii82OTc2MjkwOS8zMDEyMzYzNDItYmRjMTRjNjItNzYwNi00NDZkLWJhMjctNDYzOTY1Y2ZmZTY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE3MTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5YmEyYTc1NDZlNmZlZTMxMDQ3NDc1ODg2Njg0NGZhYzk2OGM5NmUzNmE4ZWE2ZDNiYTQyOGM1NjNhZTMwY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Vg0K3u2RGjErsm91QKdatHWxoIuH5ou4IXNtIwg6hQU)
> 
> В целом, как-то пустовато у эшей, я понимаю что они съебали и забрали самое ценное, но нет бардака, накинь какого-то хлама, камней там, чисто декораций, и может каких-то безделушек как сказал кону
> 
> Далее... Зоны, зона в руине должна покрывать всю руину, кроме пустоты естессна ![image](https://private-user-images.githubusercontent.com/69762909/301238878-913a1e09-3b97-452c-bb95-076b2ea64ef3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjE2MjksIm5iZiI6MTcwNjcyMTMyOSwicGF0aCI6Ii82OTc2MjkwOS8zMDEyMzg4NzgtOTEzYTFlMDktM2I5Ny00NTJjLWJiOTUtMDc2YjJlYTY0ZWYzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE3MTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZmNlMWRjMzIzMmFiYzA5YzdkOTQ3NjNkNmU3MTkzNTZiMDY5ODc0YzA4N2M0ZmNhOWIzZmU3NDYwMGI1ZWImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ZYZN1QXRB0Di-9LG9eQQCCaePwpJeV1xXC9msLe4vQw)
> 
> Вот так ![image](https://private-user-images.githubusercontent.com/69762909/301239189-9856449b-9c31-46c6-87b7-9a12c79801b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjE2MjksIm5iZiI6MTcwNjcyMTMyOSwicGF0aCI6Ii82OTc2MjkwOS8zMDEyMzkxODktOTg1NjQ0OWItOWMzMS00NmM2LTg3YjctOWExMmM3OTgwMWI5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE3MTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZTE2NjQ1M2VjZWFlNWI5Yjg0YWY5MTgxNzVhOWQwZGJjNjg5YWYyODBjYzgxMDk2NmFhYmEyMzBkMWZlZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s-ibjk1LSiQlybDsh3CfhKPJz6jq4u8OYUXnManuVrA)
> 
> Все плитки пола не lavaland_air Это значит что атмос будет активен если руина выпадет - не хорошо Создай lavaland air аналог для травы, и используй lavaland air полы, с изменёнными стейтами, дерево если что есть лавалендское ![image](https://private-user-images.githubusercontent.com/69762909/301239938-b60562e7-2ee3-4509-bd51-07027a93280b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MjE2MjksIm5iZiI6MTcwNjcyMTMyOSwicGF0aCI6Ii82OTc2MjkwOS8zMDEyMzk5MzgtYjYwNTYyZTctMmVlMy00NTA5LWJkNTEtMDcwMjdhOTMyODBiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDE3MTUyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY0OWFiZGQwYmI2NTI1YTdlZjhlYjZjYzY5MWE5ZDM1ZjViNzc2N2E2ZTI0YjZmN2I1Yjc3ZTNkZGM5ZmIwOGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N3E0XcpaHl_8m-24GcUGYPiTITv8iZuTlcqGKkBcVvk)
> 
> Ну и побольше бардака бы, разрушений, как минимум пол слегка поломать, а то только пыль

на то и рассчет, что нет защиты от бури

2024-01-31 17:16 UTC, Kar4es commented
> на то и рассчет, что нет защиты от бури

у эшей

2024-01-31 17:17 UTC, Kar4es commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	cost = 25 // В себе имеет платы консоли заключенных и хим раздратчик, так же пнв модуль
уверен что стоит уменьшить? для антагов хорошие платы и пнв модуль

2024-01-31 17:32 UTC, Aylong220 commented
> на то и рассчет, что нет защиты от бури

Причём тут защита от бури? 
Я про то что зоны нет
Глянь руины оффов какие там зоны снаружи и внутри руины

2024-01-31 17:37 UTC, Aylong220 commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	cost = 25 // В себе имеет платы консоли заключенных и хим раздратчик, так же пнв модуль
Не вижу применения платы консоли заключённых, пнв модуль - похуй, в РнД просто так могут дать. Хим раздатчик из самого ценного, но это ещё руина должна выпасть

2024-02-07 06:47 UTC, Aylong220 commented
В следующий раз сам откроешь, а то я драфты не смотрю

2024-02-07 06:50 UTC, Aylong220 approved these changes

2024-02-07 07:23 UTC, dj-34 requested changes
Про турф хелперы не забыл?

2024-02-07 07:23 UTC, dj-34 commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	name = "Заброшенный лагерь эшей"
```suggestion
	name = "Заброшенный лагерь Эшей"
```

2024-02-07 07:23 UTC, dj-34 commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	name = "Церковь Чизуса."
```suggestion
	name = "Церковь Чизуса"
```

2024-02-07 07:24 UTC, Kar4es commented
> Про турф хелперы не забыл?

Вроде как нет, потом еще проверять буду

2024-02-07 14:32 UTC, dj-34 requested changes

2024-02-07 14:32 UTC, dj-34 commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	description = "Старый заброшенный аванпост. Его постигла участь разлома лаваленда."
```suggestion
	description = "Старый заброшенный аванпост. Его постигла участь разлома Лаваленда."
```

2024-02-07 14:32 UTC, dj-34 commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	cost = 20 // имеется книга призыва сыра
```suggestion
	cost = 20 // Имеется книга призыва сыра
```

2024-02-07 14:32 UTC, dj-34 commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	cost = 15 // на базе в сейфе есть ЕКА
Не сильно ЕКА? (уточните кто-нибудь, а?)

2024-02-07 14:33 UTC, dj-34 requested changes
Без кринжа
old_avanpost.dmm -> old_outpost.dmm

2024-02-07 14:34 UTC, Kar4es commented on modular_ss220/maps220/code/RandomRuins/lavaland_ruins.dm
> +	cost = 15 // на базе в сейфе есть ЕКА
обсуждал с Эйлонгом, он просил запрятать получше. Насчет стоимости не уверен

2024-02-07 14:34 UTC, Kar4es commented
> Без кринжа old_avanpost.dmm -> old_outpost.dmm

бля

2024-02-07 14:50 UTC, dj-34 approved these changes
Насчет ЕКА хз, в остальном вроде окей?

2024-02-07 20:09 UTC, Aylong220 commented
А ЕКА откуда? Не было же

2024-02-08 04:22 UTC, Aylong220 approved these changes

2024-02-08 12:58 UTC, merged