Add: Pneumatic rifle
ss220club/Paradise-SS220 pull request #993
Opened 2024-02-06 12:42 UTC by TheFckReal

## Что этот PR делает
Добавляет новое оружие: пневматическое ружье со специальными магазинами и патронами (шариками). Нестандартные шарики содержат вещества (в данном случае капсаицин в перечном магазине), с которыми реагирует живое существо как при касании с реагентом (вне зависимости от выбранной части тела при стрельбе). 
### Добавлены спрайты:
1. Пустого шарика, магазина для пустых шариков.
2. Шариков с капсаицином, магазина для них.
3. Пневматического оружия.
### Добавлен звук:
1. Пневматического выстрела.
### Добавлены карго ящики:
1. Пневморужья: 2 пневморужья, 2 перечных магазина. Стоимость 500.
2. Перечных магазинов: 3 перечных магазина. Стоимость 250.

## Почему это хорошо для игры
Это позволяет разнообразить список нелетального вооружения дальнего боя (который крайне мал), добавит интереса игры на СБ, даст возможность тратить деньги на нелетальное вооружение для отдела СБ (и не заниматься перманентным накопительством).

## Изображения изменений
![pneumashoots](https://github.com/ss220club/Paradise-SS220/assets/102225891/42f5fc25-5548-4b96-98e7-d5b07bd72220)

## Тестирование
На локалке с товарищем. Были проверены: эффект выстрелов с очками/маской, без очков/маски, заполнение шариками, выгрузка шариков из магазина, заказ каргоящика.

## Changelog

:cl:
add: Пневматическое ружье
soundadd: Звук пневматического выстрела
imageadd: Спрайты для пневмаружья, шариков и магазинов
/:cl:

2024-02-06 13:50 UTC, Aylong220 commented
Не обязательно делить это на 3, просто add: Добавлено пневморужьё, Взять можно там-то за то-то
И я не вижу проджектайла на видосе

2024-02-06 17:55 UTC, TheFckReal commented
> Не обязательно делить это на 3, просто add: Добавлено пневморужьё, Взять можно там-то за то-то ![image](https://private-user-images.githubusercontent.com/69762909/302651179-00b422ea-d0dd-41b8-912e-2a078fde5616.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcyNDA0ODMsIm5iZiI6MTcwNzI0MDE4MywicGF0aCI6Ii82OTc2MjkwOS8zMDI2NTExNzktMDBiNDIyZWEtZDBkZC00MWI4LTkxMmUtMmEwNzhmZGU1NjE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA2VDE3MjMwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkMjBkZmU1YjllNjlmMzBhNWE0ZjdmY2E1YmZkNTNhMjFlNGU4OTIxNWEzZTM1ZmY1NjhiMDM5M2ZjMTJmZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.U8CmtIg0DnRLsWMwILk5i4ZicNDW1qzJsFFzckUUGJY)
> 
> И я не вижу проджектайла на видосе

На 1 гифке есть, но, видимо, из-за пониженного качества его почти не видно (однако если сильно приблизить, то можно заметить, они еще быстро летят). Добавил 2 гифку, где четко видно все с перезарядкой.

2024-02-07 06:45 UTC, Aylong220 requested changes
Подметил пару косяков, возможно местами не прав

2024-02-07 06:45 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +	magazine = new /obj/item/ammo_box/magazine/pneuma/pepper
```suggestion
```

Не надо, это делается только у двустволки, и то, в инициализации

2024-02-07 06:45 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +	item_state = "pneumagun"
```suggestion
```
Если item_state не указан, используется icon_state, он у тебя такой же, значит дублировать не надо

2024-02-07 06:45 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +	w_class = WEIGHT_CLASS_NORMAL
```suggestion
	w_class = WEIGHT_CLASS_BULKY
```

2024-02-07 06:45 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +	actions_types = list()
```suggestion
	actions_types = list()
```
Зачем?

2024-02-07 06:45 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +	update_icon()
```suggestion
```
В этом всём нет смысла

2024-02-07 06:45 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +//Базовые боеприпасы для пневморужья
```suggestion
// Базовые боеприпасы для пневморужья
```
Пробелы добавь, а то местами есть местами нет

2024-02-07 08:46 UTC, TheFckReal commented on modular_ss220/objects/code/weapons.dm
> +	magazine = new /obj/item/ammo_box/magazine/pneuma/pepper
В данном случае надо (насколько я понял). Почему? Потому что mag_type у пневморужья - это .../pneuma. То есть абстракция. Все конкретные магазины наследуются от ../pneuma/, например .../pepper/pneuma. Таким образом выходит что разные по текстуре и реагентам (да даже логике работы) магазины подходят для стандартного пневморужья

А magazine инициализируется от mag_type (а мне это не надо, это просто пустые шарики). Потому заранее магазин и создается. Вот.

2024-02-07 08:48 UTC, dj-34 commented on modular_ss220/objects/code/weapons.dm
> +	actions_types = list()
Ну я так понимаю из-за того что у подтипа automatic есть действия, здесь он их обнуляет, верно?

2024-02-07 08:54 UTC, TheFckReal commented on modular_ss220/objects/code/weapons.dm
> +	w_class = WEIGHT_CLASS_NORMAL
Не уверен, насколько это корректно. Ориентировался на лазган/еган, они NORMAL. Просто в целом он по размерам не большоу даже на картинке, от которой ориентировались.

2024-02-07 08:54 UTC, TheFckReal commented on modular_ss220/objects/code/weapons.dm
> +	actions_types = list()
Верно, у автоматика есть стандартное действие переключения режима огня. Мне он не нужен.

2024-02-07 09:01 UTC, TheFckReal commented on modular_ss220/objects/code/weapons.dm
> +	update_icon()
Я ориентировался на код другого оружия и я, может, неправильно понимаю, но это разве используется для любой инициализации оружия? Если да, то так как текстура оружия разная в зависимости от магазина, а не mag_type, то это необходимо. Иначе уберу.

2024-02-07 09:01 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +	update_icon()
Убери и проверь
Думаю разницы не будет

2024-02-07 09:07 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +	w_class = WEIGHT_CLASS_NORMAL
Для нормала спрайт не очень компактный

2024-02-07 09:53 UTC, Legendaxe commented on modular_ss220/objects/code/weapons.dm
> +	w_class = WEIGHT_CLASS_NORMAL
Пускай будет нормал, вспомни спрайт tiny сигарет.

2024-02-08 10:09 UTC, Legendaxe approved these changes

2024-02-08 10:43 UTC, Aylong220 approved these changes

2024-02-09 10:33 UTC, merged