Add: Выкидной ножик aka стилет
ss220club/Paradise-SS220 pull request #994
Opened 2024-02-06 13:35 UTC by HardexZ

## Что этот PR делает
Добавлен новый ножик который появляется в техах, шанс появления равен дымовой бомбе.
Наносит 8 брут урона, в сложенном состоянии имеет размер tiny, в разложенном small, так же его можно повесить на пояс.

## Почему это хорошо для игры
Новое интересное оружие из техов.

## Изображения изменений
![image (1)](https://github.com/ss220club/Paradise-SS220/assets/33863785/f7147184-a466-40e1-a2e0-3ef0b85ef9cf)
![image](https://github.com/ss220club/Paradise-SS220/assets/33863785/a445500b-c0f1-42d5-b9ed-a883d6893fea)
![image3](https://github.com/ss220club/Paradise-SS220/assets/33863785/b6671ec6-f804-4d6c-89b8-c37e3c2594f4)

## Тестирование
Тест на локалке

## Changelog

:cl:
add: Добавлен выкидной нож в пул контробанды из техов

/:cl:

2024-02-06 13:54 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +		to_chat(user, span_notice("Вы сложили [src.name]."))
```suggestion
		to_chat(user, span_userdanger("Вы разложили [src]"))
		item_state = item_state_on
		icon_state = icon_state_on
		w_class = WEIGHT_CLASS_SMALL
		force = force_on
		attack_verb = attack_verb_on
	else
		to_chat(user, span_notice("Вы сложили [src]."))
```
Name тут не обязательно

2024-02-06 13:54 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +		to_chat(user, span_notice("Вы сложили [src.name]."))
В одноразовых переменных тоже смысла особо нет, да и выглядит нелепо, имхо

2024-02-06 20:53 UTC, Legendaxe requested changes

2024-02-06 20:53 UTC, Legendaxe commented on modular_ss220/objects/code/weapons.dm
> +		item_state = item_state_on
Это касается всех icon_state в этом проке - глянь как это сделано в других местах, смену иконок нужно вынести в отдельный прок update_icon_state, а в этом проке только вызывать update_icon.

2024-02-07 03:12 UTC, Aylong220 commented on modular_ss220/objects/code/weapons.dm
> +	sharp = TRUE
Это ведь не даёт заточить, ибо оно уже острое, зачем удалять?

2024-02-07 07:34 UTC, HardexZ commented on modular_ss220/objects/code/weapons.dm
> +	sharp = TRUE
По идее это что бы ткань или хлеб к примеру резать, я на столько это понимаю

2024-02-07 07:51 UTC, PhantornRU commented
Я когда-то рассказывал как апдейтить стейт правильно. Пишу на примере "как апдейтить сакуру":

Пишешь прок для своего объекта и уже в нём как в примере:
```
"твой объект"/update_overlays()
  . = ..()
  cut_overlays()
  if(grass)
    add_overlays("[название добавляемого стейта травы]")
  add_overlays("[название стейта твоего дерева]")
  if(leaves)
    add_overlays("[название добавляемого стейта падающей анимированной листвы]")
```

Потом при взаимодействиях с этим деревом твоей тяпкой ты вызываешь прок:
```
  update_icon(UPDATE_OVERLAYS)
```

Примеры:
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/212b3c99-d77b-4613-bfb3-bdc5f44dbf14)

После чего ты должен где-то вызвать:
![image](https://github.com/ss220club/Paradise-SS220/assets/41479614/95a91861-a75a-45b3-a59e-6cb631287294)

2024-02-07 07:51 UTC, PhantornRU requested changes
Попробуй изменить апдейты чтобы тебе не пришлось с ними ебаться

2024-02-24 07:12 UTC, PhantornRU commented
мерж конфликты

2024-03-12 18:19 UTC, Legendaxe commented on modular_ss220/objects/code/weapons.dm
> +	sharp = TRUE
Это нужно было удалить потому что этот ПР добавляет стилет, а sharp = TRUE был добавлен уже существующему предмету который не имеет никакого отношения к стилету

2024-03-12 18:21 UTC, Legendaxe commented
> Если это будет висеть ещё 3 дня, я ебанусь Ну-ка ревью давайте, а то запросили изменения и забыли :madge:

Так он не вынес изменения спрайта в update_icon_state

2024-03-12 18:22 UTC, AyIong commented
@HardexZ слышал? Ну короче, если вообще никак не получится это сделать, можешь покнуть кого-то из разрабов в #разработчик-и-игрок
Или как там этот канал называется в дискорде

2024-03-12 20:08 UTC, HardexZ commented
вроде испарвил как должно быть

2024-03-12 20:13 UTC, Legendaxe requested changes
Последнее минорное изменение и можно лить

2024-03-12 20:13 UTC, Legendaxe commented on modular_ss220/objects/code/weapons.dm
> +	return..()
```suggestion
	return ..()
```

2024-03-12 20:17 UTC, Legendaxe approved these changes

2024-03-12 20:17 UTC, merged