Add: wyci wallet
ss220club/Paradise-SS220 pull request #995
Opened 2024-02-06 14:56 UTC by HardexZ

## Что этот PR делает
Новый кошель для донеров за 12 очков.

## Почему это хорошо для игры
Больше разнообразия, ну точно не плохо

## Изображения изменений
![image](https://github.com/ss220club/Paradise-SS220/assets/33863785/dbbcaf7e-526b-46d5-a125-a9743bf5bb75)
![image](https://github.com/ss220club/Paradise-SS220/assets/33863785/e7d893ac-4923-4165-8ae2-2810fa440a0c)

## Тестирование
Тест на локалке

## Changelog

:cl:
add: Новый бумажник wyci в лодауте
/:cl:

2024-02-07 06:36 UTC, Aylong220 approved these changes

2024-02-07 07:25 UTC, dj-34 requested changes

2024-02-07 07:25 UTC, dj-34 commented on modular_ss220/objects/code/wallets.dm
> +	photo_overlay = "photo_wyci_overlay"
```suggestion
	name = "Кошелек WYCI"
	desc = "Кошелек, законодателя моды Wyci,\ 
	украшен золотой пуговицей cшит позолочеными и платиновыми нитями, сверх прочный.\ 
	И сверх модный. И сверх дорогой. И сверх wyci."
	icon = 'modular_ss220/objects/icons/wallets.dmi'
	icon_state = "wallet_wyci"
	photo_overlay = "photo_wyci_overlay"
```

2024-02-07 07:31 UTC, PhantornRU commented on modular_ss220/objects/code/wallets.dm
> +	И сверх модный. И сверх дорогой. И сверх wyci."
Делаем прямую отсылку, что это не опечатка на ВУЧа, а именно отсылка WHEN YOU CODE IT
```suggestion
	И сверх модный. И сверх дорогой. И сшит по принципу WYCI."
```

2024-02-07 07:31 UTC, PhantornRU commented on modular_ss220/objects/code/wallets.dm
> +	desc = "Кошелек, законодателя моды Wyci,\
```suggestion
	desc = "Кошелек, законодателя моды W.Y.C.I.,\
```

2024-02-07 07:31 UTC, PhantornRU commented on modular_ss220/objects/code/wallets.dm
> +	name = "Кошелек WYCI"
Это абревиатура, может тогда и выделить её?
```suggestion
	name = "Кошелек W.Y.C.I."
```

2024-02-08 07:42 UTC, dj-34 approved these changes

2024-02-08 10:08 UTC, merged